'use strict';

exports.BattlePokedex = {
    pidgeyalola: {
        num: 16,
        species: "Pidgey-Alola",
        baseSpecies: "Pidgey",
        forme: "Alola",
        formeLetter: "A",
        types: ["Ground", "Ghost"],
        baseStats: {
            hp: 40,
            atk: 40,
            def: 40,
            spa: 45,
            spd: 35,
            spe: 51
        },
        abilities: {0: "Cursed Body", 1: "Overcoat", H: "Serene Grace"},
		 weightkg: 1.8,
    },
        pidgeottoalola: {
        num: 17,
        species: "Pidgeotto-Alola",
        baseSpecies: "Pidgeotto",
        forme: "Alola",
        formeLetter: "A",
        types: ["Ground", "Ghost"],
        baseStats: {
            hp: 63,
            atk: 60,
            def: 55,
            spa: 60,
            spd: 50,
            spe: 61
        },
        abilities: {0: "Cursed Body", 1: "Overcoat", H: "Serene Grace"},
		  weightkg: 30,
    },
     pidgeotalola: {
        num: 18,
        species: "Pidgeot-Alola",
        baseSpecies: "Pidgeot",
        forme: "Alola",
        formeLetter: "A",
        types: ["Ground", "Ghost"],
        baseStats: {
            hp: 80,
            atk: 80,
            def: 75,
            spa: 83,
            spd: 70,
            spe: 91
        },
        abilities: {0: "Cursed Body", 1: "Overcoat", H: "Serene Grace"},
		  weightkg: 39.5,
    },
	     pidgeotalolamega: {
        num: 18,
        species: "Pidgeot-Alola-Mega",
        baseSpecies: "Pidgeot",
        forme: "Alola-Mega",
        formeLetter: "AM",
        types: ["Ground", "Ghost"],
        baseStats: {
            hp: 80,
            atk: 120,
            def: 80,
            spa: 120,
            spd: 80,
            spe: 51
        },
        abilities: {0: "Adaptability"},
		  weightkg: 50.5,	  
    },
	   nidoranfalola: {
        num: 29,
        species: "Nidoran-F-Alola",
        baseSpecies: "Nidoran-F",
		  gender: "F",
        forme: "Alola",
        formeLetter: "A",
        types: ["Grass"],
        baseStats: { 
            hp: 35,
            atk: 57,
            def: 32,
            spa: 60,
            spd: 30,
            spe: 61
        },
        abilities: {0: "Chlorophyll", 1: "Leaf Guard", H: "Sheer Force"},
		  weightkg: 7,
    },
	    nidoranaalola: {
        num: 30,
        species: "Nidorana-Alola",
        baseSpecies: "Nidorana",
		  gender: "F",
        forme: "Alola",
        formeLetter: "A",
        types: ["Grass"],
        baseStats: { 
            hp: 50,
            atk: 72,
            def: 47,
            spa: 75,
            spd: 45,
            spe: 76
        },
        abilities: {0: "Chlorophyll", 1: "Leaf Guard", H: "Sheer Force"},
			 weightkg: 20,
    },
	   nidoqueenalola: {
        num: 31,
        species: "Nidoqueen-Alola",
        baseSpecies: "Nidoqueen",
        forme: "Alola",
        formeLetter: "A",
        types: ["Grass", "Fire"],
        baseStats: {
            hp: 60,
            atk: 85,
            def: 67,
            spa: 122,
            spd: 65,
            spe: 106
        },
        abilities: {0: "Chlorophyll", 1: "Drought", H: "Sheer Force"},
			weightkg: 60,
    },
	  nidoranmalola: {
        num: 32,
        species: "Nidoran-M-Alola",
        baseSpecies: "Nidoran-M",
        forme: "Alola",
        formeLetter: "A",
        types: ["Water"],
        baseStats: {
            hp: 36,
            atk: 57,
            def: 30,
            spa: 60,
            spd: 30,
            spe: 60
        },
        abilities: {0: "Swift Swim", 1: "Hydration", H: "Sheer Force"},
		  weightkg: 9,
    },
	     nidorinoalola: {
        num: 33,
        species: "Nidorino-Alola",
        baseSpecies: "Nidorino",
        forme: "Alola",
        formeLetter: "A",
        types: ["Water"],
        baseStats: {
            hp: 51,
            atk: 72,
            def: 47,
            spa: 75,
            spd: 45,
            spe: 75
        },
        abilities: {0: "Swift Swim", 1: "Hydration", H: "Sheer Force"},
		  weightkg: 19.5,
    },
	     nidokingalola: {
        num: 34,
        species: "Nidoking-Alola",
        baseSpecies: "Nidoking",
        forme: "Alola",
        formeLetter: "A",
        types: ["Water"],
        baseStats: {
            hp: 61,
            atk: 85,
            def: 67,
            spa: 122,
            spd: 65,
            spe: 105
        },
        abilities: {0: "Swift Swim", 1: "Drizzle", H: "Sheer Force"},
			  weightkg: 62,
    },
	     cleffaalola: {
        num: 173,
        species: "Cleffa-Alola",
        baseSpecies: "Cleffa",
        forme: "Alola",
        formeLetter: "A",
        types: ["Fire", "Fairy"],
		  baseStats: {hp: 50, atk: 25, def: 28, spa: 45, spd: 55, spe: 15},
        abilities: {0: "Magic Guard", 1: "Magic Bounce", H: "Telepathy"},
		  weightkg: 3,
    },
	     clefairyalola: {
        num: 35,
        species: "Clefairy-Alola",
        baseSpecies: "Clefairy",
        forme: "Alola",
        formeLetter: "A",
        types: ["Fire", "Fairy"],
        baseStats: {hp: 70, atk: 45, def: 48, spa: 60, spd: 65, spe: 35},
        abilities: {0: "Magic Guard", 1: "Magic Bounce", H: "Telepathy"},
		  weightkg: 7.5,
    },
	     clefablealola: {
        num: 36,
        species: "Clefable-Alola",
        baseSpecies: "Clefable ",
        forme: "Alola",
        formeLetter: "A",
        types: ["Fire", "Fairy"],
        baseStats: {hp: 95, atk: 70, def: 73, spa: 95, spd: 90, spe: 60},
        abilities: {0: "Magic Guard", 1: "Magic Bounce", H: "Telepathy"},
		  weightkg: 40,
    },
		 
	    bulbasauralola: {
        num: 1,
        species: "Bulbasaur-Alola",
        baseSpecies: "Bulbasaur",
        forme: "Alola",
        formeLetter: "A",
        types: ["Fire"],
        baseStats: {
            hp: 45,
            atk: 39,
            def: 69,
            spa: 75,
            spd: 65,
            spe: 25
        },
        abilities: {0: "Blaze", H: "Sheer Force"},
        weightkg: 6.9,
    },
    ivysauralola: {
        num:2 ,
        species: "Ivysaur-Alola",
        baseSpecies: "Ivysaur",
        forme: "Alola",
        formeLetter: "A",
        types: ["Fire", "Ground"],
        baseStats: {
            hp: 60,
            atk: 52,
            def: 82,
            spa: 95,
            spd: 80,
            spe: 35
        },
        abilities: {0: "Blaze", H: "Sheer Force"}, 
        weightkg: 13,
    },
    venusauralola: {
        num:3 ,
        species: "Venusaur-Alola",
        baseSpecies: "Venusaur",
        forme: "Alola",
        formeLetter: "A",
        types: ["Fire", "Ground"], 
        baseStats: {
            hp: 80,
            atk: 72,
            def: 103,
            spa: 120,
            spd: 100,
            spe: 50
        },
        abilities: {0: "Blaze", H: "Sheer Force"},
        weightkg: 100,
    },
    charmanderalola: {
        num: 4,
        species: "Charmander-Alola",
        baseSpecies: "Charmander",
        forme: "Alola",
        formeLetter: "A",
        types: ["Electric"],
        baseStats: {
            hp: 39,
            atk: 52,
            def: 33,
            spa: 55,
            spd: 40,
            spe: 90
        },
        abilities: {0: "Quick Feet", H: "Volt Absorb"},
        weightkg: 8.5,
    },
    charmeleonalola: {
        num: 5,
        species: "Charmeleon-Alola",
        baseSpecies: "Charmeleon",
        forme: "Alola",
        formeLetter: "A",
        types: ["Electric", "Poison"],
        baseStats: {
            hp: 58,
            atk: 69,
            def: 48,
            spa: 70,
            spd: 60,
            spe: 100
        },
        abilities: {0: "Poison Point", H: "Volt Absorb"}, 
        weightkg: 19,
    },
    charizardalola: {
        num: 6,
        species: "Charizard-Alola",
        baseSpecies: "Charizard",
        forme: "Alola",
        formeLetter: "A",
        types: ["Electric", "Poison"], 
        baseStats: {
            hp: 78,
            atk: 101,
            def: 61,
            spa: 109,
            spd: 65,
            spe: 120
        },
        abilities: {0: "Levitate", H: "Lightning Rod"},
        weightkg: 90.5,
    },
    squirtlealola: {
        num: 7,
        species: "Squirtle-Alola",
        baseSpecies: "Squirtle",
        forme: "Alola",
        formeLetter: "A",
        types: ["Psychic", "Fighting"],
        baseStats: {
            hp: 44,
            atk: 44,
            def: 70,
            spa: 53,
            spd: 68,
            spe: 35
        },
        abilities: {0: "Inner Focus", H: "Filter"}, 
        weightkg: 9,
    },
    wartortlealola: {
        num: 8,
        species: "Wartortle-Alola",
        baseSpecies: "Wartortle",
        forme: "Alola",
        formeLetter: "A",
        types: ["Psychic", "Fighting"], 
        baseStats: {
            hp: 61,
            atk: 55,
            def: 87,
            spa: 70,
            spd: 87,
            spe: 45
        },
        abilities: {0: "Inner Focus", H: "Filter"}, 
        weightkg: 22.5,
    },
    /*blastoisealola: {
        num: 9,
        species: "Blastoise-Alola",
        baseSpecies: "Blastoise",
        forme: "Alola",
        formeLetter: "A",
        types: ["Psychic", "Fighting"], 
        baseStats: {
            hp: 85,
            atk: 68,
            def: 110,
            spa: 92,
            spd: 115,
            spe: 60
        },
        abilities: {0: "A1", 1: "A2", H: "A3"}, OR {0: "A1", H: "A2"}, OR {0: "A1"},
        weightkg: 85.5,
    },*/
    caterpiealola: {
        num:10 ,
        species: "Caterpie-Alola",
        baseSpecies: "Caterpie",
        forme: "Alola",
        formeLetter: "A",
        types: ["Bug", "Ghost"], 
        baseStats: {
            hp: 45,
            atk: 20,
            def: 30,
            spa: 20,
            spd: 30,
            spe: 50
        },
        abilities: {0: "Shield Dust", H: "Anticipation"}, 
        weightkg: 2.9,
    },
    metapodalola: {
        num: 11,
        species: "Metapod-Alola",
        baseSpecies: "Metapod",
        forme: "Alola",
        formeLetter: "A",
        types: ["Bug", "Ghost"],
        baseStats: {
            hp: 50,
            atk: 20,
            def: 55,
            spa: 20,
            spd: 35,
            spe: 25
        },
        abilities: {0: "Shed Skin"},
        weightkg: 9.9,
    },
    butterfreealola: {
        num: 12,
        species: "Butterfree-Alola",
        baseSpecies: "Butterfree",
        forme: "Alola",
        formeLetter: "A",
        types: ["Bug", "Ghost"],
        baseStats: {
            hp: 60,
            atk: 35,
            def: 50,
            spa: 100,
            spd: 70,
            spe: 80
        },
        abilities: {0: "Tinted Lens", H: "Infiltrator"}, 
        weightkg: 30,
    },
    weedlealola: {
        num: 13,
        species: "Weedle-Alola",
        baseSpecies: "Weedle",
        forme: "Alola",
        formeLetter: "A",
        types: ["Bug", "Ghost"], 
        baseStats: {
            hp: 35,
            atk: 40,
            def: 30,
            spa: 15,
            spd: 20,
            spe: 55
        },
        abilities: {0: "Adaptability", H: "Magic Guard"}, 
        weightkg: 1.2,
    },
    kakunaalola: {
        num: 14,
        species: "Kakuna-Alola",
        baseSpecies: "Kakuna",
        forme: "Alola",
        formeLetter: "A",
        types: ["Bug", "Ghost"],
        baseStats: {
            hp: 45,
            atk: 40,
            def: 45,
            spa: 15,
            spd: 35,
            spe: 25
        },
        abilities: {0: "Shed Skin"},
        weightkg: 5,
    },
    beedrillalola: {
        num: 15,
        species: "Beedrill-Alola",
        baseSpecies: "Beedrill",
        forme: "Alola",
        formeLetter: "A",
        types: ["Bug", "Ghost"],
        baseStats: {
            hp: 60,
            atk: 100,
            def: 50,
            spa: 35,
            spd: 65,
            spe: 85
        },
        abilities: {0: "Levitate", H: "Magic Guard"}, 
        weightkg: 10.5,
    },
    };
