'use strict';
exports.BattleItems = {
	"venusauriumz": {
		id: "venusauriumz",
		name: "Venusaurium-Z",
		onTakeItem: false,
		zMove: "Swampy Smackdown",
		zMoveFrom: "Energy Ball",
		zMoveUser: ["Venusaur"],
		desc: "If the holder is Venusaur with the move Energy Ball, it can use Swampy Smackdown.",
	},
	"charizardiumz": {
		id: "charizardiumz",
		name: "Charizardium-Z",
		onTakeItem: false,
		zMove: "Intensified Inferno",
		zMoveFrom: "Flamethrower",
		zMoveUser: ["Charizard"],
		desc: "If the holder is Charizard with the move Flamethrower, it can use Intensified Inferno.",
	},
	"blastoisiumz": {
		id: "blastoisiumz",
		name: "Blastoisium-Z",
		onTakeItem: false,
		zMove: "Destructive Downpour",
		zMoveFrom: "Scald",
		zMoveUser: ["Blastoise"],
		desc: "If the holder is Blastoise with the move Scald, it can use Destructive Downpour.",
	},
	"alolaninetaliumz": {
		id: "alolaninetaliumz",
		name: "Alolaninetalium-Z",
		onTakeItem: false,
		zMove: "Hail Hydra",
		zMoveFrom: "Blizzard",
		zMoveUser: ["Ninetales-Alola"],
		desc: "If the holder is Ninetales-Alola with the move Blizzard, it can use Hail Hydra.",
	},
	"tyraniumz": {
		id: "tyraniumz",
		name: "Tyranium-Z",
		onTakeItem: false,
		zMove: "Pursuing Strike",
		zMoveFrom: "Pursuit",
		zMoveUser: ["Tyranitar"],
		desc: "If the holder is Tyranitar with the move Pursuit, it can use Pursuing Strike.",
	},
	"hippowniumz": {
		id: "hippowniumz",
		name: "Hippownium-Z",
		onTakeItem: false,
		zMove: "Earthly Crush",
		zMoveFrom: "Earthquake",
		zMoveUser: ["Hippowdon"],
		desc: "If the holder is Hippowdon with the move Earthquake, it can use Earthly Crush.",
	},
	"abomasnowniumz": {
		id: "abomasnowniumz",
		name: "Abomasnownium-Z",
		onTakeItem: false,
		zMove: "Blossoming Life Drain",
		zMoveFrom: "Giga Drain",
		zMoveUser: ["Abomasnow"],
		desc: "If the holder is Abomasnow with the move Gig Drain, it can use Blossoming Life Drain.",
	},
	"gigaliumz": {
		id: "gigaliumz",
		name: "Gigalium-Z",
		onTakeItem: false,
		zMove: "Honing Rocks",
		zMoveFrom: "Rock Polish",
		zMoveUser: ["Gigalith"],
		desc: "If the holder is Gigalith with the move Rock Polish, it can use Honing Rocks.",
	},
	"vanilliumz": {
		id: "vanilliumz",
		name: "Vanillium-Z",
		onTakeItem: false,
		zMove: "Snowstorm Spinkle",
		zMoveFrom: "Blizzard",
		zMoveUser: ["Vanilluxe"],
		desc: "If the holder is Vanilluxe with the move Blizzard, it can use Snowstorm Spinkle.",
	},
	"ninetalesiumz": {
		id: "ninetalesiumz",
		name: "Ninetalesium-Z",
		onTakeItem: false,
		zMove: "Inferno Burst",
		zMoveFrom: "Fire Blast",
		zMoveUser: ["Ninetales"],
		desc: "If the holder is Ninetales with the move Fire Blast, it can use Inferno Burst.",
	},
	"groudoniumz": {
		id: "groudoniumz",
		name: "Groudonium-Z",
		onTakeItem: false,
		zMove: "Blitzing Tremor",
		zMoveFrom: "Precipice Blades",
		zMoveUser: ["Groudon"],
		desc: "If the holder is Groudon with the move Precipice Blades, it can use Blitzing Tremor.",
	},
	"torkoaliumz": {
		id: "torkoaliumz",
		name: "Torkoalium-Z",
		onTakeItem: false,
		zMove: "Pyrotechnics",
		zMoveFrom: "Heat Wave",
		zMoveUser: ["Torkoal"],
		desc: "If the holder is Torkoal with the move Heat Wave, it can use Pyrotechnics.",
	},
	"politoediumz": {
		id: "politoediumz",
		name: "Politoedium-Z",
		onTakeItem: false,
		zMove: "Toad's Hypno-Spiral",
		zMoveFrom: "Hypnosis",
		zMoveUser: ["Politoed"],
		desc: "If the holder is a Politoed with the move Hypnosis, it can use Toad's Hypno-Spiral.",
	},
	"kyogriumz": {
		id: "kyogriumz",
		name: "Kyogrium-Z",
		onTakeItem: false,
		zMove: "Depthstride Decimation",
		zMoveFrom: "Origin Pulse",
		zMoveUser: ["Kyogre"],
		desc: "If the holder is a Kyogre with the move Origin Pulse, it can use Depthstride Decimation.",
	},
	"pelipiumz": {
		id: "pelipiumz",
		name: "Pelipium-Z",
		onTakeItem: false,
		zMove: "High Delivery Deluge",
		zMoveFrom: "Hydro Pump",
		zMoveUser: ["Pelipper"],
		desc: "If the holder is a Pelipper with the move Hydro Pump, it can use High Delivery Deluge.",
	},
	"lucariumz": {
		id: "lucariumz",
		name: "Lucarium-Z",
		onTakeItem: false,
		zMove: "Inner Aura Focus",
		zMoveFrom: "Laser Focus",
		zMoveUser: ["Lucario"],
		desc: "If the holder is a Lucario with the move Laser Focus, it can use Inner Aura Focus.",
	},
	"greninjiumz": {
		id: "greninjiumz",
		name: "Greninjium-Z",
		onTakeItem: false,
		zMove: "Hyper Water Shuriken",
		zMoveFrom: "Water Shuriken",
		zMoveUser: ["Greninja", "Greninja-Ash"],
		desc: "If the holder is a Greninja with the move Water Shuriken, it can use Hyper Water Shuriken.",
	},
	"omastatiumz": {
		id: "omastatiumz",
		name: "Omastatium-Z",
		onTakeItem: false,
		zMove: "Sacred Spiral",
		zMoveFrom: "Hydro Pump",
		zMoveUser: ["Omastar"],
		desc: "If the holder is an Omastar with the move Hydro Pump, it can use Sacred Spiral.",
	},
	"celebiumz": {
		id: "celebiumz",
		name: "Celebium-Z",
		onTakeItem: false,
		zMove: "Omnitemporal Blast",
		zMoveFrom: "Future Sight",
		zMoveUser: ["Celebi"],
		desc: "If the holder is Celebi with the move Future Sight, it can use Omnitemporal Blast.",
	},
	"regigigiumz": {
		id: "regigigiumz",
		name: "Regigigium-Z",
		onTakeItem: false,
		zMove: "Ancient Servant's Ascension",
		zMoveFrom: "Crush Grip",
		zMoveUser: ["Regigigas"],
		desc: "If the holder is Regigigas with the move Crush Grip, it can use Ancient Servant's Ascension.",
	},
	"gothitelliumz": {
		id: "gothitelliumz",
		name: "Gothitellium Z",
		onTakeItem: false,
		zMove: "Celestial Curse",
		zMoveFrom: "Future Sight",
		zMoveUser: ["Gothitelle"],
		desc: "If the holder is Gothitelle with the move Future Sight, it can use Celestial Curse.",
	},
	"torteriumz": {
		id: "torteriumz",
		name: "Torterium-Z",
		onTakeItem: false,
		zMove: "Catostrophic Continent Crash",
		zMoveFrom: "Wood Hammer",
		zMoveUser: ["Torterra"],
		desc: "If the holder is a Torterra with the move Wood Hammer, it can use Catostrophic Continent Crash.",
	},
	"empoliumz": {
		id: "empoliumz",
		name: "Empolium-Z",
		onTakeItem: false,
		zMove: "Superior Strike",
		zMoveFrom: "Aqua Jet",
		zMoveUser: ["Empoleon"],
		desc: "If the holder is a Empoleon with the move Aqua Jet, it can use Superior Strike.",
	},
	"infernapiumz": {
		id: "infernapiumz",
		name: "Infernapium-Z",
		onTakeItem: false,
		zMove: "Infernal Flare Up",
		zMoveFrom: "Flare Blitz",
		zMoveUser: ["Infernape"],
		desc: "If the holder is a Infernape with the move Flare Blitz, it can use Infernal Flare Up.",
	},
	"exeggutiumz": {
		id: "exeggutiumz",
		name: "Exeggutium Z",
		onTakeItem: false,
		zMove: "Crashing Coco Craze",
		zMoveFrom: "Dragon Hammer",
		zMoveUser: ["Exeggutor-Alola"],
		desc: "If the holder is a Exeggutor-Alola with the move Dragon Hammer, it can use Crashing Coco Craze.",
	},
	"alolaslashiumz": {
		id: "alolaslashiumz",
		name: "Alolaslashium-Z",
		onTakeItem: false,
		zMove: "Frozen Flechettes",
		zMoveFrom: "Icicle Crash",
		zMoveUser: ["Sandslash-Alola"],
		desc: "If the holder is a Sandslash-Alola with the move Icicle Crash, it can use Frozen Flechettes.",
	},
	"alodugtriumz": {
		id: "alodugtriumz",
		name: "Alodugtrium-Z",
		onTakeItem: false,
		zMove: "Indestructable Hair Whips",
		zMoveFrom: "Iron Head",
		zMoveUser: ["Dugtrio-Alola"],
		desc: "If the holder is a Dugtrio-Alola with the move Iron Head, it can use Indestructable Hair Whips.",
	},
	"arbokiumz": {
		id: "arbokiumz",
		name: "Arbokium Z",
		onTakeItem: false,
		zMove: "Venomous Fang Bite",
		zMoveFrom: "Poison Fang",
		zMoveUser: ["Arbok"],
		desc: "If the holder is a Arbok with the move Poison Fang, it can use Venomous Fang Bite.",
	},
	"aloraticiumz": {
		id: "aloraticiumz",
		name: "Aloraticium-Z",
		onTakeItem: false,
		zMove: "Striking Jaw Crush",
		zMoveFrom: "Crunch",
		zMoveUser: ["Raticate-Alola"],
		desc: "If the holder is a Raticate-Alola with the move Crunch, it can use Striking Jaw Crush.",
	},
	"kingiumz": {
		id: "kingiumz",
		name: "Kingium-Z",
		onTakeItem: false,
		zMove: "Emperor's New Land",
		zMoveFrom: "Earthquake",
		zMoveUser: ["Nidoking"],
		desc: "If the holder is a Nidoking with the move Earthquake, it can use Emperor's New Land.",
	},
	"alopersiumz": {
		id: "alopersiumz",
		name: "Alopersium-Z",
		onTakeItem: false,
		zMove: "Parting Burst",
		zMoveFrom: "Parting Shot",
		zMoveUser: ["Persian-Alola"],
		desc: "If the holder is a Persian-Alola with the move Parting Shot, it can use Parting Burst.",
	},
	"rapidashiumz": {
		id: "rapidashiumz",
		name: "Rapidashium-Z",
		onTakeItem: false,
		zMove: "Stampeding Solar Strike",
		zMoveFrom: "Flare Blitz",
		zMoveUser: ["Rapidash"],
		desc: "If the holder is a Rapidash with the move Flare Blitz, it can use Stampeding Solar Strike.",
	},
	"gengariumz": {
		id: "gengariumz",
		name: "Gengarium Z",
		onTakeItem: false,
		zMove: "Sneaky Shade Strike",
		zMoveFrom: "Shadow Ball",
		zMoveUser: ["Gengar"],
		desc: "If the holder is a Gengar with the move Shadow Ball, it can use Sneaky Shade Strike.",
	},
	"pinsiriumz": {
		id: "pinsiriumz",
		name: "Pinsirium-Z",
		onTakeItem: false,
		zMove: "Super Razor Crusher",
		zMoveFrom: "X-Scissor",
		zMoveUser: ["Pinsir"],
		desc: "If the holder is a Pinsir with the move X-Scissor, it can use Super Razor Crusher.",
	},
	"feraligatiumz": {
		id: "feraligatiumz",
		name: "Feraligatium Z",
		onTakeItem: false,
		zMove: "Ferocious Death Roll",
		zMoveFrom: "Aqua Tail",
		zMoveUser: ["Feraligatr"],
		desc: "If the holder is a Feraligatr with the move Aqua Tail, it can use Ferocious Death Roll.",
	},
	"amberiumz": {
		id: "amberiumz",
		name: "Amberium-Z",
		onTakeItem: false,
		zMove: "Annihilating Ancient Amber",
		zMoveFrom: "Aerial Ace",
		zMoveUser: ["Aerodactyl"],
		desc: "If the holder is a Aerodactyl with the move Aerial Ace, it can use Annihilating Ancient Amber.",
	},
	"mewtwoniumz": {
		id: "mewtwoniumz",
		name: "Mewtwonium Z",
		onTakeItem: false,
		zMove: "Supernova Strike",
		zMoveFrom: "Psystrike",
		zMoveUser: ["Mewtwo"],
		desc: "If the holder is a Mewtwo with the move Psystrike, it can use Supernova Strike.",
	},
	"meganiumz": {
		id: "meganiumz",
		name: "Meganium Z",
		onTakeItem: false,
		zMove: "Fantastic Forest Fortress",
		zMoveFrom: "Petal Blizzard",
		zMoveUser: ["Meganium"],
		desc: "If the holder is a Meganium with the move Petal Blizzard, it can use Fantastic Forest Fortress.",
	},
	"typhlosiumz": {
		id: "typhlosiumz",
		name: "Typhlosium-Z",
		onTakeItem: false,
		zMove: "Eruption Destruction",
		zMoveFrom: "Eruption",
		zMoveUser: ["Typhlosion"],
		desc: "If the holder is a Typhlosion with the move Eruption, it can use Eruption Destruction.",
	},
	"feraligatiumz": {
		id: "feraligatiumz",
		name: "Feraligatium -Z",
		onTakeItem: false,
		zMove: "Ferocious Death Roll",
		zMoveFrom: "Aqua Tail",
		zMoveUser: ["Feraligatr"],
		desc: "If the holder is a Feraligatr with the move Aqua Tail, it can use Ferocious Death Roll.",
	},
	"politoediumz": {
		id: "politoediumz",
		name: "Politoedium-Z",
		onTakeItem: false,
		zMove: "Toad's Hypno-Spiral",
		zMoveFrom: "Hypnosis",
		zMoveUser: ["Politoed"],
		desc: "If the holder is a Politoed with the move Hypnosis, it can use Toad's Hypno-Spiral.",
	},
	"hercroniumz": {
		id: "hercroniumz",
		name: "Hercronium Z",
		onTakeItem: false,
		zMove: "Rhino Rush",
		zMoveFrom: "Megahorn",
		zMoveUser: ["Heracross"],
		desc: "If the holder is a Heracross with the move Megahorn, it can use Rhino Rush.",
	},
	"delibiumz": {
		id: "delibiumz",
		name: "Delibium-Z",
		onTakeItem: false,
		zMove: "A Time For Giving",
		zMoveFrom: "Present",
		zMoveUser: ["Delibird"],
		desc: "If the holder is a Delibird with the move Present, it can use A Time For Giving.",
	},
	"enteiumz": {
		id: "enteiumz",
		name: "Enteium-Z",
		onTakeItem: false,
		zMove: "Rose of Kōjin",
		zMoveFrom: "Sacred Fire",
		zMoveUser: ["Entei"],
		desc: "If the holder is a Entei with the move Sacred Fire, it can use Rose of Kōjin.",
	},
	"lugiumz": {
		id: "lugiumz",
		name: "Lugium-Z",
		onTakeItem: false,
		zMove: "Mythical Tempest",
		zMoveFrom: "Aeroblast",
		zMoveUser: ["Lugia"],
		desc: "If the holder is a Lugia with the move Aeroblast, it can use Mythical Tempest.",
	},
	"sceptiliumz": {
		id: "sceptiliumz",
		name: "Sceptilium-Z",
		onTakeItem: false,
		zMove: "Leaf Maelstrom",
		zMoveFrom: "Leaf Storm",
		zMoveUser: ["Sceptile"],
		desc: "If the holder is a Sceptile with the move Leaf Storm, it can use Leaf Maelstrom.",
	},
	"blazikiumz": {
		id: "blazikiumz",
		name: "Blazikium Z",
		onTakeItem: false,
		zMove: "Blazing Meteor Kick",
		zMoveFrom: "Blaze Kick",
		zMoveUser: ["Blaziken"],
		desc: "If the holder is a Blaziken with the move Blaze Kick, it can use Blazing Meteor Kick.",
	},
	"swampiumz": {
		id: "swampiumz",
		name: "Swampium-Z",
		onTakeItem: false,
		zMove: "Reckless Hydro Hammering",
		zMoveFrom: "Waterfall",
		zMoveUser: ["Swampert"],
		desc: "If the holder is a Swampert with the move Waterfall, it can use Reckless Hydro Hammering.",
	},
	"sabliumz": {
		id: "sabliumz",
		name: "Sablium-Z",
		onTakeItem: false,
		zMove: "Sleight of Hand",
		zMoveFrom: "Quash",
		zMoveUser: ["Sableye"],
		desc: "If the holder is a Sableye with the move Quash, it can use Sleight of Hand.",
	},
	"mawiliumz": {
		id: "mawiliumz",
		name: "Mawilium-Z",
		onTakeItem: false,
		zMove: "Harsh Tooth Honing",
		zMoveFrom: "Iron Head",
		zMoveUser: ["Mawile"],
		desc: "If the holder is a Mawile with the move Iron Head, it can use Harsh Tooth Honing.",
	},
	"regirockiumz": {
		id: "regirockiumz",
		name: "Regirockium-Z",
		onTakeItem: false,
		zMove: "Armor-Build Blades",
		zMoveFrom: "Stone Edge",
		zMoveUser: ["Regirock"],
		desc: "If the holder is a Regirock with the move Stone Edge, it can use Armor-Build Blades.",
	},
	"regiciumz": {
		id: "regiciumz",
		name: "Regicium-Z",
		onTakeItem: false,
		zMove: "Fortifying Frost Storm",
		zMoveFrom: "Ice Beam",
		zMoveUser: ["Regice"],
		desc: "If the holder is a Regice with the move Ice Beam, it can use Fortifying Frost Storm.",
	},
	"registeeliumz": {
		id: "registeeliumz",
		name: "Registeelium-Z",
		onTakeItem: false,
		zMove: "Ultimate Alloy Cannon",
		zMoveFrom: "Flash Cannon",
		zMoveUser: ["Registeel"],
		desc: "If the holder is a Registeel with the move Flash Cannon, it can use Ultimate Alloy Cannon.",
	},
	"staraptiumz": {
		id: "staraptiumz",
		name: "Staraptium-Z",
		onTakeItem: false,
		zMove: "Dive Bomb",
		zMoveFrom: "Brave Bird",
		zMoveUser: ["Staraptor"],
		desc: "If the holder is a Staraptor with the move Brave Bird, it can use Dive Bomb.",
	},
	"drifbliumz": {
		id: "drifbliumz",
		name: "Drifblium-Z",
		onTakeItem: false,
		zMove: "Super POP!",
		zMoveFrom: "Explosion",
		zMoveUser: ["Drifblim"],
		desc: "If the holder is a Drifblim with the move Explosion, it can use Super POP!.",
	},
	"lucariumz": {
		id: "lucariumz",
		name: "Lucarium-Z",
		onTakeItem: false,
		zMove: "Inner Aura Focus",
		zMoveFrom: "Laser Focus",
		zMoveUser: ["Lucario"],
		desc: "If the holder is a Lucario with the move Laser Focus, it can use Inner Aura Focus.",
	},
	"meowthiumz": {
		id: "meowthiumz",
		name: "Meowthium-Z",
		onTakeItem: false,
		zMove: "Golden Coin Barrage",
		zMoveFrom: "Pay Day",
		zMoveUser: ["Meowth"],
		desc: "If the holder is a Meowth with the move Pay Day, it can use Golden Coin Barrage.",
	},
	"alomukiumz": {
		id: "alomukiumz",
		name: "Alomukium-Z",
		onTakeItem: false,
		zMove: "Necrotic Burst",
		zMoveFrom: "Gunk Shot",
		zMoveUser: ["Muk-Alola"],
		desc: "If the holder is a Muk-Alola with the move Gunk Shot, it can use Necrotic Burst.",
	},
	"serperiumz":{
id: "serperiumz",
name: "Serperium-Z",
onTakeItem: false,
zMove: "Noble Forest Serpent",
zMoveFrom: "Glare",
zMoveUser: ["Serperior"],
desc: "If the holder is a Serperior with the move Glare, it can use Noble Forest Serpent.",
},
	"reuniumz":{
id: "reuniumz",
name: "Reunium-Z",
onTakeItem: false,
zMove: "Rock-Crushing Grip",
zMoveFrom: "Psyshock",
zMoveUser: ["Reuniclus"],
desc: "If the holder is a Reuniclus with the move Psyshock, it can use Rock-Crushing Grip.",
},
	"chandeluriumz":{
id: "chandeluriumz",
name: "Chandelurium-Z",
onTakeItem: false,
zMove: "Haunted Ignis",
zMoveFrom: "Hex",
zMoveUser: ["Chandelure"],
desc: "If the holder is a Chandelure with the move Hex, it can use Haunted Ignis.",
},
	"delphoxiumz":{
id: "delphoxiumz",
name: "Delphoxium-Z",
onTakeItem: false,
zMove: "Searing Spell",
zMoveFrom: "Mystical Fire",
zMoveUser: ["Delphox"],
desc: "If the holder is a Delphox with the move Mystical Fire, it can use Searing Spell.",
},
	"talonfliumz":{
id: "talonfliumz",
name: "Talonflium-Z",
onTakeItem: false,
zMove: "Blazing Bullet Strike",
zMoveFrom: "Flare Blitz",
zMoveUser: ["Talonflame"],
desc: "If the holder is a Talonflame with the move Flare Blitz, it can use Blazing Bullet Strike.",
},
	"sylviumz":{
id: "sylviumz",
name: "Sylvium-Z",
onTakeItem: false,
zMove: "Draining Ribbon Dance",
zMoveFrom: "Draining Kiss",
zMoveUser: ["Sylveon"],
desc: "If the holder is a Sylveon with the move Draining Kiss, it can use Draining Ribbon Dance.",
},
	"volcaniumz":{
id: "volcaniumz",
name: "Volcanium-Z",
onTakeItem: false,
zMove: "Ignited Flare Outburst",
zMoveFrom: "Fire Blast",
zMoveUser: ["Volcanion"],
desc: "If the holder is a Volcanion with the move Fire Blast, it can use Ignited Flare Outburst.",
},
	"toucanniumz":{
id: "toucanniumz",
name: "Toucannium-Z",
onTakeItem: false,
zMove: "Beak Overdrive",
zMoveFrom: "Beak Blast",
zMoveUser: ["Toucannon"],
desc: "If the holder is a Toucannon with the move Beak Blast, it can use Beak Overdrive.",
},
	"mudsdaliumz":{
id: "mudsdaliumz",
name: "Mudsdalium-Z",
onTakeItem: false,
zMove: "Horse Shoe Rack",
zMoveFrom: "High Horsepower",
zMoveUser: ["Mudsdale"],
desc: "If the holder is a Mudsdale with the move High Horsepower, it can use Horse Shoe Rack.",
},
	"passimiumz":{
id: "passimiumz",
name: "Passimium-Z",
onTakeItem: false,
zMove: "Coconut Crash",
zMoveFrom: "Rock Smash",
zMoveUser: ["Passimian"],
desc: "If the holder is a Passimian with the move Rock Smash, it can use Coconut Crash.",
},
	"palossandiumz":{
id: "palossandiumz",
name: "Palossandium-Z",
onTakeItem: false,
zMove: "Abhorrent Absorbing Abyss",
zMoveFrom: "Earth Power",
zMoveUser: ["Palossand"],
desc: "If the holder is a Palossand with the move Earth Power, it can use Abhorrent Absorbing Abyss.",
},
	"drampiumz":{
id: "drampiumz",
name: "Drampium-Z",
onTakeItem: false,
zMove: "Relic Dragon Roar",
zMoveFrom: "Hyper Voice",
zMoveUser: ["Drampa"],
desc: "If the holder is a Drampa with the move Hyper Voice, it can use Relic Dragon Roar.",
},
	"kartaniumz":{
id: "kartaniumz",
name: "Kartanium-Z",
onTakeItem: false,
zMove: "Slaughtering Slash",
zMoveFrom: "Smart Strike",
zMoveUser: ["Kartana"],
desc: "If the holder is a Kartana with the move Smart Strike, it can use Slaughtering Slash.",
},
	"naganadeliumz":{
id: "naganadeliumz",
name: "Naganadelium-Z",
onTakeItem: false,
zMove: "Naga Venom Bomb",
zMoveFrom: "Sludge Bomb",
zMoveUser: ["Naganadel"],
desc: "If the holder is a Naganadel with the move Sludge Bomb, it can use Naga Venom Bomb.",
},
	"stakatakiumz":{
id: "stakatakiumz",
name: "Stakatakium-Z",
onTakeItem: false,
zMove: "The Stack Attacks",
zMoveFrom: "Stone Edge",
zMoveUser: ["Stakataka"],
desc: "If the holder is a Stakataka with the move Stone Edge, it can use The Stack Attacks.",
},
	"blacephaliumz":{
id: "blacephaliumz",
name: "Blacephalium-Z",
onTakeItem: false,
zMove: "Nuclear Fireworks Display",
zMoveFrom: "Mind Blown",
zMoveUser: ["Blacephalon"],
desc: "If the holder is a Blacephalon with the move Mind Blown, it can use Nuclear Fireworks Display.",
},
	"zeraoriumz":{
id: "zeraoriumz",
name: "Zeraorium-Z",
onTakeItem: false,
zMove: "Grasp of All Energy",
zMoveFrom: "Plasma Fists",
zMoveUser: ["Zeraora"],
desc: "If the holder is a Zeraora with the move Plasma Fists, it can use Grasp of All Energy.",
},
	"chesniumz": {
		id: "chesniumz",
		name: "Chesnium Z",
		onTakeItem: false,
		zMove: "Fortress of Thorns",
		zMoveFrom: "Spiky Shield",
		zMoveUser: ["Chesnaught"],
		desc: "If the holder is Chesnaught with the move Spiky Shield, it can use Fortress of Thorns.",
	},
	"nidoquiumz":{
id: "nidoquiumz",
name: "Nidoquium-Z",
onTakeItem: false,
zMove: "Royal Wave",
zMoveFrom: "Earth Power",
zMoveUser: ["Nidoqueen"],
desc: "If the holder is a Nidoqueen with the move Earth Power, it can use Royal Wave.",
},
	"wiggliumz":{
id: "wiggliumz",
name: "Wigglium-Z",
onTakeItem: false,
zMove: "Lovely Lullaby",
zMoveFrom: "Sing",
zMoveUser: ["Wigglytuff"],
desc: "If the holder is a Wigglytuff with the move Sing, it can use Lovely Lullaby.",
},
	"pelipiumz":{
id: "pelipiumz",
name: "Pelipium-Z",
onTakeItem: false,
zMove: "High Delivery Deluge",
zMoveFrom: "Hydro Pump",
zMoveUser: ["Pelipper"],
desc: "If the holder is a Pelipper with the move Hydro Pump, it can use High Delivery Deluge.",
},
	"emboariumz":{
id: "emboariumz",
name: "Emboarium-Z",
onTakeItem: false,
zMove: "Flaming Force Out",
zMoveFrom: "Heat Crash",
zMoveUser: ["Emboar"],
desc: "If the holder is a Emboar with the move Heat Crash, it can use Flaming Force Out.",
},
	"samurottiumz":{
id: "samurottiumz",
name: "Samurottium-Z",
onTakeItem: false,
zMove: "Sharp Shell Strike",
zMoveFrom: "Razor Shell",
zMoveUser: ["Samurott"],
desc: "If the holder is a Samurott with the move Razor Shell, it can use Sharp Shell Strike.",
},
	"spindiumz":{
id: "spindiumz",
name: "Spindium-Z",
onTakeItem: false,
zMove: "Clumsy Commotion",
zMoveFrom: "Teeter Dance",
zMoveUser: ["Spinda"],
desc: "If the holder is a Spinda with the move Teeter Dance, it can use Clumsy Commotion.",
},
	"loppiumz":{
id: "loppiumz",
name: "Loppium-Z",
onTakeItem: false,
zMove: "Loyalty Lunge",
zMoveFrom: "Return",
zMoveUser: ["Lopunny"],
desc: "If the holder is a Lopunny with the move Return, it can use Loyalty Lunge.",
},
	"dialgiumz":{
id: "dialgiumz",
name: "Dialgium-Z",
onTakeItem: false,
zMove: "Time Crash",
zMoveFrom: "Roar of Time",
zMoveUser: ["Dialga"],
desc: "If the holder is a Dialga with the move Roar of Time, it can use Time Crash.",
},
	"zebstrikiumz":{
id: "zebstrikiumz",
name: "Zebstrikium-Z",
onTakeItem: false,
zMove: "Zealous Zephyr Zap",
zMoveFrom: "Wild Charge",
zMoveUser: ["Zebstrika"],
desc: "If the holder is a Zebstrika with the move Wild Charge, it can use Zealous Zephyr Zap.",
},
	"jackfrostiumz":{
id: "jackfrostiumz",
name: "Jackfrostium-Z",
onTakeItem: false,
zMove: "Jack Frost's Cruelty",
zMoveFrom: "Freeze-Dry",
zMoveUser: ["Cryogonal"],
desc: "If the holder is a Cryogonal with the move Freeze-Dry, it can use Jack Frost's Cruelty.",
},
	"reshiramiumz":{
id: "reshiramiumz",
name: "Reshiramium-Z",
onTakeItem: false,
zMove: "Ignis Veritatis",
zMoveFrom: "Fusion Flare",
zMoveUser: ["Reshiram", "Kyurem-White"],
desc: "If the holder is a Reshiram or Kyurem-White with the move Fusion Flare, it can use Ignis Veritatis.",
},
	"zekromiumz":{
id: "zekromiumz",
name: "Zekromium-Z",
onTakeItem: false,
zMove: "Fulgur Idealis",
zMoveFrom: "Fusion Bolt",
zMoveUser: ["Zekrom", "Kyurem-Black"],
desc: "If the holder is a Zekrom or Kyurem-Black with the move Fusion Bolt, it can use Fulgur Idealis.",
},
	"turtoniumz":{
id: "turtoniumz",
name: "Turtonium-Z",
onTakeItem: false,
zMove: "Shocking Shell Hell",
zMoveFrom: "Shell Trap",
zMoveUser: ["Turtonator"],
desc: "If the holder is a Turtonator with the move Shell Trap, it can use Shocking Shell Hell.",
},
	"soliumz":{
id: "soliumz",
name: "Solium-Z",
onTakeItem: false,
zMove: "Dwarf Star Crush",
zMoveFrom: "Sunsteel Strike",
zMoveUser: ["Solgaleo"],
desc: "If the holder is a Solgaleo with the move Sunsteel Strike, it can use Dwarf Star Crush.",
},
	"luniumz":{
id: "luniumz",
name: "Lunium-Z",
onTakeItem: false,
zMove: "Lunatic Laser",
zMoveFrom: "Moongeist Beam",
zMoveUser: ["Lunala"],
desc: "If the holder is a Lunala with the move Moongeist Beam, it can use Lunatic Laser.",
},
	"giratiniumz":{
id: "giratiniumz",
name: "Giratinium-Z",
onTakeItem: false,
zMove: "Distorted Strike",
zMoveFrom: "Shadow Force",
zMoveUser: ["Giratina"],
desc: "If the holder is a Giratina with the move Shadow Force, it can use Distorted Strike.",
},
	"genesectiumz":{
id: "genesectiumz",
name: "Genesectium-Z",
onTakeItem: false,
zMove: "Techno Burst",
zMoveFrom: "Techno Blast",
zMoveUser: ["Genesect"],
desc: "If the holder is a Genesect with the move Techno Blast, it can use Techno Burst.",
},
	"xerniumz":{
id: "xerniumz",
name: "Xernium-Z",
onTakeItem: false,
zMove: "Aura of Life",
zMoveFrom: "Geomancy",
zMoveUser: ["Xerneas"],
desc: "If the holder is a Xerneas with the move Geomancy, it can use Aura of Life.",
},
	"yveltiumz":{
id: "yveltiumz",
name: "Yveltium-Z",
onTakeItem: false,
zMove: "Aura of Death",
zMoveFrom: "Oblivion Wing",
zMoveUser: ["Yveltal"],
desc: "If the holder is a Yveltal with the move Oblivion Wing, it can use Aura of Death.",
},
	"zygardiumz":{
id: "zygardiumz",
name: "Zygardium-Z",
onTakeItem: false,
zMove: "Bring Order to the World",
zMoveFrom: "Thousand Waves",
zMoveUser: ["Zygarde-10%", "Zygarde", "Zygarde-Complete"],
desc: "If the holder is a Zygarde forme with the move Thousand Waves, it can use Bring Order to the World.",
},
	"hoopiumz":{
id: "hoopiumz",
name: "Hoopium-Z",
onTakeItem: false,
zMove: "Unleashed Power of the Djinn",
zMoveFrom: "Hyperspace Hole",
zMoveUser: ["Hoopa", "Hoopa-Unbound"],
desc: "If the holder is a Hoopa forme with the move Hyperspace Hole, it can use Unleashed Power of the Djinn.",
},
};
