'use strict';

/**@type {{[k: string]: TemplateData}} */
let BattlePokedex = {
stomarate: {
	num: 1.5,
	species: "Stomarate",
	types: ["Fighting", "Water"],
	baseStats: {hp: 85, atk: 135, def: 100, spa: 85, spd: 80, spe: 115},
	abilities: {0: "Iron Fist", 1: "Swift Swim", H: "Water Veil"},
	prevo: "mantill",
},
tectowary: {
	num: 2.5,
	species: "Tectowary",
	types: ["Ground"],
	baseStats: {hp: 100, atk: 110, def: 125, spa: 60, spd: 70, spe: 60},
	abilities: {0: "Rock Head", 1: "Swift Swim", H: "Poison Heal"},
	prevo: "quakea",
},
torataturi: {
	num: 3.5,
	species: "Torataturi",
	types: ["Fire", "Grass"],
	baseStats: {hp: 100, atk: 100, def: 90, spa: 120, spd: 90, spe: 100},
	abilities: {0: "Compound Eyes", 1: "NA", H: "Flash Fire"},
	prevo: "na",
	evos: ["n", "a"],
},
quakea: {
	num: 4.5,
	species: "Quakea",
	types: ["Ground"],
	baseStats: {hp: 60, atk: 70, def: 65, spa: 40, spd: 50, spe: 70},
	abilities: {0: "Keen Eye", 1: "NA", H: "Prankster"},
	prevo: "na",
	evos: ["tectowary"],
},
shockjina: {
	num: 5.5,
	species: "Shockjina",
	types: ["Electric", "Water"],
	baseStats: {hp: 85, atk: 55, def: 70, spa: 125, spd: 115, spe: 100},
	abilities: {0: "Levitate", 1: "NA"},
	prevo: "na",
	evos: ["n", "a"],
},
eudyxie: {
	num: 6.5,
	species: "Eudyxie",
	types: ["Fairy"],
	baseStats: {hp: 60, atk: 80, def: 65, spa: 60, spd: 70, spe: 85},
	abilities: {0: "Cute Charm", 1: "NA"},
	prevo: "na",
	evos: ["icairy"],
},
icairy: {
	num: 7.5,
	species: "Icairy",
	types: ["Fairy"],
	baseStats: {hp: 70, atk: 110, def: 75, spa: 70, spd: 90, spe: 115},
	abilities: {0: "Cute Charm", 1: "NA"},
	prevo: "eudyxie",
	evos: ["n", "a"],
},
boxill: {
	num: 8.5,
	species: "Boxill",
	types: ["Water"],
	baseStats: {hp: 50, atk: 50, def: 50, spa: 45, spd: 30, spe: 75},
	abilities: {0: "Iron Fist", 1: "NA", H: "Water Veil"},
	prevo: "na",
	evos: ["mantill"],
},
mantill: {
	num: 9.5,
	species: "Mantill",
	types: ["Water", "Fighting"],
	baseStats: {hp: 75, atk: 95, def: 70, spa: 50, spd: 35, spe: 95},
	abilities: {0: "Iron Fist", 1: "NA", H: "Water Veil"},
	prevo: "boxill",
	evos: ["stomarate"],
},
peawort: {
	num: 10.5,
	species: "Peawort",
	types: ["Grass", "Fairy"],
	baseStats: {hp: 85, atk: 55, def: 40, spa: 45, spd: 55, spe: 30},
	abilities: {0: "Overgrow", 1: "NA", H: "Water Suction"},
	prevo: "na",
	evos: ["utripea"],
},
utripea: {
	num: 11.5,
	species: "Utripea",
	types: ["Grass", "Fairy"],
	baseStats: {hp: 115, atk: 75, def: 50, spa: 55, spd: 75, spe: 50},
	abilities: {0: "Overgrow", 1: "NA", H: "Water Suction"},
	prevo: "peawort",
	evos: ["peacaria"],
},
peacaria: {
	num: 12.5,
	species: "Peacaria",
	types: ["Grass", "Fairy"],
	baseStats: {hp: 155, atk: 115, def: 60, spa: 65, spd: 75, spe: 60},
	abilities: {0: "Overgrow", 1: "NA", H: "Water Suction"},
	prevo: "utripea",
	evos: ["n", "a"],
},
platysear: {
	num: 13.5,
	species: "Platysear",
	types: ["Fire", "Poison"],
	baseStats: {hp: 50, atk: 65, def: 55, spa: 40, spd: 45, spe: 55},
	abilities: {0: "Blaze", 1: "NA", H: "Poison Touch"},
	prevo: "na",
	evos: ["platypyre"],
},
platypyre: {
	num: 14.5,
	species: "Platypyre",
	types: ["Fire", "Poison"],
	baseStats: {hp: 70, atk: 95, def: 75, spa: 50, spd: 55, spe: 75},
	abilities: {0: "Blaze", 1: "Reckless", H: "Poison Touch"},
	prevo: "platysear",
	evos: ["ataninferno"],
},
anatinferno: {
	num: 15.5,
	species: "Anatinferno",
	types: ["Fire", "Poison"],
	baseStats: {hp: 80, atk: 115, def: 95, spa: 60, spd: 75, spe: 105},
	abilities: {0: "Blaze", 1: "Reckless", H: "Poison Touch"},
	prevo: "platypyre",
	evos: ["n", "a"],
},
phindra: {
	num: 16.5,
	species: "Phindra",
	types: ["Water", "Dragon"],
	baseStats: {hp: 45, atk: 45, def: 50, spa: 65, spd: 40, spe: 65},
	abilities: {0: "Torrent", 1: "NA", H: "Cute Charm"},
	prevo: "na",
	evos: ["gondol"],
},
gondol: {
	num: 17.5,
	species: "Gondol",
	types: ["Water", "Dragon"],
	baseStats: {hp: 60, atk: 55, def: 70, spa: 90, spd: 60, spe: 85},
	abilities: {0: "Torrent", 1: "Levitate", H: "Cute Charm"},
	prevo: "phindra",
	evos: ["dolphadon"],
},
dolphadon: {
	num: 18.5,
	species: "Dolphadon",
	types: ["Water", "Dragon"],
	baseStats: {hp: 75, atk: 60, def: 90, spa: 115, spd: 80, spe: 110},
	abilities: {0: "Torrent", 1: "Frisk", H: "Cute Charm"},
	prevo: "gondol",
	evos: ["n", "a"],
},
torchoney: {
	num: 19.5,
	species: "Torchoney",
	types: ["Bug", "Fire"],
	baseStats: {hp: 40, atk: 65, def: 40, spa: 50, spd: 20, spe: 70},
	abilities: {0: "Swarm", 1: "NA"},
	prevo: "na",
	evos: ["flambee"],
},
flambee: {
	num: 20.5,
	species: "Flambee",
	types: ["Bug", "Fire"],
	baseStats: {hp: 70, atk: 115, def: 70, spa: 90, spd: 50, spe: 120},
	abilities: {0: "Swarm", 1: "NA"},
	prevo: "torchoney",
	evos: ["n", "a"],
},
demornet: {
	num: 21.5,
	species: "Demornet",
	types: ["Dark", "Bug"],
	baseStats: {hp: 100, atk: 125, def: 70, spa: 110, spd: 105, spe: 40},
	abilities: {0: "Swarm", 1: "Run Away", H: "NA"},
	prevo: "na",
	evos: ["n", "a"],
},
flaminqua: {
	num: 22.5,
	species: "Flaminqua",
	types: ["Fire", "Water"],
	baseStats: {hp: 110, atk: 75, def: 90, spa: 110, spd: 85, spe: 60},
	abilities: {0: "Generalist", 1: "Download", H: "NA"},
	prevo: "na",
	evos: ["n", "a"],
},
mediogre: {
	num: 23.5,
	species: "Mediogre",
	types: ["Normal"],
	baseStats: {hp: 95, atk: 95, def: 85, spa: 75, spd: 75, spe: 80},
	abilities: {0: "Sturdy", 1: "NA"},
	prevo: "na",
	evos: ["n", "a"],
},
phantorm: {
	num: 24.5,
	species: "Phantorm",
	types: ["Ghost", "Bug"],
	baseStats: {hp: 70, atk: 50, def: 30, spa: 80, spd: 80, spe: 55},
	abilities: {0: "Mental Snap", 1: "NA"},
	prevo: "na",
	evos: ["specterfly"],
},
specterfly: {
	num: 25.5,
	species: "Specterfly",
	types: ["Ghost", "Bug"],
	baseStats: {hp: 100, atk: 70, def: 60, spa: 110, spd: 110, spe: 85},
	abilities: {0: "Mental Snap", 1: "Guardian", H: "NA"},
	prevo: "phantorm",
	evos: ["n", "a"],
},
gearabbit: {
	num: 26.5,
	species: "Gearabbit",
	types: ["Normal", "Steel"],
	baseStats: {hp: 35, atk: 70, def: 40, spa: 30, spd: 35, spe: 70},
	abilities: {0: "Steelworker", 1: "NA"},
	prevo: "na",
	evos: ["mechalope"],
},
mechalope: {
	num: 27.5,
	species: "Mechalope",
	types: ["Normal", "Steel"],
	baseStats: {hp: 65, atk: 105, def: 80, spa: 60, spd: 65, spe: 100},
	abilities: {0: "Steelworker", 1: "NA"},
	prevo: "gearabbit",
	evos: ["n", "a"],
},
xiphimil: {
	num: 28.5,
	species: "Xiphimil",
	types: ["Electric", "Ice"],
	baseStats: {hp: 40, atk: 75, def: 50, spa: 35, spd: 30, spe: 65},
	abilities: {0: "Lightning Rod", 1: "NA"},
	prevo: "na",
	evos: ["xiphiamp"],
},
xiphiamp: {
	num: 29.5,
	species: "Xiphiamp",
	types: ["Electric", "Ice"],
	baseStats: {hp: 75, atk: 125, def: 100, spa: 85, spd: 60, spe: 110},
	abilities: {0: "Lightning Rod", 1: "NA"},
	prevo: "xiphimil",
	evos: ["n", "a"],
},
gargrotesque: {
	num: 30.5,
	species: "Gargrotesque",
	types: ["Rock", "Fighting"],
	baseStats: {hp: 100, atk: 85, def: 115, spa: 135, spd: 95, spe: 25},
	abilities: {0: "Intimidate", 1: "NA", H: "Dry Skin"},
	prevo: "na",
	evos: ["n", "a"],
},
kiwikiwi: {
	num: 31.5,
	species: "Kiwikiwi",
	types: ["Grass", "Ghost"],
	baseStats: {hp: 35, atk: 72, def: 38, spa: 35, spd: 51, spe: 68},
	abilities: {0: "Insectivore", 1: "Moxie", H: "NA"},
	prevo: "na",
	evos: ["spirikiwi"],
},
spirikiwi: {
	num: 32.5,
	species: "Spirikiwi",
	types: ["Grass", "Ghost"],
	baseStats: {hp: 65, atk: 122, def: 68, spa: 65, spd: 81, spe: 108},
	abilities: {0: "Insectivore", 1: "NA"},
	prevo: "kiwikiwi",
	evos: ["n", "a"],
},
optish: {
	num: 33.5,
	species: "Optish",
	types: ["Flying", "Electric"],
	baseStats: {hp: 20, atk: 30, def: 20, spa: 50, spd: 20, spe: 80},
	abilities: {0: "Dazzling", 1: "NA"},
	prevo: "na",
	evos: ["eelux"],
},
eelux: {
	num: 34.5,
	species: "Eelux",
	types: ["Flying", "Electric"],
	baseStats: {hp: 60, atk: 70, def: 50, spa: 120, spd: 70, spe: 160},
	abilities: {0: "Dazzling", 1: "Sheer Force", H: "NA"},
	prevo: "optish",
	evos: ["n", "a"],
},
vampacabra: {
	num: 35.5,
	species: "Vampacabra",
	types: ["Dark"],
	baseStats: {hp: 71, atk: 128, def: 101, spa: 56, spd: 65, spe: 110},
	abilities: {0: "Life Sucker", 1: "Psychic Surge", H: "NA"},
	prevo: "na",
	evos: ["n", "a"],
},
scorponek: {
	num: 36.5,
	species: "Scorponek",
	types: ["Poison", "Steel"],
	baseStats: {hp: 105, atk: 120, def: 95, spa: 85, spd: 75, spe: 55},
	abilities: {0: "Bulletproof", 1: "Psychic Surge", H: "Corrosion"},
	prevo: "na",
	evos: ["n", "a"],
},
kaithril: {
	num: 37.5,
	species: "Kaithril",
	types: ["Steel", "Water"],
	baseStats: {hp: 105, atk: 135, def: 75, spa: 105, spd: 85, spe: 30},
	abilities: {0: "Pressure", 1: "NA", H: "Weak Armor"},
	prevo: "na",
	evos: ["n", "a"],
},
noodlord: {
	num: 38.5,
	species: "Noodlord",
	types: ["Ground", "Flying"],
	baseStats: {hp: 130, atk: 100, def: 110, spa: 150, spd: 100, spe: 90},
	abilities: {0: "Gravity Noodles", 1: "NA"},
	prevo: "na",
	evos: ["n", "a"],
},
monklops: {
	num: 39.5,
	species: "Monklops",
	types: ["Fairy", "Fighting"],
	baseStats: {hp: 120, atk: 115, def: 90, spa: 95, spd: 65, spe: 50},
	abilities: {0: "Gladiate", 1: "NA"},
	prevo: "na",
	evos: ["n", "a"],
},
liquitty: {
	num: 40.5,
	species: "Liquitty",
	types: ["Poison", "Psychic"],
	baseStats: {hp: 75, atk: 35, def: 50, spa: 75, spd: 60, spe: 10},
	abilities: {0: "Infiltrator", 1: "Shield Dust", H: "NA"},
	prevo: "na",
	evos: ["feliquid"],
},
feliquid: {
	num: 41.5,
	species: "Feliquid",
	types: ["Poison", "Psychic"],
	baseStats: {hp: 115, atk: 75, def: 90, spa: 125, spd: 95, spe: 35},
	abilities: {0: "Infiltrator", 1: "Filter", H: "NA"},
	prevo: "liquitty",
	evos: ["n", "a"],
},
hammedge: {
	num: 42.5,
	species: "Hammedge",
	types: ["Dark", "Steel"],
	baseStats: {hp: 40, atk: 30, def: 55, spa: 65, spd: 35, spe: 70},
	abilities: {0: "Soul Jaws", 1: "Fluffy", H: "NA"},
	prevo: "na",
	evos: ["hammershred"],
},
hammershred: {
	num: 43.5,
	species: "Hammershred",
	types: ["Dark", "Steel"],
	baseStats: {hp: 70, atk: 60, def: 105, spa: 115, spd: 65, spe: 120},
	abilities: {0: "Soul Jaws", 1: "NA"},
	prevo: "hammeredge",
	evos: ["n", "a"],
},
robotato: {
	num: 44.5,
	species: "Robotato",
	types: ["Grass", "Electric"],
	baseStats: {hp: 110, atk: 135, def: 115, spa: 65, spd: 65, spe: 45},
	abilities: {0: "Battle Armor", 1: "NA", H: "Galvanize"},
	prevo: "na",
	evos: ["n", "a"],
},
snugworm: {
	num: 45.5,
	species: "Snugworm",
	types: ["Bug", "Normal"],
	baseStats: {hp: 55, atk: 65, def: 60, spa: 25, spd: 25, spe: 50},
	abilities: {0: "Swarm", 1: "NA", H: "Silkmaker"},
	prevo: "na",
	evos: ["clothcoon"],
},
clothcoon: {
	num: 46.5,
	species: "Clothcoon",
	types: ["Bug", "Normal"],
	baseStats: {hp: 65, atk: 75, def: 120, spa: 35, spd: 35, spe: 25},
	abilities: {0: "Swarm", 1: "NA", H: "Silkmaker"},
	prevo: "snugworm",
	evos: ["mothluff"],
},
mothluff: {
	num: 47.5,
	species: "Mothluff",
	types: ["Bug", "Normal"],
	baseStats: {hp: 85, atk: 115, def: 120, spa: 65, spd: 75, spe: 75},
	abilities: {0: "Swarm", 1: "NA", H: "Silkmaker"},
	prevo: "clothcoon",
	evos: ["n", "a"],
},
felinheit: {
	num: 48.5,
	species: "Felinheit",
	types: ["Fire", "Ice"],
	baseStats: {hp: 44, atk: 30, def: 44, spa: 67, spd: 44, spe: 67},
	abilities: {0: "Thermal Shock", 1: "NA"},
	prevo: "na",
	evos: ["kelvitty"],
},
kelvitty: {
	num: 49.5,
	species: "Kelvitty",
	types: ["Fire", "Ice"],
	baseStats: {hp: 77, atk: 60, def: 77, spa: 123, spd: 77, spe: 123},
	abilities: {0: "Thermal Shock", 1: "NA"},
	prevo: "felinheit",
	evos: ["n", "a"],
},
reptilice: {
	num: 50.5,
	species: "Reptilice",
	types: ["Ice"],
	baseStats: {hp: 45, atk: 65, def: 100, spa: 40, spd: 45, spe: 25},
	abilities: {0: "Ice Body", 1: "NA", H: "Refrigerate"},
	prevo: "na",
	evos: ["rawdyr"],
},
rawdyr: {
	num: 51.5,
	species: "Rawdyr",
	types: ["Ice", "Dragon"],
	baseStats: {hp: 65, atk: 90, def: 90, spa: 60, spd: 70, spe: 70},
	abilities: {0: "Ice Body", 1: "NA", H: "Refrigerate"},
	prevo: "reptilice",
	evos: ["polisdyr"],
},
polisdyr: {
	num: 52.5,
	species: "Polisdyr",
	types: ["Ice", "Dragon"],
	baseStats: {hp: 85, atk: 125, def: 70, spa: 70, spd: 85, spe: 100},
	abilities: {0: "Dancer", 1: "NA", H: "Refrigerate"},
	prevo: "polisdyr",
	evos: ["n", "a"],
},
campyre: {
	num: 53.5,
	species: "Campyre",
	types: ["Fire"],
	baseStats: {hp: 75, atk: 40, def: 65, spa: 50, spd: 45, spe: 5},
	abilities: {0: "Flame Body", 1: "NA", H: "Flash Fire"},
	prevo: "na",
	evos: ["bonpyre"],
},
bonpyre: {
	num: 54.5,
	species: "Bonpyre",
	types: ["Fire"],
	baseStats: {hp: 125, atk: 80, def: 115, spa: 100, spd: 95, spe: 20},
	abilities: {0: "Flame Body", 1: "NA", H: "Flash Fire"},
	prevo: "campyre",
	evos: ["n", "a"],
},
velocicop: {
	num: 55.5,
	species: "Velocicop",
	types: ["Fighting", "Electric"],
	baseStats: {hp: 40, atk: 67, def: 53, spa: 36, spd: 44, spe: 79},
	abilities: {0: "Guts", 1: "NA"},
	prevo: "na",
	evos: ["enforciraptor"],
},
enforciraptr: {
	num: 56.5,
	species: "Enforciraptr",
	types: ["Fighting", "Electric"],
	baseStats: {hp: 60, atk: 117, def: 82, spa: 73, spd: 75, spe: 131},
	abilities: {0: "Guts", 1: "NA"},
	prevo: "velocicop",
	evos: ["n", "a"],
},
spirilter: {
	num: 57.5,
	species: "Spirilter",
	types: ["Ghost"],
	baseStats: {hp: 120, atk: 90, def: 70, spa: 135, spd: 95, spe: 5},
	abilities: {0: "Spirit Flow", 1: "NA"},
	prevo: "na",
	evos: ["n", "a"],
},
gurundire: {
	num: 58.5,
	species: "Gurundire",
	types: ["Water", "Dark"],
	baseStats: {hp: 115, atk: 130, def: 100, spa: 80, spd: 95, spe: 80},
	abilities: {0: "Intimidate", 1: "NA", H: "Strong Jaw"},
	prevo: "na",
	evos: ["n", "a"],
},
zepeboil: {
	num: 59.5,
	species: "Zepeboil",
	types: ["Water", "Fire"],
	baseStats: {hp: 70, atk: 50, def: 50, spa: 70, spd: 60, spe: 20},
	abilities: {0: "Filter", 1: "NA"},
	prevo: "na",
	evos: ["zepeblimp"],
},
zepeblimp: {
	num: 60.5,
	species: "Zepeblimp",
	types: ["Water", "Fire"],
	baseStats: {hp: 140, atk: 70, def: 60, spa: 120, spd: 100, spe: 40},
	abilities: {0: "Levitate", 1: "NA"},
	prevo: "zepeboil",
	evos: ["n", "a"],
},
orbitron: {
	num: 61.5,
	species: "Orbitron",
	types: ["Flying"],
	baseStats: {hp: 151, atk: 67, def: 113, spa: 131, spd: 61, spe: 47},
	abilities: {0: "Beast Boost", 1: "NA"},
	prevo: "cometroid",
	evos: ["n", "a"],
},
quackodile: {
	num: 62.5,
	species: "Quackodile",
	types: ["Water", "Flying"],
	baseStats: {hp: 50, atk: 80, def: 40, spa: 55, spd: 35, spe: 60},
	abilities: {0: "Strong Jaw", 1: "NA"},
	prevo: "na",
	evos: ["sauroose"],
},
sauroose: {
	num: 63.5,
	species: "Sauroose",
	types: ["Water", "Flying"],
	baseStats: {hp: 80, atk: 130, def: 70, spa: 85, spd: 65, spe: 110},
	abilities: {0: "Strong Jaw", 1: "NA"},
	prevo: "quackodile",
	evos: ["n", "a"],
},
stelight: {
	num: 64.5,
	species: "Stelight",
	types: ["Rock", "Ghost"],
	baseStats: {hp: 65, atk: 35, def: 70, spa: 85, spd: 80, spe: 5},
	abilities: {0: "Drought", 1: "NA", H: "Solar Power"},
	prevo: "na",
	evos: ["sololith"],
},
sololith: {
	num: 65.5,
	species: "Sololith",
	types: ["Rock", "Ghost"],
	baseStats: {hp: 95, atk: 65, def: 100, spa: 135, spd: 120, spe: 20},
	abilities: {0: "Drought", 1: "Regenerator", H: "Solar Power"},
	prevo: "stelight",
	evos: ["n", "a"],
},
kittooth: {
	num: 66.5,
	species: "Kittooth",
	types: ["Rock", "Normal"],
	baseStats: {hp: 60, atk: 82, def: 60, spa: 45, spd: 45, spe: 70},
	abilities: {0: "Quick Feet", 1: "Regenerator", H: "NA"},
	prevo: "na",
	evos: ["n", "a"],
},
fataline: {
	num: 67.5,
	species: "Fataline",
	types: ["Rock", "Normal"],
	baseStats: {hp: 80, atk: 131, def: 80, spa: 65, spd: 65, spe: 100},
	abilities: {0: "Quick Feet", 1: "NA"},
	prevo: "na",
	evos: ["n", "a"],
},
boivaurum: {
	num: 68.5,
	species: "Boivaurum",
	types: ["Steel", "Fire"],
	baseStats: {hp: 90, atk: 130, def: 90, spa: 115, spd: 80, spe: 95},
	abilities: {0: "Intimidate", 1: "NA", H: "Levitate"},
	prevo: "na",
	evos: ["n", "a"],
},
spidirt: {
	num: 69.5,
	species: "Spidirt",
	types: ["Bug", "Ground"],
	baseStats: {hp: 75, atk: 60, def: 135, spa: 60, spd: 125, spe: 60},
	abilities: {0: "Concealment", 1: "NA"},
	prevo: "na",
	evos: ["n", "a"],
},
burnk: {
	num: 70.5,
	species: "Burnk",
	types: ["Grass"],
	baseStats: {hp: 50, atk: 85, def: 75, spa: 30, spd: 75, spe: 5},
	abilities: {0: "Pressure", 1: "NA", H: "Magic Guard"},
	prevo: "na",
	evos: ["redwarmth"],
},
redwarmth: {
	num: 71.5,
	species: "Redwarmth",
	types: ["Grass", "Fire"],
	baseStats: {hp: 90, atk: 125, def: 115, spa: 70, spd: 115, spe: 20},
	abilities: {0: "Pressure", 1: "NA", H: "Magic Guard"},
	prevo: "burnk",
	evos: ["n", "a"],
},
nauseox: {
	num: 72.5,
	species: "Nauseox",
	types: ["Poison"],
	baseStats: {hp: 120, atk: 75, def: 95, spa: 120, spd: 70, spe: 55},
	abilities: {0: "Intimidate", 1: "NA", H: "Sap Sipper"},
	prevo: "na",
	evos: ["n", "a"],
},
warillaur: {
	num: 73.5,
	species: "Warillaur",
	types: ["Dark", "Fighting"],
	baseStats: {hp: 90, atk: 135, def: 80, spa: 85, spd: 75, spe: 115},
	abilities: {0: "Apocalypse", 1: "Damp", H: "Adaptability"},
	prevo: "na",
	evos: ["n", "a"],
},
murea: {
	num: 74.5,
	species: "Murea",
	types: ["Dark", "Ghost"],
	baseStats: {hp: 115, atk: 85, def: 90, spa: 135, spd: 80, spe: 75},
	abilities: {0: "Apocalypse", 1: "NA", H: "Cursed Body"},
	prevo: "na",
	evos: ["n", "a"],
},
locusteed: {
	num: 75.5,
	species: "Locusteed",
	types: ["Dark", "Bug"],
	baseStats: {hp: 90, atk: 85, def: 75, spa: 115, spd: 80, spe: 135},
	abilities: {0: "Apocalypse", H: "Swarm"},
	prevo: "na",
	evos: ["n", "a"],
},
horsirus: {
	num: 76.5,
	species: "Horsirus",
	types: ["Dark", "Poison"],
	baseStats: {hp: 135, atk: 90, def: 115, spa: 80, spd: 85, spe: 75},
	abilities: {0: "Apocalypse", H: "Poison Touch"},
	prevo: "na",
	evos: ["n", "a"],
},
cometroid: {
	num: 77.5,
	species: "Cometroid",
	types: ["Flying"],
	baseStats: {hp: 61, atk: 53, def: 61, spa: 67, spd: 61, spe: 97},
	abilities: {0: "Beast Boost", H: "NA"},
	prevo: "na",
	evos: ["orbitron"],
},
sweel: {
	num: 78.5,
	species: "Sweel",
	types: ["Ground", "Electric"],
	baseStats: {hp: 70, atk: 80, def: 105, spa: 110, spd: 75, spe: 110},
	abilities: {0: "Storm Drain", H: "Galvanize"},
	prevo: "na",
	evos: ["n", "a"],
},
boombusk: {
	num: 79.5,
	species: "Boombusk",
	types: ["Normal", "Electric"],
	baseStats: {hp: 76, atk: 50, def: 136, spa: 126, spd: 118, spe: 48},
	abilities: {0: "Steelworker", H: "NA"},
	prevo: "na",
	evos: ["n", "a"],
},
};

exports.BattlePokedex = BattlePokedex;
