'use strict';

exports.BattlePokedex = {
    leafien: {
        num: 1000001,
        species: "Leafien",
        types: ["Grass"],
        baseStats: {hp: 38, atk: 42, def: 40, spa: 52, spd: 28, spe: 40},
        abilities: {0: "Overgrow", H: "Sap Sipper"},
	evos: ["branchion"],
	heightm: 0.5,
	weightkg: 3.9,
	color: "Green",
	eggGroups: ["Monster", "Grass"],
	},
  branchion: {
        num: 1000002,
        species: "Branchion",
        types: ["Grass"],
        baseStats: {hp: 53, atk: 58, def: 60, spa: 55, spd: 43, spe: 50},
        abilities: {0: "Overgrow", H: "Sap Sipper"},
        evos: ["treenomian"],
        prevo: "branchion",
	heightm: 1.2,
	weightkg: 36.3,
	color: "Green",
	eggGroups: ["Monster", "Grass"],
	},
  treenomian: {
        num: 1000003,
        species: "Treenomian",
        types: ["Grass", "Ground"],
        baseStats: {hp: 88, atk: 103, def: 110, spa: 70, spd: 98, spe: 76},
        abilities: {0: "Overgrow", H: "Sap Sipper"},
        evos: ["treenomian"],
        prevo: "branchion",
	heightm: 1.5,
	weightkg: 73.9,
	color: "Green",
	eggGroups: ["Monster", "Grass"],
	},
  laviniou: {
        num: 1000004,
        species: "Laviniou",
        types: ["Fire"],
        baseStats: {hp: 30, atk: 50, def: 48, spa: 56, spd: 40, spe: 40},
        abilities: {0: "Blaze", H: "Sheer Force"},
        evos: ["marsminian"],
	heightm: 0.8,
	weightkg: 4.2,
	color: "Red",
	eggGroups: ["Monster", "Field"],
	},
  marsminian: {
        num: 1000005,
        species: "Marsminian",
        types: ["Fire","Steel"],
        baseStats: {hp: 70, atk: 76, def: 70, spa: 75, spd: 62, spe: 71},
        abilities: {0: "Blaze", H: "Sheer Force"},
        evos: ["volcanolion"],
        prevo: "laviniou",
	heightm: 1.8,
	weightkg: 54.2,
	color: "Red",
	eggGroups: ["Monster", "Field"],
	},
  volcanolion: {
        num: 1000006,
        species: "Volcanolion",
        types: ["Fire","Steel"],
        baseStats: {hp: 75, atk: 110, def: 90, spa: 105, spd: 73, spe: 99},
        abilities: {0: "Blaze", H: "Sheer Force"},
        prevo: "marsminian",
	heightm: 3.5,
	weightkg: 92.2,
	color: "Red",
	eggGroups: ["Monster", "Field"],
	},
   aquario: {
        num: 1000007,
        species: "Aquario",
        types: ["Water"],
        baseStats: {hp: 36, atk: 45, def: 28, spa: 85, spd: 65, spe: 54},
        abilities: {0: "Torrent", H: "Dry Skin"},
        evos: ["seamunian"],
	heightm: 1.1,
	weightkg: 10.2,
	color: "Blue",
	eggGroups: ["Water 1", "Monster"],
	},
   seamunian: {
        num: 1000008,
        species: "Seamunian",
        types: ["Water"],
        baseStats: {hp: 59, atk: 72, def: 86, spa: 95, spd: 74, spe: 72},
       abilities: {0: "Torrent", H: "Dry Skin"},
        evos: ["poseidocze"],
        prevo: "aquario",
	heightm: 1.8,
	weightkg: 36.2,
	color: "Blue",
	eggGroups: ["Water 1", "Monster"],
	},
   poseidocze: {
        num: 1000009,
        species: "Poseidocze",
        types: ["Water", "Electric"],
        baseStats: {hp: 86, atk: 103, def: 70, spa: 120, spd: 78, spe: 91},
        abilities: {0: "Torrent", H: "Dry Skin"},
        prevo: "seamunian",
	heightm: 3.9,
	weightkg: 100.2,
	color: "Blue",
	eggGroups: ["Water 1", "Monster"],
	},
   avislon: {
        num: 1000010,
        species: "Avislon",
        types: ["Psychic", "Flying"],
        baseStats: {hp: 28, atk: 40, def: 19, spa: 25, spd: 68, spe: 75},
        abilities: {0: "Keen Eye", 1: "Big Pecks", H: "Aerilate"},
        evos: ["avislorion"],
	},
   avislorion: {
        num: 1000011,
        species: "Avislorion",
        types: ["Psychic", "Flying"],
        baseStats: {hp: 39, atk: 56, def: 38, spa: 40, spd: 75, spe: 88},
        abilities: {0: "Keen Eye", 1: "Big Pecks", H: "Aerilate"},
        evos: ["avissolorian"],
        prevo: "avislon",
        },
   avissolorian: {
        num: 1000012,
        species: "Avissolorian",
        types: ["Psychic", "Flying"],
        baseStats: {hp: 74, atk: 89, def: 64, spa: 71, spd: 110, spe: 122},
        abilities: {0: "Keen Eye", 1: "Big Pecks", H: "Aerilate"},
        prevo: "avislorion",
        },
   buglian: {
        num: 1000013,
        species: "Buglian",
        types: ["Bug"],
        baseStats: {hp: 22, atk: 11, def: 36, spa: 19, spd: 60, spe: 44},
        abilities: {0: "Shield Dust", 1: "Run Away", H: "Poison Point"},
        evos: ["cocoonian"],
        },
   cocoonian: {
        num: 1000014,
        species: "Cocoonian",
        types: ["Bug"],
        baseStats: {hp: 56, atk: 25, def: 70, spa: 21, spd: 78, spe: 56},
        abilities: {0: "Shed Skin", H: "Poison Point"},
        evos: ["butternian"],
        prevo: "buglian",
        },
   butternian: {
        num: 1000015,
        species: "Butternian",
        types: ["Bug", "Psychic"],
        baseStats: {hp: 82, atk: 65, def: 54, spa: 101, spd: 120, spe: 95},
        abilities: {0: "Tinted Lens", H: "Adaptability"},
        prevo: "cocoonian",
        },
   menebrus: {
        num: 1000016,
        species: "Menebrus",
        types: ["Dark", "Electric"],
        baseStats: {hp: 28, atk: 55, def: 60, spa: 38, spd: 70, spe: 42},
        abilities: {0: "Prankster", 1: "Cold Blood", H: "Motor Drive"},
        evos: ["dillyabrus"],
        },
   dillyabrus: {
        num: 1000017,
        species: "Dillyabrus",
        types: ["Dark", "Electric"],
        baseStats: {hp: 65, atk: 59, def: 77, spa: 46, spd: 100, spe: 51},
        abilities: {0: "Prankster", 1: "Cold Blood", H: "Motor Drive"},
        evos: ["tenebrus"],
        prevo: "menebrus",
        },
   tenebrus: {
        num: 1000018,
        species: "Tenebrus",
        types: ["Dark", "Electric"],
        baseStats: {hp: 110, atk: 72, def: 121, spa: 59, spd: 130, spe: 70},
        abilities: {0: "Prankster", 1: "Cold Blood", H: "Motor Drive"},
        prevo: "dillyabrus",
        },
    caniki: {
        num: 1000019,
        species: "Caniki",
        types: ["Normal"],
        baseStats: {hp: 45, atk: 32, def: 70, spa: 25, spd: 41, spe: 66},
        abilities: {0: "Pickup", 1: "Strong Jaw", H: "Run Away"},
        evos: ["cabotieki"],
        },
    cabotieki: {
        num: 1000020,
        species: "Cabotieki",
        types: ["Normal", "Fighting"],
        baseStats: {hp: 65, atk: 70, def: 75, spa: 50, spd: 70, spe: 101},
        abilities: {0: "Pickup", 1: "Strong Jaw", H: "Run Away"},
        prevo: "caniki",
        },
    foxini: {
        num: 1000021,
        species: "Foxini",
        types: ["Fire", "Dark"],
        baseStats: {hp: 85, atk: 45, def: 70, spa: 70, spd: 35, spe: 110},
        abilities: {0: "Flash Fire", H: "Moxie"},
        evos: ["kyubini"],
        },
    kyubini: {
        num: 1000022,
        species: "Kyubini",
        types: ["Fire", "Dark"],
        baseStats: {hp: 115, atk: 75, def: 75, spa: 100, spd: 56, spe: 120},
        abilities: {0: "Flash Fire", H: "Moxie"},
        prevo: "foxini",
        },
    medusia: {
        num: 1000023,
        species: "Medusia",
        types: ["Poison", "Rock"],
        baseStats: {hp: 100, atk: 100, def: 56, spa: 110, spd: 70, spe: 80},
        abilities: {0: "Liquid Ooze", H: "Poison Point"},
        evos: ["Does Not Evolve"],
        },
    puncheon: {
        num: 1000024,
        species: "Puncheon",
        types: ["Fighting"],
        baseStats: {hp: 95, atk: 110, def: 65, spa: 65, spd: 130, spe: 60},
        abilities: {0: "Tough Claws", H: "Punchilate"},
        prevo: "eevee",
        },
    zephyreon: {
        num: 1000025,
        species: "Zephyreon",
        types: ["Flying"],
        baseStats: {hp: 65, atk: 65, def: 60, spa: 130, spd: 95, spe: 110},
        abilities: {0: "Gale Wings", H: "Defiant"},
        prevo: "eevee",
        },
    landineon: {
        num: 1000026,
        species: "Landineon",
        types: ["Ground"],
        baseStats: {hp: 130, atk: 110, def: 65, spa: 60, spd: 95, spe: 65},
        abilities: {0: "Sand Stream", H: "Landinate"},
        prevo: "eevee",
        },
    tombeon: {
        num: 1000027,
        species: "Tombeon",
        types: ["Ghost"],
        baseStats: {hp: 110, atk: 60, def: 130, spa: 95, spd: 65, spe: 65},
        abilities: {0: "Cursed Body", H: "Gates of Hell"},
        preevo: "eevee",
        },
    quetzaleon: {
        num: 1000028,
        species: "Quetzaleon",
        types: ["Dragon"],
        baseStats: {hp: 95, atk: 130, def: 60, spa: 65, spd: 65, spe: 110},
        abilities: {0: "Multiscale", H: "Predator"},
        prevo: "eevee",
        },
     lobotohm: {
         num: 1000029,
         species: "Lobotohm",
         types: ["Electric"],
         baseStats: {hp: 65, atk: 60, def: 39, spa: 85, spd: 58, spe: 75},
         abilities: {0: "Lighting Rod", H: "Magnet Pull"},
         evos: ["tegolohm"],
         },
     tegolohm: {
         num: 1000030,
         species: "Tegolohm",
         types: ["Electric", "Steel"],
         baseStats: {hp: 65, atk: 100, def: 64, spa: 98, spd: 79, spe: 110},
         abilities: {0: "Lighting Rod", 1: "Gear Force", H: "Magnet Pull"},
         prevo: "lobotohm",
         },
     lingerspeed: {
         num: 1000031,
         species: "Lingerspeed",
         types: ["Bug"],
         baseStats: {hp: 35, atk: 50, def: 38, spa: 34, spd: 41, spe: 106},
         abilities: {0: "Speed Boost", H: "Leadership"},
         evos: ["fingerspeed"],
         },
     fingerspeed: {
         num: 1000032,
         species: "Fingerspeed",
         types: ["Bug", "Dark"],
         baseStats: {hp: 35, atk: 102, def: 50, spa: 50, spd: 41, spe: 135},
         abilities: {0: "Speed Boost", H: "Leadership"},
         prevo: "lingerspeed",
         },
     medicura: {
         num: 1000033,
         species: "Medicura",
         types: ["Normal", "Fairy"],
         baseStats: {hp: 110, atk: 90, def: 75, spa: 110, spd: 90, spe: 38},
         abilities: {0: "Medicine"},
         evos: ["Does Not Evolve"],
         },
     lovelord: {
         num: 1000034,
         species: "Lovelord",
         types: ["Water", "Fairy"],
         baseStats: {hp: 63, atk: 80, def: 95, spa: 100, spd: 70, spe: 106},
         abilities: {0: "Swift Swim", H: "Hydration"},
         prevo: "luvdisc",
         },
     pimentio: {
         num: 1000035,
         species: "Pimentio",
         types: ["Grass", "Fire"],
         baseStats: {hp: 35, atk: 58, def: 60, spa: 45, spd: 52, spe: 95},
         abilities: {0: "Flash Fire", H: "Chlorophyll"},
         evos: ["arrabiatan"],
         },
     arrabiatan: {
         num: 1000036,
         species: "Arrabiatan",
         types: ["Grass", "Fire"],
         baseStats: {hp: 70, atk: 85, def: 90, spa: 105, spd: 65, spe: 108},
         abilities: {0: "Flash Fire", H: "Chlorophyll"},
         prevo: "pimentio",
         },
     munculu: {
         num: 1000037,
         species: "Munculu",
         types: ["Grass", "Dragon"],
         baseStats: {hp: 20, atk: 60, def: 25, spa: 70, spd: 45, spe: 80},
         abilities: {0: "Swift Swim", 1: "Sheer Force", H: "Dragon Force"},
         evos: ["lorinculus"],
         },
     lorinculus: {
         num: 1000038,
         species: "Lorinculus",
         types: ["Grass", "Dragon"],
         baseStats: {hp: 35, atk: 85, def: 45, spa: 90, spd: 55, spe: 110},
         abilities: {0: "Swift Swim", 1: "Sheer Force", H: "Dragon Force"},
         evos: ["dracunculus"],
         prevo: "munculu",
         },
     dracunculus: {
         num: 1000039,
         species: "Dracunculus",
         types: ["Grass", "Dragon"],
         baseStats: {hp: 70, atk: 140, def: 50, spa: 140, spd: 50, spe: 150},
         abilities: {0: "Swift Swim", 1: "Sheer Force", H: "Dragon Force"},
         prevo: "lorinculus",
         },
     celiantooth: {
         num: 1000040,
         species: "Celiantooth",
         types: ["Rock", "Fire"],
         baseStats: {hp: 60, atk: 90, def: 70, spa: 38, spd: 66, spe: 84},
         abilities: {0: "Rock Head", H: "Battle Armor"},
         evos: ["siciliantooth"],
         },
     siciliantooth: {
         num: 1000041,
         species: "Siciliantooth",
         types: ["Rock", "Fire"],
         baseStats: {hp: 90, atk: 120, def: 74, spa: 50, spd: 82, spe: 99},
         abilities: {0: "Rock Head", H: "Battle Armor"},
         prevo: "celiantooth",
         },
     doomiraptor: {
         num: 1000042,
         species: "Doomiraptor",
         types: ["Rock", "Ghost"],
         baseStats: {hp: 65, atk: 71, def: 78, spa: 72, spd: 65, spe: 59},
         abilities: {0: "Cursed Body", H: "Mummy"},
         evos: ["brachiodoom"],
         },
     brachiodoom: {
         num: 1000043,
         species: "Brachiodoom",
         types: ["Rock", "Ghost"],
         baseStats: {hp: 107, atk: 98, def: 105, spa: 95, spd: 90, spe: 46},
         abilities: {0: "Cursed Body", H: "Mummy"},
         prevo: "doomiraptor",
         },
     duniliar: {
         num: 1000044,
         species: "Duniliar",
         types: ["Ground"],
         baseStats: {hp: 65, atk: 55, def: 70, spa: 65, spd: 70, spe: 28},
         abilities: {0: "Sand Rush", 1: "Sand Stream", H: "Sand Force"},
         evos: ["duniliandinar"],
         },
    duniliandinar: {
         num: 1000045,
         species: "Duniliandinar",
         types: ["Ground"],
         baseStats: {hp: 100, atk: 90, def: 75, spa: 85, spd: 90, spe: 65},
         abilities: {0: "Sand Rush", 1: "Sand Stream", H: "Sand Force"},
         prevo: "duniliar",
         },
    helldragoon: {
         num: 1000046,
         species: "Helldragoon",
         types: ["Ghost", "Dragon"],
         baseStats: {hp: 98, atk: 124, def: 75, spa: 110, spd: 75, spe: 85},
         abilities: {0: "Fiendish Shield", H: "Telepathy"},
         evos: ["Does Not Evolve"],
         },
     heavendragoon: {
         num: 1000047,
         species: "Heavendragoon",
         types: ["Fairy", "Dragon"],
         baseStats: {hp: 98, atk: 110, def: 75, spa: 124, spd: 75, spe: 85},
         abilities: {0: "Heavenly Shield", H: "Telepathy"},
         evos: ["Does Not Evolve"],
         },
     chillifish: {
         num: 1000048,
         species: "Chillifish",
         types: ["Water", "Ice"],
         baseStats: {hp: 62, atk: 46, def: 70, spa: 52, spd: 60, spe: 36},
         abilities: {0: "Water Absorb", H: "Ice Body"},
         evos: ["icynifish"],
         },
     icynifish: {
         num: 1000049,
         species: "Icynifish",
         types: ["Water", "Ice"],
         baseStats: {hp: 77, atk: 71, def: 85, spa: 64, spd: 71, spe: 50},
         abilities: {0: "Water Absorb", H: "Ice Body"},
         evos: ["coldiafish"],
         prevo: "chillifish",
         },
     coldiafish: {
         num: 1000050,
         species: "Coldiafish",
         types: ["Water", "Ice"],
         baseStats: {hp: 92, atk: 97, def: 101, spa: 82, spd: 86, spe: 71},
         abilities: {0: "Water Absorb", H: "Ice Body"},
         prevo: "icynifish",
         },
     kittyrius: {
         num: 1000051,
         species: "Kittyrius",
         types: ["Fire", "Ghost"],
         baseStats: {hp: 35, atk: 61, def: 32, spa: 70, spd: 52, spe: 68},
         abilities: {0: "Flash Fire", 1: "Technician", H: "Insomnia"},
         evos: ["cerberinius"],
         },
     cerberinius: {
         num: 1000052,
         species: "Cerberinius",
         types: ["Fire", "Ghost"],
         baseStats: {hp: 70, atk: 100, def: 47, spa: 98, spd: 60, spe: 84},
         abilities: {0: "Flash Fire", 1: "Technician", H: "Insomnia"},
         prevo: "kittyrius",
         },
     venominous: {
         num: 1000053,
         species: "Venominous",
         types: ["Poison"],
         baseStats: {hp: 85, atk: 90, def: 115, spa: 111, spd: 68, spe: 101},
         abilities: {0: "Shed Skin", 1: "Liquid Ooze", H: "Poison Touch"},
         evos: ["Does Not Evolve"],
         },
     angelin: {
         num: 1000054,
         species: "Angelin",
         types: ["Fairy", "Flying"],
         baseStats: {hp: 38, atk: 36, def: 70, spa: 98, spd: 51, spe: 62},
         abilities: {0: "Pixilate", H: "Aerilate"},
         evos: ["archangelin", "darkangelin"],
         },
     archangelin: {
         num: 1000055,
         species: "Archangelin",
         types: ["Fairy", "Flying"],
         baseStats: {hp: 60, atk: 40, def: 75, spa: 117, spd: 72, spe: 84},
         abilities: {0: "Fairy Aura", H: "Aerilate"},
         prevo: "angelin",
         },
     darkangelin: {
         num: 1000056,
         species: "Darkangelin",
         types: ["Dark", "Flying"],
         baseStats: {hp: 60, atk: 117, def: 72, spa: 40, spd: 75, spe: 84},
         abilities: {0: "Dark Aura", H: "Aerilate"},
         prevo: "angelin",
         },
     tintinar: {
         num: 1000057,
         species: "Tintinar",
         types: ["Steel"],
         baseStats: {hp: 30, atk: 55, def: 40, spa: 70, spd: 52, spe: 25},
         abilities: {0: "Clear Body", H: "Levitate"},
         evos: ["hourglinar"],
         },
     hourglinar: {
         num: 1000058,
         species: "Hourglinar",
         types: ["Steel"],
         baseStats: {hp: 50, atk: 71, def: 48, spa: 78, spd: 65, spe: 40},
         abilities: {0: "Clear Body", H: "Levitate"},
         evos: ["clockinar"],
         prevo: "tintinar",
         },
     clockinar: {
         num: 1000059,
         species: "Clockinar",
         types: ["Steel"],
         baseStats: {hp: 75, atk: 89, def: 60, spa: 101, spd: 84, spe: 51},
         abilities: {0: "Clear Body", H: "Levitate"},
         prevo: "hourglinar",
         },
     emolgor: {
         num: 1000060,
         species: "Emolgor",
         types: ["Electric", "Flying"],
         baseStats: {hp: 65, atk: 90, def: 81, spa: 101, spd: 84, spe: 116},
         abilities: {0: "Static", H: "Motor Drive"},
         prevo: "emolga",
         },
     drapionord: {
         num: 1000061,
         species: "Drapionord",
         types: ["Poison", "Dark"],
         baseStats: {hp: 85, atk: 112, def: 124, spa: 60, spd: 95, spe: 103},
         abilities: {0: "Battle Armor", 1: "Sniper", H: "Keen Eye"},
         prevo: "drapion",
         },
     miniskhan: {
         num: 1000062,
         species: "Miniskhan",
         types: ["Normal"],
         baseStats: {hp: 62, atk: 68, def: 56, spa: 30, spd: 56, spe: 71},
         abilities: {0: "Early Bird", 1: "Scrappy", H: "Inner Focus"},
         evos: ["kangaskhan"],
         },
     athenie: {
         num: 1000063,
         species: "Athenie",
         types: ["Fairy"],
         baseStats: {hp: 100, atk: 100, def: 100, spa: 100, spd: 100, spe: 100},
         abilities: {0: "Goddess Aura"},
         evos: ["Does Not Evolve"],
         },
     hellmaster: {
         num: 1000064,
         species: "Hellmaster",
         types: ["Ghost", "Dark"],
         baseStats: {hp: 117, atk: 131, def: 98, spa: 123, spd: 107, spe: 104},
         abilities: {0: "Gates of Hell"},
         evos: ["Does Not Evolve"],
         },
     heavenmaster: {
         num: 1000065,
         species: "Heavenmaster",
         types: ["Fairy", "Grass"],
         baseStats: {hp: 117, atk: 123, def: 107, spa: 131, spd: 98, spe: 104},
         abilities: {0: "Gates of Heaven"},
         evos: ["Does Not Evolve"],
         },
     venusidess: {
         num: 1000066,
         species: "Venusidess",
         types: ["Normal"],
         baseStats: {hp: 101, atk: 110, def: 78, spa: 110, spd: 71, spe: 110},
         abilities: {0: "Cute Charm", H: "Pressure"},
         evos: ["Does Not Evolve"],
         },
     chronogod: {
         num: 1000067,
         species: "Chronogod",
         types: ["Psychic","Steel"],
         baseStats: {hp: 86, atk: 137, def: 65, spa: 85, spd: 102, spe: 105},
         abilities: {0: "Technician", H: "Regenerator"},
         evos: ["Does Not Evolve"],
         },
     gaiadiness: {
         num: 1000068,
         species: "Gaiadiness",
         types: ["Ground","Grass"],
         baseStats: {hp: 101, atk: 40, def: 145, spa: 59, spd: 170, spe: 65},
         abilities: {0: "Poison Heal", H: "Magic Guard"},
         evos: ["Does Not Evolve"],
         },
     zeusidian: {
         num: 1000069,
         species: "Zeusidian",
         types: ["Electric","Flying"],
         baseStats: {hp: 90, atk: 105, def: 85, spa: 140, spd: 70, spe: 110},
         abilities: {0: "Galvanize", H: "Aerilate"},
         evos: ["Does Not Evolve"],
         },
     heracladian: {
         num: 1000070,
         species: "Heracladian",
         types: ["Fighting","Steel"],
         baseStats: {hp: 105, atk: 140, def: 100, spa: 50, spd: 100, spe: 105},
         abilities: {0: "Iron Fist", 1: "Unburden", H: "Reckless"},
         evos: ["Does Not Evolve"],
         },
     divernoon: {
         num: 1000071,
         species: "Divernoon",
         types: ["Dragon","Steel"],
         baseStats: {hp: 56, atk: 71, def: 100, spa: 50, spd: 65, spe: 45},
         abilities: {0: "Tough Claws", 1: "Mega Launcher", H: "Filter"},
         evos: ["juggernaut"],
         },
     juggernaut: {
         num: 1000072,
         species: "Juggernaut",
         types: ["Dragon","Steel"],
         baseStats: {hp: 86, atk: 115, def: 120, spa: 130, spd: 85, spe: 60},
         abilities: {0: "Tough Claws", 1: "Mega Launcher", H: "Filter"},
         preevo: "divernoon",
         },
      peralarep: {
         num: 1000073,
         species: "Peralarep",
         types: ["Normal","Psychic"],
         baseStats: {hp: 90, atk: 105, def: 95, spa: 120, spd: 75, spe: 110},
         abilities: {0: "Inner Focus", 1: "Magic Bounce", H: "Sap Sipper"},
         preevo: "girafarig",
         },
      stanttrio: {
         num: 1000074,
         species: "Stanttrio",
         types: ["Normal","Fighting"],
         baseStats: {hp: 88, atk: 125, def: 82, spa: 105, spd: 80, spe: 115},
         abilities: {0: "Intimidate", 1: "Adaptability", H: "Sap Sipper"},
         preevo: "stantler",
         },
      spooksparce: {
         num: 1000075,
         species: "Spooksparce",
         types: ["Normal","Ghost"],
         baseStats: {hp: 150, atk: 90, def: 90, spa: 80, spd: 85, spe: 55},
         abilities: {0: "Serene Grace", 1: "Cursed Body", H: "Magic Guard"},
         preevo: "dunsparce",
         },
      depthduck: {
         num: 1000076,
         species: "Depthduck",
         types: ["Water","Psychic"],
         baseStats: {hp: 90, atk: 92, def: 88, spa: 120, spd: 95, spe: 105},
         abilities: {0: "Drizzle", 1: "Cloud Nine", H: "Swift Swim"},
         preevo: "golduck",
         },
      thatu: {
         num: 1000077,
         species: "Thatu",
         types: ["Psychic","Flying"],
         baseStats: {hp: 95, atk: 80, def: 90, spa: 135, spd: 95, spe: 95},
         abilities: {0: "Synchronize", 1: "Psychic Surge", H: "Magic Bounce"},
         preevo: "xatu",
         },
      naipiat: {
         num: 1000078,
         species: "Naipiat",
         types: ["Poison","Dark"],
         baseStats: {hp: 95, atk: 125, def: 80, spa: 75, spd: 100, spe: 100},
         abilities: {0: "Intimidate", 1: "Shed Skin", H: "Strong Jaw"},
         preevo: "arbok",
	 	 },
      monstrosect: {
         num: 1000079,
         species: "Monstrosect",
         types: ["Bug","Dark"],
         baseStats: {hp: 75, atk: 130, def: 95, spa: 83, spd: 120, spe: 65},
         abilities: {0: "Effect Spore", 1: "Dry Skin", H: "Intimidate"},
         preevo: "parasect",
         },
       sewgramp: {
         num: 1000080,
         species: "Sewgramp",
         types: ["Water","Ice"],
         baseStats: {hp: 100, atk: 85, def: 95, spa: 115, spd: 110, spe: 87},
         abilities: {0: "Thick Fat", 1: "Snow Warning", H: "Slush Rush"},
         preevo: "dewgong",
         },
       lordmime: {
         num: 1000081,
         species: "Lordmime",
         types: ["Psychic","Fairy"],
         baseStats: {hp: 110, atk: 35, def: 105, spa: 110, spd: 135, spe: 95},
         abilities: {0: "Regenerator", 1: "Filter", H: "Technician"},
         preevo: "mrmime",
         },
	levrokiss: {
         num: 1000082,
         species: "Levrokiss",
         types: ["Ice","Psychic"],
         baseStats: {hp: 85, atk: 55, def: 65, spa: 140, spd: 110, spe: 115},
         abilities: {0: "Supervision", 1: "Forewarn", H: "Dry Skin"},
         preevo: "jynx",
	 	},
	harfairy: {
         num: 1000083,
         species: "Harfairy",
         types: ["Fairy","Flying"],
         baseStats: {hp: 130, atk: 50, def: 90, spa: 106, spd: 116, spe: 90},
         abilities: {0: "Magic Guard", 1: "Keen Eye", H: "Tinted Lens"},
         preevo: "noctowl",
	 },
	 ledistruggle: {
         num: 1000084,
         species: "Ledistruggle",
         types: ["Bug","Fighting"],
         baseStats: {hp: 80, atk: 65, def: 70, spa: 55, spd: 130, spe: 100},
         abilities: {0: "Huge Power", 1: "Early Bird", H: "Iron Fist"},
         preevo: "ledian",
	 },
	 ironledy: {
         num: 1000085,
         species: "Ironledy",
         types: ["Bug","Steel"],
         baseStats: {hp: 90, atk: 80, def: 105, spa: 25, spd: 130, spe: 65},
         abilities: {0: "Steelworker", 1: "Light Metal", H: "Filter"},
         preevo: "ledian",
         },
	 coldiledy: {
         num: 1000086,
         species: "Coldiledy",
         types: ["Bug","Ice"],
         baseStats: {hp: 70, atk: 35, def: 60, spa: 115, spd: 120, spe: 95},
         abilities: {0: "Absolute Zero", 1: "Early Bird", H: "Mountaineer"},
         preevo: "ledian",
         },
	 arachnodeath: {
         num: 1000087,
         species: "Arachnodeath",
         types: ["Bug","Ghost"],
         baseStats: {hp: 75, atk: 125, def: 80, spa: 70, spd: 90, spe: 65},
         abilities: {0: "Renegate", 1: "Reaper Slice", H: "Sniper"},
         preevo: "ariados",
         },
	 sunflorest: {
         num: 1000088,
         species: "Sunflorest",
         types: ["Grass","Fire"],
         baseStats: {hp: 95, atk: 125, def: 65, spa: 125, spd: 95, spe: 50},
         abilities: {0: "Chlorophyll", 1: "Solar Power", H: "Drought"},
         preevo: "sunflora",
         },
	 sowoulfish: {
         num: 1000089,
         species: "Sowoulfish",
         types: ["Water","Poison"],
         baseStats: {hp: 80, atk: 120, def: 100, spa: 55, spd: 75, spe: 105},
         abilities: {0: "Toxic Emanations", 1: "Levitate", H: "Intimidate"},
         preevo: "qwilfish",
         },
	crystalcargo: {
         num: 1000090,
         species: "Crystalcargo",
         types: ["Fire","Ice"],
         baseStats: {hp: 90, atk: 55, def: 130, spa: 125, spd: 90, spe: 70},
         abilities: {0: "Ice Body", 1: "Flame Body", H: "Weak Armor"},
         preevo: "magcargo",
         },
	 lupustyena: {
         num: 1000091,
         species: "Lupustyena",
         types: ["Dark","Fairy"],
         baseStats: {hp: 80, atk: 120, def: 80, spa: 65, spd: 75, spe: 95},
         abilities: {0: "Intimidate", 1: "Adaptability", H: "Moxie"},
         preevo: "mightyena",
         },
	 phenilow: {
         num: 1000092,
         species: "Phenilow",
         types: ["Normal","Fire"],
         baseStats: {hp: 70, atk: 95, def: 75, spa: 100, spd: 60, spe: 140},
         abilities: {0: "Sheer Force", H: "Scrappy"},
         preevo: "swellow",
         },
	 diplusle: {
         num: 1000093,
         species: "Diplusle",
         types: ["Electric","Fairy"],
         baseStats: {hp: 80, atk: 60, def: 55, spa: 105, spd: 85, spe: 115},
         abilities: {0: "Plus", H: "Mist Skimmer"},
         preevo: "plusle",
         },
	 diminun: {
         num: 1000094,
         species: "Diminun",
         types: ["Electric","Fairy"],
         baseStats: {hp: 80, atk: 50, def: 50, spa: 105, spd: 100, spe: 115},
         abilities: {0: "Minus", H: "Mist Skimmer"},
         preevo: "minun",
         },
	 shittowalot: {
         num: 1000095,
         species: "Shittowalot",
         types: ["Poison","Ground"],
         baseStats: {hp: 115, atk: 98, def: 93, spa: 83, spd: 108, spe: 75},
         abilities: {0: "Levitate", 1: "Sticky Hold", H: "Gluttony"},
         preevo: "swalot",
         },
	 dizzypinda: {
         num: 1000096,
         species: "Dizzypinda",
         types: ["Normal","Fighting"],
         baseStats: {hp: 80, atk: 110, def: 80, spa: 110, spd: 80, spe: 110},
         abilities: {0: "Own Tempo", 1: "Tangled Feet", H: "Contrary"},
         preevo: "spinda",
         },
	 brainypinda: {
         num: 1000097,
         species: "Brainypinda",
         types: ["Normal","Psychic"],
         baseStats: {hp: 90, atk: 80, def: 120, spa: 120, spd: 80, spe: 90},
         abilities: {0: "Own Tempo", 1: "Tangled Feet", H: "Miracle Dash"},
         preevo: "spinda",
	     },
	 cicocacturne: {
         num: 1000098,
         species: "Cicocacturne",
         types: ["Grass","Dark"],
         baseStats: {hp: 85, atk: 135, def: 70, spa: 135, spd: 70, spe: 70},
         abilities: {0: "Dark Aura", H: "Water Absorb"},
         preevo: "cacturne",
         },
	 duocleon: {
         num: 1000099,
         species: "Duocleon",
         types: ["Normal"],
         baseStats: {hp: 80, atk: 105, def: 80, spa: 70, spd: 130, spe: 70},
         abilities: {0: "Duosweep", H: "Protean"},
         preevo: "kecleon",
         },
	 frutipius: {
         num: 1000100,
         species: "Frutipius",
         types: ["Grass","Water"],
         baseStats: {hp: 114, atk: 80, def: 95, spa: 94, spd: 107, spe: 67},
         abilities: {0: "Swift Swim", 1: "Rain Power", H: "Harvest"},
         preevo: "tropius",
         },
	 ruinicanth: {
         num: 1000101,
         species: "Ruinicanth",
         types: ["Rock","Water"],
         baseStats: {hp: 110, atk: 115, def: 145, spa: 50, spd: 85, spe: 75},
         abilities: {0: "Swift Swim", 1: "Rock Head", H: "Rain Power"},
         preevo: "relicanth",
         },
	 mastrikune: {
         num: 1000102,
         species: "Maestrikune",
         types: ["Bug","Fighting"],
         baseStats: {hp: 97, atk: 100, def: 71, spa: 60, spd: 61, spe: 90},
         abilities: {0: "Swarm", H: "Technician"},
         preevo: "kricketune",
         },
	 vespiking: {
         num: 1000103,
         species: "Vespiking",
         types: ["Bug","Dark"],
         gender: "M",
         baseStats: {hp: 90, atk: 120, def: 97, spa: 120, spd: 97, spe: 70},
         abilities: {0: "Pressure", H: "Hustle"},
         preevo: "combee",
         },
	 rumblesquirchu: {
         num: 1000104,
         species: "Rumblesquirchu",
         types: ["Electric","Fighting"],
         baseStats: {hp: 70, atk: 120, def: 60, spa: 120, spd: 60, spe: 120},
         abilities: {0: "Punchilate", 1:"Keen Eye", H: "Volt Absorb"},
         preevo: "pachirisu",
         },
	 upritot: {
         num: 1000104,
         species: "Upritot",
         types: ["Normal","Flying"],
         baseStats: {hp: 96, atk: 75, def: 65, spa: 117, spd: 62, spe: 116},
         abilities: {0: "Cacophony", 1:"Tangled Feet", H: "Big Pecks"},
         preevo: "chatot",
	     },
	 rootonny: {
         num: 1000105,
         species: "Rootonny",
         types: ["Plante","Dragon"],
         baseStats: {hp: 129, atk: 125, def: 102, spa: 110, spd: 102, spe: 16},
         abilities: {0: "Intimidate", H: "Root Block"},
         preevo: "carnivine"
         },
	 darkyneon: {
         num: 1000106,
         species: "Darkyneon",
         types: ["Water","Dark"],
         baseStats: {hp: 94, atk: 104, def: 91, spa: 89, spd: 96, spe: 111},
         abilities: {0: "Swift Swim", 1:"Defiant", H: "Water Veil"},
         preevo: "lumineon",
	     },
	 dunkwoobat: {
         num: 1000107,
         species: "Dunkwoobat",
         types: ["Psychic","Flying"],
         baseStats: {hp: 99, atk: 40, def: 95, spa: 96, spd: 110, spe: 124},
         abilities: {0: "Unaware", 1:"Wonder Skin", H: "Simple"},
         preevo: "swoobat",
	     },
	 rushsculinbluestriped: {
         num: 1000108,
         species: "Rushsculinbluestriped",
         types: ["Water","Rock"],
         baseStats: {hp: 100, atk: 132, def: 95, spa: 90, spd: 75, spe: 98},
         abilities: {0: "Rock Head", 1:"Adaptability", H: "Mold Breaker"},
         preevo: "basculinbluestriped",
	     },
	 rushsculin: {
         num: 1000109,
         species: "Rushsculin",
         types: ["Water","Steel"],
         baseStats: {hp: 90, atk: 132, def: 75, spa: 90, spd: 75, spe: 128},
         abilities: {0: "Rock Head", 1:"Adaptability", H: "Mold Breaker"},
         preevo: "basculin",
	     },
	 swampractus: {
         num: 1000110,
         species: "Swampractus",
         types: ["Grass","Water"],
         baseStats: {hp: 95, atk: 106, def: 82, spa: 130, spd: 87, spe: 70},
         abilities: {0: "Swift Swim", 1:"Chlorophyll", H: "Rain Power"},
         preevo: "maractus",
	     },
	 macrafty: {
	     num: 100111,
	     species: "Macrafty",
	     types: ["Dark", "Fighting"],
	     baseStats: {hp: 85, atk: 115, def: 125, spa: 55, spd: 125, spe: 83},
	     abilities: {0: "Shed Skin", 1: "Moxie", H: "Intimidate"},
	     prevo: "scrafty",
	     },
	 shockifisk: {
	     num: 100112,
	     species: "Shockifisk",
	     types: ["Ground", "Electric"],
	     baseStats: {hp: 119, atk: 71, def: 114, spa: 95, spd: 122, spe: 45},
	     abilities: {0: "Static", 1: "Limber", H: "Rough Skin"},
	     preevo: "stunfisk",
	     },
	 druddigonional: {
	     num: 100113,
	     species: "Druddigonional",
	     types: ["Dragon","Poison"],
	     baseStats: {hp: 87, atk: 135, def: 100, spa: 60, spd: 110, spe: 103},
	     abilities: {0: "Rough Skin", 1: "Sheer Force", H: "Mold Breaker"},
	     preevo: "druddigon",
	     },
	 heatvinemor: {
	     num: 100114,
	     species: "Heatvinemor",
	     types: ["Fire","Grass"],
	     baseStats: {hp: 105, atk: 112, def: 76, spa: 130, spd: 86, spe: 80},
	     abilities: {0: "Gluttony", 1: "Flash Fire", H: "No Guard"},
	     preevo: "heatmor",
	     },
	 furfroulove: {
	     num: 100115,
	     species: "Furfroulove",
	     types: ["Normal","Fairy"],
	     baseStats: {hp: 105, atk: 95, def: 80, spa: 70, spd: 115, spe: 122},
	     abilities: {0: "Fur Coat"},
	     preevo: "furfrou",
	     },
	 furfrouhate: {
	     num: 100116,
	     species: "Furfrouhate",
	     types: ["Normal","Ghost"],
	     baseStats: {hp: 95, atk: 105, def: 90, spa: 80, spd: 105, spe: 112},
	     abilities: {0: "Fur Coat"},
	     preevo: "furfrou",
	     },
	 psychowstic: {
	     num: 100117,
	     species: "Psychowstic",
	     types: ["Psychic"],
	     gender: "M",
	     baseStats: {hp: 94, atk: 53, def: 91, spa: 128, spd: 91, spe: 114},
	     abilities: {0: "Keen Eye", 1: "Psychic Surge", H: "Prankster"},
	     preevo: "meowstic",
	     },
	 ladybowstic: {
	    num: 100118,
	    species: "Ladybowstic",
	    types: ["Psychic","Fighting"],
	    gender: "F",
	    baseStats: {hp: 94, atk: 48, def: 81, spa: 138, spd: 91, spe: 124},
	    abilities: {0: "Keen Eye", 1: "Miracle Dash", H: "Competitive"},
	    preevo: "meowsticf",
	    },
	 voltaikiolisk: {
	    num: 100119,
	    species: "Voltaikiolisk",
	    types: ["Normal","Electric"],
	    baseStats: {hp: 87, atk: 65, def: 67, spa: 139, spd: 104, spe: 124},
	    abilities: {0: "Rain Power", 1: "Surge Surfer", H: "Solar Power"},
	    preevo: "heliolisk",
	    },
	 qweebombee: {
	    num: 100120,
	    species: "Queebombee",
	    types: ["Bug","Fairy"],
	    baseStats: {hp: 90, atk: 65, def: 70, spa: 125, spd: 80, spe: 139},
	    abilities: {0: "Simple", 1: "Shield Dust", H: "Dazzling"},
	    preevo: "ribombee",
	    },
	 shikoniitic: {
	    num: 100121,
	    species: "Shikoniitic",
	    types: ["Grass","Fairy"],
	    baseStats: {hp: 75, atk: 55, def: 100, spa: 115, spd: 110, spe: 40},
	    abilities: {0: "Prankster", 1: "Effect Spore", H: "Rain Dish"},
	    preevo: "shiinotic",
	    },
	 bukumumuku: {
	    num: 100122,
	    species: "bukumumuku",
	    types: ["Water"],
	    baseStats: {hp: 75, atk: 70, def: 155, spa: 50, spd: 150, spe: 10},
	    abilities: {0: "Innards Out", 1: "Unaware"},
	    preevo: "pyukumuku",
	   },
	 giantomala: {
	   num: 100123,
	   species: "Giantomala",
	   types: ["Normal"],
	   baseStats: {hp: 85, atk: 140, def: 85, spa: 80, spd: 120, spe: 85},
	   abilities: {0: "Comatose"},
	   preevo: "komala",
	   },
	 hitogedemaru: {
	   num: 100124,
	   species: "Hitogedemaru",
	   types: ["Electric","Steel"],
	   baseStats: {hp: 85, atk: 128, def: 78, spa: 45, spd: 93, spe: 121},
	   abilities: {0: "Iron Barbs", 1: "Gear Force", H: "Sturdy"},
	   preevo: "togedemaru",
	   },
	 orianxish: {
	   num: 100125,
	   species: "Orianxish",
	   types: ["Psychic", "Water"],
	   baseStats: {hp: 88, atk: 130, def: 80, spa: 75, spd: 95, spe: 122},
	   abilities: {0: "Dazzling", 1: "Strong Jaw", H: "Psychic Surge"},
	   preevo: "bruxish",
	   },
	 dumbiduck: {
	   num: 100126,
	   species: "Dumbiduck",
	   types: ["Normal","Flying"],
	   baseStats: {hp: 77, atk: 130, def: 75, spa: 78, spd: 77, spe: 100},
	   abilities: {0: "Keen Eye", 1: "Sheer Force", H: "Defiant"},
	   preevo: "farfetch'd",
	   },
	 octilmar: {
	   num: 100127,
	   species: "Octilmar",
	   types: ["Water","Poison"],
	   baseStats: {hp: 90, atk: 125, def: 87, spa: 125, spd: 87, spe: 70},
	   abilities: {0: "Suction Cups", 1: "Sniper", H: "Moody"},
	   preevo: "octillery",
	   },
	 asterosmos: {
	    num: 100128,
	   species: "Asterosmos",
	   types: ["Ghost","Dark"],
	   baseStats: {hp: 51, atk: 109, def: 43, spa: 187, spd: 61, spe: 119},
	   abilities: {0: "Beast Boost"},
      },
	 saltydrong: {
       num: 100129,
	   species: "Saltydrong",
	   types: ["Water","Steel"],
	   baseStats: {hp: 81, atk: 121, def: 57, spa: 97, spd: 193, spe: 21},
	   abilities: {0: "Beast Boost"},
	   },
	 rouxdounion: {
       num: 100130,
	   species: "Rouxdounion",
	   types: ["Flying","Fire"],
	   baseStats: {hp: 63, atk: 129, def: 131, spa: 83, spd: 73, spe: 91},
	   abilities: {0: "Beast Boost"},
	   },
	 mystishovel: {
      num: 100131,
	   species: "Mystishovel",
	   types: ["Ground","Fairy"],
	   baseStats: {hp: 67, atk: 143, def: 83, spa: 59, spd: 127, spe: 91},
	   abilities: {0: "Beast Boost"},
	   },
	   trofearow: {
		num: 100132,
		species: "Trofearow",
		types: ["Normal", "Flying"],
		baseStats: {hp: 82, atk: 110, def: 75, spa: 66, spd: 81, spe: 120},
		abilities: {0: "Keen Eye", H: "Sniper"},
		prevo: "fearow",
		},
	   diglandlash: {
		num: 100133,
		species: "Diglandlash",
		types: ["Ground", "Steel"],
		baseStats: {hp: 85, atk: 120, def: 115, spa: 55, spd: 75, spe: 80},
		abilities: {0: "Sand Veil", H: "Sand Force"},
		prevo: "sandslash",
		},
	   toxinomoth: {
		num: 100134,
		species: "Toxinomoth",
		types: ["Bug", "Poison"],
		baseStats: {hp: 95, atk: 80, def: 85, spa: 110, spd: 100, spe: 110},
		abilities: {0: "Shield Dust", 1: "Tinted Lens", H: "Wonder Skin"},
		prevo: "venomoth",
		},
	   rumblepidash: {
		num: 100135,
		species: "Rumblepidash",
		types: ["Fire", "Fighting"],
		baseStats: {hp: 75, atk: 130, def: 80, spa: 100, spd: 90, spe: 140},
		abilities: {0: "Sheer Force", 1: "Flash Fire", H: "Flame Body"},
		prevo: "rapidash",
		},
	   murinowak: {
		num: 100135,
		species: "Murinowak",
		types: ["Ground", "Fighting"],
		baseStats: {hp: 75, atk: 105, def: 120, spa: 70, spd: 105, spe: 75},
		abilities: {0: "Rock Head", 1: "Lightning Rod", H: "Sheer Force"},
		prevo: "marowak",
		},
	   murinowakalola: {
		num: 100135,
		species: "Murinowak-Alola",
		baseSpecies: "Murinowak",
		forme: "Alola",
		formeLetter: "A",
		types: ["Ghost", "Fighting"],
		baseStats: {hp: 75, atk: 105, def: 120, spa: 70, spd: 105, spe: 75},
		abilities: {0: "Rock Head", 1: "Lightning Rod", H: "Sheer Force"},
		prevo: "marowakalola",
		},
	   weetrizing: {
		num: 100136,
		species: "Weetrizing",
		types: ["Poison", "Fire"],
		baseStats: {hp: 85, atk: 105, def: 140, spa: 100, spd: 90, spe: 85},
		abilities: {0: "Levitate"},
		prevo: "weezing",
		},
	   scottprass: {
		num: 100137,
		species: "Scottprass",
		types: ["Water", "Ice"],
		baseStats: {hp: 150, atk: 105, def: 90, spa: 105, spd: 110, spe: 80},
		abilities: {0: "Water Absorb", 1: "Shell Armor", H: "Lightning Rod"},
		prevo: "lapras",
		},
	   grizzlax: {
		num: 100138,
		species: "Grizzlax",
		types: ["Normal", "Dark"],
		baseStats: {hp: 190, atk: 130, def: 85, spa: 75, spd: 140, spe: 40},
		abilities: {0: "Immunity", 1: "Thick Fat", H: "Gluttony"},
		prevo: "snorlax",
		},
	   shiningturn: {
		num: 100139,
		species: "Shiningturn",
		types: ["Water", "Electric"],
		baseStats: {hp: 145, atk: 63, def: 78, spa: 106, spd: 96, spe: 77},
		abilities: {0: "Illumnate", 1: "Volt Absorb", H: "Water Absorb"},
		prevo: "lanturn",
		},
	   darkaraos: {
		num: 100140,
		species: "Darkaraos",
		types: ["Electric", "Dark"],
		baseStats: {hp: 90, atk: 115, def: 85, spa: 75, spd: 90, spe: 55},
		abilities: {0: "Static", H: "Electric Surge"},
		prevo: "flaaffy",
		},
	   punchuwoodo: {
		num: 100141,
		species: "Punchuwoodo",
		types: ["Rock", "Fighting"],
		baseStats: {hp: 85, atk: 140, def: 100, spa: 30, spd: 75, spe: 70},
		abilities: {0: "Sturdy", 1: "Rock Head", H: "Rattled"},
		prevo: "sudowoodo",
		},
	   kingranbull: {
		num: 100142,
		species: "Kingranbull",
		types: ["Fairy", "Fighting"],
		baseStats: {hp: 110, atk: 145, def: 90, spa: 70, spd: 80, spe: 65},
		abilities: {0: "Intimidate", 1: "Iron Fist", H: "Rattled"},
		prevo: "granbull",
		},
	   ionmantine: {
		num: 100143,
		species: "Ionmantine",
		types: ["Water", "Electric"],
		baseStats: {hp: 110, atk: 60, def: 90, spa: 100, spd: 165, spe: 85},
		abilities: {0: "Water Absorb", 1: "Swift Swim", H: "Volt Absorb"},
		prevo: "mantine",
		},
	   speenoone: {
		num: 100144,
		species: "Speenoone",
		types: ["Normal"],
		baseStats: {hp: 98, atk: 110, def: 91, spa: 40, spd: 81, spe: 125},
		abilities: {0: "Pickup", 1: "Gluttony", H: "Quick Feet"},
		prevo: "linoone",
		},
	   astrock: {
		num: 100146,
		species: "Astrock",
		types: ["Rock", "Psychic"],
		baseStats: {hp: 34, atk: 41, def: 55, spa: 36, spd: 55, spe: 37},
		abilities: {0: "Levitate"},
		evos: ["solrock", "lunatone"],
		},
	   ultimence: {
		num: 100147,
		species: "Ultimence",
		types: ["Dragon", "Fighting"],
		baseStats: {hp: 95, atk: 145, def: 80, spa: 70, spd: 95, spe: 115},
		abilities: {0: "Intimidate", H: "Iron Fist"},
		prevo: "shelgon",
		},
	   bibararel: {
		num: 100148,
		species: "Bibararel",
		types: ["Normal", "Water"],
		baseStats: {hp: 94, atk: 105, def: 75, spa: 70, spd: 90, spe: 101},
		abilities: {0: "Simple", 1: "Unaware", H: "Moody"},
		prevo: "bibarel",
		},
	   floatrazel: {
		num: 100149,
		species: "Floatrazel",
		types: ["Water", "Fighting"],
		baseStats: {hp: 105, atk: 120, def: 70, spa: 125, spd: 75, spe: 130},
		abilities: {0: "Swift Swim", H: "Water Veil"},
		prevo: "floatzel",
		},
	   olderrim: {
		num: 100150,
		species: "Olderrim",
		types: ["Grass", "Fairy"],
		baseStats: {hp: 100, atk: 85, def: 95, spa: 115, spd: 75, spe: 85},
		abilities: {0: "Solar Power"},
		prevo: "cherrim",
		},
	   mismergius: {
		num: 100152,
		species: "Mismergius",
		types: ["Ghost", "Fighting"],
		baseStats: {hp: 75, atk: 115, def: 105, spa: 90, spd: 85, spe: 125},
		abilities: {0: "Guts"},
		prevo: "mismagius",
		},
	   mistergius: {
		num: 100153,
		species: "Mistergius",
		types: ["Ghost", "Dark"],
		baseStats: {hp: 75, atk: 65, def: 85, spa: 140, spd: 120, spe: 125},
		abilities: {0: "Magic Bounce"},
		prevo: "mismagius",
		},
	   chiefkrow: {
		num: 100154,
		species: "Chiefkrow",
		types: ["Dark", "Flying"],
		baseStats: {hp: 125, atk: 120, def: 72, spa: 115, spd: 75, spe: 115},
		abilities: {0: "Insomnia", 1: "Super Luck", H: "Moxie"},
		prevo: "honchkrow",
		},
	   duktank: {
		num: 100155,
		species: "Duktank",
		types: ["Poison", "Dark"],
		baseStats: {hp: 123, atk: 118, def: 77, spa: 111, spd: 61, spe: 94},
		abilities: {0: "Keen Eye", 1: "Stench", H: "Aftermath"},
		prevo: "skuntank",
		},
	   goldong: {
		num: 100156,
		species: "Goldong",
		types: ["Steel", "Psychic"],
		baseStats: {hp: 97, atk: 119, def: 136, spa: 89, spd: 136, spe: 20},
		abilities: {0: "Levitate", 1: "Heatproof", H: "Heavy Metal"},
		prevo: "bronzong",
		},
	   valhallomb: {
		num: 100157,
		species: "Valhallomb",
		types: ["Ghost", "Rock"],
		baseStats: {hp: 70, atk: 112, def: 123, spa: 112, spd: 123, spe: 45},
		abilities: {0: "Pressure", H: "Infiltrator"},
		prevo: "spiritomb",
		},
	   burrowbit: {
		num: 100158,
		species: "Burrowbit",
		types: ["Ground"],
		baseStats: {hp: 90, atk: 65, def: 61, spa: 75, spd: 78, spe: 85},
		abilities: {0: "Pickup", 1: "Cheek Pouch", H: "Huge Power"},
		prevo: "bunnelby",
		},
	   panboo: {
		num: 100159,
		species: "Panboo",
		types: ["Fighting", "Grass"],
		baseStats: {hp: 115, atk: 140, def: 70, spa: 30, spd: 80, spe: 85},
		abilities: {0: "Iron Fist", 1: "Mold Breaker", H: "Grassy Surge"},
		prevo: "pancham",
		},
	   kurisch: {
		num: 100160,
		species: "Kurisch",
		types: ["Fairy", "Psychic"],
		baseStats: {hp: 105, atk: 65, def: 130, spa: 115, spd: 75, spe: 10},
		abilities: {0: "Healer", H: "Magic Bounce"},
		prevo: "spritzee",
		},
	   shushup: {
		num: 100161,
		species: "Shushup",
		types: ["Fairy", "Poison"],
		baseStats: {hp: 91, atk: 120, def: 95, spa: 105, spd: 85, spe: 40},
		abilities: {0: "Liquid Ooze", H: "Toxic Emanations"},
		prevo: "spritzee",
		},
	   swirloodle: {
		num: 100162,
		species: "Swirloodle",
		types: ["Fairy", "Psychic"],
		baseStats: {hp: 80, atk: 115, def: 90, spa: 70, spd: 105, spe: 90},
		abilities: {0: "Aroma Veil", 1: "Unburden", H: "Fur Coat"},
		prevo: "swirlix",
		},
	   calacles: {
		num: 100163,
		species: "Calacles",
		types: ["Psychic", "Dark"],
		baseStats: {hp: 106, atk: 122, def: 108, spa: 73, spd: 85, spe: 83},
		abilities: {0: "Contrary", 1:"Suction Cups", H: "Dark Aura"},
		prevo: "malamar",
		},
	   kelpeen: {
		num: 100164,
		species: "Kelpeen",
		types: ["Poison", "Water"],
		baseStats: {hp: 70, atk: 85, def: 85, spa: 75, spd: 75, spe: 45},
		abilities: {0: "Poison Point", 1:"Poison Touch", H: "Adaptability"},
		evos: ["kelpdra"],
		prevo: "skrelp",
		},
	   kelpdra: {
		num: 100165,
		species: "Kelpdra",
		types: ["Poison", "Dragon"],
		baseStats: {hp: 95, atk: 110, def: 95, spa: 105, spd: 135, spe: 55},
		abilities: {0: "Poison Point", 1:"Poison Touch", H: "Adaptability"},
		prevo: "kelpeen",
		},
	   fuzruff: {
		num: 100166,
		species: "Fuzruff",
		types: ["Normal"],
		baseStats: {hp: 48, atk: 50, def: 41, spa: 60, spd: 31, spe: 70},
		abilities: {0: "Fur Coat"},
		evos: ["furfrou"],
		},
	   clawkencode: {
		num: 100167,
		species: "Clawkencode",
		types: ["Water", "Fighting"],
		baseStats: {hp: 90, atk: 72, def: 87, spa: 135, spd: 71, spe: 50},
		abilities: {0: "Mega Launcher"},
		prevo: "clauncher",
		},
	   repsolar: {
		num: 100168,
		species: "Repsolar",
		types: ["Electric", "Fire"],
		baseStats: {hp: 72, atk: 70, def: 72, spa: 124, spd: 110, spe: 127},
		abilities: {0: "Dry Skin", 1: "Electric Surge", H: "Solar Power"},
		prevo: "heliolisk",
		},
	   hawlito: {
		num: 100169,
		species: "Hawlito",
		types: ["Fighting"],
		baseStats: {hp: 65, atk: 76, def: 51, spa: 56, spd: 43, spe: 96},
		abilities: {0: "Limber", 1: "Unburden", H: "Mold Breaker"},
		evos: ["hawlucha"],
		},
	   hawpeon: {
		num: 100170,
		species: "Hawpeon",
		types: ["Fighting", "Flying"],
		baseStats: {hp: 91, atk: 114, def: 89, spa: 91, spd: 78, spe: 131},
		abilities: {0: "Limber", 1: "Unburden", H: "Mold Breaker"},
		prevo: "hawlucha",
		},
	   denfounee: {
		num: 100171,
		species: "Denfounee",
		types: ["Electric", "Fairy"],
		baseStats: {hp: 85, atk: 65, def: 73, spa: 97, spd: 83, spe: 125},
		abilities: {0: "Cheek Pouch", 1: "Pixilate", H: "Magnetism"},
		prevo: "dedenne",
		},
	   caribur: {
		num: 100172,
		species: "Caribur",
		types: ["Rock", "Fairy"],
		baseStats: {hp: 77, atk: 179, def: 72, spa: 179, spd: 72, spe: 77},
		abilities: {0: "Clear Body", 1: "Serene Grace", H: "Sturdy"},
		prevo: "carbink",
		},
	   carbank: {
		num: 100173,
		species: "Carbank",
		types: ["Rock", "Fairy"],
		baseStats: {hp: 77, atk: 72, def: 179, spa: 72, spd: 179, spe: 77},
		abilities: {0: "Clear Body", 1: "Solid Rock", H: "Sturdy"},
		prevo: "carbink",
		},
	   locklept: {
		num: 100174,
		species: "Locklept",
		types: ["Steel", "Fairy"],
		baseStats: {hp: 82, atk: 110, def: 130, spa: 110, spd: 126, spe: 93},
		abilities: {0: "Prankster", 1: "Iron Barbs", H: "Magician"},
		prevo: "klefki",
		},
	   kledamourki: {
		num: 100175,
		species: "Kledamourki",
		types: ["Steel", "Fairy"],
		baseStats: {hp: 82, atk: 130, def: 126, spa: 130, spd: 110, spe: 93},
		abilities: {0: "Prankster", 1: "Magic Bounce", H: "Magician"},
		prevo: "klefki",
		},
      quagsire: {
		inherit: true,
		abilities: {0: "Water Absorb", H: "Unaware"},
		otherFormes: ["quagsiremega"],
         },
      quagsiremega: {
		num: 195,
		species: "Quagsire-Mega",
		baseSpecies: "Quagsire",
		forme: "Mega",
		formeLetter: "M",
		types: ["Water", "Ground"],
		baseStats: {hp: 95, atk: 125, def: 105, spa: 65, spd: 95, spe: 45},
		abilities: {0: "Landinate"},
         },
      luxray: {
		inherit: true,
		abilities: {0: "Rivalry", 1: "Intimidate", H: "Guts"},
		otherFormes: ["luxraymegaa" , "luxraymegab"],
         },
     luxraymegaa: {
		num: 405,
		species: "Luxray-Mega-A",
		baseSpecies: "Luxray",
		forme: "Mega",
		formeLetter: "M",
		types: ["Electric", "Fighting"],
		baseStats: {hp: 80, atk: 140, def: 99, spa: 105, spd: 89, spe: 110},
		abilities: {0: "Justified"},
         },
     luxraymegab: {
		num: 405,
		species: "Luxray-Mega-B",
		baseSpecies: "Luxray",
		forme: "Mega",
		formeLetter: "M",
		types: ["Electric", "Dark"],
		baseStats: {hp: 80, atk: 160, def: 79, spa: 95, spd: 109, spe: 100},
		abilities: {0: "Strong Jaw"},
         },
     arcanine: {
		inherit: true,
		abilities: {0: "Intimidate", 1: "Flash Fire", H: "Justified"},
		otherFormes: ["arcaninemega"],
         },
     arcaninemega: {
		num: 59,
		species: "Arcanine-Mega",
		baseSpecies: "Arcanine",
		forme: "Mega",
		formeLetter: "M",
		types: ["Fire", "Dragon"],
		baseStats: {hp: 90, atk: 140, def: 100, spa: 80, spd: 120, spe: 125},
		abilities: {0: "Fur Coat"},
         },
     haxorus: {
		inherit: true,
		abilities: {0: "Rivalry", 1: "Mold Breaker", H: "Unnerve"},
		otherFormes: ["haxorusmega"],
        },
     haxorusmega: {
		num: 612,
		species: "Haxorus-Mega",
		baseSpecies: "Haxorus",
		forme: "Mega",
		formeLetter: "M",
		types: ["Dragon"],
		baseStats: {hp: 76, atk: 157, def: 120, spa: 70, spd: 90, spe: 127},
		abilities: {0: "Dragon Force"},
        },
     mienshao: {
		inherit: true,
		abilities: {0: "Inner Focus", 1: "Regenerator", H: "Reckless"},
		otherFormes: ["mienshaomega"],
        },
     mienshaomega: {
		num: 620,
		species: "Mienshao-Mega",
		baseSpecies: "Mienshao",
		forme: "Mega",
		formeLetter: "M",
		types: ["Fighting", "Fairy"],
		baseStats: {hp: 65, atk: 145, def: 90, spa: 95, spd: 80, spe: 135},
		abilities: {0: "Moxie"},
        },
     primeape: {
		inherit: true,
		abilities: {0: "Vital Spirit", 1: "Anger Point", H: "Defiant"},
		otherFormes: ["primeapemega"],  
        },
     primeapemega: {
		num: 57,
		species: "Primeape-Mega",
		baseSpecies: "Primeape",
		forme: "Mega",
		formeLetter: "M",
		types: ["Fighting", "Steel"],
		baseStats: {hp: 65, atk: 135, def: 90, spa: 60, spd: 100, spe: 105},
		abilities: {0: "Punchilate"},
        },
     gothitelle: {
		inherit: true,
		abilities: {0: "Frisk", 1: "Competitive", H: "Shadow Tag"},
		otherFormes: ["gothitellemega"], 
	},    
     gothitellemega: {
		num: 576,
		species: "Gothitelle-Mega",
		baseSpecies: "Gothitelle",
		forme: "Mega",
		formeLetter: "M",
		types: ["Psychic", "Fairy"],
		baseStats: {hp: 70, atk: 55, def: 125, spa: 130, spd: 110, spe: 100},
		abilities: {0: "Goddess Aura"},
        },
     magnezone: {
		inherit: true,
		abilities: {0: "Magnet Pull", 1: "Sturdy", H: "Analytic"},
		otherFormes: ["magnezonemega"], 
        },    
     magnezonemega: {
		num: 462,
		species: "Magnezone-Mega",
		baseSpecies: "Magnezone",
		forme: "Mega",
		formeLetter: "M",
		types: ["Electric", "Steel"],
		baseStats: {hp: 70, atk: 90, def: 115, spa: 160, spd: 90, spe: 110},
		abilities: {0: "Gear Force"},
        },
     zangoose: {
		inherit: true,
		abilities: {0: "Immunity", H: "Toxic Boost"},
		otherFormes: ["zangoosemega"],
	},    
     zangoosemega: {
		num: 335,
		species: "Zangoose-Mega",
		baseSpecies: "Zangoose",
		forme: "Mega",
		formeLetter: "M",
		types: ["Normal", "Fighting"],
		baseStats: {hp: 73, atk: 145, def: 70, spa: 60, spd: 80, spe: 130},
		abilities: {0: "Guts"},
	},
     bisharp: {
		inherit: true,
		abilities: {0: "Defiant", 1: "Inner Focus", H: "Pressure"},
		otherFormes: ["bisharpmega"], 
        },    
     bisharpmega: {
	        num: 625,
		species: "Bisharp-Mega",
		baseSpecies: "Bisharp",
		forme: "Mega",
		formeLetter: "M",
		types: ["Dark", "Steel"],
		baseStats: {hp: 65, atk: 155, def: 110, spa: 60, spd: 70, spe: 130},
		abilities: {0: "Cold Blood"},
         },
     weavile: {
		inherit: true,
		abilities: {0: "Pressure", H: "Pickpocket"},
		otherFormes: ["weavilemega"],
	 },   
     weavilemega: {
	        num: 461,
		species: "Weavile-Mega",
		baseSpecies: "Weavile",
		forme: "Mega",
		formeLetter: "M",
		types: ["Dark", "Ice"],
		baseStats: {hp: 70, atk: 150, def: 80, spa: 45, spd: 115, spe: 150},
		abilities: {0: "Technician"},    
         },
     ninjask: {
		inherit: true,
		abilities: {0: "Speed Boost", H: "Infiltrator"},
		otherFormes: ["ninjaskmega"],
    	 },   
     ninjaskmega: {
	        num: 291,
		species: "Ninjask-Mega",
		baseSpecies: "Ninjask",
		forme: "Mega",
		formeLetter: "M",
		types: ["Bug", "Flying"],
		baseStats: {hp: 61, atk: 130, def: 65, spa: 50, spd: 80, spe: 170},
		abilities: {0: "Leadership"},     
         },
     dugtrio: {
		inherit: true,
		abilities: {0: "Sand Veil", 1: "Arena Trap", H: "Sand Force"},
		otherFormes: ["dugtriomega"],
	 },   
     dugtriomega: {
	        num: 51,
		species: "Dugtrio-Mega",
		baseSpecies: "Dugtrio",
		forme: "Mega",
		formeLetter: "M",
		types: ["Ground"],
		baseStats: {hp: 35, atk: 120, def: 65, spa: 50, spd: 100, spe: 155},
		abilities: {0: "Landinate"},         
         },
     hippowdon: {
		inherit: true,
		abilities: {0: "Sand Stream", H: "Sand Force"},
		otherFormes: ["hippowdonmega"],
	 },   
     hippowdonmega: {
	        num: 450,
		species: "Hippowdon-Mega",
		baseSpecies: "Hippowdon",
		forme: "Mega",
		formeLetter: "M",
		types: ["Ground", "Steel"],
		baseStats: {hp: 108, atk: 142, def: 138, spa: 68, spd: 102, spe: 67},
		abilities: {0: "Sand Force"}, 
         },
     chandelure: {
		inherit: true,
		abilities: {0: "Flash Fire", 1 : "Flame Body", H: "Infiltrator"},
		otherFormes: ["chandeluremega"],
         },   
     chandeluremega: {
	        num: 609,
		species: "Chandelure-Mega",
		baseSpecies: "Chandelure",
		forme: "Mega",
		formeLetter: "M",
		types: ["Ghost", "Fire"],
		baseStats: {hp: 60, atk: 55, def: 120, spa: 165, spd: 110, spe: 110},
		abilities: {0: "Final Flicker"}, 
         },
     grumpig: {
		inherit: true,
		abilities: {0: "Thick Fat", 1: "Own Tempo", H: "Gluttony"},
		otherFormes: ["grumpigmega"],
         },   
     grumpigmega: {
	        num: 326,
		species: "Grumpig-Mega",
		baseSpecies: "Grumpig",
		forme: "Mega",
		formeLetter: "M",
		types: ["Psychic"],
		baseStats: {hp: 80, atk: 45, def: 95, spa: 130, spd: 110, spe: 110},
		abilities: {0: "Medicine"}, 
         },
     blissey: {
		inherit: true,
		abilities: {0: "Natural Cure", 1: "Serene Grace", H: "Healer"},
		otherFormes: ["blisseymega"],
         },   
     blisseymega: {
	        num: 242,
		species: "Blissey-Mega",
		baseSpecies: "Blissey",
		forme: "Mega",
		formeLetter: "M",
		types: ["Normal", "Fairy"],
		baseStats: {hp: 255, atk: 10, def: 60, spa: 105, spd: 155, spe: 55},
		abilities: {0: "Medicine"}, 
          },
     corsola: {
		inherit: true,
		abilities: {0: "Hustle", 1: "Natural Cure", H: "Regenerator"},
		otherFormes: ["corsolamega"],
          },   
     corsolamega: {
	        num: 222,
		species: "Corsola-Mega",
		baseSpecies: "Corsola",
		forme: "Mega",
		formeLetter: "M",
		types: ["Water", "Rock"],
		baseStats: {hp: 65, atk: 70, def: 105, spa: 115, spd: 95, spe: 60},
		abilities: {0: "Crush Coral"}, 
           },
     chimecho: {
		inherit: true,
		abilities: {0: "Levitate"},
		otherFormes: ["chimechomega"],
           },   
     chimechomega: {
	        num: 358,
		species: "Chimecho-Mega",
		baseSpecies: "Chimecho",
		forme: "Mega",
		formeLetter: "M",
		types: ["Psychic", "Fairy"],
		baseStats: {hp: 75, atk: 50, def: 80, spa: 145, spd: 90, spe: 115},
		abilities: {0: "Pixilate"}, 
           },
     seviper: {
		inherit: true,
		abilities: {0: "Shed Skin", H: "Infiltrator"},
		otherFormes: ["sevipermega"],
           },   
     sevipermega: {
	        num: 336,
		species: "Seviper-Mega",
		baseSpecies: "Seviper",
		forme: "Mega",
		formeLetter: "M",
		types: ["Poison", "Dark"],
		baseStats: {hp: 73, atk: 125, def: 80, spa: 130, spd: 60, spe: 90},
		abilities: {0: "Adaptability"}, 
	   },
     meganium: {
		inherit: true,
		abilities: {0: "Overgrow", H: "Leaf Guard"},
		otherFormes: ["meganiummega"],		
           },   
     meganiummega: {
	        num: 154,
		species: "Meganium-Mega",
		baseSpecies: "Meganium",
		forme: "Mega",
		formeLetter: "M",
		types: ["Grass", "Psychic"],
		baseStats: {hp: 80, atk: 52, def: 110, spa: 163, spd: 120, spe: 100},
		abilities: {0: "Triage"}, 
	   },
    typhlosion: {
		inherit: true,
		abilities: {0: "Blaze", H: "Flash Fire"},
		otherFormes: ["typhlosionmega"],
           },   
     typhlosionmega: {
	        num: 157,
		species: "Typhlosion-Mega",
		baseSpecies: "Typhlosion",
		forme: "Mega",
		formeLetter: "M",
		types: ["Fire"],
		baseStats: {hp: 78, atk: 94, def: 98, spa: 159, spd: 85, spe: 120},
		abilities: {0: "Drought"}, 
           },
     feraligatr: {
		inherit: true,
		abilities: {0: "Torrent", H: "Sheer Force"},
		otherFormes: ["feraligatrmega"],
	   },   
     feraligatrmega: {
	        num: 160,
		species: "Feraligatr-Mega",
		baseSpecies: "Feraligatr",
		forme: "Mega",
		formeLetter: "M",
		types: ["Water", "Dark"],
		baseStats: {hp: 85, atk: 155, def: 120, spa: 79, spd: 83, spe: 108},
		abilities: {0: "Sheer Force"}, 
          }, 
     florges: {
		inherit: true,
		abilities: {0: "Flower Veil", H: "Symbiosis"},
		otherFormes: ["florgesmega"],
	  },   
     florgesmega: {
	        num: 671,
		species: "Florges-Mega",
		baseSpecies: "Florges",
		forme: "Mega",
		formeLetter: "M",
		types: ["Fairy"],
		baseStats: {hp: 75, atk: 68, def: 118, spa: 142, spd: 164, spe: 85},
		abilities: {0: "Misty Surge"},
	 }, 
     flygon: {
		inherit: true,
		abilities: {0: "Levitate"},
		otherFormes: ["flygonmega"],  
	 },   
     flygonmega: {
	        num: 330,
		species: "Flygon-Mega",
		baseSpecies: "Flygon",
		forme: "Mega",
		formeLetter: "M",
		types: ["Bug", "Dragon"],
		baseStats: {hp: 80, atk: 135, def: 100, spa: 100, spd: 80, spe: 125},
		abilities: {0: "Tinted Lens"}, 
         },
     hydreigon: {
		inherit: true,
		abilities: {0: "Levitate"},
		otherFormes: ["hydreigonmega"],
	 },
     hydreigonmega: {
	        num: 635,
		species: "Hydreigon-Mega",
		baseSpecies: "Hydreigon",
		forme: "Mega",
		formeLetter: "M",
		types: ["Dark", "Dragon"],
		baseStats: {hp: 92, atk: 105, def: 110, spa: 165, spd: 100, spe: 128},
	        abilities: {0: "Mega Launcher"},
         },
     milotic: {
		inherit: true,
		abilities: {0: "Marvel Scale", 1: "Competitive", H: "Cute Charm"},
		otherFormes: ["miloticmega"],
          },
     miloticmega: {
	        num: 350,
		species: "Milotic-Mega",
		baseSpecies: "Milotic",
		forme: "Mega",
		formeLetter: "M",
		types: ["Water", "Dragon"],
		baseStats: {hp: 95, atk: 60, def: 134, spa: 145, spd: 145, spe: 61},
		abilities: {0: "Multiscale"},
          }, 
      vileplume: {
		inherit: true,
		abilities: {0: "Chlorophyll", H: "Effect Spore"},
		otherFormes: ["vileplumemega"],
          },
     vileplumemega: {
	        num: 45,
		species: "Vileplume-Mega",
		baseSpecies: "Vileplume",
		forme: "Mega",
		formeLetter: "M",
		types: ["Grass", "Poison"],
		baseStats: {hp: 75, atk: 80, def: 115, spa: 150, spd: 110, spe: 60},
		abilities: {0: "Toxic Emanations"},
       	  },
     mamoswine: {
	        inherit: true,
	        abilities: {0: "Oblivious", 1: "Snow Cloak", H: "Thick Fat"},
	       	otherFormes: ["mamoswinemega"],
	  },
     mamoswinemega: {
	        num: 473,
		species: "Mamoswine-Mega",
		baseSpecies: "Mamoswine",
		forme: "Mega",
		formeLetter: "M",
		types: ["Ice", "Ground"],
		baseStats: {hp: 110, atk: 140, def: 100, spa: 100, spd: 90, spe: 90},
		abilities: {0: "Absolute Zero"},
       	  },
      mismagius: {
	        inherit: true,
	        abilities: {0: "Levitate"},
	       	otherFormes: ["mismagiusmega"],
	  },
     mismagiusmega: {
	        num: 429,
		species: "Mismagius-Mega",
		baseSpecies: "Mismagius",
		forme: "Mega",
		formeLetter: "M",
		types: ["Ghost"],
		baseStats: {hp: 60, atk: 75, def: 85, spa: 135, spd: 115, spe: 130},
		abilities: {0: "Renegate"},
       	  }, 
      drifblim: {
	        inherit: true,
	        abilities: {0: "Aftermath", 1: "Unburden", H: "Flare Boost"},
	       	otherFormes: ["drifblimmega"],
	  },
     drifblimmega: {
	        num: 426,
		species: "Drifblim-Mega",
		baseSpecies: "Drifblim",
		forme: "Mega",
		formeLetter: "M",
		types: ["Ghost", "Flying"],
		baseStats: {hp: 150, atk: 80, def: 64, spa: 120, spd: 74, spe: 110},
		abilities: {0: "Reaper Slice"},
       	  }, 
      goodra: {
	        inherit: true,
	        abilities: {0: "Sap Sipper", 1: "Hydration", H: "Gooey"},
	       	otherFormes: ["goodramega"],
	  },
     goodramega: {
	        num: 706,
		species: "Goodra-Mega",
		baseSpecies: "Goodra",
		forme: "Mega",
		formeLetter: "M",
		types: ["Dragon", "Poison"],
		baseStats: {hp: 90, atk: 130, def: 90, spa: 130, spd: 150, spe: 110},
	        abilities: {0: "Punchproof"},
         },
     skarmory: {
	        inherit: true,
	        abilities: {0: "Keen Eye", 1: "Sturdy", H: "Weak Armor"},
	       	otherFormes: ["skarmorymega"],
       	  }, 
     skarmorymega: {
	        num: 227,
		species: "Skarmory-Mega",
		baseSpecies: "Skarmory",
		forme: "Mega",
		formeLetter: "M",
		types: ["Steel", "Flying"],
		baseStats: {hp: 65, atk: 110, def: 160, spa: 40, spd: 110, spe: 80},
		abilities: {0: "Aerilate"},
       	  }, 
	tangrowth: {
	        inherit: true,
	        abilities: {0: "Chlorophyll", 1: "Leaf Guard", H: "Regenerator"},
	       	otherFormes: ["tangrowthmega"],
       	  }, 
     tangrowthmega: {
	        num: 465,
		species: "Tangrowth-Mega",
		baseSpecies: "Tangrowth",
		forme: "Mega",
		formeLetter: "M",
		types: ["Grass", "Poison"],
		baseStats: {hp: 100, atk: 120, def: 140, spa: 125, spd: 110, spe: 40},
		abilities: {0: "Regenerator"},
       	  }, 
	avalugg: {
	        inherit: true,
	        abilities: {0: "Own Tempo", 1: "Ice Body", H: "Sturdy"},
	       	otherFormes: ["avaluggmega"],
       	  }, 
     avaluggmega: {
	        num: 713,
		species: "Avalugg-Mega",
		baseSpecies: "Avalugg",
		forme: "Mega",
		formeLetter: "M",
		types: ["Ice", "Steel"],
		baseStats: {hp: 95, atk: 147, def: 204, spa: 44, spd: 96, spe: 28},
		abilities: {0: "Solid Ice"},
       	  }, 
	shuckle: {
	        inherit: true,
	        abilities: {0: "Sturdy", 1: "Gluttony", H: "Contrary"},
	       	otherFormes: ["shucklemega"],
       	  }, 
     shucklemega: {
	        num: 213,
		species: "Shuckle-Mega",
		baseSpecies: "Shuckle",
		forme: "Mega",
		formeLetter: "M",
		types: ["Bug", "Rock"],
		baseStats: {hp: 20, atk: 160, def: 100, spa: 100, spd: 100, spe: 125},
		abilities: {0: "Adaptability"},
       	  }, 
	  torterra: {
	        inherit: true,
	        abilities: {0: "Overgrow", H: "Shell Armor"},
	       	otherFormes: ["torterramega"],
	  },
	  torterramega: {
	        num: 389,
		species: "Torterra-Mega",
		baseSpecies: "Torterra",
		forme: "Mega",
		formeLetter: "M",
		types: ["Grass", "Ground"],
		baseStats: {hp: 95, atk: 134, def: 125, spa: 95, spd: 105, spe: 71},
		abilities: {0: "Root Block"},
       	  }, 
	  infernape: {
	        inherit: true,
	        abilities: {0: "Blaze", H: "Iron Fist"},
	       	otherFormes: ["infernapemega"],
	  },
	  infernapemega: {
	        num: 392,
		species: "Infernape-Mega",
		baseSpecies: "Infernape",
		forme: "Mega",
		formeLetter: "M",
		types: ["Fire", "Fighting"],
		baseStats: {hp: 76, atk: 129, def: 86, spa: 129, spd: 86, spe: 128},
		abilities: {0: "Tough Claws"},
       	  }, 
	  serperior: {
	        inherit: true,
	        abilities: {0: "Overgrow", H: "Contrary"},
	       	otherFormes: ["serperiormega"],
	  },
	  serperiormega: {
	        num: 497,
		species: "Serperior-Mega",
		baseSpecies: "Serperior",
		forme: "Mega",
		formeLetter: "M",
		types: ["Grass", "Dragon"],
		baseStats: {hp: 75, atk: 85, def: 110, spa: 120, spd: 115, spe: 123},
		abilities: {0: "Contrary"},
       	  }, 
	   empoleon: {
	        inherit: true,
	        abilities: {0: "Torrent", H: "Defiant"},
	       	otherFormes: ["empoleonmega"],
	  },
	  empoleonmega: {
	        num: 395,
		species: "Empoleon-Mega",
		baseSpecies: "Empoleon",
		forme: "Mega",
		formeLetter: "M",
		types: ["Water", "Steel"],
		baseStats: {hp: 84, atk: 96, def: 128, spa: 131, spd: 131, spe: 60},
		abilities: {0: "Heatproof"},
       	  }, 
	   emboar: {
	        inherit: true,
	        abilities: {0: "Blaze", H: "Reckless"},
	       	otherFormes: ["emboarmega"],
	  },
	  emboarmega: {
	        num: 500,
		species: "Emboar-Mega",
		baseSpecies: "Emboar",
		forme: "Mega",
		formeLetter: "M",
		types: ["Fire", "Fighting"],
		baseStats: {hp: 110, atk: 148, def: 75, spa: 125, spd: 75, spe: 95},
		abilities: {0: "Rock Head"},
       	  }, 
	   samurott: {
	        inherit: true,
	        abilities: {0: "Torrent", H: "Shell Armor"},
	       	otherFormes: ["samurottmega"],
	  },
	  samurottmega: {
	        num: 503,
		species: "Samurott-Mega",
		baseSpecies: "Samurott",
		forme: "Mega",
		formeLetter: "M",
		types: ["Water", "Fighting"],
		baseStats: {hp: 95, atk: 125, def: 95, spa: 138, spd: 80, spe: 105},
		abilities: {0: "Water Veil"},
       	  }, 
	   chesnaught: {
	        inherit: true,
	        abilities: {0: "Overgrow", H: "Bulletproof"},
	       	otherFormes: ["chesnaughtmega"],
	  },
	  chesnaughtmega: {
	        num: 652,
		species: "Chesnaught-Mega",
		baseSpecies: "Chesnaught",
		forme: "Mega",
		formeLetter: "M",
		types: ["Grass", "Fighting"],
		baseStats: {hp: 88, atk: 137, def: 132, spa: 84, spd: 95, spe: 94},
		abilities: {0: "Bulletproof"},
       	  },
	   delphox: {
	        inherit: true,
	        abilities: {0: "Blaze", H: "Magician"},
	       	otherFormes: ["delphoxmega"],
	  },
	  delphoxmega: {
	        num: 655,
		species: "Delphox-Mega",
		baseSpecies: "Delphox",
		forme: "Mega",
		formeLetter: "M",
		types: ["Fire", "Psychic"],
		baseStats: {hp: 75, atk: 79, def: 92, spa: 144, spd: 120, spe: 134},
		abilities: {0: "Drought"},
       	  }, 
	  decidueye: {
	        inherit: true,
	        abilities: {0: "Overgrow", H: "Long Reach"},
	       	otherFormes: ["decidueyemega"],
	  },
	  decidueyemega: {
	        num: 724,
		species: "Decidueye-Mega",
		baseSpecies: "Decidueye",
		forme: "Mega",
		formeLetter: "M",
		types: ["Grass", "Ghost"],
		baseStats: {hp: 78, atk: 127, def: 85, spa: 120, spd: 110, spe: 110},
		abilities: {0: "Renegate"},
       	  },
	  incineroar: {
	        inherit: true,
	        abilities: {0: "Blaze", H: "Intimidate"},
	       	otherFormes: ["incineroarmega"],
	  },
	  incineroarmega: {
	        num: 727,
		species: "Incineroar-Mega",
		baseSpecies: "Incineroar",
		forme: "Mega",
		formeLetter: "M",
		types: ["Fire", "Dark"],
		baseStats: {hp: 95, atk: 135, def: 110, spa: 90, spd: 100, spe: 100},
		abilities: {0: "Defiant"},
       	  }, 
	  delphox: {
	        inherit: true,
	        abilities: {0: "Blaze", H: "Magician"},
	       	otherFormes: ["delphoxmega"],
	  },
	  primarinamega: {
	        num: 730,
		species: "Primarina-Mega",
		baseSpecies: "Primarina",
		forme: "Mega",
		formeLetter: "M",
		types: ["Water", "Fairy"],
		baseStats: {hp: 80, atk: 74, def: 104, spa: 151, spd: 136, spe: 85},
		abilities: {0: "Rain Power"},
       	  }, 
       raichualola: {
		num: 26,
		species: "Raichu-Alola",
		baseSpecies: "Raichu",
		forme: "Alola",
		formeLetter: "A",
		types: ["Electric", "Psychic"],
		baseStats: {hp: 60, atk: 85, def: 50, spa: 95, spd: 85, spe: 110},
		abilities: {0: "Surge Surfer", H: "Miracle Dash"},
		heightm: 0.7,
		weightkg: 21,
		color: "Brown",
		prevo: "pikachu",
		evoLevel: 1,
		eggGroups: ["Field", "Fairy"],
		spritenum: 925,
	},
	staryu: {
		num: 120,
		species: "Staryu",
		types: ["Water"],
		gender: "N",
		baseStats: {hp: 30, atk: 45, def: 55, spa: 70, spd: 55, spe: 85},
		abilities: {0: "Illuminate", 1: "Natural Cure", H: "Analytic"},
		heightm: 0.8,
		weightkg: 34.5,
		color: "Brown",
		evos: ["starmie", "starmiejillian"],
		eggGroups: ["Water 3"],
	},
        starmie: {
		num: 121,
		species: "Starmie",
		types: ["Water", "Psychic"],
		gender: "N",
		baseStats: {hp: 60, atk: 75, def: 85, spa: 100, spd: 85, spe: 115},
		abilities: {0: "Illuminate", 1: "Natural Cure", H: "Analytic"},
		heightm: 1.1,
		weightkg: 80,
		color: "Purple",
		prevo: "staryu",
		evoLevel: 1,
		eggGroups: ["Water 3"],
		otherFormes: ["starmiejillian"],
	},
        starmiejillian: {
		num: 121,
		species: "Starmie-Jillian",
		baseSpecies: "Starmie",
		forme: "Jillian",
		formeLetter: "J",
		types: ["Water", "Psychic"],
		baseStats: {hp: 60, atk: 70, def: 80, spa: 110, spd: 85, spe: 115},
		abilities: {0: "Miracle Dash"},
		heightm: 1.1,
		weightkg: 80,
		color: "Purple",
		prevo: "staryu",
		evoLevel: 1,
		eggGroups: ["Water 3"],
        },
        tauros: {
		num: 128,
		species: "Tauros",
		types: ["Normal"],
		gender: "M",
		baseStats: {hp: 75, atk: 100, def: 95, spa: 40, spd: 70, spe: 110},
		abilities: {0: "Intimidate", 1: "Anger Point", H: "Sheer Force"},
		heightm: 1.4,
		weightkg: 88.4,
		color: "Brown",
		eggGroups: ["Field"],
	        otherFormes: ["taurosjillian"],
	},
        taurosjillian: {
		num: 128,
		species: "Tauros-Jillian",
		baseSpecies: "Tauros",
		forme: "Jillian",
		formeLetter: "J",
		types: ["Normal", "Grass"],
		baseStats: {hp: 75, atk: 120, def: 85, spa: 30, spd: 70, spe: 110},
		abilities: {0: "Brush Rusher"},
		heightm: 1.4,
		weightkg: 88.4,
		color: "Brown",
		eggGroups: ["Field"],
	},
	delibird: {
		num: 225,
		species: "Delibird",
		types: ["Ice", "Flying"],
		baseStats: {hp: 45, atk: 55, def: 45, spa: 65, spd: 45, spe: 75},
		abilities: {0: "Vital Spirit", 1: "Hustle", H: "Insomnia"},
		heightm: 0.9,
		weightkg: 16,
		color: "Red",
		eggGroups: ["Water 1", "Field"],
		otherFormes: "delibirdjillian",
	},
	delibirdjillian: {
		num: 225,
		species: "Delibird-Jillian",
		baseSpecies: "Delibird",
		forme: "Jillian",
		formeLetter: "J",
		types: ["Ice", "Fighting"],
		baseStats: {hp: 45, atk: 75, def: 35, spa: 55, spd: 35, spe: 85},
		abilities: {0: "Snow Warning", H: "Slush Rush"},
		heightm: 0.9,
		weightkg: 16,
		color: "Yellow",
		eggGroups: ["Water 1", "Field"],
	},
	lombre: {
		num: 271,
		species: "Lombre",
		types: ["Water", "Grass"],
		baseStats: {hp: 60, atk: 50, def: 50, spa: 60, spd: 70, spe: 50},
		abilities: {0: "Swift Swim", 1: "Rain Dish", H: "Own Tempo"},
		heightm: 1.2,
		weightkg: 32.5,
		color: "Green",
		prevo: "lotad",
		evos: ["ludicolo", "ludicolojillian"],
		evoLevel: 14,
		eggGroups: ["Water 1", "Grass"],
	},
	ludicolo: {
		num: 272,
		species: "Ludicolo",
		types: ["Water", "Grass"],
		baseStats: {hp: 80, atk: 70, def: 70, spa: 90, spd: 100, spe: 70},
		abilities: {0: "Swift Swim", 1: "Rain Dish", H: "Own Tempo"},
		heightm: 1.5,
		weightkg: 55,
		prevo: "lombre",
		evoLevel: 14,
		eggGroups: ["Water 1", "Grass"],
		otherFormes: ["ludicolojillian"],
	},
	ludicolojillian: {
		num: 272,
		species: "Ludicolo-Jillian",
		baseSpecies: "Ludicolo",
		forme: "Jillian",
		formeLetter: "J",
		types: ["Water", "Grass"],
		baseStats: {hp: 80, atk: 70, def: 70, spa: 90, spd: 100, spe: 70},
		abilities: {0: "Swift Swim", 1: "Rain Dish", H: "Dancer"},
		heightm: 1.5,
		weightkg: 55,
		prevo: "lombre",
		evoLevel: 14,
		eggGroups: ["Water 1", "Grass"],
	},
	roselia: {
		num: 315,
		species: "Roselia",
		types: ["Grass", "Poison"],
		baseStats: {hp: 50, atk: 60, def: 45, spa: 100, spd: 80, spe: 65},
		abilities: {0: "Natural Cure", 1: "Poison Point", H: "Leaf Guard"},
		heightm: 0.3,
		weightkg: 2,
		color: "Green",
		prevo: "budew",
		evos: ["roserade", "roseradejillian"],
		evoLevel: 1,
		eggGroups: ["Fairy", "Grass"],
        },
	roserade: {
		num: 407,
		species: "Roserade",
		types: ["Grass", "Poison"],
		baseStats: {hp: 60, atk: 70, def: 65, spa: 125, spd: 105, spe: 90},
		abilities: {0: "Natural Cure", 1: "Poison Point", H: "Technician"},
		heightm: 0.9,
		weightkg: 14.5,
		color: "Green",
		prevo: "roselia",
		evoLevel: 1,
		eggGroups: ["Fairy", "Grass"],
		otherFormes: ["roseradejillian"],
	},
	roseradejillian: {
		num: 407,
		species: "Roserade-Jillian",
		baseSpecies: "Roserade",
		forme: "Jillian",
		formeLetter: "J",
		types: ["Grass", "Fire"],
		baseStats: {hp: 60, atk: 80, def: 60, spa: 135, spd: 100, spe: 90},
		abilities: {0: "Chlorophyll", 1: "Brush Rusher", H: "Technician"},
		heightm: 0.9,
		weightkg: 14.5,
		color: "Green",
		prevo: "roselia",
		evoLevel: 1,
		eggGroups: ["Fairy", "Grass"],
	},
	combee: {
		num: 415,
		species: "Combee",
		types: ["Bug", "Flying"],
		genderRatio: {M: 0.875, F: 0.125},
		baseStats: {hp: 30, atk: 30, def: 42, spa: 30, spd: 42, spe: 70},
		abilities: {0: "Honey Gather", H: "Hustle"},
		heightm: 0.3,
		weightkg: 5.5,
		color: "Yellow",
		evos: ["vespiquen", "vespiquenjillian"],
		eggGroups: ["Bug"],
	},
	vespiquen: {
		num: 416,
		species: "Vespiquen",
		types: ["Bug", "Flying"],
		gender: "F",
		baseStats: {hp: 70, atk: 80, def: 102, spa: 80, spd: 102, spe: 40},
		abilities: {0: "Pressure", H: "Unnerve"},
		heightm: 1.2,
		weightkg: 38.5,
		color: "Yellow",
		prevo: "combee",
		evoLevel: 21,
		eggGroups: ["Bug"],
		otherFormes: ["vespiquenjillian"],
	},
	vespiquenjillian: {
		num: 416,
		species: "Vespiquen-Jillian",
		baseSpecies: "Vespiquen",
		forme: "Jillian",
		formeLetter: "J",
		types: ["Bug", "Poison"],
		gender: "F",
		baseStats: {hp: 70, atk: 102, def: 80, spa: 102, spd: 80, spe: 70},
		abilities: {0: "Pressure", H: "Queenly Majesty"},
		heightm: 1.2,
		weightkg: 38.5,
		color: "Yellow",
		prevo: "combee",
		evoLevel: 21,
		eggGroups: ["Bug"],
       },
       deerling: {
		num: 585,
		species: "Deerling",
		baseForme: "Spring",
		types: ["Normal", "Grass"],
		baseStats: {hp: 60, atk: 60, def: 50, spa: 40, spd: 50, spe: 75},
		abilities: {0: "Chlorophyll", 1: "Sap Sipper", H: "Serene Grace"},
		heightm: 0.6,
		weightkg: 19.5,
		color: "Pink",
		evos: ["sawsbuck"],
		eggGroups: ["Field"],
		otherForms: ["deerlingsummer", "deerlingautumn", "deerlingwinter"],
	        otherFormes: ["deerlingjillian"],
	},
	deerlingjillian: {
		num: 585,
		species: "Deerling-Jillian",
		baseSpecies: "Deerling",
		forme: "Jillian",
		formeLetter: "J",
		types: ["Normal", "Grass"],
		baseStats: {hp: 60, atk: 70, def: 50, spa: 40, spd: 50, spe: 85},
		abilities: {0: "Brush Rusher"},
		heightm: 0.6,
		weightkg: 19.5,
		color: "Red",
		evos: ["sawsbuckjillian"],
		eggGroups: ["Field"],
	},
	sawsbuck: {
		num: 586,
		species: "Sawsbuck",
		baseForme: "Spring",
		types: ["Normal", "Grass"],
		baseStats: {hp: 80, atk: 100, def: 70, spa: 60, spd: 70, spe: 95},
		abilities: {0: "Chlorophyll", 1: "Sap Sipper", H: "Serene Grace"},
		heightm: 1.9,
		weightkg: 92.5,
		color: "Brown",
		prevo: "deerling",
		evoLevel: 34,
		eggGroups: ["Field"],
		otherForms: ["sawsbucksummer", "sawsbuckautumn", "sawsbuckwinter"],
		otherFormes: ["sawsbuckjillian"],	
	},
	sawsbuckjillian: {
		num: 586,
		species: "Sawsbuck-Jillian",
		baseSpecies: "Sawsbuck",
		forme: "Jillian",
		formeLetter: "J",
		types: ["Normal", "Grass"],
		baseStats: {hp: 80, atk: 110, def: 70, spa: 60, spd: 70, spe: 105},
		abilities: {0: "Brush Rusher"},
		heightm: 1.9,
		weightkg: 92.5,
		color: "Red",
		prevo: "deerlingjillian",
		evoLevel: 34,
		eggGroups: ["Field"],
	},
	panpour: {
		num: 515,
		species: "Panpour",
		types: ["Water"],
		genderRatio: {M: 0.875, F: 0.125},
		baseStats: {hp: 50, atk: 53, def: 48, spa: 53, spd: 48, spe: 64},
		abilities: {0: "Gluttony", H: "Torrent"},
		heightm: 0.6,
		weightkg: 13.5,
		color: "Blue",
		evos: ["simipour", "simipourjillian"],
		eggGroups: ["Field"],
	},
	simipour: {
		num: 516,
		species: "Simipour",
		types: ["Water"],
		genderRatio: {M: 0.875, F: 0.125},
		baseStats: {hp: 75, atk: 98, def: 63, spa: 98, spd: 63, spe: 101},
		abilities: {0: "Gluttony", H: "Torrent"},
		heightm: 1,
		weightkg: 29,
		color: "Blue",
		prevo: "panpour",
		evoLevel: 1,
		eggGroups: ["Field"],
		otherForme: ["simipourjillian"],
	},
	simipourjillian: {
		num: 516,
		species: "Simipour-Jillian",
		baseSpecies: "Simipour",
		forme: "Jillian",
		formeLetter: "J",
		types: ["Water", "Fairy"],
		genderRatio: {M: 0.875, F: 0.125},
		baseStats: {hp: 75, atk: 93, def: 56, spa: 113, spd: 60, spe: 101},
		abilities: {0: "Mist Skimmer"},
		heightm: 1,
		weightkg: 29,
		color: "Blue",
		prevo: "panpour",
		evoLevel: 1,
		eggGroups: ["Field"],
	},
	litleo: {
		num: 667,
		species: "Litleo",
		types: ["Fire", "Normal"],
		genderRatio: {M: 0.125, F: 0.875},
		baseStats: {hp: 62, atk: 50, def: 58, spa: 73, spd: 54, spe: 72},
		abilities: {0: "Rivalry", 1: "Unnerve", H: "Moxie"},
		heightm: 0.6,
		weightkg: 13.5,
		color: "Brown",
		evos: ["pyroar"],
		eggGroups: ["Field"],
		otherForme: ["litleojillian"],
	},
	litleojillian: {
		num: 667,
		species: "Litleo-Jillian",
		baseSpecies: "Litleo",
		forme: "Jillian",
		formeLetter: "J",
		types: ["Fire", "Psychic"],
		genderRatio: {M: 0.125, F: 0.875},
		baseStats: {hp: 72, atk: 50, def: 58, spa: 83, spd: 54, spe: 72},
		abilities: {0: "Rivalry", 1: "Unnerve", H: "Soul-Heart"},
		heightm: 0.6,
		weightkg: 13.5,
		color: "Purple",
		evos: ["pyroarjillian"],
		eggGroups: ["Field"],
	},
	pyroar: {
		num: 668,
		species: "Pyroar",
		types: ["Fire", "Normal"],
		genderRatio: {M: 0.125, F: 0.875},
		baseStats: {hp: 86, atk: 68, def: 72, spa: 109, spd: 66, spe: 106},
		abilities: {0: "Rivalry", 1: "Unnerve", H: "Moxie"},
		heightm: 1.5,
		weightkg: 81.5,
		color: "Brown",
		prevo: "litleo",
		evoLevel: 35,
		eggGroups: ["Field"],
		otherForme: ["pyroarjillian"],
	},
	pyroarjillian: {
		num: 668,
		species: "Pyroar-Jillian",
		baseSpecies: "Pyroar",
		forme: "Jillian",
		formeLetter: "J",
		types: ["Fire", "Psychic"],
		genderRatio: {M: 0.125, F: 0.875},
		baseStats: {hp: 101, atk: 68, def: 72, spa: 124, spd: 56, spe: 106},
		abilities: {0: "Miracle Dash"},
		heightm: 1.5,
		weightkg: 81.5,
		color: "Purple",
		prevo: "litleojillian",
		evoLevel: 35,
		eggGroups: ["Field"],
	},
	clefable: {
		num: 36,
		species: "Clefable",
		types: ["Fairy"],
		genderRatio: {M: 0.25, F: 0.75},
		baseStats: {hp: 95, atk: 70, def: 73, spa: 95, spd: 90, spe: 60},
		abilities: {0: "Cute Charm", 1: "Magic Guard", H: "Unaware"},
		heightm: 1.3,
		weightkg: 40,
		color: "Pink",
		prevo: "clefairy",
		evoLevel: 1,
		eggGroups: ["Fairy"],
		otherFormes: ["clefablejillian"],
	},
	clefablejillian: {
		num: 36,
		species: "Clefable-Jillian",
		baseSpecies: "Clefable",
		forme: "Jillian",
		formeLetter: "J",
		types: ["Fairy", "Steel"],
		genderRatio: {M: 0.25, F: 0.75},
		baseStats: {hp: 95, atk: 50, def: 83, spa: 95, spd: 110, spe: 50},
		abilities: {0: "Iron Barbs", 1: "Magic Bounce", H: "Unaware"},
		heightm: 1.3,
		weightkg: 40,
		color: "Pink",
		prevo: "clefairy",
		evoLevel: 1,
		eggGroups: ["Fairy"],
	},
	azumarill: {
		num: 184,
		species: "Azumarill",
		types: ["Water", "Fairy"],
		baseStats: {hp: 100, atk: 50, def: 80, spa: 60, spd: 80, spe: 50},
		abilities: {0: "Thick Fat", 1: "Huge Power", H: "Sap Sipper"},
		heightm: 0.8,
		weightkg: 28.5,
		color: "Blue",
		prevo: "marill",
		evoLevel: 18,
		eggGroups: ["Water 1", "Fairy"],
		otherFormes: ["azumarilljillian"],
	},
	azumarilljillian: {
		num: 184,
		species: "Azumarill-Jillian",
		baseSpecies: "Azumarill",
		forme: "Jillian",
		formeLetter: "J",
		types: ["Fighting", "Fairy"],
		baseStats: {hp: 100, atk: 70, def: 70, spa: 50, spd: 80, spe: 50},
		abilities: {0: "Thick Fat", 1: "Huge Power", H: "Sap Sipper"},
		heightm: 0.8,
		weightkg: 28.5,
		color: "Pink",
		prevo: "marill",
		evoLevel: 18,
		eggGroups: ["Water 1", "Fairy"],
	},
	exploud: {
		num: 295,
		species: "Exploud",
		types: ["Normal"],
		baseStats: {hp: 104, atk: 91, def: 63, spa: 91, spd: 73, spe: 68},
		abilities: {0: "Soundproof", H: "Scrappy"},
		heightm: 1.5,
		weightkg: 84,
		color: "Blue",
		prevo: "loudred",
		evoLevel: 40,
		eggGroups: ["Monster", "Field"],
		otherFormes: ["exploudjillian"],
	},
	exploudjillian: {
		num: 295,
		species: "Exploud-Jillian",
		baseSpecies: "Exploud",
		forme: "Jillian",
		formeLetter: "J",
		types: ["Normal", "Fighting"],
		baseStats: {hp: 104, atk: 91, def: 63, spa: 96, spd: 68, spe: 68},
		abilities: {0: "Sheer Force", H: "Scrappy"},
		heightm: 1.5,
		weightkg: 84,
		color: "Brown",
		prevo: "loudred",
		evoLevel: 40,
		eggGroups: ["Monster", "Field"],
	},
	croagunk: {
		num: 453,
		species: "Croagunk",
		types: ["Poison", "Fighting"],
		baseStats: {hp: 48, atk: 61, def: 40, spa: 61, spd: 40, spe: 50},
		abilities: {0: "Anticipation", 1: "Dry Skin", H: "Poison Touch"},
		heightm: 0.7,
		weightkg: 23,
		color: "Blue",
		evos: ["toxicroak"],
		eggGroups: ["Human-Like"],
		otherForme: ["croagunkjillian"],
	},
	croagunkjillian: {
		num: 453,
		species: "Croagunk-Jillian",
		baseSpecies: "Croagunk",
		forme: "Jillian",
		formeLetter: "J",
		types: ["Poison", "Dark"],
		baseStats: {hp: 48, atk: 61, def: 40, spa: 61, spd: 40, spe: 50},
		abilities: {0: "Moxie", 1: "Dry Skin", H: "Corrosion"},
		heightm: 0.7,
		weightkg: 23,
		color: "Black",
		evos: ["toxicroakjillian"],
		eggGroups: ["Human-Like"],
	},
  	toxicroak: {
		num: 454,
		species: "Toxicroak",
		types: ["Poison", "Fighting"],
		baseStats: {hp: 83, atk: 106, def: 65, spa: 86, spd: 65, spe: 85},
		abilities: {0: "Anticipation", 1: "Dry Skin", H: "Poison Touch"},
		heightm: 1.3,
		weightkg: 44.4,
		color: "Blue",
		prevo: "croagunk",
		evoLevel: 37,
		eggGroups: ["Human-Like"],
		otherForme: ["toxicroakjillian"],
	},
	toxicroakjillian: {
		num: 454,
		species: "Toxicroak-Jillian",
		baseSpecies: "Toxicroak",
		forme: "Jillian",
		formeLetter: "J",
		types: ["Poison", "Dark"],
		baseStats: {hp: 83, atk: 106, def: 65, spa: 86, spd: 65, spe: 85},
		abilities: {0: "Moxie", 1: "Dry Skin", H: "Corrosion"},
		heightm: 1.3,
		weightkg: 44.4,
		color: "Black",
		prevo: "croagunkjillian",
		evoLevel: 37,
		eggGroups: ["Human-Like"],
	},
	alomomola: {
		num: 594,
		species: "Alomomola",
		types: ["Water"],
		baseStats: {hp: 165, atk: 75, def: 80, spa: 40, spd: 45, spe: 65},
		abilities: {0: "Healer", 1: "Hydration", H: "Regenerator"},
		heightm: 1.2,
		weightkg: 31.6,
		color: "Pink",
		eggGroups: ["Water 1", "Water 2"],
		otherForme: ["alomomolajillian"],
	},
	alomomolajillian: {
		num: 594,
		species: "Alomomola-Jillian",
		baseSpecies: "Alomomola",
		forme: "Jillian",
		formeLetter: "J",
		types: ["Water", "Dragon"],
		baseStats: {hp: 165, atk: 75, def: 80, spa: 40, spd: 75, spe: 55},
		abilities: {0: "Medicine", 1: "Hydration", H: "Regenerator"},
		heightm: 1.2,
		weightkg: 31.6,
		color: "Pink",
		eggGroups: ["Water 1", "Water 2"],
	},
	toxapex: {
		num: 748,
		species: "Toxapex",
		types: ["Poison", "Water"],
		baseStats: {hp: 50, atk: 63, def: 152, spa: 53, spd: 142, spe: 35},
		abilities: {0: "Merciless", 1: "Limber", H: "Regenerator"},
		heightm: 0.7,
		weightkg: 14.5,
		color: "Blue",
		prevo: "mareanie",
		evoLevel: 38,
		eggGroups: ["Water 1"],
		otherForme: ["toxapexjillian"],	
	},
	toxapexjillian: {
		num: 748,
		species: "Toxapex-Jillian",
		baseSpecies: "Toxapex",
		forme: "Jillian",
		formeLetter: "J",
		types: ["Poison", "Steel"],
		baseStats: {hp: 50, atk: 63, def: 152, spa: 53, spd: 142, spe: 35},
		abilities: {0: "Merciless", 1: "Levitate", H: "Regenerator"},
		heightm: 0.7,
		weightkg: 14.5,
		color: "Purple",
		prevo: "mareanie",
		evoLevel: 38,
		eggGroups: ["Water 1"],
	},
	comfey: {
		num: 764,
		species: "Comfey",
		types: ["Fairy"],
		genderRatio: {M: 0.25, F: 0.75},
		baseStats: {hp: 51, atk: 52, def: 90, spa: 82, spd: 110, spe: 100},
		abilities: {0: "Flower Veil", 1: "Triage", H: "Natural Cure"},
		heightm: 0.1,
		weightkg: 0.3,
		color: "Green",
		eggGroups: ["Grass"],
		otherFormes: ["comfeyjillian"],
	},
	comfeyjillian: {
		num: 764,
		species: "Comfey-Jillian",
		baseSpecies: "Comfey",
		forme: "Jillian",
		formeLetter: "J",
		types: ["Fairy", "Poison"],
		genderRatio: {M: 0.25, F: 0.75},
		baseStats: {hp: 51, atk: 42, def: 90, spa: 102, spd: 110, spe: 100},
		abilities: {0: "Flower Veil", 1: "Triage", H: "Magic Bounce"},
		heightm: 0.1,
		weightkg: 0.3,
		color: "Pink",
		eggGroups: ["Grass"],
	},
	drampa: {
		num: 780,
		species: "Drampa",
		types: ["Normal", "Dragon"],
		baseStats: {hp: 78, atk: 60, def: 85, spa: 135, spd: 91, spe: 36},
		abilities: {0: "Berserk", 1: "Sap Sipper", H: "Cloud Nine"},
		heightm: 3,
		weightkg: 185,
		color: "White",
		eggGroups: ["Monster", "Dragon"],
		otherFormes: ["drampajillian"],	
	},
	drampajillian: {
		num: 780,
		species: "Drampa-Jillian",
		baseSpecies: "Drampa",
		forme: "Jillian",
		formeLetter: "J",
		types: ["Normal", "Dragon"],
		baseStats: {hp: 78, atk: 60, def: 85, spa: 145, spd: 91, spe: 31},
		abilities: {0: "Berserk", 1: "Sap Sipper", H: "Adaptability"},
		heightm: 3,
		weightkg: 185,
		color: "White",
		eggGroups: ["Monster", "Dragon"],
	},
	shellos: {
		num: 422,
		species: "Shellos",
		baseForme: "West",
		types: ["Water"],
		baseStats: {hp: 76, atk: 48, def: 48, spa: 57, spd: 62, spe: 34},
		abilities: {0: "Sticky Hold", 1: "Storm Drain", H: "Sand Force"},
		heightm: 0.3,
		weightkg: 6.3,
		color: "Purple",
		evos: ["gastrodon", "gastrodonjillian"],
		eggGroups: ["Water 1", "Amorphous"],
		otherForms: ["shelloseast"],
	},
	gastrodon: {
		num: 423,
		species: "Gastrodon",
		baseForme: "West",
		types: ["Water", "Ground"],
		baseStats: {hp: 111, atk: 83, def: 68, spa: 92, spd: 82, spe: 39},
		abilities: {0: "Sticky Hold", 1: "Storm Drain", H: "Sand Force"},
		heightm: 0.9,
		weightkg: 29.9,
		color: "Purple",
		prevo: "shellos",
		evoLevel: 30,
		eggGroups: ["Water 1", "Amorphous"],
		otherForms: ["gastrodoneast", "gastrodonjillian"],
	},
	gastrodonjillian: {
		num: 423,
		species: "Gastrodon-Jillian",
		baseSpecies: "Gastrodon",
		forme: "Jillian",
		formeLetter: "J",
		types: ["Water", "Ground"],
		baseStats: {hp: 111, atk: 63, def: 68, spa: 112, spd: 82, spe: 39},
		abilities: {0: "Sticky Hold", 1: "Storm Drain", H: "Burning Heal"},
		heightm: 3,
		weightkg: 185,
		color: "White",
		eggGroups: ["Monster", "Dragon"],
	},
};
/* https://pastebin.com/8SudG3w9 */
