export const Pokedex: {[k: string]: ModdednameData} = {
	butterchomp: {
		fusion: ["Butterfree", "Garchomp"],
		num: -1,
		name: "Butterchomp",
		types: ["Bug", "Dragon"],
		baseStats: {hp: 85, atk: 95, def: 75, spa: 95, spd: 85, spe: 101},
		abilities: {0: "Ragged Senses"},
		weightkg: 63.5,
	},
	bascugly: {
		fusion: ["Basculin", "Purugly"],
		num: -2,
		name: "Bascugly",
		types:["Water", "Normal"],
		baseStats: {hp: 70, atk: 90, def: 70, spa: 80, spd: 70, spe: 115},
		abilities: {0: "Ignorant Adapting"},
		weightkg: 30.9,
	},
	tapusawk: {
		fusion: ["Tapu Bulu", "Sawk"],
		num: -3,
		name: "Tapu Sawk",
		types:["Grass", "Fighting"],
		baseStats: {hp: 76, atk: 130, def: 100, spa: 60, spd: 100, spe: 90},
		abilities: {0: "Needle Surge"},
		weightkg: 48.25,
	},
	wormaiclus: {
		fusion: ["Wormadam-Trash", "Reuniclus"],
		num: -4,
		name: "Wormaiclus",
		types:["Steel", "Psychic"],
		baseStats: {hp: 91, atk: 70, def: 99, spa: 105, spd: 99, spe: 33},
		abilities: {0: "Epidermis Recovery"},
		weightkg: 13.3,
	},
	nidoreena: {
		fusion: ["Nidoking", "Tsareena"],
		num: -5,
		name: "Nidoreena",
		types:["Poison", "Grass"],
		baseStats: {hp: 80, atk: 115, def: 97, spa: 69, spd: 97, spe: 87},
		abilities: {0: "Royal Pressure"},
		weightkg: 41.7,
	},
	persaconda: {
		fusion: ["Persian", "Sandaconda"],
		num: -6,
		name: "Persaconda",
		types:["Normal", "Ground"],
		baseStats: {hp: 68, atk: 100, def: 100, spa: 65, spd: 70, spe: 110},
		abilities: {0: "Sand Stream"},
		weightkg: 48.75,
	},
	swalagross: {
		fusion: ["Swalot", "Metagross"],
		num: -7,
		name: "Swalagross",
		types:["Poison", "Steel"],
		baseStats: {hp: 100, atk: 115, def: 115, spa: 87, spd: 90, spe: 65},
		abilities: {0: "My Body, My Choice"},
		weightkg: 315,
	},
	ramaparaptor: {
		fusion: ["Rampardos", "Staraptor"],
		num: -8,
		name: "Ramaparaptor",
		types:["Rock", "Normal"],
		baseStats: {hp: 103, atk: 150, def: 72, spa: 62, spd: 62, spe: 80},
		abilities: {0: "Domination"},
		weightkg: 63.7,
	},
	dragasire: {
		fusion: ["Dragapult", "Quagsire"],
		num: -9,
		name: "Dragasire",
		types:["Dragon", "Water"],
		baseStats: {hp: 95, atk: 110, def: 90, spa: 85, spd: 80, spe: 93},
		abilities: {0: "Complete Ignorance"},
		weightkg: 62.5,
	},
	slasle: {
		fusion: ["Slaking", "Plusle"],
		num: -10,
		name: "Slasle",
		types:["Normal", "Electric"],
		baseStats: {hp: 105, atk: 110, def: 71, spa: 110, spd: 71, spe: 110},
		abilities: {0: "Shocker"},
		weightkg: 67.35,
	},
	dubdos: {
		fusion: ["Dubwool", "Zapdos"],
		num: -11,
		name: "Dubdos",
		types:["Normal", "Electric"],
		baseStats: {hp: 94, atk: 95, def: 95, spa: 95, spd: 95, spe: 100},
		abilities: {0: "Volty Fur"},
		weightkg: 47.8,
	},
	toxtriceebel: {
		fusion: ["Toxtricity-Low-Key", "Victreebel"],
		num: -12,
		name: "Toxtriceebel",
		types:["Electric", "Grass"],
		baseStats: {hp: 80, atk: 105, def: 70, spa: 110, spd: 75, spe: 94},
		abilities: {0: "Mumble Rap"},
		weightkg: 27.75,
	},
	gliscremie: {
		fusion: ["Gliscor", "Alcremie"],
		num: -13,
		name: "Gliscremie",
		types:["Ground", "Fairy"],
		baseStats: {hp: 75, atk: 85, def: 105, spa: 85, spd: 105, spe: 86},
		abilities: {0: "Healing Scent"},
		weightkg: 21.5,
	},
	spirisopod: {
		fusion: ["Spiritomb", "Golisopod"],
		num: -14,
		name: "Spirisopod",
		types:["Dark", "Bug"],
		baseStats: {hp: 68, atk: 112, def: 128, spa: 92, spd: 108, spe: 38},
		abilities: {0: "Hit and Run"},
		weightkg: 108,
	},
	tornabeat: {
		fusion: ["Tornadus", "Volbeat"],
		num: -15,
		name: "Tornabeat",
		types:["Flying", "Bug"],
		baseStats: {hp: 80, atk: 105, def: 79, spa: 105, spd: 90, spe: 115},
		abilities: {0: "Prankster"},
		weightkg: 40.35,
	},
	weezking: {
		fusion: ["Weezing", "Slowking"],
		num: -16,
		name: "Weezking",
		types:["Poison", "Psychic"],
		baseStats: {hp: 89, atk: 85, def: 110, spa: 100, spd: 100, spe: 45},
		abilities: {0: "Recovering Fumes"},
		weightkg: 44.5,
	},
	typhlobat: {
		fusion: ["Typhlosion", "Crobat"],
		num: -17,
		name: "Typhlobat",
		types:["Fire", "Flying"],
		baseStats: {hp: 85, atk: 100, def: 83, spa: 100, spd: 85, spe: 120},
		abilities: {0: "Firey Breakthrough"},
		weightkg: 77.25,
	},
	chimerem: {
		fusion: ["Chimecho", "Kyurem"],
		num: -18, 
		name: "Chimerem",
		types:["Psychic", "Ice"],
		baseStats: {hp: 105, atk: 100, def: 90, spa: 115, spd: 95, spe: 92},
		abilities: {0: "Airborne Oppression"}, 
		weightkg: 163, 
	},
	duskcino: {
		fusion: ["Dusknoir", "Cinccino"],
		num: -19,
		name: "Duskcino",
		types:["Ghost", "Normal"],
		baseStats: {hp: 65, atk: 105, def: 105, spa: 66, spd: 105, spe: 90},
		abilities: {0: "Visual Professional"},
		weightkg: 57.05,
	},
	kecletana: {
		fusion: ["Kecleon", "Kartana"],
		num: -20,
		name: "Kecletana",
		types:["Normal", "Grass"],
		baseStats: {hp: 60, atk: 140, def: 110, spa: 76, spd: 80, spe: 76},
		abilities: {0: "Identity Theft"},
		weightkg: 11.05,
	},
	xataskewda: {
		fusion: ["Xatu", "Barraskewda"],
		num: -21,
		name: "Xataskewda",
		types:["Psychic", "Water"],
		baseStats: {hp: 65, atk: 100, def: 72, spa: 95, spd: 72, spe: 115},
		abilities: {0: "Wet Reflection"},
		weightkg: 22.5,
	},
	hoopiinotic: {
		fusion: ["Hoopa", "Shiinotic"],
		num: -22,
		name: "Hoopiinotic",
		types:["Psychic", "Fairy"],
		baseStats: {hp: 76, atk: 80, def: 80, spa: 125, spd: 125, spe: 56},
		abilities: {0: "Scammer"},
		weightkg: 10.25,
	},
	ariarados: {
		fusion: ["Ariados", "Gyarados"],
		num: -23,
		name: "Ariarados",
		types:["Bug", "Water"],
		baseStats: {hp: 90, atk: 110, def: 75, spa: 65, spd: 90, spe: 78},
		abilities: {0: "Entomophobia"},
		weightkg: 134.25,
	},
	mimidactyl: {
		fusion: ["Mimikyu", "Aerodactyl"],
		num: -24, 
		name: "Mimidactyl",
		baseForme: "Disguised",
		types:["Ghost", "Flying"],
		baseStats: {hp: 70, atk: 100, def: 85, spa: 69, spd: 95, spe: 115},
		abilities: {0: "Freighting Costume"}, 
		weightkg: 29.85,
		otherFormes: ["Mimidactyl-Busted"],
		formeOrder: ["Mimidactyl", "Mimidactyl-Busted"],
	},
	mimidactylbusted: {
		fusion: ["Mimikyu", "Aerodactyl"],
		num: -24, 
		name: "Mimidactyl",
		baseSpecies: "Mimidactyl",
		forme: "Busted",
		types:["Ghost", "Flying"],
		baseStats: {hp: 70, atk: 100, def: 85, spa: 69, spd: 95, spe: 115},
		abilities: {0: "Freighting Costume"}, 
		weightkg: 29.85,
		requiredAbility: "Freighting Costume",
		battleOnly: "Mimidactyl",
	},
	stantilego: {
		fusion: ["Stantler", "Nihilego"],
		num: -25,
		name: "Stantilego",
		types:["Normal", "Rock"],
		baseStats: {hp: 100, atk: 75, def: 60, spa: 110, spd: 106, spe: 106},
		abilities: {0: "Beasty Sipping"},
		weightkg: 63.35,
	},
	trevecuno: {
		fusion: ["Trevenant", "Articuno"],
		num: -26,
		name: "Trevecuno",
		types:["Ghost", "Ice"],
		baseStats: {hp: 95, atk: 100, def: 95, spa: 85, spd: 105, spe: 85},
		abilities: {0: "Healing Stress"},
		weightkg: 63.2,
	},
	calyrexamprider: {
		fusion: ["Calyrex", "Ampharos"],
		num: -27,
		name: "Calyrex-Amp-Rider",
		types:["Psychic", "Electric"],
		baseStats: {hp: 113, atk: 85, def: 85, spa: 100, spd: 90, spe: 70},
		abilities: {0: "As One (Ampharos)"},
		weightkg: 34.6,
	},
	leavoo: {
		fusion: ["Leavanny", "Kommo-o"],
		num: -28,
		name: "Leavo-o",
		types:["Bug", "Dragon"],
		baseStats: {hp: 85, atk: 110, def: 110, spa: 100, spd: 95, spe: 88},
		abilities: {0: "Bug Spray"},
		weightkg: 49.35,
	},
	corsizor: {
		fusion: ["Corsola", "Scizor"],
		num: -29,
		name: "Corsizor",
		types:["Water", "Steel"],
		baseStats: {hp: 73, atk: 100, def: 100, spa: 65, spd: 90, spe: 65},
		abilities: {0: "Thinking Process"},
		weightkg: 61.5,
	},
	wigglytres: {
		fusion: ["Wigglytuff", "Moltres"],
		num: -30,
		name: "Wigglytres",
		types:["Fairy", "Fire"],
		baseStats: {hp: 121, atk: 90, def: 80, spa: 105, spd: 80, spe: 70},
		abilities: {0: "Flaming Rage"},
		weightkg: 39,
	},
};