"use strict";Object.defineProperty(exports, "__esModule", {value: true}); const Pokedex = {
	porygon2: {
		inherit: true,
		species: "Porygon2",
		types: ["Normal"],
		baseStats: {hp: 75, atk: 70, def: 80, spa: 95, spd: 90, spe: 65},
		abilities: {0: "No Ability"},
		// prevo: null,
	},
	jellicent: {
		inherit: true,
		species: "Jellicent",
		types: ["Water", "Ghost"],
		baseStats: {hp: 110, atk: 60, def: 105, spa: 80, spd: 75, spe: 60},
		abilities: {0: "No Ability"},
		// prevo: null,
	},
	crabominable: {
		inherit: true,
		species: "Crabominable",
		types: ["Fighting", "Ice"],
		baseStats: {hp: 97, atk: 122, def: 77, spa: 60, spd: 67, spe: 52},
		abilities: {0: "No Ability"},
		// prevo: null,
	},
	oricoriosensu: {
		inherit: true,
		species: "Oricorio-Sensu",
		types: ["Ghost", "Flying"],
		baseStats: {hp: 80, atk: 70, def: 70, spa: 112, spd: 80, spe: 88},
		abilities: {0: "No Ability"},
		// prevo: null,
	},
	wigglytuff: {
		inherit: true,
		species: "Wigglytuff",
		types: ["Normal", "Fairy"],
		baseStats: {hp: 140, atk: 105, def: 52, spa: 110, spd: 68, spe: 60},
		abilities: {0: "No Ability"},
		// prevo: null,
	},
	wormadamtrash: {
		inherit: true,
		species: "Wormadam-Trash",
		types: ["Bug", "Steel"],
		baseStats: {hp: 70, atk: 75, def: 110, spa: 85, spd: 110, spe: 40},
		abilities: {0: "No Ability"},
		// prevo: null,
	},
	heatmor: {
		inherit: true,
		species: "Heatmor",
		types: ["Fire"],
		baseStats: {hp: 70, atk: 101, def: 80, spa: 55, spd: 69, spe: 100},
		abilities: {0: "No Ability"},
		// prevo: null,
	},
	beheeyem: {
		inherit: true,
		species: "Beheeyem",
		types: ["Psychic"],
		baseStats: {hp: 77, atk: 47, def: 60, spa: 109, spd: 77, spe: 89},
		abilities: {0: "No Ability"},
		// prevo: null,
	},
	golbat: {
		inherit: true,
		species: "Golbat",
		types: ["Poison", "Flying"],
		baseStats: {hp: 75, atk: 80, def: 70, spa: 75, spd: 75, spe: 95},
		abilities: {0: "No Ability"},
		// prevo: null,
	},
	eelektross: {
		inherit: true,
		species: "Eelektross",
		types: ["Electric", "Water"],
		baseStats: {hp: 85, atk: 115, def: 80, spa: 105, spd: 80, spe: 55},
		abilities: {0: "No Ability"},
		// prevo: null,
	},
	togedemaru: {
		inherit: true,
		species: "Togedemaru",
		types: ["Electric", "Steel"],
		baseStats: {hp: 65, atk: 98, def: 63, spa: 40, spd: 83, spe: 111},
		abilities: {0: "No Ability"},
		// prevo: null,
	},
	garchomp: {
		inherit: true,
		species: "Garchomp",
		types: ["Dragon", "Ground"],
		baseStats: {hp: 108, atk: 110, def: 75, spa: 60, spd: 70, spe: 87},
		abilities: {0: "No Ability"},
		// prevo: null,
	},
	whimsicott: {
		inherit: true,
		species: "Whimsicott",
		types: ["Grass", "Fairy"],
		baseStats: {hp: 80, atk: 67, def: 85, spa: 77, spd: 75, spe: 106},
		abilities: {0: "No Ability"},
		// prevo: null,
	},
	skuntank: {
		inherit: true,
		species: "Skuntank",
		types: ["Poison", "Dark"],
		baseStats: {hp: 103, atk: 83, def: 77, spa: 81, spd: 72, spe: 84},
		abilities: {0: "No Ability"},
		// prevo: null,
	},
	lycanrocdusk: {
		inherit: true,
		species: "Lycanroc-Dusk",
		types: ["Rock"],
		baseStats: {hp: 85, atk: 116, def: 75, spa: 55, spd: 75, spe: 84},
		abilities: {0: "No Ability"},
		// prevo: null,
	},
	frosmoth: {
		inherit: true,
		species: "Frosmoth",
		types: ["Ice", "Bug"],
		baseStats: {hp: 70, atk: 65, def: 60, spa: 125, spd: 95, spe: 60},
		abilities: {0: "No Ability"},
		// prevo: null,
	},
	dragonair: {
		inherit: true,
		species: "Dragonair",
		types: ["Dragon"],
		baseStats: {hp: 66, atk: 105, def: 50, spa: 95, spd: 50, spe: 99},
		abilities: {0: "No Ability"},
		// prevo: null,
	},
	reshiram: {
		inherit: true,
		species: "Reshiram",
		types: ["Dragon", "Fire"],
		baseStats: {hp: 129, atk: 65, def: 87, spa: 86, spd: 60, spe: 53},
		abilities: {0: "No Ability"},
		// prevo: null,
	},
	aegislash: {
		inherit: true,
		species: "Aegislash",
		types: ["Steel", "Ghost"],
		baseStats: {hp: 50, atk: 125, def: 150, spa: 50, spd: 65, spe: 40},
		abilities: {0: "No Ability"},
		// prevo: null,
	},
	camerupt: {
		inherit: true,
		species: "Camerupt",
		types: ["Fire", "Ground"],
		baseStats: {hp: 90, atk: 70, def: 80, spa: 105, spd: 70, spe: 75},
		abilities: {0: "No Ability"},
		// prevo: null,
	},
	empoleon: {
		inherit: true,
		species: "Empoleon",
		types: ["Water", "Steel"],
		baseStats: {hp: 99, atk: 88, def: 68, spa: 93, spd: 101, spe: 61},
		abilities: {0: "No Ability"},
		// prevo: null,
	},
	chesnaught: {
		inherit: true,
		species: "Chesnaught",
		types: ["Grass", "Fighting"],
		baseStats: {hp: 88, atk: 107, def: 112, spa: 54, spd: 75, spe: 74},
		abilities: {0: "No Ability"},
		// prevo: null,
	},
	delibird: {
		inherit: true,
		species: "Delibird",
		types: ["Ice", "Flying"],
		baseStats: {hp: 75, atk: 90, def: 55, spa: 90, spd: 65, spe: 100},
		abilities: {0: "No Ability"},
		// prevo: null,
	},
}; exports.Pokedex = Pokedex;