export const Scripts: {[k: string]: ModdedBattleScriptsData} = {
	init: function () {
/*
		for (const id in this.dataCache.Pokedex) {
			const poke = this.dataCache.Pokedex[id];
			if (poke.restrictedLearnset) {
				console.log(this.toID(poke.name));
				const thisPoke = this.toID(poke.name);
				const learnset = this.dataCache.Learnsets[this.toID(poke.name)].learnset;
				for (const move in learnset) {
					console.log(thisPoke + " has " + move);
					const moveid = this.dataCache.Moves[move];
					if (moveid.isNonstandard) {
						console.log(moveid.isNonstandard);
						delete this.modData('Learnsets', thisPoke).learnset.moveid;
					}
				}
			}
		}
*/
		// Riolu
		this.modData("Learnsets", "riolu").learnset.partingshot = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.taunt = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.aerialace = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.allyswitch = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.ancientpower = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.aurasphere = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.batonpass = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.calmmind = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.chargebeam = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.confide = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.confusion = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.curse = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.cut = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.dazzlinggleam = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.defensecurl = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.detect = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.doubleteam = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.doubleedge = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.dreameater = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.dualwingbeat = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.earthpower = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.echoedvoice = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.endure = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.energyball = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.expandingforce = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.facade = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.fling = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.futuresight = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.gigadrain = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.gigaimpact = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.grassknot = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.grassyglide = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.grassyterrain = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.healbell = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.healingwish = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.helpinghand = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.holdback = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.hyperbeam = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.imprison = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.laserfocus = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.lastresort = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.leafblade = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.leafstorm = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.leechseed = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.lifedew = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.lightscreen = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.magiccoat = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.magicroom = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.magicalleaf = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.metronome = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.mimic = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.mudslap = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.nastyplot = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.naturepower = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.perishsong = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.pollenpuff = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.protect = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.psychup = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.psychic = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.psychicterrain = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.psychocut = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.raindance = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.recover = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.reflect = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.rest = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.round = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.safeguard = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.sandstorm = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.seedbomb = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.shadowball = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.shockwave = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.skillswap = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.sleeptalk = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.snore = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.solarbeam = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.solarblade = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.stealthrock = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.substitute = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.suckerpunch = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.sunnyday = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.swagger = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.sweetscent = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.swift = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.swordsdance = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.synthesis = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.thunderwave = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.toxic = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.trick = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.trickroom = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.uturn = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.uproar = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.waterpulse = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.weatherball = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.wonderroom = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.worryseed = ["8L1"];
		this.modData("Learnsets", "riolu").learnset.zenheadbutt = ["8L1"];
		// Articuno
		delete this.modData('Learnsets', 'articuno').learnset.auroraveil;
		// Hoopa
		delete this.modData('Learnsets', 'hoopa').learnset.darkpulse;
		delete this.modData('Learnsets', 'hoopa').learnset.knockoff;
		delete this.modData('Learnsets', 'hoopa').learnset.thief;
		delete this.modData('Learnsets', 'hoopa').learnset.throatchop;
		delete this.modData('Learnsets', 'hoopa').learnset.psyshock;
		delete this.modData('Learnsets', 'hoopa').learnset.quash;
		// Gallade
		this.modData("Learnsets", "gallade").learnset.ironhead = ["8L1"];
		this.modData("Learnsets", "gallade").learnset.bulletpunch = ["8L1"];
		this.modData("Learnsets", "gallade").learnset.metalclaw = ["8L1"];
		this.modData("Learnsets", "gallade").learnset.powertrip = ["8L1"];
		this.modData("Learnsets", "gallade").learnset.meteormash = ["8L1"];
		this.modData("Learnsets", "gallade").learnset.yawn = ["8L1"];
		this.modData("Learnsets", "gallade").learnset.steelbeam = ["8L1"];
		this.modData("Learnsets", "gallade").learnset.rockpolish = ["8L1"];
		// Gardevoir
		this.modData("Learnsets", "gardevoir").learnset.flashcannon = ["8L1"];
		this.modData("Learnsets", "gardevoir").learnset.rockpolish = ["8L1"];
		this.modData("Learnsets", "gardevoir").learnset.gearup = ["8L1"];
		// Morpeko
		this.modData("Learnsets", "morpeko").learnset.swordsdance = ["8L1"];
		this.modData("Learnsets", "morpeko").learnset.stealthrock = ["8L1"];
		this.modData("Learnsets", "morpeko").learnset.playrough = ["8L1"];
		this.modData("Learnsets", "morpeko").learnset.superpower = ["8L1"];
		this.modData("Learnsets", "morpeko").learnset.knockoff = ["8L1"];
		this.modData("Learnsets", "morpeko").learnset.stuffcheeks = ["8L1"];
		this.modData("Learnsets", "morpeko").learnset.recycle = ["8L1"];
		// Zapdos-Galar
		this.modData("Learnsets", "zapdosgalar").learnset.toxic = ["8L1"];
		this.modData("Learnsets", "zapdosgalar").learnset.defog = ["8L1"];
		this.modData("Learnsets", "zapdosgalar").learnset.watergun = ["8L1"];
		this.modData("Learnsets", "zapdosgalar").learnset.waterpulse = ["8L1"];
		this.modData("Learnsets", "zapdosgalar").learnset.earthquake = ["8L1"];
		this.modData("Learnsets", "zapdosgalar").learnset.swordsdance = ["8L1"];
		this.modData("Learnsets", "zapdosgalar").learnset.flamecharge = ["8L1"];
		this.modData("Learnsets", "zapdosgalar").learnset.stoneedge = ["8L1"];
		this.modData("Learnsets", "zapdosgalar").learnset.rockslide = ["8L1"];
		this.modData("Learnsets", "zapdosgalar").learnset.irondefense = ["8L1"];
		this.modData("Learnsets", "zapdosgalar").learnset.ironhead = ["8L1"];
		this.modData("Learnsets", "zapdosgalar").learnset.poisonjab = ["8L1"];
		this.modData("Learnsets", "zapdosgalar").learnset.spikes = ["8L1"];
		// Archeops
		this.modData("Learnsets", "archeops").learnset.flamethrower = ["8L1"];
		this.modData("Learnsets", "archeops").learnset.fireblast = ["8L1"];
		this.modData("Learnsets", "archeops").learnset.burnup = ["8L1"];
		this.modData("Learnsets", "archeops").learnset.lavaplume = ["8L1"];
		this.modData("Learnsets", "archeops").learnset.bravebird = ["8L1"];
		this.modData("Learnsets", "archeops").learnset.revenge = ["8L1"];
		// Castform
		this.modData("Learnsets", "castform").learnset.terrainpulse = ["8L1"];
		this.modData("Learnsets", "castform").learnset.naturepower = ["8L1"];
		this.modData("Learnsets", "castform").learnset.electricterrain = ["8L1"];
		this.modData("Learnsets", "castform").learnset.grassyterrain = ["8L1"];
		this.modData("Learnsets", "castform").learnset.mistyterrain = ["8L1"];
		this.modData("Learnsets", "castform").learnset.psychicterrain = ["8L1"];
		this.modData("Learnsets", "castform").learnset.grassyglide = ["8L1"];
		this.modData("Learnsets", "castform").learnset.risingvoltage = ["8L1"];
		this.modData("Learnsets", "castform").learnset.mistyexplosion = ["8L1"];
		this.modData("Learnsets", "castform").learnset.expandingforce = ["8L1"];
		this.modData("Learnsets", "castform").learnset.explosion = ["8L1"];
		this.modData("Learnsets", "castform").learnset.powergem = ["8L1"];
		this.modData("Learnsets", "castform").learnset.recover = ["8L1"];
		this.modData("Learnsets", "castform").learnset.psychic = ["8L1"];
		this.modData("Learnsets", "castform").learnset.psyshock = ["8L1"];
		this.modData("Learnsets", "castform").learnset.dazzlinggleam = ["8L1"];
		this.modData("Learnsets", "castform").learnset.moonblast = ["8L1"];
		this.modData("Learnsets", "castform").learnset.irondefense = ["8L1"];
		this.modData("Learnsets", "castform").learnset.calmmind = ["8L1"];
		this.modData("Learnsets", "castform").learnset.stealthrock = ["8L1"];
		this.modData("Learnsets", "castform").learnset.taunt = ["8L1"];
		this.modData("Learnsets", "castform").learnset.hypervoice = ["8L1"];
		this.modData("Learnsets", "castform").learnset.gigadrain = ["8L1"];
		this.modData("Learnsets", "castform").learnset.trick = ["8L1"];
		this.modData("Learnsets", "castform").learnset.electroweb = ["8L1"];
		delete this.modData('Learnsets', 'castform').learnset.fireblast;
		delete this.modData('Learnsets', 'castform').learnset.flamethrower;
		delete this.modData('Learnsets', 'castform').learnset.hydropump;
		delete this.modData('Learnsets', 'castform').learnset.scald;
		delete this.modData('Learnsets', 'castform').learnset.ember;
		delete this.modData('Learnsets', 'castform').learnset.hail;
		delete this.modData('Learnsets', 'castform').learnset.raindance;
		delete this.modData('Learnsets', 'castform').learnset.sunnyday;
		delete this.modData('Learnsets', 'castform').learnset.sandstorm;
		delete this.modData('Learnsets', 'castform').learnset.incinerate;
		delete this.modData('Learnsets', 'castform').learnset.powdersnow;
		delete this.modData('Learnsets', 'castform').learnset.watergun;
		delete this.modData('Learnsets', 'castform').learnset.waterpulse;
		// Corsola
		this.modData("Learnsets", "corsola").learnset.gigadrain = ["8L1"];
		this.modData("Learnsets", "corsola").learnset.energyball = ["8L1"];
		this.modData("Learnsets", "corsola").learnset.seedbomb = ["8L1"];
		this.modData("Learnsets", "corsola").learnset.spikes = ["8L1"];
		// Chatot
		this.modData("Learnsets", "chatot").learnset.rockout = ["8L1"];
		this.modData("Learnsets", "chatot").learnset.eeriespell = ["8L1"];
		this.modData("Learnsets", "chatot").learnset.stoneedge = ["8L1"];
		this.modData("Learnsets", "chatot").learnset.rockslide = ["8L1"];
		this.modData("Learnsets", "chatot").learnset.ancientpower = ["8L1"];
		this.modData("Learnsets", "chatot").learnset.partingshot = ["8L1"];
		this.modData("Learnsets", "chatot").learnset.snarl = ["8L1"];
		// Ariados
		this.modData("Learnsets", "ariados").learnset.focusblast = ["8L1"];
		this.modData("Learnsets", "ariados").learnset.sludgewave = ["8L1"];
		this.modData("Learnsets", "ariados").learnset.bugbuzz = ["8L1"];
		this.modData("Learnsets", "ariados").learnset.shadowball = ["8L1"];
		// Carnivine
		this.modData("Learnsets", "carnivine").learnset.doubleedge = ["8L1"];
		this.modData("Learnsets", "carnivine").learnset.hypervoice = ["8L1"];
		this.modData("Learnsets", "carnivine").learnset.leechlife = ["8L1"];
		this.modData("Learnsets", "carnivine").learnset.superfang = ["8L1"];
		this.modData("Learnsets", "carnivine").learnset.poisonfang = ["8L1"];
		this.modData("Learnsets", "carnivine").learnset.suckerpunch = ["8L1"];
		this.modData("Learnsets", "carnivine").learnset.toxicspikes = ["8L1"];
		// Noctowl
		this.modData("Learnsets", "noctowl").learnset.uturn = ["8L1"];
		this.modData("Learnsets", "noctowl").learnset.darkpulse = ["8L1"];
		this.modData("Learnsets", "noctowl").learnset.moonlight = ["8L1"];
		this.modData("Learnsets", "noctowl").learnset.taunt = ["8L1"];
		this.modData("Learnsets", "noctowl").learnset.yawn = ["8L1"];
		// Lurantis
		this.modData("Learnsets", "lurantis").learnset.chloroscythe = ["8L1"];
		this.modData("Learnsets", "lurantis").learnset.roost = ["8L1"];
		this.modData("Learnsets", "lurantis").learnset.stunspore = ["8L1"];
		// Octillery
		this.modData("Learnsets", "octillery").learnset.flipturn = ["8L1"];
		this.modData("Learnsets", "octillery").learnset.darkpulse = ["8L1"];
		this.modData("Learnsets", "octillery").learnset.aurasphere = ["8L1"];
		this.modData("Learnsets", "octillery").learnset.dragonpulse = ["8L1"];
		this.modData("Learnsets", "octillery").learnset.wrap = ["8L1"];
		this.modData("Learnsets", "octillery").learnset.laserfocus = ["8L1"];
		this.modData("Learnsets", "octillery").learnset.knockoff = ["8L1"];
		this.modData("Learnsets", "octillery").learnset.payback = ["8L1"];
		this.modData("Learnsets", "octillery").learnset.brutalswing = ["8L1"];
		this.modData("Learnsets", "octillery").learnset.taunt = ["8L1"];
		this.modData("Learnsets", "octillery").learnset.torment = ["8L1"];
		this.modData("Learnsets", "octillery").learnset.snarl = ["8L1"];
		// Unfezant
		this.modData("Learnsets", "unfezant").learnset.psychocut = ["8L1"];
		this.modData("Learnsets", "unfezant").learnset.brickbreak = ["8L1"];
		this.modData("Learnsets", "unfezant").learnset.swordsdance = ["8L1"];
		// Kricketune
		this.modData("Learnsets", "kricketune").learnset.roost = ["8L1"];
		this.modData("Learnsets", "kricketune").learnset.earthquake = ["8L1"];
		// Leafeon
		this.modData("Learnsets", "leafeon").learnset.stompingtantrum = ["8L1"];
		this.modData("Learnsets", "leafeon").learnset.hornleech = ["8L1"];
		this.modData("Learnsets", "leafeon").learnset.lowkick = ["8L1"];
		// Dedenne
		this.modData("Learnsets", "dedenne").learnset.petalblizzard = ["8L1"];
		this.modData("Learnsets", "dedenne").learnset.leechseed = ["8L1"];
		this.modData("Learnsets", "dedenne").learnset.swordsdance = ["8L1"];
		this.modData("Learnsets", "dedenne").learnset.berrybomb = ["8L1"];
		// Electrode
		this.modData("Learnsets", "electrode").learnset.focusblast = ["8L1"];
		this.modData("Learnsets", "electrode").learnset.energyball = ["8L1"];
		// Luxray
		this.modData("Learnsets", "luxray").learnset.icebeam = ["8L1"];
		this.modData("Learnsets", "luxray").learnset.iciclecrash = ["8L1"];
		this.modData("Learnsets", "luxray").learnset.iceshard = ["8L1"];
		this.modData("Learnsets", "luxray").learnset.blizzard = ["8L1"];
		// Seviper
		this.modData("Learnsets", "seviper").learnset.firefang = ["8L1"];
		this.modData("Learnsets", "seviper").learnset.icefang = ["8L1"];
		this.modData("Learnsets", "seviper").learnset.thunderfang = ["8L1"];
		this.modData("Learnsets", "seviper").learnset.psychicfangs = ["8L1"];
		this.modData("Learnsets", "seviper").learnset.voltswitch = ["8L1"];
		// Kangaskhan
		this.modData("Learnsets", "kangaskhan").learnset.bulkup = ["8L1"];
		this.modData("Learnsets", "kangaskhan").learnset.stealthrock = ["8L1"];
		this.modData("Learnsets", "kangaskhan").learnset.stoneedge = ["8L1"];
		// Venusaur
		this.modData("Learnsets", "venusaur").learnset.sludgewave = ["8L1"];
		// Charizard
		this.modData("Learnsets", "charizard").learnset.bravebird = ["8L1"];
		// Blastoise
		this.modData("Learnsets", "blastoise").learnset.poisonfang = ["8L1"];
		// Scyther
		this.modData("Learnsets", "scyther").learnset.mindrake = ["8L1"];
		this.modData("Learnsets", "scyther").learnset.psychic = ["8L1"];
		this.modData("Learnsets", "scyther").learnset.psyshock = ["8L1"];
		this.modData("Learnsets", "scyther").learnset.psychocut = ["8L1"];
		this.modData("Learnsets", "scyther").learnset.telekinesis = ["8L1"];
		this.modData("Learnsets", "scyther").learnset.zenheadbutt = ["8L1"];
		this.modData("Learnsets", "scyther").learnset.leechlife = ["8L1"];
		this.modData("Learnsets", "scyther").learnset.torment = ["8L1"];
		this.modData("Learnsets", "scyther").learnset.roleplay = ["8L1"];
		this.modData("Learnsets", "scyther").learnset.skillswap = ["8L1"];
		this.modData("Learnsets", "scyther").learnset.speedswap = ["8L1"];
		this.modData("Learnsets", "scyther").learnset.flash = ["8L1"];
		// Probopass
		this.modData("Learnsets", "probopass").learnset.relicrejuvenation = ["8L1"];
		this.modData("Learnsets", "probopass").learnset.psywave = ["8L1"];
		this.modData("Learnsets", "probopass").learnset.futuresight = ["8L1"];
		this.modData("Learnsets", "probopass").learnset.trick = ["8L1"];
		this.modData("Learnsets", "probopass").learnset.bodypress = ["8L1"];
		// Luxio
		this.modData("Learnsets", "luxio").learnset.agility = ["8L1"];
		// Banette
		this.modData("Learnsets", "banette").learnset.copycat = ["8L1"];
		this.modData("Learnsets", "banette").learnset.uturn = ["8L1"];
		this.modData("Learnsets", "banette").learnset.swordsdance = ["8L1"];
		// Heracross
		this.modData("Learnsets", "heracross").learnset.meteormash = ["8L1"];
		this.modData("Learnsets", "heracross").learnset.crosschop = ["8L1"];
		// Pidgeot
		this.modData("Learnsets", "pidgeot").learnset.thunderwave = ["8L1"];
		// Kirlia
		this.modData("Learnsets", "kirlia").learnset.moonblast = ["8L1"];
		this.modData("Learnsets", "kirlia").learnset.focusblast = ["8L1"];
		this.modData("Learnsets", "kirlia").learnset.aurasphere = ["8L1"];
		this.modData("Learnsets", "kirlia").learnset.flashcannon = ["8L1"];
		this.modData("Learnsets", "kirlia").learnset.mysticalfire = ["8L1"];
		this.modData("Learnsets", "kirlia").learnset.vacuumwave = ["8L1"];
		this.modData("Learnsets", "kirlia").learnset.airslash = ["8L1"];
		this.modData("Learnsets", "kirlia").learnset.hex = ["8L1"];
		this.modData("Learnsets", "kirlia").learnset.workup = ["8L1"];
		this.modData("Learnsets", "kirlia").learnset.roost = ["8L1"];
		this.modData("Learnsets", "kirlia").learnset.defog = ["8L1"];
		// Sandslash
		this.modData("Learnsets", "sandslash").learnset.rototiller = ["8L1"];
		this.modData("Learnsets", "sandslash").learnset.toxicspikes = ["8L1"];
		// Pelipper
		this.modData("Learnsets", "pelipper").learnset.yawn = ["8L1"];
		this.modData("Learnsets", "pelipper").learnset.taunt = ["8L1"];
		this.modData("Learnsets", "pelipper").learnset.featherdance = ["8L1"];
		this.modData("Learnsets", "pelipper").learnset.thunderwave = ["8L1"];
		// Monferno
		this.modData("Learnsets", "monferno").learnset.zenheadbutt = ["8L1"];
		this.modData("Learnsets", "monferno").learnset.moonblast = ["8L1"];
		// Greedent
		this.modData("Learnsets", "greedent").learnset.earthpower = ["8L1"];
		this.modData("Learnsets", "greedent").learnset.energyball = ["8L1"];
		this.modData("Learnsets", "greedent").learnset.bulldoze = ["8L1"];
		this.modData("Learnsets", "greedent").learnset.woodhammer = ["8L1"];
		this.modData("Learnsets", "greedent").learnset.curse = ["8L1"];
		this.modData("Learnsets", "greedent").learnset.recycle = ["8L1"];
		this.modData("Learnsets", "greedent").learnset.rockslide = ["8L1"];
		this.modData("Learnsets", "greedent").learnset.stoneedge = ["8L1"];
		this.modData("Learnsets", "greedent").learnset.thunderpunch = ["8L1"];
		this.modData("Learnsets", "greedent").learnset.icepunch = ["8L1"];
		this.modData("Learnsets", "greedent").learnset.firepunch = ["8L1"];
		// Indeedee-F
		this.modData("Learnsets", "indeedeef").learnset.moonblast = ["8L1"];
		this.modData("Learnsets", "indeedeef").learnset.moonlight = ["8L1"];
		this.modData("Learnsets", "indeedeef").learnset.charm = ["8L1"];
		// Primarina
		this.modData("Learnsets", "primarina").learnset.deepseafinale = ["8L1"];
		// Hoopa
		this.modData("Learnsets", "hoopa").learnset.heavyslam = ["8L1"];
		this.modData("Learnsets", "hoopa").learnset.flashcannon = ["8L1"];
		this.modData("Learnsets", "hoopa").learnset.irondefense = ["8L1"];
		this.modData("Learnsets", "hoopa").learnset.ironhead = ["8L1"];
		this.modData("Learnsets", "hoopa").learnset.charm = ["8L1"];
		this.modData("Learnsets", "hoopa").learnset.moonblast = ["8L1"];
		this.modData("Learnsets", "hoopa").learnset.playrough = ["8L1"];
		this.modData("Learnsets", "hoopa").learnset.sandstorm = ["8L1"];
		this.modData("Learnsets", "hoopa").learnset.ancientpower = ["8L1"];
		this.modData("Learnsets", "hoopa").learnset.wish = ["8L1"];
		// Clefable
		delete this.modData('Learnsets', 'clefairy').learnset.teleport;
		delete this.modData('Learnsets', 'clefable').learnset.teleport;
		// Delibird
		this.modData("Learnsets", "delibird").learnset.uturn = ["8L1"];
		this.modData("Learnsets", "delibird").learnset.drainpunch = ["8L1"];
		this.modData("Learnsets", "delibird").learnset.superpower = ["8L1"];
		this.modData("Learnsets", "delibird").learnset.tripleaxel = ["8L1"];
		this.modData("Learnsets", "delibird").learnset.iciclecrash = ["8L1"];
		// Vanilluxe
		this.modData("Learnsets", "vanilluxe").learnset.muddywater = ["8L1"];
		// Oranguru
		this.modData("Learnsets", "oranguru").learnset.uturn = ["8L1"];
		this.modData("Learnsets", "oranguru").learnset.agility = ["8L1"];
		this.modData("Learnsets", "oranguru").learnset.amnesia = ["8L1"];
		this.modData("Learnsets", "oranguru").learnset.calmmind = ["8L1"];
		this.modData("Learnsets", "oranguru").learnset.confusion = ["8L1"];
		this.modData("Learnsets", "oranguru").learnset.expandingforce = ["8L1"];
		this.modData("Learnsets", "oranguru").learnset.healpulse = ["8L1"];
		this.modData("Learnsets", "oranguru").learnset.hypnosis = ["8L1"];
		this.modData("Learnsets", "oranguru").learnset.imprison = ["8L1"];
		this.modData("Learnsets", "oranguru").learnset.lightscreen = ["8L1"];
		this.modData("Learnsets", "oranguru").learnset.magiccoat = ["8L1"];
		this.modData("Learnsets", "oranguru").learnset.mirrorcoat = ["8L1"];
		this.modData("Learnsets", "oranguru").learnset.miracleeye = ["8L1"];
		this.modData("Learnsets", "oranguru").learnset.psybeam = ["8L1"];
		this.modData("Learnsets", "oranguru").learnset.psychic = ["8L1"];
		this.modData("Learnsets", "oranguru").learnset.psyshock = ["8L1"];
		this.modData("Learnsets", "oranguru").learnset.psychocut = ["8L1"];
		this.modData("Learnsets", "oranguru").learnset.reflect = ["8L1"];
		this.modData("Learnsets", "oranguru").learnset.skillswap = ["8L1"];
		this.modData("Learnsets", "oranguru").learnset.storedpower = ["8L1"];
		this.modData("Learnsets", "oranguru").learnset.trick = ["8L1"];
		this.modData("Learnsets", "oranguru").learnset.zenheadbutt = ["8L1"];
		this.modData("Learnsets", "oranguru").learnset.dazzlinggleam = ["8L1"];
		this.modData("Learnsets", "oranguru").learnset.shadowball = ["8L1"];
		this.modData("Learnsets", "oranguru").learnset.energyball = ["8L1"];
		this.modData("Learnsets", "oranguru").learnset.grasswhistle = ["8L1"];
		this.modData("Learnsets", "oranguru").learnset.hypervoice = ["8L1"];
		this.modData("Learnsets", "oranguru").learnset.mysticalfire = ["8L1"];
		this.modData("Learnsets", "oranguru").learnset.laserfocus = ["8L1"];
		this.modData("Learnsets", "oranguru").learnset.mindreader = ["8L1"];
		this.modData("Learnsets", "oranguru").learnset.trickroom = ["8L1"];
		this.modData("Learnsets", "oranguru").learnset.coaching = ["8L1"];
		this.modData("Learnsets", "oranguru").learnset.nastyplot = ["8L1"];
		this.modData("Learnsets", "oranguru").learnset.focusblast = ["8L1"];
		this.modData("Learnsets", "oranguru").learnset.overheat = ["8L1"];
		// Primeape
		this.modData("Learnsets", "primeape").learnset.throatchop = ["8L1"];
		this.modData("Learnsets", "primeape").learnset.hyperbeam = ["8L1"];
		this.modData("Learnsets", "primeape").learnset.gigaimpact = ["8L1"];
		this.modData("Learnsets", "primeape").learnset.shadowball = ["8L1"];
		this.modData("Learnsets", "primeape").learnset.stoneedge = ["8L1"];
		this.modData("Learnsets", "primeape").learnset.highhorsepower = ["8L1"];
		this.modData("Learnsets", "primeape").learnset.magicroom = ["8L1"];
		this.modData("Learnsets", "primeape").learnset.powerswap = ["8L1"];
		this.modData("Learnsets", "primeape").learnset.trick = ["8L1"];
		this.modData("Learnsets", "primeape").learnset.extrasensory = ["8L1"];
		this.modData("Learnsets", "primeape").learnset.hex = ["8L1"];
		this.modData("Learnsets", "primeape").learnset.spiritbreak = ["8L1"];
		this.modData("Learnsets", "primeape").learnset.ironhead = ["8L1"];
		this.modData("Learnsets", "primeape").learnset.lashout = ["8L1"];
		this.modData("Learnsets", "primeape").learnset.playrough = ["8L1"];
		this.modData("Learnsets", "primeape").learnset.morningsun = ["8L1"];
		this.modData("Learnsets", "primeape").learnset.charm = ["8L1"];
		this.modData("Learnsets", "primeape").learnset.disarmingvoice = ["8L1"];
		this.modData("Learnsets", "primeape").learnset.dazzlinggleam = ["8L1"];
		this.modData("Learnsets", "primeape").learnset.sweetkiss = ["8L1"];
		this.modData("Learnsets", "primeape").learnset.energyball = ["8L1"];
		this.modData("Learnsets", "primeape").learnset.solarbeam = ["8L1"];
		this.modData("Learnsets", "primeape").learnset.solarblade = ["8L1"];
		this.modData("Learnsets", "primeape").learnset.flamethrower = ["8L1"];
		this.modData("Learnsets", "primeape").learnset.mysticalfire = ["8L1"];
		this.modData("Learnsets", "primeape").learnset.fireblast = ["8L1"];
		this.modData("Learnsets", "primeape").learnset.blazekick = ["8L1"];
		this.modData("Learnsets", "primeape").learnset.zenheadbutt = ["8L1"];
		this.modData("Learnsets", "primeape").learnset.thunderwave = ["8L1"];
		this.modData("Learnsets", "primeape").learnset.psychic = ["8L1"];
		this.modData("Learnsets", "primeape").learnset.painsplit = ["8L1"];
		this.modData("Learnsets", "primeape").learnset.foulplay = ["8L1"];
		this.modData("Learnsets", "primeape").learnset.torment = ["8L1"];
		this.modData("Learnsets", "primeape").learnset.throatchop = ["8L1"];
		this.modData("Learnsets", "primeape").learnset.mistyterrain = ["8L1"];
		this.modData("Learnsets", "primeape").learnset.faketears = ["8L1"];
		this.modData("Learnsets", "primeape").learnset.knockoff = ["8L1"];
		// Machamp
		this.modData("Learnsets", "machamp").learnset.machpunch = ["8L1"];
		this.modData("Learnsets", "machamp").learnset.forcepalm = ["8L1"];
		this.modData("Learnsets", "machamp").learnset.laserfocus = ["8L1"];
		this.modData("Learnsets", "machamp").learnset.flamewheel = ["8L1"];
		this.modData("Learnsets", "machamp").learnset.stormthrow = ["8L1"];
		this.modData("Learnsets", "machamp").learnset.circlethrow = ["8L1"];
		// Wartortle
		this.modData("Learnsets", "wartortle").learnset.iciclespear = ["8L1"];
		this.modData("Learnsets", "wartortle").learnset.iceball = ["8L1"];
		this.modData("Learnsets", "wartortle").learnset.hammerarm = ["8L1"];
		// Garbodor
		this.modData("Learnsets", "garbodor").learnset.barrier = ["8L1"];
		this.modData("Learnsets", "garbodor").learnset.blizzard = ["8L1"];
		this.modData("Learnsets", "garbodor").learnset.cosmicpower = ["8L1"];
		this.modData("Learnsets", "garbodor").learnset.crosspoison = ["8L1"];
		this.modData("Learnsets", "garbodor").learnset.expandingforce = ["8L1"];
		this.modData("Learnsets", "garbodor").learnset.futuresight = ["8L1"];
		this.modData("Learnsets", "garbodor").learnset.guardswap = ["8L1"];
		this.modData("Learnsets", "garbodor").learnset.gravity = ["8L1"];
		this.modData("Learnsets", "garbodor").learnset.hail = ["8L1"];
		this.modData("Learnsets", "garbodor").learnset.healblock = ["8L1"];
		this.modData("Learnsets", "garbodor").learnset.icebeam = ["8L1"];
		this.modData("Learnsets", "garbodor").learnset.icepunch = ["8L1"];
		this.modData("Learnsets", "garbodor").learnset.imprison = ["8L1"];
		this.modData("Learnsets", "garbodor").learnset.magiccoat = ["8L1"];
		this.modData("Learnsets", "garbodor").learnset.magicroom = ["8L1"];
		this.modData("Learnsets", "garbodor").learnset.meditate = ["8L1"];
		this.modData("Learnsets", "garbodor").learnset.meteorbeam = ["8L1"];
		this.modData("Learnsets", "garbodor").learnset.meteormash = ["8L1"];
		this.modData("Learnsets", "garbodor").learnset.mist = ["8L1"];
		this.modData("Learnsets", "garbodor").learnset.powerswap = ["8L1"];
		this.modData("Learnsets", "garbodor").learnset.psybeam = ["8L1"];
		this.modData("Learnsets", "garbodor").learnset.psychicterrain = ["8L1"];
		this.modData("Learnsets", "garbodor").learnset.psychocut = ["8L1"];
		this.modData("Learnsets", "garbodor").learnset.psyshock = ["8L1"];
		this.modData("Learnsets", "garbodor").learnset.skillswap = ["8L1"];
		this.modData("Learnsets", "garbodor").learnset.speedswap = ["8L1"];
		this.modData("Learnsets", "garbodor").learnset.stoneedge = ["8L1"];
		this.modData("Learnsets", "garbodor").learnset.swift = ["8L1"];
		this.modData("Learnsets", "garbodor").learnset.telekinesis = ["8L1"];
		this.modData("Learnsets", "garbodor").learnset.teleport = ["8L1"];
		this.modData("Learnsets", "garbodor").learnset.trick = ["8L1"];
		this.modData("Learnsets", "garbodor").learnset.trickroom = ["8L1"];
		this.modData("Learnsets", "garbodor").learnset.wonderroom = ["8L1"];
		this.modData("Learnsets", "garbodor").learnset.zenheadbutt = ["8L1"];
		this.modData("Learnsets", "garbodor").learnset.recover = ["8L1"];
		// Yanmega
		this.modData("Learnsets", "yanmega").learnset.dracometeor = ["8L1"];
		this.modData("Learnsets", "yanmega").learnset.dragonpulse = ["8L1"];
		this.modData("Learnsets", "yanmega").learnset.dragontail = ["8L1"];
		this.modData("Learnsets", "yanmega").learnset.flashcannon = ["8L1"];
		// Rotom-Fan
		this.modData("Learnsets", "rotomfan").learnset.flashcannon = ["8L1"];
		this.modData("Learnsets", "rotomfan").learnset.steelbeam = ["8L1"];
		// Oricorio-Sensu
		this.modData("Learnsets", "oricorio").learnset.quiverdance = ["8L1"];
		this.modData("Learnsets", "oricorio").learnset.fierydance = ["8L1"];
		this.modData("Learnsets", "oricorio").learnset.heatwave = ["8L1"];
		// Oricorio-Pom-Pom
		this.modData("Learnsets", "oricorio").learnset.doubleedge = ["8L1"];
		this.modData("Learnsets", "oricorio").learnset.bravebird = ["8L1"];
		this.modData("Learnsets", "oricorio").learnset.drillpeck = ["8L1"];
		this.modData("Learnsets", "oricorio").learnset.nightslash = ["8L1"];
		this.modData("Learnsets", "oricorio").learnset.rapidspin = ["8L1"];
		this.modData("Learnsets", "oricorio").learnset.revelationspin = ["8L1"];
		this.modData("Learnsets", "oricorio").learnset.stompingtantrum = ["8L1"];
		this.modData("Learnsets", "oricorio").learnset.tripleaxel = ["8L1"];
		this.modData("Learnsets", "oricorio").learnset.dualwingbeat = ["8L1"];
		this.modData("Learnsets", "oricorio").learnset.megakick = ["8L1"];
		// Ledian
		this.modData("Learnsets", "ledian").learnset.closecombat = ["8L1"];
		this.modData("Learnsets", "ledian").learnset.bulletpunch = ["8L1"];
		this.modData("Learnsets", "ledian").learnset.lunge = ["8L1"];
		// Accelgor
		this.modData("Learnsets", "accelgor").learnset.darkpulse = ["8L1"];
		this.modData("Learnsets", "accelgor").learnset.foulplay = ["8L1"];
		this.modData("Learnsets", "accelgor").learnset.taunt = ["8L1"];
		this.modData("Learnsets", "accelgor").learnset.mysticalfire = ["8L1"];
		// Floatzel
		this.modData("Learnsets", "floatzel").learnset.flipturn = ["8L1"];
		this.modData("Learnsets", "floatzel").learnset.drainpunch = ["8L1"];
		this.modData("Learnsets", "floatzel").learnset.doublekick = ["8L1"];
		this.modData("Learnsets", "floatzel").learnset.assurance = ["8L1"];
		this.modData("Learnsets", "floatzel").learnset.rapidspin = ["8L1"];
		this.modData("Learnsets", "floatzel").learnset.closecombat = ["8L1"];
		// Furret
		this.modData("Learnsets", "furret").learnset.spiritbreak = ["8L1"];
		this.modData("Learnsets", "furret").learnset.playrough = ["8L1"];
		this.modData("Learnsets", "furret").learnset.slackoff = ["8L1"];
		// Masquerain
		this.modData("Learnsets", "masquerain").learnset.flipturn = ["8L1"];
		this.modData("Learnsets", "masquerain").learnset.surf = ["8L1"];
		// Arbok
		this.modData("Learnsets", "arbok").learnset.leechlife = ["8L1"];
		this.modData("Learnsets", "arbok").learnset.dragonrush = ["8L1"];
		this.modData("Learnsets", "arbok").learnset.scaleshot = ["8L1"];
		this.modData("Learnsets", "arbok").learnset.dracometeor = ["8L1"];
		this.modData("Learnsets", "arbok").learnset.taunt = ["8L1"];
		// Flygon
		this.modData("Learnsets", "flygon").learnset.leechlife = ["8L1"];
		this.modData("Learnsets", "flygon").learnset.quiverdance = ["8L1"];
		// Polteageist
		this.modData("Learnsets", "polteageist").learnset.scald = ["8L1"];
		this.modData("Learnsets", "polteageist").learnset.greentea = ["8L1"];
		// Kyurem-Black
		this.modData("Learnsets", "kyuremblack").learnset.futureshock = ["8L1"];
		// Obstagoon
		this.modData("Learnsets", "obstagoon").learnset.breakdown = ["8L1"];
		// Starmie
		this.modData("Learnsets", "starmie").learnset.shootingstar = ["8L1"];
		// Xurkitree
		this.modData("Learnsets", "xurkitree").learnset.haywire = ["8L1"];
		// Skuntank
		this.modData("Learnsets", "skuntank").learnset.stinkbomb = ["8L1"];
		this.modData("Learnsets", "skuntank").learnset.knockoff = ["8L1"];
		this.modData("Learnsets", "skuntank").learnset.willowisp = ["8L1"];
		this.modData("Learnsets", "skuntank").learnset.thunderwave = ["8L1"];
		this.modData("Learnsets", "skuntank").learnset.gunkshot = ["8L1"];
		this.modData("Learnsets", "skuntank").learnset.blazekick = ["8L1"];
		this.modData("Learnsets", "skuntank").learnset.aromatherapy = ["8L1"];
		this.modData("Learnsets", "skuntank").learnset.bulkup = ["8L1"];
		this.modData("Learnsets", "skuntank").learnset.partingshot = ["8L1"];
		this.modData("Learnsets", "skuntank").learnset.poisondart = ["8L1"];
		// Tauros
		this.modData("Learnsets", "tauros").learnset.stampede = ["8L1"];
		// Sudowoodo
		this.modData("Learnsets", "sudowoodo").learnset.petrify = ["8L1"];
		this.modData("Learnsets", "sudowoodo").learnset.poltergeist = ["8L1"];
		this.modData("Learnsets", "sudowoodo").learnset.hex = ["8L1"];
		this.modData("Learnsets", "sudowoodo").learnset.shadowball = ["8L1"];
		// Runerigus
		this.modData("Learnsets", "runerigus").learnset.rarerune = ["8L1"];
		this.modData("Learnsets", "runerigus").learnset.painsplit = ["8L1"];
		// Talonflame
		this.modData("Learnsets", "talonflame").learnset.softboiled = ["8L1"];
		this.modData("Learnsets", "talonflame").learnset.partingshot = ["8L1"];
		this.modData("Learnsets", "talonflame").learnset.rapidspin = ["8L1"];
		// Incineroar
		this.modData("Learnsets", "incineroar").learnset.heelheat = ["8L1"];
		this.modData("Learnsets", "incineroar").learnset.dragonclaw = ["8L1"];
		this.modData("Learnsets", "incineroar").learnset.superfang = ["8L1"];
		// Dracovish
		this.modData("Learnsets", "dracovish").learnset.dragonclaw = ["8L1"];
		this.modData("Learnsets", "dracovish").learnset.hydropump = ["8L1"];
		this.modData("Learnsets", "dracovish").learnset.icebeam = ["8L1"];
		this.modData("Learnsets", "dracovish").learnset.lunge = ["8L1"];
		this.modData("Learnsets", "dracovish").learnset.healbell = ["8L1"];
		this.modData("Learnsets", "dracovish").learnset.taunt = ["8L1"];
		this.modData("Learnsets", "dracovish").learnset.flipturn = ["8L1"];
		delete this.modData('Learnsets', 'dracovish').learnset.fishiousrend;
		// Armaldo
		this.modData("Learnsets", "armaldo").learnset.lunge = ["8L1"];
		// Hitmonlee
		this.modData("Learnsets", "hitmonlee").learnset.shadowclaw = ["8L1"];
		// Flaaffy
		this.modData("Learnsets", "flaaffy").learnset.slackoff = ["8L1"];
		this.modData("Learnsets", "flaaffy").learnset.hypervoice = ["8L1"];
		this.modData("Learnsets", "flaaffy").learnset.dragonrush = ["8L1"];
		this.modData("Learnsets", "flaaffy").learnset.aurorabeam = ["8L1"];
		this.modData("Learnsets", "flaaffy").learnset.energyblast = ["8L1"];
		// Sunflora
		this.modData("Learnsets", "sunflora").learnset.uturn = ["8L1"];
		this.modData("Learnsets", "sunflora").learnset.aromatherapy = ["8L1"];
		// Avalugg
		this.modData("Learnsets", "avalugg").learnset.stealthrock = ["8L1"];
		// Deoxys
		this.modData("Learnsets", "deoxys").learnset.topsyturvy = ["8L1"];
		delete this.modData('Learnsets', 'deoxys').learnset.spikes;
		delete this.modData('Learnsets', 'deoxys').learnset.nastyplot;
		delete this.modData('Learnsets', 'deoxys').learnset.superpower;
		delete this.modData('Learnsets', 'deoxys').learnset.extremespeed;
		delete this.modData('Learnsets', 'deoxys').learnset.magiccoat;
		delete this.modData('Learnsets', 'deoxys').learnset.taunt;
		delete this.modData('Learnsets', 'deoxys').learnset.focusblast;
		delete this.modData('Learnsets', 'deoxys').learnset.drainpunch;
		delete this.modData('Learnsets', 'deoxys').learnset.brickbreak;
		delete this.modData('Learnsets', 'deoxys').learnset.agility;
		// Cherrim
		this.modData("Learnsets", "cherrim").learnset.firepunch = ["8L1"];
		this.modData("Learnsets", "cherrim").learnset.flareblitz = ["8L1"];
		this.modData("Learnsets", "cherrim").learnset.firelash = ["8L1"];
		this.modData("Learnsets", "cherrim").learnset.willowisp = ["8L1"];
		this.modData("Learnsets", "cherrim").learnset.fierydance = ["8L1"];
		// Ampharos
		this.modData("Learnsets", "ampharos").learnset.slackoff = ["8L1"];
		this.modData("Learnsets", "ampharos").learnset.hypervoice = ["8L1"];
		this.modData("Learnsets", "ampharos").learnset.dragonrush = ["8L1"];
		this.modData("Learnsets", "ampharos").learnset.aurorabeam = ["8L1"];
		this.modData("Learnsets", "ampharos").learnset.energyblast = ["8L1"];
		// Centiskorch
		this.modData("Learnsets", "centiskorch").learnset.scaleshot = ["8L1"];
		this.modData("Learnsets", "centiskorch").learnset.recover = ["8L1"];
		this.modData("Learnsets", "centiskorch").learnset.suckerpunch = ["8L1"];
		this.modData("Learnsets", "centiskorch").learnset.firstimpression = ["8L1"];
		this.modData("Learnsets", "centiskorch").learnset.uturn = ["8L1"];
		this.modData("Learnsets", "centiskorch").learnset.earthquake = ["8L1"];
		this.modData("Learnsets", "centiskorch").learnset.toxic = ["8L1"];
		this.modData("Learnsets", "centiskorch").learnset.rapidspin = ["8L1"];
		// Magmortar
		this.modData("Learnsets", "magmortar").learnset.recover = ["8L1"];
		this.modData("Learnsets", "magmortar").learnset.aurasphere = ["8L1"];
		this.modData("Learnsets", "magmortar").learnset.sludgebomb = ["8L1"];
		this.modData("Learnsets", "magmortar").learnset.dragonpulse = ["8L1"];
		this.modData("Learnsets", "magmortar").learnset.vacuumwave = ["8L1"];
		// Electivire
		this.modData("Learnsets", "electivire").learnset.knockoff = ["8L1"];
		this.modData("Learnsets", "electivire").learnset.suckerpunch = ["8L1"];
		this.modData("Learnsets", "electivire").learnset.swordsdance = ["8L1"];
		this.modData("Learnsets", "electivire").learnset.closecombat = ["8L1"];
		this.modData("Learnsets", "electivire").learnset.machpunch = ["8L1"];
		this.modData("Learnsets", "electivire").learnset.drainpunch = ["8L1"];
		this.modData("Learnsets", "electivire").learnset.meteormash = ["8L1"];
		// Swampert
		this.modData("Learnsets", "swampert").learnset.absorb = ["8L1"];
		this.modData("Learnsets", "swampert").learnset.afteryou = ["8L1"];
		this.modData("Learnsets", "swampert").learnset.bulletseed = ["8L1"];
		this.modData("Learnsets", "swampert").learnset.cut = ["8L1"];
		this.modData("Learnsets", "swampert").learnset.encore = ["8L1"];
		this.modData("Learnsets", "swampert").learnset.energyball = ["8L1"];
		this.modData("Learnsets", "swampert").learnset.flowershield = ["8L1"];
		this.modData("Learnsets", "swampert").learnset.gigadrain = ["8L1"];
		this.modData("Learnsets", "swampert").learnset.grassknot = ["8L1"];
		this.modData("Learnsets", "swampert").learnset.grassyterrain = ["8L1"];
		this.modData("Learnsets", "swampert").learnset.growth = ["8L1"];
		this.modData("Learnsets", "swampert").learnset.helpinghand = ["8L1"];
		this.modData("Learnsets", "swampert").learnset.ingrain = ["8L1"];
		this.modData("Learnsets", "swampert").learnset.leafstorm = ["8L1"];
		this.modData("Learnsets", "swampert").learnset.leechseed = ["8L1"];
		this.modData("Learnsets", "swampert").learnset.lightscreen = ["8L1"];
		this.modData("Learnsets", "swampert").learnset.megadrain = ["8L1"];
		this.modData("Learnsets", "swampert").learnset.morningsun = ["8L1"];
		this.modData("Learnsets", "swampert").learnset.naturepower = ["8L1"];
		this.modData("Learnsets", "swampert").learnset.petalblizzard = ["8L1"];
		this.modData("Learnsets", "swampert").learnset.petaldance = ["8L1"];
		this.modData("Learnsets", "swampert").learnset.pound = ["8L1"];
		this.modData("Learnsets", "swampert").learnset.razorleaf = ["8L1"];
		this.modData("Learnsets", "swampert").learnset.safeguard = ["8L1"];
		this.modData("Learnsets", "swampert").learnset.seedbomb = ["8L1"];
		this.modData("Learnsets", "swampert").learnset.sludgebomb = ["8L1"];
		this.modData("Learnsets", "swampert").learnset.solarbeam = ["8L1"];
		this.modData("Learnsets", "swampert").learnset.sunnyday = ["8L1"];
		this.modData("Learnsets", "swampert").learnset.sweetscent = ["8L1"];
		this.modData("Learnsets", "swampert").learnset.swordsdance = ["8L1"];
		this.modData("Learnsets", "swampert").learnset.synthesis = ["8L1"];
		this.modData("Learnsets", "swampert").learnset.worryseed = ["8L1"];
		// Copperajah
		this.modData("Learnsets", "copperajah").learnset.aerialace = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.agility = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.aircutter = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.airslash = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.aquajet = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.batonpass = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.blizzard = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.bubblebeam = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.bugbite = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.bugbuzz = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.confide = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.defog = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.doubleteam = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.energyball = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.fellstinger = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.gigadrain = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.gust = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.haze = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.hydropump = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.icebeam = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.icywind = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.infestation = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.liquidation = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.lunge = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.mimic = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.mindreader = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.mist = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.mudslap = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.powersplit = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.psybeam = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.psychup = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.quickattack = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.quiverdance = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.raindance = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.roost = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.scald = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.shadowball = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.solarbeam = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.stickyweb = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.stringshot = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.strugglebug = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.stunspore = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.sunnyday = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.sweetscent = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.swift = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.tailwind = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.thief = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.toxic = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.twister = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.uturn = ["8L1"];
		this.modData("Learnsets", "copperajah").learnset.waterpulse = ["8L1"];
		// Pyroar
		this.modData("Learnsets", "pyroar").learnset.nastyplot = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.aerialace = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.allyswitch = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.assurance = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.blazekick = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.blizzard = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.bugbite = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.bugbuzz = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.chargebeam = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.electroweb = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.endure = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.energyball = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.explosion = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.extremespeed = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.fellstinger = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.flashcannon = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.fly = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.furycutter = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.gigadrain = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.gravity = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.gunkshot = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.honeclaws = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.icebeam = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.infestation = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.irondefense = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.ironhead = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.lastresort = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.leechlife = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.lightscreen = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.lockon = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.magiccoat = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.magnetrise = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.metalclaw = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.metalsound = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.psychic = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.quickattack = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.recycle = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.reflect = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.rockpolish = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.screech = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.selfdestruct = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.shadowclaw = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.shiftgear = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.shockwave = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.simplebeam = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.slash = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.steelbeam = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.strugglebug = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.swift = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.technoblast = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.thunder = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.thunderwave = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.thunderbolt = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.triattack = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.uturn = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.xscissor = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.zapcannon = ["8L1"];
		this.modData("Learnsets", "pyroar").learnset.zenheadbutt = ["8L1"];
		// Pinsir
		this.modData("Learnsets", "pinsir").learnset.acrobatics = ["8L1"];
		this.modData("Learnsets", "pinsir").learnset.aerialace = ["8L1"];
		this.modData("Learnsets", "pinsir").learnset.agility = ["8L1"];
		this.modData("Learnsets", "pinsir").learnset.aquatail = ["8L1"];
		this.modData("Learnsets", "pinsir").learnset.batonpass = ["8L1"];
		this.modData("Learnsets", "pinsir").learnset.counter = ["8L1"];
		this.modData("Learnsets", "pinsir").learnset.crosspoison = ["8L1"];
		this.modData("Learnsets", "pinsir").learnset.darkpulse = ["8L1"];
		this.modData("Learnsets", "pinsir").learnset.defog = ["8L1"];
		this.modData("Learnsets", "pinsir").learnset.detect = ["8L1"];
		this.modData("Learnsets", "pinsir").learnset.dreameater = ["8L1"];
		this.modData("Learnsets", "pinsir").learnset.earthpower = ["8L1"];
		this.modData("Learnsets", "pinsir").learnset.firefang = ["8L1"];
		this.modData("Learnsets", "pinsir").learnset.honeclaws = ["8L1"];
		this.modData("Learnsets", "pinsir").learnset.icefang = ["8L1"];
		this.modData("Learnsets", "pinsir").learnset.irontail = ["8L1"];
		this.modData("Learnsets", "pinsir").learnset.metalclaw = ["8L1"];
		this.modData("Learnsets", "pinsir").learnset.mudslap = ["8L1"];
		this.modData("Learnsets", "pinsir").learnset.nightslash = ["8L1"];
		this.modData("Learnsets", "pinsir").learnset.payback = ["8L1"];
		this.modData("Learnsets", "pinsir").learnset.poisonjab = ["8L1"];
		this.modData("Learnsets", "pinsir").learnset.poisonsting = ["8L1"];
		this.modData("Learnsets", "pinsir").learnset.poisontail = ["8L1"];
		this.modData("Learnsets", "pinsir").learnset.powertrick = ["8L1"];
		this.modData("Learnsets", "pinsir").learnset.rockpolish = ["8L1"];
		this.modData("Learnsets", "pinsir").learnset.roost = ["8L1"];
		this.modData("Learnsets", "pinsir").learnset.sandattack = ["8L1"];
		this.modData("Learnsets", "pinsir").learnset.sandtomb = ["8L1"];
		this.modData("Learnsets", "pinsir").learnset.sandstorm = ["8L1"];
		this.modData("Learnsets", "pinsir").learnset.screech = ["8L1"];
		this.modData("Learnsets", "pinsir").learnset.skyattack = ["8L1"];
		this.modData("Learnsets", "pinsir").learnset.sludgebomb = ["8L1"];
		this.modData("Learnsets", "pinsir").learnset.steelwing = ["8L1"];
		this.modData("Learnsets", "pinsir").learnset.swift = ["8L1"];
		this.modData("Learnsets", "pinsir").learnset.tailwind = ["8L1"];
		this.modData("Learnsets", "pinsir").learnset.taunt = ["8L1"];
		this.modData("Learnsets", "pinsir").learnset.thunderfang = ["8L1"];
		this.modData("Learnsets", "pinsir").learnset.torment = ["8L1"];
		this.modData("Learnsets", "pinsir").learnset.uturn = ["8L1"];
		this.modData("Learnsets", "pinsir").learnset.venoshock = ["8L1"];
		this.modData("Learnsets", "pinsir").learnset.wingattack = ["8L1"];
		// Toucannon
		this.modData("Learnsets", "toucannon").learnset.allyswitch = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.bodyslam = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.calmmind = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.chargebeam = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.confusion = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.counter = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.curse = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.dazzlinggleam = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.dig = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.disable = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.doubleedge = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.drainpunch = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.dreameater = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.dynamicpunch = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.encore = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.endure = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.energyball = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.expandingforce = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.facade = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.firepunch = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.fling = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.focusblast = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.focuspunch = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.foulplay = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.futuresight = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.gigaimpact = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.grassknot = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.gravity = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.guardsplit = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.guardswap = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.headbutt = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.hyperbeam = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.icepunch = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.imprison = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.irontail = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.kinesis = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.laserfocus = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.lightscreen = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.magiccoat = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.magicroom = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.megakick = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.megapunch = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.metronome = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.mimic = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.nastyplot = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.nightshade = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.powerswap = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.powertrick = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.psybeam = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.psychup = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.psychic = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.psychicterrain = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.psychocut = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.psychoshift = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.psyshock = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.raindance = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.recover = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.recycle = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.reflect = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.roleplay = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.safeguard = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.seismictoss = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.shadowball = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.shockwave = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.skillswap = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.skullbash = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.speedswap = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.storedpower = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.submission = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.swift = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.takedown = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.taunt = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.teleport = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.thunderpunch = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.thunderwave = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.torment = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.triattack = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.trick = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.trickroom = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.wonderroom = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.zapcannon = ["8L1"];
		this.modData("Learnsets", "toucannon").learnset.zenheadbutt = ["8L1"];
		// Tapu Koko
		this.modData("Learnsets", "tapukoko").learnset.amnesia = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.ancientpower = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.attract = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.avalanche = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.bite = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.blizzard = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.bodyslam = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.bulldoze = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.charm = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.curse = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.defensecurl = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.detect = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.dig = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.doubleedge = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.earthpower = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.earthquake = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.endeavor = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.fissure = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.flail = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.freezedry = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.furyattack = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.hail = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.headbutt = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.highhorsepower = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.hornattack = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.icebeam = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.icefang = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.iceshard = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.iciclecrash = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.iciclespear = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.icywind = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.mimic = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.mist = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.mudshot = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.mudslap = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.peck = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.powdersnow = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.rockslide = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.rocksmash = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.rocktomb = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.sandtomb = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.sandstorm = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.scaryface = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.stealthrock = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.stompingtantrum = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.stoneedge = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.strength = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.superpower = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.tackle = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.takedown = ["8L1"];
		this.modData("Learnsets", "tapukoko").learnset.thrash = ["8L1"];
		// Rotom-Heat
		this.modData("Learnsets", "rotomheat").learnset.afteryou = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.allyswitch = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.amnesia = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.aromatherapy = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.attract = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.batonpass = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.bellydrum = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.blizzard = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.bodyslam = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.bounce = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.brickbreak = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.bubblebeam = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.calmmind = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.chargebeam = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.charm = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.confide = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.copycat = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.cosmicpower = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.counter = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.covet = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.curse = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.dazzlinggleam = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.defensecurl = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.detect = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.dig = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.disarmingvoice = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.doubleteam = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.doubleedge = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.drainpunch = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.drainingkiss = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.dreameater = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.dualwingbeat = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.dynamicpunch = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.echoedvoice = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.encore = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.endeavor = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.endure = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.facade = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.faketears = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.fireblast = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.firepunch = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.flamethrower = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.fling = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.focusblast = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.focuspunch = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.followme = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.gigaimpact = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.grassknot = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.gravity = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.growl = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.headbutt = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.healbell = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.healpulse = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.healingwish = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.helpinghand = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.hyperbeam = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.hypervoice = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.icebeam = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.icepunch = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.icywind = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.imprison = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.incinerate = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.irontail = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.knockoff = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.laserfocus = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.lastresort = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.lifedew = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.lightscreen = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.magiccoat = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.magicalleaf = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.megakick = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.megapunch = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.meteorbeam = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.meteormash = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.metronome = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.mimic = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.minimize = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.mistyexplosion = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.mistyterrain = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.moonblast = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.moonlight = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.mudslap = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.mysticalfire = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.playrough = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.pound = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.poweruppunch = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.present = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.protect = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.psychup = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.psychic = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.psyshock = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.raindance = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.recycle = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.reflect = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.rest = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.retaliate = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.rocksmash = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.roleplay = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.rollout = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.round = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.safeguard = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.seismictoss = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.shadowball = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.shockwave = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.sing = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.skullbash = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.sleeptalk = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.snore = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.softboiled = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.solarbeam = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.splash = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.stealthrock = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.storedpower = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.strength = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.submission = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.substitute = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.sunnyday = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.swagger = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.sweetkiss = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.takedown = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.teleport = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.thunder = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.thunderpunch = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.thunderwave = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.thunderbolt = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.tickle = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.toxic = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.triattack = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.trick = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.uproar = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.watergun = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.waterpulse = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.wish = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.wonderroom = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.workup = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.zapcannon = ["8L1"];
		this.modData("Learnsets", "rotomheat").learnset.zenheadbutt = ["8L1"];
		// Fearow
		this.modData("Learnsets", "fearow").learnset.bravebird = ["8L1"];
		this.modData("Learnsets", "fearow").learnset.cottonguard = ["8L1"];
		this.modData("Learnsets", "fearow").learnset.darkpulse = ["8L1"];
		this.modData("Learnsets", "fearow").learnset.dualwingbeat = ["8L1"];
		this.modData("Learnsets", "fearow").learnset.hex = ["8L1"];
		this.modData("Learnsets", "fearow").learnset.honeclaws = ["8L1"];
		this.modData("Learnsets", "fearow").learnset.magiccoat = ["8L1"];
		this.modData("Learnsets", "fearow").learnset.playrough = ["8L1"];
		this.modData("Learnsets", "fearow").learnset.poltergeist = ["8L1"];
		this.modData("Learnsets", "fearow").learnset.shadowball = ["8L1"];
		this.modData("Learnsets", "fearow").learnset.shadowsneak = ["8L1"];
		this.modData("Learnsets", "fearow").learnset.willowisp = ["8L1"];
		this.modData("Learnsets", "fearow").learnset.uturn = ["8L1"];
		this.modData("Learnsets", "fearow").learnset.charm = ["8L1"];
		this.modData("Learnsets", "fearow").learnset.faketears = ["8L1"];
		this.modData("Learnsets", "fearow").learnset.tearfullook = ["8L1"];
		this.modData("Learnsets", "fearow").learnset.spite = ["8L1"];
		// Mightyena
		this.modData("Learnsets", "mightyena").learnset.berrybomb = ["8L1"];
		this.modData("Learnsets", "mightyena").learnset.berryblast = ["8L1"];
		this.modData("Learnsets", "mightyena").learnset.thunderwave = ["8L1"];
		this.modData("Learnsets", "mightyena").learnset.stunspore = ["8L1"];
		this.modData("Learnsets", "mightyena").learnset.energyball = ["8L1"];
		this.modData("Learnsets", "mightyena").learnset.gigadrain = ["8L1"];
		this.modData("Learnsets", "mightyena").learnset.grassknot = ["8L1"];
		this.modData("Learnsets", "mightyena").learnset.knockoff = ["8L1"];
		this.modData("Learnsets", "mightyena").learnset.leechseed = ["8L1"];
		this.modData("Learnsets", "mightyena").learnset.nastyplot = ["8L1"];
		this.modData("Learnsets", "mightyena").learnset.psychicfangs = ["8L1"];
		this.modData("Learnsets", "mightyena").learnset.seedbomb = ["8L1"];
		this.modData("Learnsets", "mightyena").learnset.shadowclaw = ["8L1"];
		this.modData("Learnsets", "mightyena").learnset.sludgebomb = ["8L1"];
		this.modData("Learnsets", "mightyena").learnset.swordsdance = ["8L1"];
		this.modData("Learnsets", "mightyena").learnset.weatherball = ["8L1"];
		this.modData("Learnsets", "mightyena").learnset.woodhammer = ["8L1"];
		this.modData("Learnsets", "mightyena").learnset.acidspray = ["8L1"];
		this.modData("Learnsets", "mightyena").learnset.shockwave = ["8L1"];
		this.modData("Learnsets", "mightyena").learnset.solarbeam = ["8L1"];
		// Manectric
		this.modData("Learnsets", "manectric").learnset.aerialace = ["8L1"];
		this.modData("Learnsets", "manectric").learnset.assurance = ["8L1"];
		this.modData("Learnsets", "manectric").learnset.flashcannon = ["8L1"];
		this.modData("Learnsets", "manectric").learnset.icefang = ["8L1"];
		this.modData("Learnsets", "manectric").learnset.irondefense = ["8L1"];
		this.modData("Learnsets", "manectric").learnset.ironhead = ["8L1"];
		this.modData("Learnsets", "manectric").learnset.knockoff = ["8L1"];
		this.modData("Learnsets", "manectric").learnset.psychicfangs = ["8L1"];
		this.modData("Learnsets", "manectric").learnset.rocktomb = ["8L1"];
		this.modData("Learnsets", "manectric").learnset.shadowclaw = ["8L1"];
		this.modData("Learnsets", "manectric").learnset.steelbeam = ["8L1"];
		this.modData("Learnsets", "manectric").learnset.suckerpunch = ["8L1"];
		this.modData("Learnsets", "manectric").learnset.superfang = ["8L1"];
		this.modData("Learnsets", "manectric").learnset.superpower = ["8L1"];
		this.modData("Learnsets", "manectric").learnset.swordsdance = ["8L1"];
		this.modData("Learnsets", "manectric").learnset.bite = ["8L1"];
		this.modData("Learnsets", "manectric").learnset.bulldoze = ["8L1"];
		this.modData("Learnsets", "manectric").learnset.doublekick = ["8L1"];
		this.modData("Learnsets", "manectric").learnset.eerieimpulse = ["8L1"];
		this.modData("Learnsets", "manectric").learnset.metalclaw = ["8L1"];
		this.modData("Learnsets", "manectric").learnset.magnetbomb = ["8L1"];
		this.modData("Learnsets", "manectric").learnset.metalburst = ["8L1"];
		this.modData("Learnsets", "manectric").learnset.metalsound = ["8L1"];
		this.modData("Learnsets", "manectric").learnset.sandtomb = ["8L1"];
		this.modData("Learnsets", "manectric").learnset.thief = ["8L1"];
		// Slaking
		this.modData("Learnsets", "slaking").learnset.shootingstar = ["8L1"];
		this.modData("Learnsets", "slaking").learnset.calmmind = ["8L1"];
		this.modData("Learnsets", "slaking").learnset.darkpulse = ["8L1"];
		this.modData("Learnsets", "slaking").learnset.disable = ["8L1"];
		this.modData("Learnsets", "slaking").learnset.extrasensory = ["8L1"];
		this.modData("Learnsets", "slaking").learnset.grassknot = ["8L1"];
		this.modData("Learnsets", "slaking").learnset.knockoff = ["8L1"];
		this.modData("Learnsets", "slaking").learnset.lightscreen = ["8L1"];
		this.modData("Learnsets", "slaking").learnset.magiccoat = ["8L1"];
		this.modData("Learnsets", "slaking").learnset.psychic = ["8L1"];
		this.modData("Learnsets", "slaking").learnset.psyshock = ["8L1"];
		this.modData("Learnsets", "slaking").learnset.shadowball = ["8L1"];
		this.modData("Learnsets", "slaking").learnset.shadowclaw = ["8L1"];
		this.modData("Learnsets", "slaking").learnset.trick = ["8L1"];
		this.modData("Learnsets", "slaking").learnset.trickroom = ["8L1"];
		this.modData("Learnsets", "slaking").learnset.yawn = ["8L1"];
		this.modData("Learnsets", "slaking").learnset.zenheadbutt = ["8L1"];
		this.modData("Learnsets", "slaking").learnset.chargebeam = ["8L1"];
		this.modData("Learnsets", "slaking").learnset.confusion = ["8L1"];
		this.modData("Learnsets", "slaking").learnset.futuresight = ["8L1"];
		this.modData("Learnsets", "slaking").learnset.gravity = ["8L1"];
		this.modData("Learnsets", "slaking").learnset.hypnosis = ["8L1"];
		this.modData("Learnsets", "slaking").learnset.imprison = ["8L1"];
		this.modData("Learnsets", "slaking").learnset.smackdown = ["8L1"];
		this.modData("Learnsets", "slaking").learnset.shockwave = ["8L1"];
		// Dragapult
		this.modData("Learnsets", "dragapult").learnset.calmmind = ["8L1"];
		this.modData("Learnsets", "dragapult").learnset.dragonclaw = ["8L1"];
		this.modData("Learnsets", "dragapult").learnset.knockoff = ["8L1"];
		this.modData("Learnsets", "dragapult").learnset.mysticalfire = ["8L1"];
		this.modData("Learnsets", "dragapult").learnset.poltergeist = ["8L1"];
		this.modData("Learnsets", "dragapult").learnset.psychic = ["8L1"];
		this.modData("Learnsets", "dragapult").learnset.shadowclaw = ["8L1"];
		this.modData("Learnsets", "dragapult").learnset.shadowsneak = ["8L1"];
		this.modData("Learnsets", "dragapult").learnset.taunt = ["8L1"];
		this.modData("Learnsets", "dragapult").learnset.scaleshot = ["8L1"];
		// Krookodile
		this.modData("Learnsets", "krookodile").learnset.agility = ["8L1"];
		this.modData("Learnsets", "krookodile").learnset.calmmind = ["8L1"];
		this.modData("Learnsets", "krookodile").learnset.extrasensory = ["8L1"];
		this.modData("Learnsets", "krookodile").learnset.fireblast = ["8L1"];
		this.modData("Learnsets", "krookodile").learnset.flamecharge = ["8L1"];
		this.modData("Learnsets", "krookodile").learnset.flamethrower = ["8L1"];
		this.modData("Learnsets", "krookodile").learnset.flareblitz = ["8L1"];
		this.modData("Learnsets", "krookodile").learnset.headsmash = ["8L1"];
		this.modData("Learnsets", "krookodile").learnset.heatwave = ["8L1"];
		this.modData("Learnsets", "krookodile").learnset.lightscreen = ["8L1"];
		this.modData("Learnsets", "krookodile").learnset.magiccoat = ["8L1"];
		this.modData("Learnsets", "krookodile").learnset.overheat = ["8L1"];
		this.modData("Learnsets", "krookodile").learnset.powergem = ["8L1"];
		this.modData("Learnsets", "krookodile").learnset.pressurecook = ["8L1"];
		this.modData("Learnsets", "krookodile").learnset.psychic = ["8L1"];
		this.modData("Learnsets", "krookodile").learnset.psychicfangs = ["8L1"];
		this.modData("Learnsets", "krookodile").learnset.reflect = ["8L1"];
		this.modData("Learnsets", "krookodile").learnset.shadowball = ["8L1"];
		this.modData("Learnsets", "krookodile").learnset.shadowclaw = ["8L1"];
		this.modData("Learnsets", "krookodile").learnset.wildcharge = ["8L1"];
		this.modData("Learnsets", "krookodile").learnset.willowisp = ["8L1"];
		this.modData("Learnsets", "krookodile").learnset.trick = ["8L1"];
		this.modData("Learnsets", "krookodile").learnset.zenheadbutt = ["8L1"];
		this.modData("Learnsets", "krookodile").learnset.mysticalfire = ["8L1"];
		this.modData("Learnsets", "krookodile").learnset.solarbeam = ["8L1"];
		this.modData("Learnsets", "krookodile").learnset.sunnyday = ["8L1"];
		this.modData("Learnsets", "krookodile").learnset.trickroom = ["8L1"];
		this.modData("Learnsets", "krookodile").learnset.meteorbeam = ["8L1"];
		// Carracosta
		this.modData("Learnsets", "carracosta").learnset.poisondart = ["8L1"];
		this.modData("Learnsets", "carracosta").learnset.bodypress = ["8L1"];
		this.modData("Learnsets", "carracosta").learnset.crosschop = ["8L1"];
		this.modData("Learnsets", "carracosta").learnset.doubleedge = ["8L1"];
		this.modData("Learnsets", "carracosta").learnset.focusblast = ["8L1"];
		this.modData("Learnsets", "carracosta").learnset.gunkshot = ["8L1"];
		this.modData("Learnsets", "carracosta").learnset.poisonjab = ["8L1"];
		this.modData("Learnsets", "carracosta").learnset.sludgebomb = ["8L1"];
		this.modData("Learnsets", "carracosta").learnset.sludgewave = ["8L1"];
		this.modData("Learnsets", "carracosta").learnset.toxicspikes = ["8L1"];
		this.modData("Learnsets", "carracosta").learnset.skittersmack = ["8L1"];
		this.modData("Learnsets", "carracosta").learnset.revenge = ["8L1"];
		this.modData("Learnsets", "carracosta").learnset.venoshock = ["8L1"];
		// Goodra
		this.modData("Learnsets", "goodra").learnset.coil = ["8L1"];
		this.modData("Learnsets", "goodra").learnset.crunch = ["8L1"];
		this.modData("Learnsets", "goodra").learnset.discharge = ["8L1"];
		this.modData("Learnsets", "goodra").learnset.doubleedge = ["8L1"];
		this.modData("Learnsets", "goodra").learnset.earthpower = ["8L1"];
		this.modData("Learnsets", "goodra").learnset.flashcannon = ["8L1"];
		this.modData("Learnsets", "goodra").learnset.heavyslam = ["8L1"];
		this.modData("Learnsets", "goodra").learnset.hypervoice = ["8L1"];
		this.modData("Learnsets", "goodra").learnset.ironhead = ["8L1"];
		this.modData("Learnsets", "goodra").learnset.knockoff = ["8L1"];
		this.modData("Learnsets", "goodra").learnset.lightscreen = ["8L1"];
		this.modData("Learnsets", "goodra").learnset.lunge = ["8L1"];
		this.modData("Learnsets", "goodra").learnset.nuzzle = ["8L1"];
		this.modData("Learnsets", "goodra").learnset.roar = ["8L1"];
		this.modData("Learnsets", "goodra").learnset.spikes = ["8L1"];
		this.modData("Learnsets", "goodra").learnset.suckerpunch = ["8L1"];
		this.modData("Learnsets", "goodra").learnset.tailslap = ["8L1"];
		this.modData("Learnsets", "goodra").learnset.voltswitch = ["8L1"];
		this.modData("Learnsets", "goodra").learnset.wildcharge = ["8L1"];
		this.modData("Learnsets", "goodra").learnset.assurance = ["8L1"];
		this.modData("Learnsets", "goodra").learnset.chargebeam = ["8L1"];
		this.modData("Learnsets", "goodra").learnset.risingvoltage = ["8L1"];
		this.modData("Learnsets", "goodra").learnset.zapcannon = ["8L1"];
		// Delcatty
		this.modData("Learnsets", "delcatty").learnset.bananasplit = ["8L1"];
		this.modData("Learnsets", "delcatty").learnset.hail = ["8L1"];
		this.modData("Learnsets", "delcatty").learnset.auroraveil = ["8L1"];
		this.modData("Learnsets", "delcatty").learnset.powdersnow = ["8L1"];
		this.modData("Learnsets", "delcatty").learnset.freezedry = ["8L1"];
		this.modData("Learnsets", "delcatty").learnset.iceshard = ["8L1"];
		this.modData("Learnsets", "delcatty").learnset.mist = ["8L1"];
		this.modData("Learnsets", "delcatty").learnset.haze = ["8L1"];
		this.modData("Learnsets", "delcatty").learnset.moonblast = ["8L1"];
		this.modData("Learnsets", "delcatty").learnset.psychic = ["8L1"];
		this.modData("Learnsets", "delcatty").learnset.uturn = ["8L1"];
		this.modData("Learnsets", "delcatty").learnset.quickattack = ["8L1"];
		this.modData("Learnsets", "delcatty").learnset.skittersmack = ["8L1"];
		this.modData("Learnsets", "delcatty").learnset.surf = ["8L1"];
		this.modData("Learnsets", "delcatty").learnset.sheercold = ["8L1"];
		this.modData("Learnsets", "delcatty").learnset.superfang = ["8L1"];
		this.modData("Learnsets", "delcatty").learnset.bodyslam = ["8L1"];
		this.modData("Learnsets", "delcatty").learnset.energyball = ["8L1"];
		this.modData("Learnsets", "delcatty").learnset.seedbomb = ["8L1"];
		// Tropius
		this.modData("Learnsets", "tropius").learnset.dracometeor = ["8L1"];
		this.modData("Learnsets", "tropius").learnset.calmmind = ["8L1"];
		this.modData("Learnsets", "tropius").learnset.earthpower = ["8L1"];
		this.modData("Learnsets", "tropius").learnset.scaleshot = ["8L1"];
		this.modData("Learnsets", "tropius").learnset.ironhead = ["8L1"];
		this.modData("Learnsets", "tropius").learnset.bananasplit = ["8L1"];
		this.modData("Learnsets", "tropius").learnset.breakingswipe = ["8L1"];
		this.modData("Learnsets", "tropius").learnset.dualwingbeat = ["8L1"];
		this.modData("Learnsets", "tropius").learnset.grassyglide = ["8L1"];
		this.modData("Learnsets", "tropius").learnset.hurricane = ["8L1"];
		this.modData("Learnsets", "tropius").learnset.weatherball = ["8L1"];
		this.modData("Learnsets", "tropius").learnset.woodhammer = ["8L1"];
		// Skitty
		this.modData("Learnsets", "skitty").learnset.skittersmack = ["8L1"];
		this.modData("Learnsets", "skitty").learnset.berrybomb = ["8L1"];
		this.modData("Learnsets", "skitty").learnset.moonlight = ["8L1"];


},

	teambuilderConfig: {
        // for micrometas to only show custom tiers
        excludeStandardTiers: true,
		  customTiers: ["GH"],
	},
};
