export const Pokedex: {[speciesid: string]: ModdedSpeciesData} = {
	venusaur: {
		inherit: true,
		otherFormes: ["Venusaur-Mega", "Venusaur-Mega-Y"],
		formeOrder: ["Venusaur", "Venusaur-Mega", "Venusaur-Mega-Y"],
	},
	venusaurmegay: {
		num: 3,
		name: "Venusaur-Mega-Y",
		baseSpecies: "Venusaur",
		forme: "Mega",
		types: ["Grass", "Fairy"],
		genderRatio: {M: 0.875, F: 0.125},
		baseStats: {hp: 80, atk: 142, def: 83, spa: 122, spd: 120, spe: 78},
		abilities: {0: "Flower Veil"},
		heightm: 2.4,
		weightkg: 155.5,
		color: "Green",
		eggGroups: ["Monster", "Grass"],
		requiredItem: "Venusaurite Y",
	},
 	abomasnow: {
		inherit: true,
		otherFormes: ["Abomasnow-Mega", "Abomasnow-Mega-X"],
		formeOrder: ["Abomasnow", "Abomasnow-Mega", "Abomasnow-Mega-X"],
	},
	abomasnowmega: {
		num: 460,
		name: "Abomasnow-Mega",
		baseSpecies: "Abomasnow",
		forme: "Mega",
		types: ["Grass", "Ice"],
		baseStats: {hp: 90, atk: 92, def: 105, spa: 132, spd: 105, spe: 70},
		abilities: {0: "Slush Rush"},
		heightm: 2.7,
		weightkg: 185,
		color: "White",
		eggGroups: ["Monster", "Grass"],
		requiredItem: "Abomasite",
	},
	abomasnowmegax: {
		num: 460,
		name: "Abomasnow-Mega-X",
		baseSpecies: "Abomasnow",
		forme: "Mega",
		types: ["Grass", "Water"],
		baseStats: {hp: 90, atk: 112, def: 95, spa: 102, spd: 135, spe: 60},
		abilities: {0: "Regenerator"},
		heightm: 2.7,
		weightkg: 185,
		color: "White",
		eggGroups: ["Monster", "Grass"],
		requiredItem: "Abomasite X",
	},
 	absol: {
		inherit: true,
		otherFormes: ["Absol-Mega", "Absol-Mega-Y"],
		formeOrder: ["Absol", "Absol-Mega", "Absol-Mega-Y"],
	},
	absolmega: {
		num: 359,
		name: "Absol-Mega",
		baseSpecies: "Absol",
		forme: "Mega",
		types: ["Dark", "Fairy"],
		baseStats: {hp: 65, atk: 160, def: 90, spa: 75, spd: 60, spe: 115},
		abilities: {0: "Magic Bounce"},
		heightm: 1.2,
		weightkg: 49,
		color: "White",
		eggGroups: ["Field"],
		requiredItem: "Absolite",
	},
	absolmegay: {
		num: 359,
		name: "Absol-Mega-Y",
		baseSpecies: "Absol",
		forme: "Mega",
		types: ["Dark", "Electric"],
		baseStats: {hp: 65, atk: 110, def: 60, spa: 115, spd: 100, spe: 115},
		abilities: {0: "Galvanize"},
		heightm: 1.2,
		weightkg: 49,
		color: "White",
		eggGroups: ["Field"],
		requiredItem: "Absolite Y",
	},
 	aerodactyl: {
		inherit: true,
		otherFormes: ["Aerodactyl-Mega", "Aerodactyl-Mega-Y"],
		formeOrder: ["Aerodactyl", "Aerodactyl-Mega", "Aerodactyl-Mega-Y"],
	},
	aerodactylmegay: {
		num: 142,
		name: "Aerodactyl-Mega-Y",
		baseSpecies: "Aerodactyl",
		forme: "Mega",
		types: ["Rock", "Flying"],
		genderRatio: {M: 0.875, F: 0.125},
		baseStats: {hp: 80, atk: 105, def: 75, spa: 130, spd: 85, spe: 140},
		abilities: {0: "Savagery"},
		heightm: 2.1,
		weightkg: 79,
		color: "Purple",
		eggGroups: ["Flying"],
		requiredItem: "Aerodactylite Y",
	},
 	aggron: {
		inherit: true,
		otherFormes: ["Aggron-Mega", "Aggron-Mega-Y"],
		formeOrder: ["Aggron", "Aggron-Mega", "Aggron-Mega-Y"],
	},
	aggronmegay: {
		num: 306,
		name: "Aggron-Mega-Y",
		baseSpecies: "Aggron",
		forme: "Mega",
		types: ["Steel", "Ghost"],
		baseStats: {hp: 70, atk: 90, def: 125, spa: 145, spd: 150, spe: 50},
		abilities: {0: "Unaware"},
		heightm: 2.2,
		weightkg: 395,
		color: "Gray",
		eggGroups: ["Monster"],
		requiredItem: "Aggronite Y",
	},
 	alakazam: {
		inherit: true,
		otherFormes: ["Alakazam-Mega", "Alakazam-Mega-X"],
		formeOrder: ["Alakazam", "Alakazam-Mega", "Alakazam-Mega-X"],
	},
	alakazammegax: {
		num: 65,
		name: "Alakazam-Mega-X",
		baseSpecies: "Alakazam",
		forme: "Mega",
		types: ["Psychic"],
		genderRatio: {M: 0.75, F: 0.25},
		baseStats: {hp: 55, atk: 135, def: 50, spa: 135, spd: 90, spe: 135},
		abilities: {0: "Sheer Force"},
		heightm: 1.2,
		weightkg: 48,
		color: "Brown",
		eggGroups: ["Human-Like"],
		requiredItem: "Alakazite X",
	},
 	altaria: {
		inherit: true,
		otherFormes: ["Altaria-Mega", "Altaria-Mega-Y"],
		formeOrder: ["Altaria", "Altaria-Mega", "Altaria-Mega-Y"],
	},
	altariamegay: {
		num: 334,
		name: "Altaria-Mega-Y",
		baseSpecies: "Altaria",
		forme: "Mega",
		types: ["Dragon", "Flying"],
		baseStats: {hp: 75, atk: 70, def: 100, spa: 125, spd: 105, spe: 115},
		abilities: {0: "Berserk"},
		heightm: 1.5,
		weightkg: 20.6,
		color: "Blue",
		eggGroups: ["Flying", "Dragon"],
		requiredItem: "Altarianite Y",
	},
 	ampharos: {
		inherit: true,
		otherFormes: ["Ampharos-Mega", "Ampharos-Mega-X"],
		formeOrder: ["Ampharos", "Ampharos-Mega", "Ampharos-Mega-X"],
	},
	ampharosmega: {
		num: 181,
		name: "Ampharos-Mega",
		baseSpecies: "Ampharos",
		forme: "Mega",
		types: ["Electric", "Dragon"],
		baseStats: {hp: 90, atk: 75, def: 115, spa: 165, spd: 120, spe: 45},
		abilities: {0: "Regenerator"},
		heightm: 1.4,
		weightkg: 61.5,
		color: "Yellow",
		eggGroups: ["Monster", "Field"],
		requiredItem: "Ampharosite",
	},
	ampharosmegax: {
		num: 181,
		name: "Ampharos-Mega-X",
		baseSpecies: "Ampharos",
		forme: "Mega",
		types: ["Electric", "Ice"],
		baseStats: {hp: 90, atk: 125, def: 120, spa: 140, spd: 100, spe: 35},
		abilities: {0: "Refrigerate"},
		heightm: 1.4,
		weightkg: 61.5,
		color: "Yellow",
		eggGroups: ["Monster", "Field"],
		requiredItem: "Ampharosite X",
	},
 	glalie: {
		inherit: true,
		otherFormes: ["Glalie-Mega", "Glalie-Mega-X"],
		formeOrder: ["Glalie", "Glalie-Mega", "Glalie-Mega-X"],
	},
	glaliemegax: {
		num: 362,
		name: "Glalie-Mega-X",
		baseSpecies: "Glalie",
		forme: "Mega",
		types: ["Ice", "Dark"],
		baseStats: {hp: 80, atk: 80, def: 70, spa: 130, spd: 100, spe: 120},
		abilities: {0: "Snow Warning"},
		heightm: 2.1,
		weightkg: 350.2,
		color: "Gray",
		eggGroups: ["Fairy", "Mineral"],
		requiredItem: "Glalitite X",
	},
	glaliemega: {
		num: 362,
		name: "Glalie-Mega",
		baseSpecies: "Glalie",
		forme: "Mega",
		types: ["Ice", "Fighting"],
		baseStats: {hp: 80, atk: 130, def: 80, spa: 100, spd: 80, spe: 110},
		abilities: {0: "Refrigerate"},
		heightm: 2.1,
		weightkg: 350.2,
		color: "Gray",
		eggGroups: ["Fairy", "Mineral"],
		requiredItem: "Glalitite",
	},
 	audino: {
		inherit: true,
		otherFormes: ["Audino-Mega", "Audino-Mega-Y"],
		formeOrder: ["Audino", "Audino-Mega", "Audino-Mega-Y"],
	},
	audinomega: {
		num: 531,
		name: "Audino-Mega",
		baseSpecies: "Audino",
		forme: "Mega",
		types: ["Normal", "Fairy"],
		baseStats: {hp: 103, atk: 60, def: 126, spa: 80, spd: 126, spe: 50},
		abilities: {0: "Triage"},
		heightm: 1.5,
		weightkg: 32,
		color: "White",
		eggGroups: ["Fairy"],
		requiredItem: "Audinite",
	},
	audinomegay: {
		num: 531,
		name: "Audino-Mega-Y",
		baseSpecies: "Audino",
		forme: "Mega",
		types: ["Normal", "Psychic"],
		baseStats: {hp: 103, atk: 60, def: 86, spa: 130, spd: 86, spe: 80},
		abilities: {0: "Magic Guard"},
		heightm: 1.5,
		weightkg: 32,
		color: "White",
		eggGroups: ["Fairy"],
		requiredItem: "Audinite Y",
	},
 	banette: {
		inherit: true,
		otherFormes: ["Banette-Mega", "Banette-Mega-Y"],
		formeOrder: ["Banette", "Banette-Mega", "Banette-Mega-Y"],
	},
	banettemega: {
		num: 354,
		name: "Banette-Mega",
		baseSpecies: "Banette",
		forme: "Mega",
		types: ["Ghost", "Dark"],
		baseStats: {hp: 64, atk: 155, def: 85, spa: 83, spd: 103, spe: 65},
		abilities: {0: "Prankster"},
		heightm: 1.2,
		weightkg: 13,
		color: "Black",
		eggGroups: ["Amorphous"],
		requiredItem: "Banettite",
	},
	banettemegay: {
		num: 354,
		name: "Banette-Mega-Y",
		baseSpecies: "Banette",
		forme: "Mega",
		types: ["Ghost", "Normal"],
		baseStats: {hp: 64, atk: 135, def: 85, spa: 83, spd: 93, spe: 95},
		abilities: {0: "Fluffy"},
		heightm: 1.2,
		weightkg: 13,
		color: "Black",
		eggGroups: ["Amorphous"],
		requiredItem: "Banettite Y",
	},
 	beedrill: {
		inherit: true,
		otherFormes: ["Beedrill-Mega", "Beedrill-Mega-Y"],
		formeOrder: ["Beedrill", "Beedrill-Mega", "Beedrill-Mega-Y"],
	},
	beedrillmegay: {
		num: 15,
		name: "Beedrill-Mega-Y",
		baseSpecies: "Beedrill",
		forme: "Mega",
		types: ["Bug", "Dark"],
		baseStats: {hp: 65, atk: 120, def: 90, spa: 15, spd: 100, spe: 105},
		abilities: {0: "Prankster"},
		heightm: 1.4,
		weightkg: 40.5,
		color: "Yellow",
		eggGroups: ["Bug"],
		requiredItem: "Beedrillite Y",
	},
 	blastoise: {
		inherit: true,
		otherFormes: ["Blastoise-Mega", "Blastoise-Mega-X"],
		formeOrder: ["Blastoise", "Blastoise-Mega", "Blastoise-Mega-X"],
	},
	blastoisemega: {
		num: 9,
		name: "Blastoise-Mega",
		baseSpecies: "Blastoise",
		forme: "Mega",
		types: ["Water", "Fighting"],
		genderRatio: {M: 0.875, F: 0.125},
		baseStats: {hp: 79, atk: 103, def: 145, spa: 135, spd: 110, spe: 58},
		abilities: {0: "Mega Launcher"},
		heightm: 1.6,
		weightkg: 101.1,
		color: "Blue",
		eggGroups: ["Monster", "Water 1"],
		requiredItem: "Blastoisinite",
	},
	blastoisemegax: {
		num: 9,
		name: "Blastoise-Mega-X",
		baseSpecies: "Blastoise",
		forme: "Mega",
		types: ["Water", "Steel"],
		genderRatio: {M: 0.875, F: 0.125},
		baseStats: {hp: 79, atk: 138, def: 110, spa: 100, spd: 145, spe: 58},
		abilities: {0: "Heavy Metal"},
		heightm: 1.6,
		weightkg: 101.1,
		color: "Blue",
		eggGroups: ["Monster", "Water 1"],
		requiredItem: "Blastoisinite X",
	},
 	camerupt: {
		inherit: true,
		otherFormes: ["Camerupt-Mega", "Camerupt-Mega-X"],
		formeOrder: ["Camerupt", "Camerupt-Mega", "Camerupt-Mega-X"],
	},
	cameruptmega: {
		num: 323,
		name: "Camerupt-Mega",
		baseSpecies: "Camerupt",
		forme: "Mega",
		types: ["Fire", "Ground"],
		baseStats: {hp: 70, atk: 130, def: 100, spa: 135, spd: 105, spe: 20},
		abilities: {0: "Drought"},
		heightm: 2.5,
		weightkg: 320.5,
		color: "Red",
		eggGroups: ["Field"],
		requiredItem: "Cameruptite",
	},
	cameruptmegax: {
		num: 323,
		name: "Camerupt-Mega-X",
		baseSpecies: "Camerupt",
		forme: "Mega",
		types: ["Fire", "Poison"],
		baseStats: {hp: 70, atk: 150, def: 90, spa: 105, spd: 75, spe: 70},
		abilities: {0: "Regenerator"},
		heightm: 2.5,
		weightkg: 320.5,
		color: "Red",
		eggGroups: ["Field"],
		requiredItem: "Cameruptite X",
	},
 	crucibelle: {
		inherit: true,
		otherFormes: ["Crucibelle-Mega", "Crucibelle-Mega-Y"],
		formeOrder: ["Crucibelle", "Crucibelle-Mega", "Crucibelle-Mega-Y"],
	},
	crucibellemegay: {
		num: -39,
		name: "Crucibelle-Mega-Y",
		baseSpecies: "Crucibelle",
		forme: "Mega",
		types: ["Dark", "Poison"],
		genderRatio: {M: 0.25, F: 0.75},
		baseStats: {hp: 106, atk: 105, def: 55, spa: 145, spd: 110, spe: 119},
		abilities: {0: "Corrosion"},
		heightm: 1.4,
		weightkg: 22.5,
		color: "Purple",
		eggGroups: ["Amorphous", "Mineral"],
		requiredItem: "Crucibellite Y",
		gen: 7,
	},
 	diancie: {
		inherit: true,
		otherFormes: ["Diancie-Mega", "Diancie-Mega-Y"],
		formeOrder: ["Diancie", "Diancie-Mega", "Diancie-Mega-Y"],
	},
	dianciemegay: {
		num: 719,
		name: "Diancie-Mega-Y",
		baseSpecies: "Diancie",
		forme: "Mega",
		types: ["Rock", "Fairy"],
		gender: "N",
		baseStats: {hp: 50, atk: 120, def: 180, spa: 120, spd: 180, spe: 50},
		abilities: {0: "Levitate"},
		heightm: 1.1,
		weightkg: 27.8,
		color: "Pink",
		eggGroups: ["Undiscovered"],
		requiredItem: "Diancite Y",
	},
 	gallade: {
		inherit: true,
		otherFormes: ["Gallade-Mega", "Gallade-Mega-Y"],
		formeOrder: ["Gallade", "Gallade-Mega", "Gallade-Mega-Y"],
	},
	gallademegay: {
		num: 475,
		name: "Gallade-Mega-Y",
		baseSpecies: "Gallade",
		forme: "Mega",
		types: ["Psychic", "Fighting"],
		gender: "M",
		baseStats: {hp: 68, atk: 105, def: 95, spa: 145, spd: 125, spe: 80},
		abilities: {0: "Technician"},
		heightm: 1.6,
		weightkg: 56.4,
		color: "White",
		eggGroups: ["Amorphous"],
		requiredItem: "Galladite Y",
	},
 	garchomp: {
		inherit: true,
		otherFormes: ["Garchomp-Mega", "Garchomp-Mega-Y"],
		formeOrder: ["Garchomp", "Garchomp-Mega", "Garchomp-Mega-Y"],
	},
	garchompmegay: {
		num: 445,
		name: "Garchomp-Mega-Y",
		baseSpecies: "Garchomp",
		forme: "Mega",
		types: ["Dragon", "Ground"],
		baseStats: {hp: 108, atk: 130, def: 115, spa: 140, spd: 105, spe: 102},
		abilities: {0: "Solar Power"},
		heightm: 1.9,
		weightkg: 95,
		color: "Blue",
		eggGroups: ["Monster", "Dragon"],
		requiredItem: "Garchompite Y",
	},
 	gardevoir: {
		inherit: true,
		otherFormes: ["Gardevoir-Mega", "Gardevoir-Mega-X"],
		formeOrder: ["Gardevoir", "Gardevoir-Mega", "Gardevoir-Mega-X"],
	},
	gardevoirmegax: {
		num: 282,
		name: "Gardevoir-Mega-X",
		baseSpecies: "Gardevoir",
		forme: "Mega",
		types: ["Psychic", "Grass"],
		baseStats: {hp: 68, atk: 65, def: 130, spa: 155, spd: 130, spe: 70},
		abilities: {0: "Triage"},
		heightm: 1.6,
		weightkg: 48.4,
		color: "White",
		eggGroups: ["Amorphous"],
		requiredItem: "Gardevoirite X",
	},
 	gengar: {
		inherit: true,
		otherFormes: ["Gengar-Mega", "Gengar-Mega-X"],
		formeOrder: ["Gengar", "Gengar-Mega", "Gengar-Mega-X"],
	},
	gengarmegax: {
		num: 94,
		name: "Gengar-Mega-X",
		baseSpecies: "Gengar",
		forme: "Mega",
		types: ["Ghost", "Fairy"],
		baseStats: {hp: 60, atk: 65, def: 105, spa: 150, spd: 105, spe: 115},
		abilities: {0: "Competitive"},
		heightm: 1.4,
		weightkg: 40.5,
		color: "Purple",
		eggGroups: ["Amorphous"],
		requiredItem: "Gengarite X",
	},
 	gyarados: {
		inherit: true,
		otherFormes: ["Gyarados-Mega", "Gyarados-Mega-Y"],
		formeOrder: ["Gyarados", "Gyarados-Mega", "Gyarados-Mega-Y"],
	},
	gyaradosmegay: {
		num: 130,
		name: "Gyarados-Mega-Y",
		baseSpecies: "Gyarados",
		forme: "Mega",
		types: ["Water", "Psychic"],
		baseStats: {hp: 95, atk: 95, def: 90, spa: 140, spd: 90, spe: 130},
		abilities: {0: "Lightning Rod"},
		heightm: 6.5,
		weightkg: 305,
		color: "Blue",
		eggGroups: ["Water 2", "Dragon"],
		requiredItem: "Gyaradosite Y",
	},
 	heracross: {
		inherit: true,
		otherFormes: ["Heracross-Mega", "Heracross-Mega-Y"],
		formeOrder: ["Heracross", "Heracross-Mega", "Heracross-Mega-Y"],
	},
	heracrossmegay: {
		num: 214,
		name: "Heracross-Mega-Y",
		baseSpecies: "Heracross",
		forme: "Mega",
		types: ["Bug", "Fighting"],
		baseStats: {hp: 80, atk: 155, def: 95, spa: 40, spd: 105, spe: 125},
		abilities: {0: "Compound Eyes"},
		heightm: 1.7,
		weightkg: 62.5,
		color: "Blue",
		eggGroups: ["Bug"],
		requiredItem: "Heracronite Y",
	},
 	houndoom: {
		inherit: true,
		otherFormes: ["Houndoom-Mega", "Houndoom-Mega-X"],
		formeOrder: ["Houndoom", "Houndoom-Mega", "Houndoom-Mega-X"],
	},
	houndoommega: {
		num: 229,
		name: "Houndoom-Mega",
		baseSpecies: "Houndoom",
		forme: "Mega",
		types: ["Dark", "Fire"],
		baseStats: {hp: 75, atk: 90, def: 90, spa: 140, spd: 90, spe: 115},
		abilities: {0: "Sheer Force"},
		heightm: 1.9,
		weightkg: 49.5,
		color: "Black",
		eggGroups: ["Field"],
		requiredItem: "Houndoominite",
	},
	houndoommegax: {
		num: 229,
		name: "Houndoom-Mega-X",
		baseSpecies: "Houndoom",
		forme: "Mega",
		types: ["Dark", "Poison"],
		baseStats: {hp: 75, atk: 130, def: 70, spa: 110, spd: 110, spe: 105},
		abilities: {0: "Strong Jaw"},
		heightm: 1.9,
		weightkg: 49.5,
		color: "Black",
		eggGroups: ["Field"],
		requiredItem: "Houndoominite X",
	},
 	kangaskhan: {
		inherit: true,
		otherFormes: ["Kangaskhan-Mega", "Kangaskhan-Mega-Y"],
		formeOrder: ["Kangaskhan", "Kangaskhan-Mega", "Kangaskhan-Mega-Y"],
	},
	kangaskhanmegay: {
		num: 115,
		name: "Kangaskhan-Mega-Y",
		baseSpecies: "Kangaskhan",
		forme: "Mega",
		types: ["Normal"],
		gender: "F",
		baseStats: {hp: 105, atk: 65, def: 120, spa: 130, spd: 110, spe: 60},
		abilities: {0: "Regenerator"},
		heightm: 2.2,
		weightkg: 100,
		color: "Brown",
		eggGroups: ["Monster"],
		requiredItem: "Kangaskhanite Y",
	},
 	latias: {
		inherit: true,
		otherFormes: ["Latias-Mega", "Latias-Mega-Y"],
		formeOrder: ["Latias", "Latias-Mega", "Latias-Mega-Y"],
	},
 	latios: {
		inherit: true,
		otherFormes: ["Latios-Mega", "Latios-Mega-X"],
		formeOrder: ["Latios", "Latios-Mega", "Latios-Mega-X"],
	},
	latiasmegay: {
		num: 380,
		name: "Latias-Mega-Y",
		baseSpecies: "Latias",
		forme: "Mega",
		types: ["Dragon", "Fairy"],
		gender: "F",
		baseStats: {hp: 80, atk: 95, def: 90, spa: 125, spd: 195, spe: 115},
		abilities: {0: "Overcoat"},
		heightm: 1.8,
		weightkg: 52,
		color: "Purple",
		eggGroups: ["Undiscovered"],
		requiredItem: "Latiasite Y",
	},
	latiosmegax: {
		num: 381,
		name: "Latios-Mega-X",
		baseSpecies: "Latios",
		forme: "Mega",
		types: ["Dragon", "Fire"],
		gender: "M",
		baseStats: {hp: 80, atk: 163, def: 75, spa: 155, spd: 100, spe: 127},
		abilities: {0: "Reckless"},
		heightm: 2.3,
		weightkg: 70,
		color: "Purple",
		eggGroups: ["Undiscovered"],
		requiredItem: "Latiosite X",
	},
 	lucario: {
		inherit: true,
		otherFormes: ["Lucario-Mega", "Lucario-Mega-Y"],
		formeOrder: ["Lucario", "Lucario-Mega", "Lucario-Mega-Y"],
	},
	lucariomegay: {
		num: 448,
		name: "Lucario-Mega-Y",
		baseSpecies: "Lucario",
		forme: "Mega",
		types: ["Fighting", "Psychic"],
		genderRatio: {M: 0.875, F: 0.125},
		baseStats: {hp: 70, atk: 70, def: 80, spa: 175, spd: 80, spe: 150},
		abilities: {0: "Dazzling"},
		heightm: 1.3,
		weightkg: 57.5,
		color: "Blue",
		eggGroups: ["Field", "Human-Like"],
		requiredItem: "Lucarionite Y",
	},
 	manectric: {
		inherit: true,
		otherFormes: ["Manectric-Mega", "Manectric-Mega-X"],
		formeOrder: ["Manectric", "Manectric-Mega", "Manectric-Mega-X"],
	},
	manectricmegax: {
		num: 310,
		name: "Manectric-Mega-X",
		baseSpecies: "Manectric",
		forme: "Mega",
		types: ["Electric", "Dark"],
		baseStats: {hp: 70, atk: 150, def: 70, spa: 80, spd: 70, spe: 135},
		abilities: {0: "Strong Jaw"},
		heightm: 1.8,
		weightkg: 44,
		color: "Yellow",
		eggGroups: ["Field"],
		requiredItem: "Manectite X",
	},
 	mawile: {
		inherit: true,
		otherFormes: ["Mawile-Mega", "Mawile-Mega-Y"],
		formeOrder: ["Mawile", "Mawile-Mega", "Mawile-Mega-Y"],
	},
	mawilemegay: {
		num: 303,
		name: "Mawile-Mega-Y",
		baseSpecies: "Mawile",
		forme: "Mega",
		types: ["Steel", "Fairy"],
		baseStats: {hp: 50, atk: 105, def: 105, spa: 65, spd: 105, spe: 50},
		abilities: {0: "Fur Coat"},
		heightm: 1,
		weightkg: 23.5,
		color: "Black",
		eggGroups: ["Field", "Fairy"],
		requiredItem: "Mawilite Y",
	},
 	sableye: {
		inherit: true,
		otherFormes: ["Sableye-Mega", "Sableye-Mega-Y"],
		formeOrder: ["Sableye", "Sableye-Mega", "Sableye-Mega-Y"],
	},
	sableyemegay: {
		num: 302,
		name: "Sableye-Mega-Y",
		baseSpecies: "Sableye",
		forme: "Mega",
		types: ["Dark", "Steel"],
		baseStats: {hp: 50, atk: 135, def: 75, spa: 45, spd: 75, spe: 100},
		abilities: {0: "Tough Claws"},
		heightm: 0.5,
		weightkg: 161,
		color: "Purple",
		eggGroups: ["Human-Like"],
		requiredItem: "Sablenite Y",
	},
 	medicham: {
		inherit: true,
		otherFormes: ["Medicham-Mega", "Medicham-Mega-Y"],
		formeOrder: ["Medicham", "Medicham-Mega", "Medicham-Mega-Y"],
	},
	medichammegay: {
		num: 308,
		name: "Medicham-Mega-Y",
		baseSpecies: "Medicham",
		forme: "Mega",
		types: ["Fighting", "Electric"],
		baseStats: {hp: 60, atk: 150, def: 75, spa: 40, spd: 75, spe: 110},
		abilities: {0: "Magic Guard"},
		heightm: 1.3,
		weightkg: 31.5,
		color: "Red",
		eggGroups: ["Human-Like"],
		requiredItem: "Medichamite Y",
	},
 	metagross: {
		inherit: true,
		otherFormes: ["Metagross-Mega", "Metagross-Mega-Y"],
		formeOrder: ["Metagross", "Metagross-Mega", "Metagross-Mega-Y"],
	},
	metagrossmegay: {
		num: 376,
		name: "Metagross-Mega-Y",
		baseSpecies: "Metagross",
		forme: "Mega",
		types: ["Steel", "Psychic"],
		gender: "N",
		baseStats: {hp: 80, atk: 115, def: 155, spa: 130, spd: 150, spe: 70},
		abilities: {0: "Analytic"},
		heightm: 2.5,
		weightkg: 942.9,
		color: "Blue",
		eggGroups: ["Mineral"],
		requiredItem: "Metagrossite Y",
	},
 	pidgeot: {
		inherit: true,
		otherFormes: ["Pidgeot-Mega", "Pidgeot-Mega-X"],
		formeOrder: ["Pidgeot", "Pidgeot-Mega", "Pidgeot-Mega-X"],
	},
	pidgeotmegax: {
		num: 18,
		name: "Pidgeot-Mega-X",
		baseSpecies: "Pidgeot",
		forme: "Mega",
		types: ["Normal", "Flying"],
		baseStats: {hp: 83, atk: 90, def: 135, spa: 70, spd: 110, spe: 91},
		abilities: {0: "Pointed Plummage"},
		heightm: 2.2,
		weightkg: 50.5,
		color: "Brown",
		eggGroups: ["Flying"],
		requiredItem: "Pidgeotite X",
	},
 	pinsir: {
		inherit: true,
		otherFormes: ["Pinsir-Mega", "Pinsir-Mega-Y"],
		formeOrder: ["Pinsir", "Pinsir-Mega", "Pinsir-Mega-Y"],
	},
	pinsirmegay: {
		num: 127,
		name: "Pinsir-Mega-Y",
		baseSpecies: "Pinsir",
		forme: "Mega",
		types: ["Bug", "Ground"],
		baseStats: {hp: 65, atk: 125, def: 130, spa: 70, spd: 150, spe: 60},
		abilities: {0: "Shield Dust"},
		heightm: 1.7,
		weightkg: 59,
		color: "Brown",
		eggGroups: ["Bug"],
		requiredItem: "Pinsirite Y",
	},
 	salamence: {
		inherit: true,
		otherFormes: ["Salamence-Mega", "Salamence-Mega-Y"],
		formeOrder: ["Salamence", "Salamence-Mega", "Salamence-Mega-Y"],
	},
	salamencemegay: {
		num: 373,
		name: "Salamence-Mega-Y",
		baseSpecies: "Salamence",
		forme: "Mega",
		types: ["Dragon", "Electric"],
		baseStats: {hp: 95, atk: 135, def: 105, spa: 150, spd: 105, spe: 110},
		abilities: {0: "Air Lock"},
		heightm: 1.8,
		weightkg: 112.6,
		color: "Blue",
		eggGroups: ["Dragon"],
		requiredItem: "Salamencite Y",
	},
 	sceptile: {
		inherit: true,
		otherFormes: ["Sceptile-Mega", "Sceptile-Mega-X"],
		formeOrder: ["Sceptile", "Sceptile-Mega", "Sceptile-Mega-X"],
	},
	sceptilemega: {
		num: 254,
		name: "Sceptile-Mega",
		baseSpecies: "Sceptile",
		forme: "Mega",
		types: ["Grass", "Dragon"],
		genderRatio: {M: 0.875, F: 0.125},
		baseStats: {hp: 70, atk: 95, def: 85, spa: 145, spd: 90, spe: 145},
		abilities: {0: "Sheer Force"},
		heightm: 1.9,
		weightkg: 55.2,
		color: "Green",
		eggGroups: ["Monster", "Dragon"],
		requiredItem: "Sceptilite",
	},
	sceptilemegax: {
		num: 254,
		name: "Sceptile-Mega-X",
		baseSpecies: "Sceptile",
		forme: "Mega",
		types: ["Grass", "Fighting"],
		genderRatio: {M: 0.875, F: 0.125},
		baseStats: {hp: 70, atk: 145, def: 95, spa: 105, spd: 95, spe: 120},
		abilities: {0: "Super Luck"},
		heightm: 1.9,
		weightkg: 55.2,
		color: "Green",
		eggGroups: ["Monster", "Dragon"],
		requiredItem: "Sceptilite X",
	},
 	blaziken: {
		inherit: true,
		otherFormes: ["Blaziken-Mega", "Blaziken-Mega-Y"],
		formeOrder: ["Blaziken", "Blaziken-Mega", "Blaziken-Mega-Y"],
	},
	blazikenmegay: {
		num: 257,
		name: "Blaziken-Mega-Y",
		baseSpecies: "Blaziken",
		forme: "Mega",
		types: ["Fire", "Electric"],
		genderRatio: {M: 0.875, F: 0.125},
		baseStats: {hp: 80, atk: 170, def: 70, spa: 150, spd: 80, spe: 110},
		abilities: {0: "Sheer Force"},
		heightm: 1.9,
		weightkg: 52,
		color: "Red",
		eggGroups: ["Field"],
		requiredItem: "Blazikenite Y",
	},
 	swampert: {
		inherit: true,
		otherFormes: ["Swampert-Mega", "Swampert-Mega-Y"],
		formeOrder: ["Swampert", "Swampert-Mega", "Swampert-Mega-Y"],
	},
	swampertmegay: {
		num: 260,
		name: "Swampert-Mega-Y",
		baseSpecies: "Swampert",
		forme: "Mega",
		types: ["Water", "Ground"],
		genderRatio: {M: 0.875, F: 0.125},
		baseStats: {hp: 100, atk: 110, def: 120, spa: 125, spd: 120, spe: 60},
		abilities: {0: "Regenerator"},
		heightm: 1.9,
		weightkg: 102,
		color: "Blue",
		eggGroups: ["Monster", "Water 1"],
		requiredItem: "Swampertite Y",
	},
 	scizor: {
		inherit: true,
		otherFormes: ["Scizor-Mega", "Scizor-Mega-Y"],
		formeOrder: ["Scizor", "Scizor-Mega", "Scizor-Mega-Y"],
	},
	scizormegay: {
		num: 212,
		name: "Scizor-Mega-Y",
		baseSpecies: "Scizor",
		forme: "Mega",
		types: ["Bug", "Fire"],
		baseStats: {hp: 70, atk: 160, def: 100, spa: 55, spd: 110, spe: 105},
		abilities: {0: "Flash Fire"},
		heightm: 2,
		weightkg: 125,
		color: "Red",
		eggGroups: ["Bug"],
		requiredItem: "Scizorite Y",
	},
 	sharpedo: {
		inherit: true,
		otherFormes: ["Sharpedo-Mega", "Sharpedo-Mega-Y"],
		formeOrder: ["Sharpedo", "Sharpedo-Mega", "Sharpedo-Mega-Y"],
	},
 	slowbro: {
		inherit: true,
		otherFormes: ["Slowbro-Mega", "Slowbro-Mega-X"],
		formeOrder: ["Slowbro", "Slowbro-Mega", "Slowbro-Mega-X"],
	},
 	steelix: {
		inherit: true,
		otherFormes: ["Steelix-Mega", "Steelix-Mega-Y"],
		formeOrder: ["Steelix", "Steelix-Mega", "Steelix-Mega-Y"],
	},
 	tyranitar: {
		inherit: true,
		otherFormes: ["Tyranitar-Mega", "Tyranitar-Mega-Y"],
		formeOrder: ["Tyranitar", "Tyranitar-Mega", "Tyranitar-Mega-Y"],
	},
 	rayquaza: {
		inherit: true,
		otherFormes: ["Rayquaza-Mega", "Rayquaza-Mega-Y"],
		formeOrder: ["Rayquaza", "Rayquaza-Mega", "Rayquaza-Mega-Y"],
	},
	sharpedomegay: {
		num: 319,
		name: "Sharpedo-Mega-Y",
		baseSpecies: "Sharpedo",
		forme: "Mega",
		types: ["Water", "Dragon"],
		baseStats: {hp: 70, atk: 120, def: 40, spa: 140, spd: 75, spe: 110},
		abilities: {0: "Turboblaze"},
		heightm: 2.5,
		weightkg: 130.3,
		color: "Blue",
		eggGroups: ["Water 2"],
		requiredItem: "Sharpedonite Y",
	},
	slowbromega: {
		num: 80,
		name: "Slowbro-Mega",
		baseSpecies: "Slowbro",
		forme: "Mega",
		types: ["Water", "Steel"],
		baseStats: {hp: 95, atk: 75, def: 180, spa: 130, spd: 90, spe: 20},
		abilities: {0: "Shell Armor"},
		heightm: 2,
		weightkg: 120,
		color: "Pink",
		eggGroups: ["Monster", "Water 1"],
		requiredItem: "Slowbronite",
	},
	slowbromegax: {
		num: 80,
		name: "Slowbro-Mega-X",
		baseSpecies: "Slowbro",
		forme: "Mega",
		types: ["Water", "Psychic"],
		baseStats: {hp: 95, atk: 125, def: 110, spa: 70, spd: 80, spe: 110},
		abilities: {0: "Regenerator"},
		heightm: 2,
		weightkg: 120,
		color: "Pink",
		eggGroups: ["Monster", "Water 1"],
		requiredItem: "Slowbronite X",
	},
	steelixmegay: {
		num: 208,
		name: "Steelix-Mega-Y",
		baseSpecies: "Steelix",
		forme: "Mega",
		types: ["Rock", "Ground"],
		baseStats: {hp: 75, atk: 155, def: 170, spa: 55, spd: 75, spe: 80},
		abilities: {0: "Rock Head"},
		heightm: 10.5,
		weightkg: 740,
		color: "Gray",
		eggGroups: ["Mineral"],
		requiredItem: "Steelixite Y",
	},
	tyranitarmegay: {
		num: 248,
		name: "Tyranitar-Mega-Y",
		baseSpecies: "Tyranitar",
		forme: "Mega",
		types: ["Rock", "Fighting"],
		baseStats: {hp: 100, atk: 124, def: 120, spa: 135, spd: 130, spe: 91},
		abilities: {0: "Lightning Rod"},
		heightm: 2.5,
		weightkg: 255,
		color: "Green",
		eggGroups: ["Monster"],
		requiredItem: "Tyranitarite Y",
	},
	rayquazamegay: {
		num: 384,
		name: "Rayquaza-Mega-Y",
		baseSpecies: "Rayquaza",
		forme: "Mega",
		types: ["Dragon", "Psychic"],
		gender: "N",
		baseStats: {hp: 105, atk: 170, def: 130, spa: 170, spd: 130, spe: 75},
		abilities: {0: "Rho Influence"},
		heightm: 10.8,
		weightkg: 392,
		color: "Green",
		eggGroups: ["Undiscovered"],
		requiredMove: "Psycho Descent",
	},
 	necrozma: {
		inherit: true,
		otherFormes: ["Necrozma-Dusk-Mane", "Necrozma-Dawn-Wings", "Necrozma-Ultra", "Necrozma-Pure"],
		formeOrder: ["Necrozma", "Necrozma-Dusk-Mane", "Necrozma-Dawn-Wings", "Necrozma-Ultra", "Necrozma-Pure"],
	},
	necrozmapure: {
		num: 800,
		name: "Necrozma-Pure",
		baseSpecies: "Necrozma",
		forme: "Ultra",
		types: ["Psychic", "Fairy"],
		gender: "N",
		baseStats: {hp: 97, atk: 97, def: 167, spa: 97, spd: 167, spe: 129},
		abilities: {0: "Shield Dust"},
		heightm: 7.5,
		weightkg: 230,
		color: "Blue",
		eggGroups: ["Undiscovered"],
		requiredItem: "Purenecrozium Z",
		battleOnly: ["Necrozma-Dawn-Wings", "Necrozma-Dusk-Mane"],
	},
 	kyogre: {
		inherit: true,
		otherFormes: ["Kyogre-Primal", "Kyogre-Edge"],
		formeOrder: ["Kyogre", "Kyogre-Primal", "Kyogre-Edge"],
	},
 	groudon: {
		inherit: true,
		otherFormes: ["Groudon-Primal", "Groudon-Fallen"],
		formeOrder: ["Groudon", "Groudon-Primal", "Groudon-Fallen"],
	},
	kyogreedge: {
		num: 382,
		name: "Kyogre-Edge",
		baseSpecies: "Kyogre",
		forme: "Edge",
		types: ["Water", "Grass"],
		gender: "N",
		baseStats: {hp: 100, atk: 130, def: 120, spa: 150, spd: 170, spe: 100},
		abilities: {0: "Primordial Soup"},
		heightm: 9.8,
		weightkg: 430,
		color: "Blue",
		eggGroups: ["Undiscovered"],
		requiredItem: "Green Orb",
	},
	groudonfallen: {
		num: 383,
		name: "Groudon-Fallen",
		baseSpecies: "Groudon",
		forme: "Fallen",
		types: ["Ground", "Steel"],
		gender: "N",
		baseStats: {hp: 100, atk: 160, def: 180, spa: 100, spd: 120, spe: 110},
		abilities: {0: "Apocalyptic Wasteland"},
		heightm: 5,
		weightkg: 999.7,
		color: "Red",
		eggGroups: ["Undiscovered"],
		requiredItem: "Golden Orb",
	},
};
