export const Pokedex: {[speciesid: string]: SpeciesData} = {
	moncub: {
		num: 1,
		name: "Moncub",
		types: ["Grass"],
		baseStats: {hp: 60, atk: 51, def: 51, spa: 51, spd: 57, spe: 40},
		abilities: {0: "Overgrow", H: "Natural Cure"},
		weightkg: 7,
		evos: ["Rabbear"],
	},
	rabbear: {
		num: 2,
		name: "Rabbear",
		types: ["Grass"],
		baseStats: {hp: 80, atk: 60, def: 73, spa: 60, spd: 82, spe: 50},
		abilities: {0: "Overgrow", H: "Natural Cure"},
		weightkg: 16,
		prevo: "Moncub",
		evoLevel: 16,
		evos: ["Grizzeal"],
	},
	grizzeal: {
		num: 3,
		name: "Grizzeal",
		types: ["Grass", "Dark"],
		baseStats: {hp: 120, atk: 89, def: 75, spa: 91, spd: 95, spe: 65},
		abilities: {0: "Overgrow", H: "Natural Cure"},
		weightkg: 200,
		prevo: "Rabbear",
		evoLevel: 32,
	},
	elephire: {
		num: 4,
		name: "Elephire",
		types: ["Fire"],
		baseStats: {hp: 45, atk: 60, def: 58, spa: 43, spd: 54, spe: 50},
		abilities: {0: "Blaze", H: "Levitate"},
		weightkg: 7,
		evos: ["Centrunkion"],
	},
	centrunkion: {
		num: 5,
		name: "Centrunkion",
		types: ["Fire", "Steel"],
		baseStats: {hp: 65, atk: 85, def: 75, spa: 48, spd: 70, spe: 62},
		abilities: {0: "Blaze", H: "Levitate"},
		weightkg: 16,
		prevo: "Elephire",
		evoLevel: 16,
		evos: ["Stampyro"],
	},
	stampyro: {
		num: 6,
		name: "Stampyro",
		types: ["Fire", "Steel"],
		baseStats: {hp: 89, atk: 110, def: 112, spa: 65, spd: 70, spe: 89},
		abilities: {0: "Blaze", H: "Levitate"},
		weightkg: 200,
		prevo: "Centrunkion",
		evoLevel: 32,
	},
	hippothesis: {
		num: 7,
		name: "Hippothesis",
		types: ["Water"],
		baseStats: {hp: 50, atk: 70, def: 50, spa: 50, spd: 50, spe: 40},
		abilities: {0: "Torrent", H: "Drizzle"},
		weightkg: 7,
		evos: ["Hippothalamus"],
	},
	hippothalamus: {
		num: 8,
		name: "Hippothalamus",
		types: ["Water"],
		baseStats: {hp: 70, atk: 85, def: 70, spa: 60, spd: 70, spe: 50},
		abilities: {0: "Torrent", H: "Drizzle"},
		weightkg: 16,
		prevo: "Hippothesis",
		evoLevel: 16,
		evos: ["Hippothagoras"],
	},
	hippothagoras: {
		num: 9,
		name: "Hippothagoras",
		types: ["Water", "Psychic"],
		baseStats: {hp: 77, atk: 105, def: 87, spa: 96, spd: 97, spe: 73},
		abilities: {0: "Torrent", H: "Drizzle"},
		weightkg: 200,
		prevo: "Hippothalamus",
		evoLevel: 32,
	},
	dwole: {
		num: 10,
		name: "Dwole",
		types: ["Normal"],
		baseStats: {hp: 33, atk: 70, def: 35, spa: 25, spd: 22, spe: 55},
		abilities: {0: "Runaway", H: "Adaptability"},
		weightkg: 10,
		evos: ["Moleder"],
	},
	moleder: {
		num: 11,
		name: "Moleder",
		types: ["Normal", "Rock"],
		baseStats: {hp: 74, atk: 102, def: 74, spa: 30, spd: 74, spe: 74},
		abilities: {0: "Run Away", 1: "Sand Force", H: "Adaptability"},
		weightkg: 50,
		prevo: "Dwole",
		evoLevel: 20,
	},
	ducket: {
		num: 12,
		name: "Ducket",
		types: ["Flying"],
		baseStats: {hp: 38, atk: 33, def: 40, spa: 47, spd: 30, spe: 57},
		abilities: {0: "Swift Swim", H: "Mega Launcher"},
		weightkg: 4,
		evos: ["Swannon"],
	},
	swannon: {
		num: 13,
		name: "Swannon",
		types: ["Water", "Flying"],
		baseStats: {hp: 68, atk: 43, def: 67, spa: 77, spd: 50, spe: 60},
		abilities: {0: "Swift Swim", H: "Mega Launcher"},
		weightkg: 11,
		prevo: "Ducket",
		evoLevel: 18,
		evos: ["Bombatross"],
	},
	bombatross: {
		num: 14,
		name: "Bombatross",
		types: ["Water", "Flying"],
		baseStats: {hp: 90, atk: 55, def: 110, spa: 100, spd: 65, spe: 60},
		abilities: {0: "Swift Swim", H: "Mega Launcher"},
		weightkg: 20,
		prevo: "Swannon",
		evoLevel: 36,
	},
	galvia: {
		num: 15,
		name: "Galvia",
		types: ["Electric", "Ground"],
		baseStats: {hp: 140, atk: 51, def: 62, spa: 53, spd: 64, spe: 50},
		abilities: {0: "Water Absorb"},
		weightkg: 3,
	},
	calistone: {
		num: 16,
		name: "Calistone",
		types: ["Fighting"],
		baseStats: {hp: 75, atk: 60, def: 55, spa: 60, spd: 35, spe: 35},
		abilities: {0: "Berserk", 1: "Bulletproof", H: "No Guard"},
		weightkg: 20,
		evos: ["Calistower"],
	},
	calistower: {
		num: 17,
		name: "Calistower",
		types: ["Fighting"],
		baseStats: {hp: 80, atk: 80, def: 80, spa: 70, spd: 80, spe: 40},
		abilities: {0: "Berserk", 1: "Bulletproof", H: "No Guard"},
		weightkg: 100,
		prevo: "Calistone",
		evoLevel: 28,
		evos: ["Calistaiji"],
	},
	calistaiji: {
		num: 18,
		name: "Calistaiji",
		types: ["Fighting"],
		baseStats: {hp: 90, atk: 55, def: 90, spa: 110, spd: 105, spe: 60},
		abilities: {0: "Berserk", 1: "Bulletproof", H: "No Guard"},
		weightkg: 400,
		prevo: "Calistower",
		evoType: "trade",
	},
	dungee: {
		num: 19,
		name: "Dungee",
		types: ["Bug"],
		baseStats: {hp: 30, atk: 50, def: 50, spa: 50, spd: 50, spe: 30},
		abilities: {0: "Swarm"},
		weightkg: 2,
		evos: ["Scarobus"],
	},
	scarobus: {
		num: 20,
		name: "Scarobus",
		types: ["Bug"],
		baseStats: {hp: 49, atk: 60, def: 80, spa: 80, spd: 75, spe: 40},
		abilities: {0: "Swarm"},
		weightkg: 2,
		prevo: "Dungee",
		evoLevel: 10,
		evos: ["Setstorm", "Kheprise"],
	},
	setstorm: {
		num: 21,
		name: "Setstorm",
		types: ["Bug", "Rock"],
		baseStats: {hp: 67, atk: 67, def: 112, spa: 94, spd: 85, spe: 41},
		abilities: {0: "Swarm", 1: "Weak Armor", H: "Sand Stream"},
		weightkg: 10,
		prevo: "Scarobus",
		evoLevel: 21,
		evoCondition: "at night",
	},
	kheprise: {
		num: 22,
		name: "Kheprise",
		types: ["Bug", "Ground"],
		baseStats: {hp: 52, atk: 126, def: 55, spa: 59, spd: 60, spe: 114},
		abilities: {0: "Swarm", 1: "White Smoke", H: "Drought"},
		weightkg: 10,
		prevo: "Scarobus",
		evoLevel: 21,
		evoCondition: "during the day",
	},
	seedlim: {
		num: 23,
		name: "Seedlim",
		types: ["Grass", "Normal"],
		baseStats: {hp: 45, atk: 50, def: 60, spa: 60, spd: 50, spe: 75},
		abilities: {0: "Poison Heal", H: "Grassy Surge"},
		weightkg: 8,
		evos: ["Peetlim"],
	},
	peetlim: {
		num: 24,
		name: "Peetlim",
		types: ["Grass", "Normal"],
		baseStats: {hp: 65, atk: 61, def: 72, spa: 84, spd: 60, spe: 85},
		abilities: {0: "Poison Heal", H: "Grassy Surge"},
		weightkg: 13,
		prevo: "Seedlim",
		evoLevel: 14,
		evos: ["Weeplim"],
	},
	weeplim: {
		num: 25,
		name: "Weeplim",
		types: ["Grass", "Normal"],
		baseStats: {hp: 80, atk: 72, def: 85, spa: 103, spd: 70, spe: 90},
		abilities: {0: "Poison Heal", H: "Grassy Surge"},
		weightkg: 20,
		prevo: "Peetlim",
		evoType: "useItem",
		evoItem: "Leaf Stone",
	},
	goblone: {
		num: 26,
		name: "Goblone",
		types: ["Rock", "Ghost"],
		baseStats: {hp: 59, atk: 35, def: 91, spa: 24, spd: 86, spe: 10},
		abilities: {0: "Storm Drain", H: "Intimidate"},
		weightkg: 50,
		evos: ["Puddogre"],
	},
	puddogre: {
		num: 27,
		name: "Puddogre",
		types: ["Rock", "Ghost"],
		baseStats: {hp: 74, atk: 70, def: 128, spa: 70, spd: 123, spe: 20},
		abilities: {0: "Storm Drain", H: "Intimidate"},
		weightkg: 500,
		prevo: "Goblone",
		evoLevel: 34,
	},
	doduoapple: {
		num: 28,
		name: "Doduo-Apple",
		baseSpecies: "Doduo",
		forme: "Apple",
		types: ["Electric", "Flying"],
		baseStats: {hp: 35, atk: 85, def: 45, spa: 35, spd: 35, spe: 75},
		abilities: {0: "Early Bird", 1: "Run Away", H: "Heavy Air"},
		weightkg: 40,
		evos: "Dodrio-Apple",
	},
	dodrioapple: {
		num: 29,
		name: "Dodrio-Apple",
		baseSpecies: "Dodrio",
		forme: "Apple",
		types: ["Electric", "Flying"],
		baseStats: {hp: 60, atk: 110, def: 75, spa: 60, spd: 75, spe: 90},
		abilities: {0: "Early Bird", 1: "Run Away", H: "Heavy Air"},
		weightkg: 90,
		prevo: "Doduo-Apple",
		evoLevel: 31,
	},
	doderror: {
		num: 30,
		name: "Doderror",
		types: ["Electric", "Flying"],
		baseStats: {hp: 70, atk: 130, def: 83, spa: 75, spd: 88, spe: 94},
		abilities: {0: "Early Bird", 1: "Run Away", H: "Heavy Air"},
		weightkg: 160,
		prevo: "Dodrio-Apple",
		evoType: "useItem",
		evoItem: "Thunder Stone",
	},
	hoothootapple: {
		num: 31,
		name: "Hoothoot-Apple",
		baseSpecies: "Hoothoot",
		forme: "Apple",
		types: ["Psychic", "Flying"],
		baseStats: {hp: 60, atk: 30, def: 30, spa: 46, spd: 46, spe: 50},
		abilities: {0: "Insomnia", 1: "Keen Eye", H: "Tinted Lens"},
		weightkg: 20,
		evos: "Noctowl-Apple",
	},
	noctowlapple: {
		num: 32,
		name: "Noctowl-Apple",
		baseSpecies: "Noctowl",
		forme: "Apple",
		types: ["Psychic", "Flying"],
		baseStats: {hp: 90, atk: 50, def: 50, spa: 96, spd: 86, spe: 80},
		abilities: {0: "Insomnia", 1: "Keen Eye", H: "Tinted Lens"},
		weightkg: 30,
		prevo: "Hoothoot-Apple",
		evoLevel: 20,
	},
	strignight: {
		num: 33,
		name: "Strignight",
		types: ["Psychic", "Flying"],
		baseStats: {hp: 100, atk: 65, def: 72, spa: 108, spd: 92, spe: 103},
		abilities: {0: "Insomnia", 1: "Keen Eye", H: "Tinted Lens"},
		weightkg: 40,
		prevo: "Noctowl-Apple",
		evoType: "useItem",
		evoItem: "Dusk Stone",
	},
	coowoo: {
		num: 34,
		name: "Coowoo",
		types: ["Normal", "Flying"],
		baseStats: {hp: 60, atk: 98, def: 78, spa: 98, spd: 78, spe: 23},
		abilities: {0: "Normalize", H: "Multiscale"},
		weightkg: 5,
	},
	hauntvea: {
		num: 35,
		name: "Hauntvea",
		types: ["Ghost", "Grass"],
		baseStats: {hp: 38, atk: 34, def: 50, spa: 65, spd: 55, spe: 60},
		abilities: {0: "Liquid Ooze", 1: "Damp", H: "Hydration"},
		weightkg: 5,
		evos: ["Spectropa"],
	},
	spectropa: {
		num: 36,
		name: "Spectropa",
		types: ["Ghost", "Grass"],
		baseStats: {hp: 75, atk: 65, def: 70, spa: 125, spd: 65, spe: 90},
		abilities: {0: "Liquid Ooze", 1: "Damp", H: "Hydration"},
		weightkg: 10,
		prevo: "Hauntvea",
		evoLevel: 30,
	},
	geecrik: {
		num: 37,
		name: "Geecrik",
		types: ["Water", "Bug"],
		baseStats: {hp: 38, atk: 45, def: 40, spa: 72, spd: 40, spe: 34},
		abilities: {0: "Truant", 1: "Liquid Voice", H: "Punk Rock"},
		weightkg: 2,
		evos: ["Crikeri"],
	},
	crikeri: {
		num: 38,
		name: "Crikeri",
		types: ["Water", "Bug"],
		baseStats: {hp: 67, atk: 70, def: 61, spa: 108, spd: 70, spe: 62},
		abilities: {0: "Truant", 1: "Liquid Voice", H: "Punk Rock"},
		weightkg: 10,
		prevo: "Geecrik",
		evoLevel: 22,
	},
	hopetta: {
		num: 39,
		name: "Hopetta",
		types: ["Water", "Fighting"],
		baseStats: {hp: 40, atk: 95, def: 60, spa: 40, spd: 30, spe: 68},
		abilities: {0: "Iron Fist", H: "Scrappy"},
		weightkg: 10,
		evos: ["Boxetta"],
	},
	boxetta: {
		num: 40,
		name: "Boxetta",
		types: ["Water", "Fighting"],
		baseStats: {hp: 70, atk: 130, def: 81, spa: 62, spd: 62, spe: 79},
		abilities: {0: "Iron Fist", H: "Scrappy"},
		weightkg: 30,
		prevo: "Hopetta",
		evoLevel: 22,
	},
	phanpyapple: {
		num: 41,
		name: "Phanpy-Apple",
		baseSpecies: "Phanpy",
		forme: "Apple",
		types: ["Grass"],
		baseStats: {hp: 80, atk: 60, def: 70, spa: 40, spd: 40, spe: 40},
		abilities: {0: "Sturdy", H: "Sand Veil"},
		weightkg: 30,
		evos: ["Donphan-Apple"],
	},
	donphanapple: {
		num: 42,
		name: "Donphan-Apple",
		baseSpecies: "Donphan",
		forme: "Apple",
		types: ["Grass", "Fighting"],
		baseStats: {hp: 90, atk: 120, def: 115, spa: 60, spd: 65, spe: 50},
		abilities: {0: "Sturdy", H: "Sand Veil"},
		weightkg: 110,
		prevo: "Phanpy-Apple",
		evoLevel: 25,
		evos: ["Kingphan"],
	},
	kingphan: {
		num: 43,
		name: "Kingphan",
		types: ["Grass", "Fighting"],
		baseStats: {hp: 100, atk: 130, def: 120, spa: 60, spd: 80, spe: 50},
		abilities: {0: "Sturdy", 1: "Stamina", H: "Filter"},
		weightkg: 240,
		prevo: "Donphan-Apple",
		evoType: "trade",
		evoItem: "War Horn",
	},
	stunkyapple: {
		num: 44,
		name: "Stunky-Apple",
		baseSpecies: "Stunky",
		forme: "Apple",
		types: ["Poison", "Water"],
		baseStats: {hp: 73, atk: 63, def: 57, spa: 41, spd: 41, spe: 54},
		abilities: {0: "Aftermath", 1: "Intimidate", H: "Corrosion"},
		weightkg: 18,
		evos: ["Skuntank-Apple"],
	},
	skuntankapple: {
		num: 45,
		name: "Skuntank-Apple",
		baseSpecies: "Skuntank",
		forme: "Apple",
		types: ["Poison", "Water"],
		baseStats: {hp: 103, atk: 87, def: 77, spa: 78, spd: 70, spe: 64},
		abilities: {0: "Aftermath", 1: "Intimidate", H: "Corrosion"},
		weightkg: 35,
		prevo: "Stunky-Apple",
		evoLevel: 34,
		evos: ["Skuntomic"],
	},
	skuntomic: {
		num: 46,
		name: "Skuntomic",
		types: ["Poison", "Water"],
		baseStats: {hp: 112, atk: 97, def: 84, spa: 80, spd: 83, spe: 84},
		abilities: {0: "Aftermath", 1: "Intimidate", H: "Corrosion"},
		weightkg: 80,
		prevo: "Skuntank-Apple",
		evoType: "trade",
		evoItem: "Corroded Waste",
	},
	croagunkapple: {
		num: 47,
		name: "Croagunk-Apple",
		baseSpecies: "Croagunk",
		forme: "Apple",
		types: ["Poison", "Fire"],
		baseStats: {hp: 48, atk: 58, def: 43, spa: 58, spd: 43, spe: 50},
		abilities: {0: "Dry Skin", 1: "Anticipation", H: "Technician"},
		weightkg: 28,
		evos: ["Toxicroak-Apple"],
	},
	toxicroakapple: {
		num: 48,
		name: "Toxicroak-Apple",
		baseSpecies: "Toxicroak",
		forme: "Apple",
		types: ["Poison", "Fire"],
		baseStats: {hp: 73, atk: 106, def: 75, spa: 91, spd: 70, spe: 75},
		abilities: {0: "Dry Skin", 1: "Anticipation", H: "Technician"},
		weightkg: 50,
		prevo: "Croagunk-Apple",
		evoLevel: 34,
		evos: ["Croantagion"],
	},
	croantagion: {
		num: 49,
		name: "Croantagion",
		types: ["Poison", "Fire"],
		baseStats: {hp: 83, atk: 116, def: 90, spa: 96, spd: 75, spe: 80},
		abilities: {0: "Effect Spore", 1: "Anticipation", H: "Technician"},
		weightkg: 90,
		prevo: "Toxicroak-Apple",
		evoType: "trade",
		evoItem: "Melt Core",
	},
	juguler: {
		num: 50,
		name: "Juguler",
		types: ["Electric"],
		baseStats: {hp: 30, atk: 60, def: 40, spa: 65, spd: 40, spe: 82},
		abilities: {0: "Prankster", H: "Electric Surge"},
		weightkg: 3,
		evos: ["Gaggular"],
	},
	gaggular: {
		num: 51,
		name: "Gaggular",
		types: ["Electric", "Dark"],
		baseStats: {hp: 67, atk: 101, def: 65, spa: 107, spd: 85, spe: 80},
		abilities: {0: "Prankster", H: "Electric Surge"},
		weightkg: 30,
		prevo: "Juguler",
		evoType: "useItem",
		evoItem: "Thunder Stone",
	},
	astromini: {
		num: 52,
		name: "Astromini",
		types: ["Steel", "Fairy"],
		baseStats: {hp: 45, atk: 75, def: 50, spa: 70, spd: 60, spe: 50},
		abilities: {0: "Lightning Rod", 1: "Klutz", H: "Magnet Pull"},
		weightkg: 40,
		evos: ["Ultranaut"],
	},
	ultranaut: {
		num: 53,
		name: "Ultranaut",
		types: ["Steel", "Fairy"],
		baseStats: {hp: 70, atk: 115, def: 80, spa: 80, spd: 85, spe: 78},
		abilities: {0: "Lightning Rod", 1: "Klutz", H: "Magnet Pull"},
		weightkg: 250,
		prevo: "Astromini",
		evoType: "levelFriendship",
		otherFormes: ["Ultranaut-V"],
		formeOrder: ["Ultranaut", "Ultranaut-V"],
	},
	ultranautv: {
		num: 53,
		name: "Ultranaut-V",
		baseSpecies: "Ultranaut",
		forme: "V",
		types: ["Steel", "Fairy"],
		baseStats: {hp: 80, atk: 155, def: 85, spa: 105, spd: 75, spe: 108},
		abilities: {0: "Fuel Heavy"},
		weightkg: 500,
		requiredMove: "Laser Sword",
		requiredItem: "Boazanian Metal",
		changesFrom: "Ultranaut",
	},
	dragutus: {
		num: 54,
		name: "Dragutus",
		types: ["Dragon"],
		baseStats: {hp: 80, atk: 70, def: 80, spa: 70, spd: 80, spe: 60},
		abilities: {0: "Regenerator"},
		evos: ["Dragulonimbus", "Dragulare", "Dragulanche"],
		weightkg: 120,
	},
	dragulonimbus: {
		num: 55,
		name: "Dragulonimbus",
		types: ["Dragon", "Electric"],
		baseStats: {hp: 80, atk: 115, def: 72, spa: 96, spd: 72, spe: 115},
		abilities: {0: "Levitate", H: "Sheer Force"},
		weightkg: 200,
		prevo: "Dragutus",
		evoLevel: 55,
		evoCondition: "with an Atk stat equal to its SpAtk stat",
	},
	dragulare: {
		num: 56,
		name: "Dragulare",
		types: ["Dragon", "Fire"],
		baseStats: {hp: 90, atk: 122, def: 80, spa: 75, spd: 103, spe: 80},
		abilities: {0: "Levitate", H: "Rock Head"},
		weightkg: 400,
		prevo: "Dragutus",
		evoLevel: 55,
		evoCondition: "with an Atk stat > its SpAtk stat",
	},
	dragulanche: {
		num: 57,
		name: "Dragulanche",
		types: ["Dragon", "Ice"],
		baseStats: {hp: 90, atk: 80, def: 105, spa: 137, spd: 80, spe: 58},
		abilities: {0: "Levitate", H: "Magic Guard"},
		weightkg: 300,
		prevo: "Dragutus",
		evoLevel: 55,
		evoCondition: "with a SpAtk stat > its Atk stat",
	},
	scrittle: {
		num: 58,
		name: "Scrittle",
		types: ["Ghost", "Flying"],
		baseStats: {hp: 30, atk: 42, def: 30, spa: 90, spd: 33, spe: 150},
		abilities: {0: "Defeatist", H: "Shadow Tag"},
		weightkg: 1,
	},
	corruptrain: {
		num: 59,
		name: "Corruptrain",
		types: ["Steel", "Poison"],
		baseStats: {hp: 100, atk: 87, def: 100, spa: 55, spd: 66, spe: 72},
		abilities: {0: "Light Metal", 1: "Heavy Metal", H: "Steam Engine"},
		weightkg: 700,
	},
	peeckay: {
		num: 60,
		name: "Peeckay",
		types: ["Flying", "Ice"],
		baseStats: {hp: 30, atk: 75, def: 35, spa: 40, spd: 40, spe: 80},
		abilities: {0: "Anticipation", 1: "Skill Link", H: "Snow Warning"},
		weightkg: 2,
		evos: ["Pasdovo"],
	},
	pasdovo: {
		num: 61,
		name: "Pasdovo",
		types: ["Flying", "Ice"],
		baseStats: {hp: 63, atk: 103, def: 83, spa: 53, spd: 103, spe: 103},
		abilities: {0: "Anticipation", 1: "Skill Link", H: "Snow Warning"},
		weightkg: 40,
		prevo: "Peeckay",
		evoType: "useItem",
		evoItem: "Shiny Stone",
	},
	glasiosaur: {
		num: 62,
		name: "Glasiosaur",
		types: ["Ice", "Water"],
		baseStats: {hp: 98, atk: 72, def: 80, spa: 130, spd: 80, spe: 75},
		abilities: {0: "Thick Fat", 1: "Soundproof", H: "Slush Rush"},
		weightkg: 300,
	},
	prettysaur: {
		num: 63,
		name: "Prettysaur",
		types: ["Rock", "Grass"],
		baseStats: {hp: 50, atk: 48, def: 87, spa: 41, spd: 74, spe: 30},
		abilities: {0: "Regenerator", 1: "Heatproof", H: "Contrary"},
		weightkg: 30,
		evos: ["Bellophus"],
	},
	bellophus: {
		num: 64,
		name: "Bellophus",
		types: ["Rock", "Grass"],
		baseStats: {hp: 90, atk: 75, def: 130, spa: 70, spd: 107, spe: 43},
		abilities: {0: "Regenerator", 1: "Heatproof", H: "Contrary"},
		weightkg: 240,
		prevo: "Prettysaur",
		evoLevel: 30,
	},
	crichus: {
		num: 65,
		name: "Crichus",
		types: ["Rock", "Steel"],
		baseStats: {hp: 50, atk: 90, def: 40, spa: 40, spd: 40, spe: 70},
		abilities: {0: "Tough Claws", 1: "Dry Skin", H: "Moxie"},
		weightkg: 6,
		evos: ["Velocust"],
	},
	velocust: {
		num: 66,
		name: "Velocust",
		types: ["Rock", "Steel"],
		baseStats: {hp: 65, atk: 107, def: 81, spa: 76, spd: 65, spe: 121},
		abilities: {0: "Tough Claws", 1: "Dry Skin", H: "Moxie"},
		weightkg: 50,
		prevo: "Crichus",
		evoLevel: 30,
	},
	kuwengu: {
		num: 67,
		name: "Kuwengu",
		types: ["Dark"],
		baseStats: {hp: 75, atk: 60, def: 70, spa: 112, spd: 85, spe: 60},
		abilities: {0: "Magic Bounce", 1: "Prankster", H: "Serene Grace"},
		weightkg: 10,
	},
	putango: {
		num: 68,
		name: "Putango",
		types: ["Normal"],
		baseStats: {hp: 75, atk: 100, def: 102, spa: 55, spd: 70, spe: 60},
		abilities: {0: "Unaware", 1: "Guts", H: "Sand Rush"},
		weightkg: 80,
	},
	/*kuwengu: {
		num: 33
		name: "Kuwengu",
		types: ["Dark"],
		baseStats: {hp: 65, atk: 60, def: 60, spa: 112, spd: 75, spe: 60},
		abilities: {0: "Magic Bounce", 1: "Prankster", H: "Serene Grace"},
		weightkg: 10,
		evos: ["Bagwugu"],
	},
	putango: {
		num: 34,
		name: "Putango",
		types: ["Normal"],
		baseStats: {hp: 65, atk: 100, def: 92, spa: 55, spd: 60, spe: 60},
		abilities: {0: "Unaware", 1: "Guts", H: "Sand Rush"},
		weightkg: 80,
		evos: ["Xeyongo"],
	},
	bagwuwu: {
		num: 54,
		name: "Bagwugu",
		types: ["Dark"],
		baseStats: {hp: 81, atk: 81, def: 71, spa: 121, spd: 91, spe: 81},
		abilities: {0: "Magic Bounce", 1: "Prankster", H: "Serene Grace"},
		weightkg: 10,
		prevo: "Kuwengu",
		evoLevel: 42,
	},
	xeyongo: {
		num: 55,
		name: "Xeyongo",
		types: ["Normal"],
		baseStats: {hp: 81, atk: 121, def: 111, spa: 61, spd: 71, spe: 81},
		abilities: {0: "Unaware", 1: "Guts", H: "Sand Rush"},
		weightkg: 80,
		prevo: "putango",
		evoLevel: 42,
	},*/
	anthusol: {
		num: 69,
		name: "Anthusol",
		types: ["Grass"],
		baseStats: {hp: 63, atk: 63, def: 63, spa: 63, spd: 63, spe: 63},
		abilities: {0: "Drought"},
		weightkg: 10,
		evos: ["Rishelios"],
	},
	rishelios: {
		num: 70,
		name: "Rishelios",
		types: ["Grass", "Fire"],
		baseStats: {hp: 81, atk: 108, def: 81, spa: 108, spd: 81, spe: 81},
		abilities: {0: "Sundancer"},
		weightkg: 90,
		prevo: "Anthusol",
		evoType: "useItem",
		evoItem: "Sun Stone",
	},
	samunata: {
		num: 71,
		name: "Samunata",
		types: ["Bug", "Dragon"],
		baseStats: {hp: 45, atk: 45, def: 37, spa: 70, spd: 48, spe: 55},
		abilities: {0: "Shell Armor", 1: "Sniper", H: "Compound Eyes"},
		weightkg: 2,
		evos: ["Odaimyo"],
	},
	odaimyo: {
		num: 72,
		name: "Odaimyo",
		types: ["Bug", "Dragon"],
		baseStats: {hp: 60, atk: 55, def: 55, spa: 90, spd: 60, spe: 85},
		abilities: {0: "Shell Armor", 1: "Sniper", H: "Compound Eyes"},
		weightkg: 12,
		prevo: "Samunata",
		evoLevel: 24,
		evos: ["Odonaga"],
	},
	odonaga: {
		num: 73,
		name: "Odonaga",
		types: ["Bug", "Dragon"],
		baseStats: {hp: 90, atk: 80, def: 90, spa: 130, spd: 110, spe: 100},
		abilities: {0: "Shell Armor", 1: "Sniper", H: "Compound Eyes"},
		weightkg: 50,
		prevo: "Odaimyo",
		evoLevel: 48,
	},
	solrockapple: {
		num: 74,
		name: "Solrock-Apple",
		baseSpecies: "Solrock",
		forme: "Apple",
		types: ["Ground", "Fairy"],
		baseStats: {hp: 105, atk: 120, def: 100, spa: 65, spd: 80, spe: 70},
		abilities: {0: "Flame Body", 1: "Chlorophyll", H: "Misty Surge"},
		weightkg: 999,
	},
	lunatoneapple: {
		num: 75,
		name: "Lunatone-Apple",
		baseSpecies: "Lunatone",
		forme: "Apple",
		types: ["Ground", "Psychic"],
		baseStats: {hp: 105, atk: 65, def: 80, spa: 120, spd: 100, spe: 70},
		abilities: {0: "Hydration", 1: "Mirror Armor", H: "Psychic Surge"},
		weightkg: 999,
	},
	venomab: {
		num: 76,
		name: "Venomab",
		types: ["Fairy", "Poison"],
		baseStats: {hp: 72, atk: 116, def: 58, spa: 143, spd: 108, spe: 103},
		abilities: {0: "Trace", H: "Competitive"},
		weightkg: 20,
	},
	forganon: {
		num: 77,
		name: "Forganon",
		types: ["Steel", "Ghost"],
		baseStats: {hp: 75, atk: 140, def: 100, spa: 100, spd: 130, spe: 55},
		abilities: {0: "Flash Fire"},
		weightkg: 999,
	},
	isladon: {
		num: 78,
		name: "Isladon",
		types: ["Water", "Grass"],
		baseStats: {hp: 130, atk: 133, def: 100, spa: 113, spd: 100, spe: 84},
		abilities: {0: "Sap Sipper"},
		weightkg: 800,
	},
	ooreina: {
		num: 79,
		name: "Ooreina",
		baseForme: "Romance",
		types: ["Fairy", "Fighting"],
		baseStats: {hp: 100, atk: 100, def: 100, spa: 100, spd: 100, spe: 100},
		abilities: {0: "Speed Boost"},
		weightkg: 15,
		otherFormes: ["Ooreina-Flare"],
		formeOrder: ["Ooreina", "Ooreina-Flare"],
	},
	ooreinaflare: {
		num: 79,
		name: "Ooreina-Flare",
		baseSpecies: "Ooreina",
		forme: "Flare",
		formeLetter: "F",
		types: ["Fairy", "Fire"],
		baseStats: {hp: 100, atk: 100, def: 100, spa: 100, spd: 100, spe: 100},
		abilities: {0: "Speed Boost"},
		weightkg: 15,
		requiredAbility: "Speed Boost",
		battleOnly: "Ooreina",
	},
	rangdemos: {
		num: 80,
		name: "Rangdemos",
		types: ["Psychic", "Poison"],
		baseStats: {hp: 75, atk: 120, def: 90, spa: 155, spd: 105, spe: 135},
		abilities: {0: "Fiendish"},
		weightkg: 100,
	},
	baronglaiv: {
		num: 81,
		name: "Baronglaiv",
		types: ["Fighting", "Ground"],
		baseStats: {hp: 150, atk: 150, def: 120, spa: 78, spd: 110, spe: 72},
		abilities: {0: "Herculean"},
		weightkg: 700,
	},
	thundra: {
		num: 82,
		name: "Thundra",
		types: ["Ice", "Electric"],
		baseStats: {hp: 110, atk: 90, def: 90, spa: 126, spd: 100, spe: 84},
		abilities: {0: "Pressure", H: "Galvanize"},
		weightkg: 600,
	},
	eruptil: {
		num: 83,
		name: "Eruptil",
		types: ["Fire", "Dark"],
		baseStats: {hp: 80, atk: 115, def: 89, spa: 122, spd: 80, spe: 114},
		abilities: {0: "Pressure", H: "Defiant"},
		weightkg: 400,
	},
	amphikits: {
		num: 84,
		name: "Amphikits",
		types: ["Water"],
		baseStats: {hp: 83, atk: 105, def: 80, spa: 111, spd: 96, spe: 125},
		abilities: {0: "Mold Breaker", H: "Natural Cure"},
		weightkg: 30,
	},
	detectrice: {
		num: 85,
		name: "Detectrice",
		types: ["Dark", "Dragon"],
		baseStats: {hp: 103, atk: 110, def: 116, spa: 100, spd: 97, spe: 74},
		abilities: {0: "Stakeout", H: "Intimidate"},
		weightkg: 25,
	},
	nosferoyle: {
		num: 86,
		name: "Nosferoyle",
		types: ["Psychic", "Ghost"],
		baseStats: {hp: 50, atk: 110, def: 80, spa: 115, spd: 129, spe: 116},
		abilities: {0: "Unnerve", H: "Nefarious"},
		weightkg: 430,
	},
	amplifire: {
		num: 87,
		name: "Amplifire",
		types: ["Fire", "Electric"],
		baseStats: {hp: 60, atk: 80, def: 82, spa: 121, spd: 91, spe: 86},
		abilities: {0: "Turboblaze", H: "Punk Rock"},
		weightkg: 100,
	},
	lumberax: {
		num: 88,
		name: "Lumberax",
		types: ["Grass", "Steel"],
		baseStats: {hp: 100, atk: 100, def: 110, spa: 85, spd: 65, spe: 70},
		abilities: {0: "Chlorophyll", H: "Tough Claws"},
		weightkg: 240,
	},
	batakala: {
		num: 89,
		name: "Batakala",
		types: ["Dark", "Ice"],
		baseStats: {hp: 90, atk: 129, def: 89, spa: 112, spd: 104, spe: 136},
		abilities: {0: "Gluttony"},
		weightkg: 550,
	},
	batambu: {
		num: 90,
		name: "Batambu",
		types: ["Flying", "Steel"],
		baseStats: {hp: 100, atk: 80, def: 100, spa: 121, spd: 156, spe: 103},
		abilities: {0: "Copper Heart"},
		weightkg: 300,
	},
	anjawoof: {
		num: 91,
		name: "Anjawoof",
		types: ["Ground"],
		baseStats: {hp: 70, atk: 80, def: 60, spa: 45, spd: 40, spe: 50},
		abilities: {0: "Pickup"},
		weightkg: 10,
	},
	anjamanis: {
		num: 92,
		name: "Anjamanis",
		types: ["Ground"],
		baseStats: {hp: 90, atk: 118, def: 85, spa: 55, spd: 70, spe: 82},
		abilities: {0: "Burrower"},
		weightkg: 60,
	},
	threador: {
		num: 93,
		name: "Threador",
		types: ["Ghost"],
		baseStats: {hp: 50, atk: 40, def: 50, spa: 65, spd: 50, spe: 51},
		abilities: {0: "Shed Skin", 1: "Swift Swim", H: "Infiltrator"},
		weightkg: 3,
	},
	bonfiper: {
		num: 94,
		name: "Bonfiper",
		types: ["Ghost", "Fire"],
		baseStats: {hp: 75, atk: 80, def: 60, spa: 115, spd: 104, spe: 91},
		abilities: {0: "Shed Skin", 1: "Swift Swim", H: "Infiltrator"},
		weightkg: 20,
	},
	goldov: {
		num: 95,
		name: "Goldov",
		types: ["Fairy", "Flying"],
		baseStats: {hp: 40, atk: 60, def: 40, spa: 30, spd: 40, spe: 65},
		abilities: {0: "Unburden", H: "Regenerator"},
		weightkg: 8,
	},
	kalover: {
		num: 96,
		name: "Kalover",
		types: ["Fairy", "Flying"],
		baseStats: {hp: 99, atk: 120, def: 80, spa: 70, spd: 85, spe: 85},
		abilities: {0: "Unburden", 1: "Glitter Bomber", H: "Regenerator"},
		weightkg: 123,
	},
	sophisturn: {
		num: 97,
		name: "Sophisturn",
		types: ["Fairy"],
		baseStats: {hp: 83, atk: 95, def: 90, spa: 51, spd: 95, spe: 76},
		abilities: {0: "Pretentious", H: "Friend Guard"},
		weightkg: 40,
	},
	trestoobee: {
		num: 98,
		name: "Trestoobee",
		types: ["Dark", "Psychic"],
		baseStats: {hp: 120, atk: 120, def: 65, spa: 85, spd: 69, spe: 51},
		abilities: {0: "Dark Giant", H: "Limber"},
		weightkg: 800,
	},
	uractal: {
		num: 99,
		name: "Uractal",
		types: ["Ice"],
		baseStats: {hp: 51, atk: 100, def: 109, spa: 130, spd: 85, spe: 50},
		abilities: {0: "Invader", H: "Solar Power"},
		weightkg: 240,
	},
	venusmog: {
		num: 100,
		name: "Venusmog",
		types: ["Poison"],
		baseStats: {hp: 80, atk: 84, def: 125, spa: 120, spd: 51, spe: 90},
		abilities: {0: "Putrid", H: "Harvest"},
		weightkg: 130,
	},
	plutrapeze: {
		num: 101,
		name: "Plutrapeze",
		types: ["Bug", "Ghost"],
		baseStats: {hp: 85, atk: 125, def: 51, spa: 125, spd: 81, spe: 113},
		abilities: {0: "Arrogant", H: "Foreign Gas"},
		weightkg: 1,
	},
	mercureign: {
		num: 102,
		name: "Mercureign",
		types: ["Flying"],
		baseStats: {hp: 64, atk: 120, def: 75, spa: 120, spd: 100, spe: 101},
		abilities: {0: "Justified", H: "Cloud Nine"},
		weightkg: 79,
	},
};
