export const Aliases = {
	// basically a bunch of names
	"seiba": "Saber",
	"artoriapendragon": "Saber",
	"artoria": "Saber",
	"arturiapendragon": "Saber",
	"arturia": "Saber",
	"altriapendragon": "Saber",
	"altria": "Saber",
	"emiya": "Archer",
	"nameless": "Archer",
	"0": "Zero (Kirby)",
	"0iris": "Zero-Iris",
	"bandannadee": "Bandana Waddle Dee",
	"bandanadee": "Bandana Waddle Dee",
	"bandannawaddledee": "Bandana Waddle Dee",
	"bandee": "Bandana Waddle Dee",
	"chirno": "cirno",
	"chiruno": "cirno",
	"kamui": "Corrin",
	"farlander": "Enderman",
	"kiira": "Galeem",
	"darz": "Dharkon",
	"flandre": "Flandre Scarlet",
	"frandlescarlet": "Flandre Scarlet",
	"frandle": "Flandre Scarlet",
	"frandrescarlet": "Flandre Scarlet",
	"frandre": "Flandre Scarlet",
	"frandollscarlet": "Flandre Scarlet",
	"frandoll": "Flandre Scarlet",
	"blob": "Gooey",
	"blobcharacter": "Gooey",
	"popopo": "Kirby",
	"kingdedede": "Dedede",
	"maskeddedede": "Dedede-Masked",
	"barufureinaito": "Morpho Knight",
	"barufureiknight": "Morpho Knight",
	"morpho": "Morpho Knight",
	"maxprofitthaltmann": "Haltmann",
	"gainsincomehaltmann": "Haltmann",
	"presidenthaltmann": "Haltmann",
	"queensectonia": "Sectonia",
	"soulofsectonia": "Sectonia-Soul",
	"casko": "Tamamo-no-Mae",
	"caster": "Tamamo-no-Mae",
	"castertamamo": "Tamamo-no-Mae",
	"lancertamamo": "Tamamo-no-Mae-Summer",
	"tamamoshark": "Tamamo-no-Mae-Summer",
	"soulravenous": "Soul Elizabeth Ravenous",
	"littleghost": "The Knight",
	"roma": "Romulus",
	"nero": "Nero Claudius",
	"redsaber": "Nero Claudius",
	"saberbride": "Nero Bride",
	"saki": "Saki Nikaido",
	"sakinikaidou": "Saki Nikaido",
	"nikaidousaki": "Saki Nikaido",
	"nikaidosaki": "Saki Nikaido",
	"sayaka": "Sayaka Miki",
	"mikisayaka": "Sayaka Miki",
	"arthur": "Arthur, King of Britons",
	"giivasunner": "SiIvaGunner",
	"silvagunner": "SiIvaGunner",
	"sandworm": "Shai Hulud",
	"nozomi": "Smol Nozomi",
	"nozoomy": "Smol Nozomi",
	"nozomitojo": "Smol Nozomi",
	"terrycrews": "Old Spice Guy",
	"mizunoai": "Ai Mizuno",
	"ai": "Ai Mizuno",
	"homer": "Homer Simpson",
	"kakarot": "Goku",
	"greg": "Greg Heffley",
	"hypercam": "Unregistered Hypercam 2",
	"mickey": "Mickey Mouse",
	"joseph": "Jospeh Joestar",
	"jonathan": "Jonathan Joestar",
	"twilight": "Twilight Sparkle",
	"momo": "Momo Yaoyorozu",
	"creati": "Momo Yaoyorozu",
	"yaoyorozumomo": "Momo Yaoyorozu",
	"kalel": "Superman",
	"clarkkent": "Superman",
	"spiderman": "Miles Morales",
};
