export const Learnsets: {[speciesid: string]: LearnsetData} = {
kermitthefrog: {learnset: {
	earthquake: ["7L1"],
	geomancy: ["7L1"],
	quickattack: ["7L1"],
	sing: ["7L1"],
	splash: ["7L1"],
	watergun: ["7L1"],
	waterpulse: ["7L1"],
}},
goku: {learnset: {
	agility: ["7L1"],
	bulkup: ["7L1"],
	closecombat: ["7L1"],
	dragonascent: ["7L1"],
	extremespeed: ["7L1"],
	quickattack: ["7L1"],
	swordsdance: ["7L1"],
	thunder: ["7L1"],
}},
wallace: {learnset: {
	agility: ["7L1"],
	bugbuzz: ["7L1"],
	fakeout: ["7L1"],
	substitute: ["7L1"],
	swordsdance: ["7L1"],
	tackle: ["7L1"],
	thunderbolt: ["7L1"],
	waterpulse: ["7L1"],
}},
gromit: {learnset: {
	agility: ["7L1"],
	earthquake: ["7L1"],
	howl: ["7L1"],
	quickattack: ["7L1"],
	thunderbolt: ["7L1"],
	waterpulse: ["7L1"],
}},
spongebob: {learnset: {
	agility: ["7L1"],
	shellsmash: ["7L1"],
	substitute: ["7L1"],
	sweetscent: ["7L1"],
	swordsdance: ["7L1"],
	tailwhip: ["7L1"],
	taunt: ["7L1"],
	watergun: ["7L1"],
	waterpulse: ["7L1"],
}},
darthvader: {learnset: {
	darkpulse: ["7L1"],
	doubleteam: ["7L1"],
	fireblast: ["7L1"],
	firefang: ["7L1"],
	minimize: ["7L1"],
	pursuit: ["7L1"],
	thunderbolt: ["7L1"],
}},
hotelmario: {learnset: {
	firefang: ["7L1"],
	firepunch: ["7L1"],
	icepunch: ["7L1"],
	minimize: ["7L1"],
	quickattack: ["7L1"],
	substitute: ["7L1"],
	swordsdance: ["7L1"],
	tackle: ["7L1"],
	volttackle: ["7L1"],
}},
waluigi: {learnset: {
	courtchange: ["7L1"],
	earthquake: ["7L1"],
	fakeout: ["7L1"],
	lightscreen: ["7L1"],
	machpunch: ["7L1"],
	pyroball: ["7L1"],
	spikes: ["7L1"],
	surf: ["7L1"],
}},
};
