'use strict';

exports.BattlePokedex = {
	fearowmega: {
      num: 22,
	   species: "Fearow-Mega",
	   baseSpecies: "Fearow",
	   forme: "Mega",
	   formeLetter: "Q",
	   types: ["Dark","Flying"],
	   baseStats: {hp: 65, atk: 130, def: 85, spa: 61, spd: 81, spe: 120},
	   abilities: {0: "Home-In"},
	   heightm: 8888,
	   weightkg: 38,
	   color: "Brown",
	   evoLevel: 1,
	   eggGroups: ["Flying"],
	},
	arbokmega: {
       num: 24,
	   species: "Arbok-Mega",
	   baseSpecies: "Arbok",
	   forme: "Mega",
	   formeLetter: "M",
	   types: ["Poison","Dragon"],
	   baseStats: {hp: 60, atk: 145, def: 69, spa: 65, spd: 119, spe: 90},
	   abilities: {0: "Acidic Poison"},
	   heightm: 8888,
	   weightkg: 65,
	   color: "Purple",
	   evoLevel: 1,
	   eggGroups: ["Field","Dragon"],
	},
	sandslashalolamega: {
       num: 28,
	   species: "Sandslash-Alola-Mega",
	   baseSpecies: "Sandslash-Alola",
	   forme: "Mega",
	   formeLetter: "M",
	   types: ["Ice","Steel"],
	   baseStats: {hp: 75, atk: 160, def: 135, spa: 25, spd: 88, spe: 70},
	   abilities: {0: "Technician"},
	   heightm: 8888,
	   weightkg: 55,
	   color: "Blue",
	   evoLevel: 1,
	   eggGroups: ["Field"],
	},
	nidoqueenmega: {
       num: 31,
	   species: "Nidoqueen-Mega",
	   baseSpecies: "Nidoqueen",
	   forme: "Mega",
	   formeLetter: "M",
	   types: ["Poison","Fairy"],
	   baseStats: {hp: 90, atk: 92, def: 117, spa: 105, spd: 125, spe: 76},
	   abilities: {0: "Regenerator"},
	   heightm: 1.3,
	   weightkg: 60,
	   color: "Blue",
	   evoLevel: 1,
	   eggGroups: ["Undiscovered"],
	},
	nidokingmega: {
       num: 34,
	   species: "Nidoking-Mega",
	   baseSpecies: "Nidoking",
	   forme: "Mega",
	   formeLetter: "M",
	   types: ["Poison","Ground"],
	   baseStats: {hp: 81, atk: 122, def: 86, spa: 122, spd: 85, spe: 109},
	   abilities: {0: "Simple"},
	   heightm: 1.4,
	   weightkg: 62,
	   color: "Purple",
	   evoLevel: 1,
	   eggGroups: ["Monster","Field"],
	},
	clefablemega: {
       num: 36,
	   species: "Clefable-Mega",
	   baseSpecies: "Clefable",
	   forme: "Mega",
	   formeLetter: "M",
	   types: ["Fairy"],
	   baseStats: {hp: 95, atk: 70, def: 97, spa: 135, spd: 107, spe: 79},
	   abilities: {0: "Unaware"},
	   heightm: 1.3,
	   weightkg: 40,
	   color: "Pink",
	   evoLevel: 1,
	   eggGroups: ["Fairy"],
	},
	ninetalesalola: {
		num: 38,
		species: "Ninetales-Alola",
		forme: "Alola",
		formeLetter: "A",
		types: ["Ice", "Fairy"],
		genderRatio: {M: 0.25, F: 0.75},
		baseStats: {hp: 73, atk: 67, def: 75, spa: 81, spd: 100, spe: 109},
		abilities: {0: "Snow Cloak", H: "Snow Warning"},
		heightm: 1.1,
		weightkg: 19.9,
		color: "Blue",
		prevo: "vulpixalola",
		evoLevel: 1,
		eggGroups: ["Field"],
	},
	ninetalesalolamega: {
       num: 38,
	   species: "Ninetales-Alola-Mega",
	   baseSpecies: "Ninetales-Alola",
	   forme: "Mega",
	   formeLetter: "M",
	   types: ["Ice","Fairy"],
	   baseStats: {hp: 73, atk: 67, def: 95, spa: 141, spd: 100, spe: 129},
	   abilities: {0: "Lanakila Force"},
	   heightm: 1.1,
	   weightkg: 19.9,
	   color: "Blue",
	   evoLevel: 1,
	   eggGroups: ["Field"],
	},
	wigglytuffmega: {
       num: 40,
	   species: "Wigglytuff-Mega",
	   baseSpecies: "Wigglytuff",
	   forme: "Mega",
	   formeLetter: "M",
	   types: ["Normal","Fairy"],
	   baseStats: {hp: 140, atk: 130, def: 65, spa: 100, spd: 65, spe: 35},
	   abilities: {0: "Sheer Force"},
	   heightm: 1,
	   weightkg: 12,
	   color: "Pink",
	   evoLevel: 1,
	   eggGroups: ["Fairy"],
	},
	persianalola: {
		num: 53,
		species: "Persian-Alola",
		forme: "Alola",
		formeLetter: "A",
		types: ["Dark"],
		baseStats: {hp: 65, atk: 60, def: 60, spa: 75, spd: 65, spe: 115},
		abilities: {0: "Fur Coat", 1: "Technician", H: "Rattled"},
		heightm: 1.1,
		weightkg: 33,
		color: "Blue",
		prevo: "meowthalola",
		evoLevel: 2,
		eggGroups: ["Field"],
	},
	persianalolamega: {
       num: 53,
	   species: "Persian-Alola-Mega",
	   baseSpecies: "Persian-Alola",
	   forme: "Mega",
	   formeLetter: "M",
	   types: ["Dark"],
	   baseStats: {hp: 65, atk: 65, def: 85, spa: 100, spd: 90, spe: 135},
	   abilities: {0: "Simple"},
	   heightm: 1.1,
	   weightkg: 33,
	   color: "Blue",
	   evoLevel: 1,
	   eggGroups: ["Field"],
	},
	primeapemega: {
       num: 57,
	   species: "Primeape-Mega",
	   baseSpecies: "Primeape",
	   forme: "Mega",
	   formeLetter: "M",
	   types: ["Fighting","Dark"],
	   baseStats: {hp: 65, atk: 165, def: 60, spa: 60, spd: 70, spe: 135},
	   abilities: {0: "Moxie"},
	   heightm: 1,
	   weightkg: 32,
	   color: "Brown",
	   evoLevel: 1,
	   eggGroups: ["Field"],
	},
	arcaninemega: {
       num: 59,
	   species: "Arcanine-Mega",
	   baseSpecies: "Arcanine",
	   forme: "Mega",
	   formeLetter: "M",
	   types: ["Fire"],
	   baseStats: {hp: 90, atk: 130, def: 100, spa: 130, spd: 100, spe: 105},
	   abilities: {0: "Spreading Flames"},
	   heightm: 1.9,
	   weightkg: 155,
	   color: "Brown",
	   evoLevel: 1,
	   eggGroups: ["Field"],
	},
	machampmega: {
       num: 68,
	   species: "Machamp-Mega",
	   baseSpecies: "Machamp",
	   forme: "Mega",
	   formeLetter: "M",
	   types: ["Fighting","Steel"],
	   baseStats: {hp: 90, atk: 155, def: 115, spa: 70, spd: 120, spe: 55},
	   abilities: {0: "Fist Master"},
	   heightm: 1.6,
	   weightkg: 130,
	   color: "Gray",
	   evoLevel: 1,
	   eggGroups: ["Human-Like"],
	},
	golemalola: {
		num: 76,
		species: "Golem-Alola",
		forme: "Alola",
		formeLetter: "A",
		types: ["Rock", "Electric"],
		baseStats: {hp: 80, atk: 120, def: 130, spa: 55, spd: 65, spe: 45},
		abilities: {0: "Magnet Pull", 1: "Sturdy", H: "Galvanize"},
		heightm: 1.7,
		weightkg: 316,
		color: "Gray",
		prevo: "graveleralola",
		evoLevel: 25,
		eggGroups: ["Mineral"],
	},
	golemalolamega: {
       num: 76,
	   species: "Golem-Alola-Mega",
	   baseSpecies: "Golem-Alola",
	   forme: "Mega",
	   formeLetter: "M",
	   types: ["Ground","Electric"],
	   baseStats: {hp: 80, atk: 150, def: 140, spa: 55, spd: 75, spe: 95},
	   abilities: {0: "Magnet Pull"},
	   heightm: 1.7,
	   weightkg: 316,
	   color: "Gray",
	   evoLevel: 1,
	   eggGroups: ["Mineral"],
	},
	kinglermega: {
       num: 99,
	   species: "Kingler-Mega",
	   baseSpecies: "Kingler",
	   forme: "Mega",
	   formeLetter: "M",
	   types: ["Water","Steel"],
	   baseStats: {hp: 55, atk: 170, def: 135, spa: 60, spd: 60, spe: 95},
	   abilities: {0: "Tough Claws"},
	   heightm: 1.3,
	   weightkg: 60,
	   color: "Red",
	   evoLevel: 1,
	   eggGroups: ["Water 3"],
	},
	marowakmega: {
       num: 105,
	   species: "Marowak-Mega",
	   baseSpecies: "Marowak",
	   forme: "Mega",
	   formeLetter: "M",
	   types: ["Ground","Ghost"],
	   baseStats: {hp: 60, atk: 170, def: 120, spa: 20, spd: 105, spe: 50},
	   abilities: {0: "Incadescent Ire"},
	   heightm: 1,
	   weightkg: 45,
	   color: "Brown",
	   evoLevel: 1,
	   eggGroups: ["Monster"],
	},
	marowakalola: {
		num: 105,
		species: "Marowak-Alola",
		forme: "Alola",
		formeLetter: "A",
		types: ["Fire", "Ghost"],
		baseStats: {hp: 60, atk: 80, def: 110, spa: 50, spd: 80, spe: 45},
		abilities: {0: "Cursed Body", 1: "Lightning Rod", H: "Rock Head"},
		heightm: 1,
		weightkg: 34,
		color: "Purple",
		prevo: "cubone",
		evoLevel: 28,
		eggGroups: ["Monster"],
	},
	marowakalolamega: {
       num: 105,
	   species: "Marowak-Alola-Mega",
	   baseSpecies: "Marowak-Alola",
	   forme: "Mega",
	   formeLetter: "M",
	   types: ["Fire","Ghost"],
	   baseStats: {hp: 60, atk: 120, def: 95, spa: 55, spd: 85, spe: 110},
	   abilities: {0: "Dancer"},
	   heightm: 1,
	   weightkg: 34,
	   color: "Purple",
	   evoLevel: 1,
	   eggGroups: ["Monster"],
	},
	starmiemega: {
       num: 121,
	   species: "Starmie-Mega",
	   baseSpecies: "Starmie",
	   forme: "Mega",
	   formeLetter: "M",
	   types: ["Water","Psychic"],
	   baseStats: {hp: 60, atk: 85, def: 105, spa: 130, spd: 105, spe: 135},
	   abilities: {0: "Compound Eyes"},
	   heightm: 1,
	   weightkg: 34,
	   color: "Purple",
	   eggGroups: ["Water 3"],
	},
	vaporeonmega: {
       num: 134,
	   species: "Vaporeon-Mega",
	   baseSpecies: "Vaporeon",
	   forme: "Mega",
	   formeLetter: "M",
	   types: ["Water", "Normal"],
	   baseStats: {hp: 130, atk: 65, def: 95, spa: 160, spd: 110, spe: 65},
	   abilities: {0: "Regenerator"},
	   heightm: 1,
	   weightkg: 29,
	   color: "Blue",
	   eggGroups: ["Field"],
	},
	jolteonmega: {
       num: 135,
	   species: "Jolteon-Mega",
	   baseSpecies: "Jolteon",
	   forme: "Mega",
	   formeLetter: "M",
	   types: ["Electric"],
	   baseStats: {hp: 65, atk: 75, def: 85, spa: 130, spd: 115, spe: 155},
	   abilities: {0: "Charged Hairs"},
	   heightm: 0.8,
	   weightkg: 24.5,
	   color: "Yellow",
	   eggGroups: ["Field"],
	},
	flareonmega: {
       num: 136,
	   species: "Flareon-Mega",
	   baseSpecies: "Flareon",
	   forme: "Mega",
	   formeLetter: "M",
	   types: ["Fire", "Normal"],
	   baseStats: {hp: 65, atk: 160, def: 110, spa: 65, spd: 130, spe: 95},
	   abilities: {0: "Reckless"},
	   heightm: 0.9,
	   weightkg: 25,
	   color: "Red",
	   eggGroups: ["Field"],
	},
	snorlaxmega: {
		num: 143,
		species: "Snorlax-Mega",
		baseSpecies: "Snorlax",
		forme: "Mega",
		formeLetter: "M",
		types: ["Normal"],
		genderRatio: {M: 0.875, F: 0.125},
		baseStats: {hp: 160, atk: 160, def: 90, spa: 80, spd: 120, spe: 30},
		abilities: {0: "Tough Claws"},
		heightm: 2.1,
		weightkg: 460,
		color: "Black",
		eggGroups: ["Monster"],
	},
	articunomega: {
		num: 144,
		species: "Articuno-Mega",
		baseSpecies: "Articuno",
		forme: "Mega",
		formeLetter: "M",
		types: ["Ice", "Flying"],
		gender: "N",
		baseStats: {hp: 90, atk: 105, def: 150, spa: 120, spd: 130, spe: 85},
		abilities: {0: "Magic Guard"},
		heightm: 1.7,
		weightkg: 55.4,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	zapdosmega: {
		num: 143,
		species: "Zapdos-Mega",
		baseSpecies: "Zapdos",
		forme: "Mega",
		formeLetter: "M",
		types: ["Electric", "Flying"],
		gender: "N",
		baseStats: {hp: 90, atk: 110, def: 105, spa: 165, spd: 90, spe: 120},
		abilities: {0: "Lightning Rod"},
		heightm: 1.6,
		weightkg: 52.6,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	moltresmega: {
		num: 146,
		species: "Moltres-Mega",
		baseSpecies: "Moltres",
		forme: "Mega",
		formeLetter: "M",
		types: ["Fire", "Flying"],
		gender: "N",
		baseStats: {hp: 90, atk: 100, def: 120, spa: 145, spd: 115, spe: 110},
		abilities: {0: "Pyromaniac"},
		heightm: 2,
		weightkg: 60,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	dragonitemega: {
		num: 149,
		species: "Dragonite-Mega",
		baseSpecies: "Dragonite",
		forme: "Mega",
		formeLetter: "M",
		types: ["Dragon", "Normal"],
		baseStats: {hp: 91, atk: 154, def: 110, spa: 115, spd: 120, spe: 110},
		abilities: {0: "Adaptability"},
		heightm: 2.2,
		weightkg: 210,
		color: "Brown",
		eggGroups: ["Water 1", "Dragon"],
	},
	meganiummega: {
		num: 154,
		species: "Meganium-Mega",
		baseSpecies: "Meganium",
		forme: "Mega",
		formeLetter: "M",
		types: ["Grass", "Dragon"],
		baseStats: {hp: 80, atk: 97, def: 130, spa: 98, spd: 130, spe: 90},
		abilities: {0: "Thick Fat"},
		heightm: 1.8,
		weightkg: 100.5,
		color: "Green",
		eggGroups: ["Monster", "Grass"],
	},
	typhlosionmega: {
		num: 157,
		species: "Typhlosion-Mega",
		baseSpecies: "Typhlosion",
		forme: "Mega",
		formeLetter: "M",
		types: ["Fire", "Ground"],
		baseStats: {hp: 78, atk: 114, def: 78, spa: 139, spd: 95, spe: 130},
		abilities: {0: "Mold Breaker"},
		heightm: 1.7,
		weightkg: 79.5,
		color: "Yellow",
		eggGroups: ["Field"],
	},
	feraligatrmega: {
		num: 160,
		species: "Feraligatr-Mega",
		baseSpecies: "Feraligatr",
		forme: "Mega",
		formeLetter: "M",
		types: ["Water", "Poison"],
		baseStats: {hp: 85, atk: 145, def: 130, spa: 89, spd: 93, spe: 88},
		abilities: {0: "Strong Jaw"},
		heightm: 2.3,
		weightkg: 88.8,
		color: "Blue",
		eggGroups: ["Monster", "Water 1"],
	},
	bellossommega: {
		num: 182,
		species: "Bellossom-Mega",
		baseSpecies: "Bellossom",
		forme: "Mega",
		formeLetter: "M",
		types: ["Grass", "Fire"],
		baseStats: {hp: 75, atk: 80, def: 120, spa: 135, spd: 130, spe: 60},
		abilities: {0: "Drought"},
		heightm: 0.4,
		weightkg: 5.8,
		color: "Green",
		eggGroups: ["Grass"],
	},
	sudowoodomega: {
		num: 185,
		species: "Sudowoodo-Mega",
		baseSpecies: "Sudowoodo",
		forme: "Mega",
		formeLetter: "M",
		types: ["Rock"],
		baseStats: {hp: 70, atk: 125, def: 120, spa: 40, spd: 95, spe: 60},
		abilities: {0: "Protean"},
		heightm: 1.2,
		weightkg: 38,
		color: "Brown",
		eggGroups: ["Mineral"],
	},
	sunfloramega: {
       num: 192,
	   species: "Sunflora-Mega",
	   baseSpecies: "Sunflora",
	   forme: "Mega",
	   formeLetter: "M",
	   types: ["Grass", "Fire"],
	   baseStats: {hp: 75, atk: 75, def: 80, spa: 165, spd: 120, spe: 30},
	   abilities: {0: "Drought"},
	   heightm: 0.8,
	   weightkg: 8.5,
	   color: "Yellow",
	   eggGroups: ["Grass"],
	},
	dunsparcemega: {
		num: 206,
		species: "Dunsparce-Mega",
		baseSpecies: "Dunsparce",
		forme: "Mega",
		formeLetter: "M",
		types: ["Normal", "Ghost"],
		baseStats: {hp: 100, atk: 95, def: 105, spa: 65, spd: 105, spe: 45},
		abilities: {0: "Unaware"},
		heightm: 1.5,
		weightkg: 14,
		color: "Yellow",
		eggGroups: ["Field"],
	},
	mantinemega: {
		num: 226,
		species: "Mantine-Mega",
		baseSpecies: "Mantine",
		forme: "Mega",
		formeLetter: "M",
		types: ["Water", "Flying"],
		baseStats: {hp: 85, atk: 40, def: 110, spa: 120, spd: 160, spe: 70},
		abilities: {0: "Comatose"},
		heightm: 2.1,
		weightkg: 220,
		color: "Purple",
		eggGroups: ["Water 1"],
	},
	donphanmega: {
		num: 232,
		species: "Donphan-Mega",
		baseSpecies: "Donphan",
		forme: "Mega",
		formeLetter: "M",
		types: ["Ground", "Steel"],
		baseStats: {hp: 90, atk: 140, def: 160, spa: 70, spd: 90, spe: 50},
		abilities: {0: "Bulletproof"},
		heightm: 1.1,
		weightkg: 120,
		color: "Gray",
		eggGroups: ["Field"],
	},
	blisseymega: {
		num: 242,
		species: "Blissey-Mega",
		baseSpecies: "Blissey",
		forme: "Mega",
		formeLetter: "M",
		types: ["Normal"],
		baseStats: {hp: 255, atk: 10, def: 40, spa: 75, spd: 175, spe: 85},
		abilities: {0: "Oblivious"},
		heightm: 1.5,
		weightkg: 46.8,
		color: "Pink",
		eggGroups: ["Fairy"],
	},
	raikoumega: {
		num: 243,
		species: "Raikou-Mega",
		baseSpecies: "Raikou",
		forme: "Mega",
		formeLetter: "M",
		types: ["Electric"],
		baseStats: {hp: 90, atk: 105, def: 85, spa: 145, spd: 110, spe: 145},
		abilities: {0: "Surge Surfer"},
		heightm: 1.9,
		weightkg: 178,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	enteimega: {
		num: 243,
		species: "Entei-Mega",
		baseSpecies: "Entei",
		forme: "Mega",
		formeLetter: "M",
		types: ["Fire"],
		baseStats: {hp: 115, atk: 150, def: 100, spa: 105, spd: 110, spe: 100},
		abilities: {0: "Beast Boost"},
		heightm: 2.1,
		weightkg: 198,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	suicunemega: {
		num: 243,
		species: "Suicune-Mega",
		baseSpecies: "Suicune",
		forme: "Mega",
		formeLetter: "M",
		types: ["Water"],
		baseStats: {hp: 100, atk: 95, def: 135, spa: 120, spd: 125, spe: 105},
		abilities: {0: "Drizzle"},
		heightm: 2,
		weightkg: 187,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	mightyenamega: {
		num: 262,
		species: "Mightyena-Mega",
		baseSpecies: "Mightyena",
		forme: "Mega",
		formeLetter: "M",
		types: ["Dark", "Fairy"],
		baseStats: {hp: 70, atk: 110, def: 100, spa: 60, spd: 60, spe: 120},
		abilities: {0: "Serene Grace"},
		heightm: 1,
		weightkg: 37,
		color: "Gray",
		eggGroups: ["Field"],
	},
	swellowmega: {
		num: 277,
		species: "Swellow-Mega",
		baseSpecies: "Swellow",
		forme: "Mega",
		formeLetter: "M",
		types: ["Normal", "Flying"],
		baseStats: {hp: 60, atk: 115, def: 65, spa: 100, spd: 60, spe: 155},
		abilities: {0: "Loudspeaker"},
		heightm: 0.7,
		weightkg: 19.8,
		color: "Blue",
		eggGroups: ["Flying"],
	},
	pelippermega: {
		num: 279,
		species: "Pelipper-Mega",
		baseSpecies: "Pelipper",
		forme: "Mega",
		formeLetter: "M",
		types: ["Water", "Flying"],
		baseStats: {hp: 60, atk: 50, def: 150, spa: 115, spd: 90, spe: 75},
		abilities: {0: "Prankster"},
		heightm: 1.2,
		weightkg: 28,
		color: "Yellow",
		eggGroups: ["Water 1", "Flying"],
	},
	breloommega: {
		num: 286,
		species: "Breloom-Mega",
		baseSpecies: "Breloom",
		forme: "Mega",
		formeLetter: "M",
		types: ["Grass", "Fighting"],
		baseStats: {hp: 60, atk: 165, def: 97, spa: 70, spd: 77, spe: 91},
		abilities: {0: "Dashing Punches"},
		heightm: 1.2,
		weightkg: 39.2,
		color: "Green",
		eggGroups: ["Fairy", "Grass"],
	},
	delcattymega: {
		num: 301,
		species: "Delcatty-Mega",
		baseSpecies: "Delcatty",
		forme: "Mega",
		formeLetter: "M",
		types: ["Normal", "Ghost"],
		baseStats: {hp: 70, atk: 65, def: 75, spa: 90, spd: 70, spe: 130},
		abilities: {0: "Infiltrator"},
		heightm: 1.1,
		weightkg: 32.6,
		color: "Purple",
		eggGroups: ["Field", "Fairy"],
	},
	torkoalmega: {
		num: 324,
		species: "Torkoal-Mega",
		baseSpecies: "Torkoal",
		forme: "Mega",
		formeLetter: "M",
		types: ["Fire", "Poison"],
		baseStats: {hp: 70, atk: 85, def: 160, spa: 125, spd: 120, spe: 10},
		abilities: {0: "Earth Rejuvenation"},
		heightm: 0.5,
		weightkg: 80.4,
		color: "Brown",
		eggGroups: ["Field"],
	},
	flygonmega: {
		num: 330,
		species: "Flygon-Mega",
		baseSpecies: "Flygon",
		forme: "Mega",
		formeLetter: "M",
		types: ["Ground", "Dragon"],
		baseStats: {hp: 80, atk: 125, def: 90, spa: 120, spd: 85, spe: 120},
		abilities: {0: "Mold Breaker"},
		heightm: 2,
		weightkg: 82,
		color: "Green",
		eggGroups: ["Bug"],
	},
	sevipermega: {
		num: 336,
		species: "Seviper-Mega",
		baseSpecies: "Seviper",
		forme: "Mega",
		formeLetter: "M",
		types: ["Poison", "Dark"],
		baseStats: {hp: 73, atk: 120, def: 60, spa: 130, spd: 60, spe: 115},
		abilities: {0: "Adaptability"},
		heightm: 2.7,
		weightkg: 52.5,
		color: "Black",
		eggGroups: ["Field", "Dragon"],
	},
	lunatonemega: {
		num: 337,
		species: "Lunatone-Mega",
		baseSpecies: "Lunatone",
		forme: "Mega",
		formeLetter: "M",
		types: ["Rock", "Dark"],
		baseStats: {hp: 90, atk: 80, def: 90, spa: 140, spd: 110, spe: 50},
		abilities: {0: "Prankster"},
		heightm: 1,
		weightkg: 168,
		color: "Yellow",
		eggGroups: ["Mineral"],
	},
	solrockmega: {
		num: 338,
		species: "Solrock-Mega",
		baseSpecies: "Solrock",
		forme: "Mega",
		formeLetter: "M",
		types: ["Rock", "Fire"],
		baseStats: {hp: 90, atk: 145, def: 105, spa: 55, spd: 85, spe: 80},
		abilities: {0: "Rock Head"},
		heightm: 1.2,
		weightkg: 154,
		color: "Red",
		eggGroups: ["Mineral"],
	},
	crawdauntmega: {
		num: 342,
		species: "Solrock-Mega",
		baseSpecies: "Solrock",
		forme: "Mega",
		formeLetter: "M",
		types: ["Water", "Dark"],
		baseStats: {hp: 63, atk: 150, def: 100, spa: 95, spd: 85, spe: 85},
		abilities: {0: "Stakeout"},
		heightm: 1.1,
		weightkg: 32.8,
		color: "Red",
		eggGroups: ["Water 1", "Water 3"],
	},
	tropiusmega: {
		num: 357,
		species: "Tropius-Mega",
		baseSpecies: "Tropius",
		forme: "Mega",
		formeLetter: "M",
		types: ["Grass", "Flying"],
		baseStats: {hp: 99, atk: 68, def: 123, spa: 92, spd: 137, spe: 41},
		abilities: {0: "Thick Fat"},
		heightm: 2,
		weightkg: 100,
		color: "Green",
		eggGroups: ["Monster", "Grass"],
	},
	huntailmega: {
		num: 367,
		species: "Huntail-Mega",
		baseSpecies: "Huntail",
		forme: "Mega",
		formeLetter: "M",
		types: ["Water", "Dark"],
		baseStats: {hp: 55, atk: 145, def: 110, spa: 95, spd: 105, spe: 75},
		abilities: {0: "Sheer Force"},
		heightm: 1.7,
		weightkg: 27,
		color: "Blue",
		eggGroups: ["Water 1"],
	},
	gorebyssmega: {
		num: 368,
		species: "Gorebyss-Mega",
		baseSpecies: "Gorebyss",
		forme: "Mega",
		formeLetter: "M",
		types: ["Water", "Psychic"],
		baseStats: {hp: 55, atk: 95, def: 105, spa: 135, spd: 125, spe: 70},
		abilities: {0: "Multiscale"},
		heightm: 1.8,
		weightkg: 22.6,
		color: "Pink",
		eggGroups: ["Water 1"],
	},
	torterramega: {
		num: 389,
		species: "Torterra-Mega",
		baseSpecies: "Torterra",
		forme: "Mega",
		formeLetter: "M",
		types: ["Grass", "Ground"],
		baseStats: {hp: 95, atk: 154, def: 105, spa: 55, spd: 95, spe: 121},
		abilities: {0: "Evergreen"},
		heightm: 2.2,
		weightkg: 310,
		color: "Green",
		eggGroups: ["Monster", "Grass"],
	},
	infernapemega: {
		num: 392,
		species: "Infernape-Mega",
		baseSpecies: "Infernape",
		forme: "Mega",
		formeLetter: "M",
		types: ["Fire", "Fighting"],
		baseStats: {hp: 76, atk: 129, def: 71, spa: 129, spd: 71, spe: 158},
		abilities: {0: "Limber"},
		heightm: 1.2,
		weightkg: 55,
		color: "Brown",
		eggGroups: ["Field", "Human-Like"],
	},
	empoleonmega: {
		num: 395,
		species: "Empoleon-Mega",
		baseSpecies: "Empoleon",
		forme: "Mega",
		formeLetter: "M",
		types: ["Water", "Steel"],
		baseStats: {hp: 76, atk: 129, def: 71, spa: 129, spd: 71, spe: 158},
		abilities: {0: "Slush Rush"},
		heightm: 1.7,
		weightkg: 84.5,
		color: "Blue",
		eggGroups: ["Water 1", "Field"],
	},
	staraptormega: {
		num: 398,
		species: "Staraptor-Mega",
		baseSpecies: "Staraptor",
		forme: "Mega",
		formeLetter: "M",
		types: ["Fighting", "Flying"],
		baseStats: {hp: 85, atk: 165, def: 85, spa: 50, spd: 80, spe: 120},
		abilities: {0: "Defiant"},
		heightm: 1.2,
		weightkg: 24.9,
		color: "Brown",
		eggGroups: ["Flying"],
	},
	roserademega: {
		num: 407,
		species: "Roserade-Mega",
		baseSpecies: "Roserade",
		forme: "Mega",
		formeLetter: "M",
		types: ["Grass", "Poison"],
		baseStats: {hp: 60, atk: 75, def: 75, spa: 165, spd: 135, spe: 105},
		abilities: {0: "Merciless"},
		heightm: 0.9,
		weightkg: 14.5,
		color: "Green",
		eggGroups: ["Fairy", "Grass"],
	},
	ambipommega: {
		num: 424,
		species: "Ambipom-Mega",
		baseSpecies: "Ambipom",
		forme: "Mega",
		formeLetter: "M",
		types: ["Normal"],
		baseStats: {hp: 75, atk: 120, def: 96, spa: 70, spd: 96, spe: 125},
		abilities: {0: "Prankster"},
		heightm: 1.2,
		weightkg: 20.3,
		color: "Purple",
		eggGroups: ["Field"],
	},
	puruglymega: {
		num: 432,
		species: "Purugly-Mega",
		baseSpecies: "Purugly",
		forme: "Mega",
		formeLetter: "M",
		types: ["Normal"],
		baseStats: {hp: 71, atk: 126, def: 88, spa: 64, spd: 69, spe: 134},
		abilities: {0: "Tough Claws"},
		heightm: 1,
		weightkg: 43.8,
		color: "Gray",
		eggGroups: ["Field"],
	},
	drapionmega: {
		num: 452,
		species: "Drapion-Mega",
		baseSpecies: "Drapion",
		forme: "Mega",
		formeLetter: "M",
		types: ["Poison", "Dark"],
		baseStats: {hp: 70, atk: 105, def: 130, spa: 70, spd: 115, spe: 110},
		abilities: {0: "Corrosion"},
		heightm: 1.3,
		weightkg: 61.5,
		color: "Purple",
		eggGroups: ["Bug", "Water 3"],
	},
	lumineonmega: {
		num: 457,
		species: "Lumineon-Mega",
		baseSpecies: "Lumineon",
		forme: "Mega",
		formeLetter: "M",
		types: ["Water", "Flying"],
		baseStats: {hp: 69, atk: 69, def: 76, spa: 109, spd: 116, spe: 121},
		abilities: {0: "Drizzle"},
		heightm: 1.2,
		weightkg: 24,
		color: "Blue",
		eggGroups: ["Water 2"],
	},
	weavilemega: {
		num: 461,
		species: "Weavile-Mega",
		baseSpecies: "Weavile",
		forme: "Mega",
		formeLetter: "M",
		types: ["Dark", "Ice"],
		baseStats: {hp: 70, atk: 145, def: 85, spa: 65, spd: 95, spe: 150},
		abilities: {0: "Technician"},
		heightm: 1.1,
		weightkg: 34,
		color: "Black",
		eggGroups: ["Field"],
	},
	magnezonemega: {
		num: 462,
		species: "Magnezone-Mega",
		baseSpecies: "Magnezone",
		forme: "Mega",
		formeLetter: "M",
		types: ["Electric", "Steel"],
		baseStats: {hp: 70, atk: 70, def: 125, spa: 160, spd: 100, spe: 110},
		abilities: {0: "Levitate"},
		heightm: 1.2,
		weightkg: 180,
		color: "Gray",
		eggGroups: ["Mineral"],
	},
	rhyperiormega: {
		num: 464,
		species: "Rhyperior-Mega",
		baseSpecies: "Rhyperior",
		forme: "Mega",
		formeLetter: "M",
		types: ["Ground","Fighting"],
		baseStats: {hp: 115, atk: 190, def: 145, spa: 65, spd: 100, spe: 20},
		abilities: {0: "Iron Fist"},
		heightm: 2.4,
		weightkg: 282.8,
		color: "Gray",
		eggGroups: ["Monster", "Field"],
	},
	tangrowthmega: {
		num: 465,
		species: "Tangrowth-Mega",
		baseSpecies: "Tangrowth",
		forme: "Mega",
		formeLetter: "M",
		types: ["Grass", "Bug"],
		baseStats: {hp: 100, atk: 130, def: 115, spa: 115, spd: 70, spe: 105},
		abilities: {0: "Wonder Skin"},
		heightm: 1.8,
		weightkg: 138.6,
		color: "Blue",
		eggGroups: ["Grass"],
	},
	electiviremega: {
		num: 466,
		species: "Electivire-Mega",
		baseSpecies: "Electivire",
		forme: "Mega",
		formeLetter: "M",
		types: ["Electric", "Fighting"],
		baseStats: {hp: 75, atk: 153, def: 67, spa: 125, spd: 115, spe: 105},
		abilities: {0: "Contrary"},
		heightm: 1.8,
		weightkg: 138.6,
		color: "Yellow",
		eggGroups: ["Human-Like"],
	},
	magmortarmega: {
		num: 467,
		species: "Magmortar-Mega",
		baseSpecies: "Magmortar",
		forme: "Mega",
		formeLetter: "M",
		types: ["Fire"],
		baseStats: {hp: 75, atk: 120, def: 77, spa: 175, spd: 130, spe: 63},
		abilities: {0: "Volcanic Haze"},
		heightm: 1.6,
		weightkg: 68,
		color: "Red",
		eggGroups: ["Human-Like"],
	},
	yanmegamega: {
		num: 469,
		species: "Yanmega-Mega",
		baseSpecies: "Yanmega",
		forme: "Mega",
		formeLetter: "M",
		types: ["Bug", "Rock"],
		baseStats: {hp: 86, atk: 106, def: 91, spa: 141, spd: 81, spe: 110},
		abilities: {0: "Technician"},
		heightm: 1.2,
		weightkg: 180,
		color: "Gray",
		eggGroups: ["Mineral"],
	},
	gliscormega: {
		num: 472,
		species: "Gliscor-Mega",
		baseSpecies: "Gliscor",
		forme: "Mega",
		formeLetter: "M",
		types: ["Flying", "Dark"],
		baseStats: {hp: 75, atk: 110, def: 140, spa: 65, spd: 120, spe: 100},
		abilities: {0: "Triage"},
		heightm: 2,
		weightkg: 42.5,
		color: "Purple",
		eggGroups: ["Bug"],
	},
	mamoswinemega: {
		num: 473,
		species: "Mamoswine-Mega",
		baseSpecies: "Mamoswine",
		forme: "Mega",
		formeLetter: "M",
		types: ["Ice", "Ground"],
		baseStats: {hp: 110, atk: 150, def: 100, spa: 80, spd: 80, spe: 110},
		abilities: {0: "Thick Fat"},
		heightm: 2.5,
		weightkg: 291,
		color: "Brown",
		eggGroups: ["Field"],
	},
	porygonzmega: {
		num: 474,
		species: "Porygon-Z-Mega",
		baseSpecies: "Porygon-Z",
		forme: "Mega",
		formeLetter: "M",
		types: ["Normal", "Bug"],
		baseStats: {hp: 85, atk: 85, def: 95, spa: 170, spd: 100, spe: 100},
		abilities: {0: "Tinted Lens"},
		heightm: 0.9,
		weightkg: 34,
		color: "Red",
		eggGroups: ["Mineral"],
	},
	probopassmega: {
		num: 476,
		species: "Probopass-Mega",
		baseSpecies: "Probopass",
		forme: "Mega",
		formeLetter: "M",
		types: ["Rock", "Steel"],
		baseStats: {hp: 60, atk: 65, def: 175, spa: 110, spd: 175, spe: 40},
		abilities: {0: "Levitate"},
		heightm: 1.4,
		weightkg: 340,
		color: "Gray",
		eggGroups: ["Mineral"],
	},
	phionemega: {
		num: 489,
		species: "Phione-Mega",
		baseSpecies: "Phione",
		forme: "Mega",
		formeLetter: "M",
		types: ["Water"],
		baseStats: {hp: 80, atk: 120, def: 80, spa: 120, spd: 80, spe: 100},
		abilities: {0: "Technician"},
		heightm: 0.4,
		weightkg: 3.1,
		color: "Blue",
		eggGroups: ["Water 1", "Fairy"],
	},
	stoutlandmega: {
		num: 508,
		species: "Stoutland-Mega",
		baseSpecies: "Stoutland",
		forme: "Mega",
		formeLetter: "M",
		types: ["Normal"],
		baseStats: {hp: 85, atk: 150, def: 110, spa: 45, spd: 110, spe: 100},
		abilities: {0: "Hustle"},
		heightm: 1.2,
		weightkg: 61,
		color: "Gray",
		eggGroups: ["Field"],
	},
	liepardmega: {
		num: 510,
		species: "Liepard-Mega",
		baseSpecies: "Liepard",
		forme: "Mega",
		formeLetter: "M",
		types: ["Dark", "Fairy"],
		baseStats: {hp: 64, atk: 123, def: 50, spa: 123, spd: 50, spe: 136},
		abilities: {0: "Prankster"},
		heightm: 1.1,
		weightkg: 37.5,
		color: "Purple",
		eggGroups: ["Field"],
	},
	simisagemega: {
		num: 512,
		species: "Simisage-Mega",
		baseSpecies: "Simisage",
		forme: "Mega",
		formeLetter: "M",
		types: ["Grass", "Water"],
		genderRatio: {M: 0.875, F: 0.125},
		baseStats: {hp: 75, atk: 108, def: 83, spa: 123, spd: 83, spe: 126},
		abilities: {0: "Adaptability"},
		heightm: 1.1,
		weightkg: 30.5,
		color: "Green",
		eggGroups: ["Field"],
	},
	simisearmega: {
		num: 514,
		species: "Simisear-Mega",
		baseSpecies: "Simisear",
		forme: "Mega",
		formeLetter: "M",
		types: ["Fire", "Grass"],
		genderRatio: {M: 0.875, F: 0.125},
		baseStats: {hp: 75, atk: 108, def: 83, spa: 123, spd: 83, spe: 126},
		abilities: {0: "Adaptability"},
		heightm: 1,
		weightkg: 28,
		color: "Red",
		eggGroups: ["Field"],
	},
	simipourmega: {
		num: 514,
		species: "Simipour-Mega",
		baseSpecies: "Simipour",
		forme: "Mega",
		formeLetter: "M",
		types: ["Water", "Fire"],
		genderRatio: {M: 0.875, F: 0.125},
		baseStats: {hp: 75, atk: 108, def: 83, spa: 123, spd: 83, spe: 126},
		abilities: {0: "Adaptability"},
		heightm: 1,
		weightkg: 29,
		color: "Blue",
		eggGroups: ["Field"],
	},
	musharnamega: {
		num: 518,
		species: "Musharna-Mega",
		baseSpecies: "Musharna",
		forme: "Mega",
		formeLetter: "M",
		types: ["Psychic", "Poison"],
		baseStats: {hp: 116, atk: 55, def: 115, spa: 140, spd: 140, spe: 21},
		abilities: {0: "Levitate"},
		heightm: 1.1,
		weightkg: 60.5,
		color: "Pink",
		eggGroups: ["Field"],
	},
	zebstrikamega: {
		num: 523,
		species: "Zebstrika-Mega",
		baseSpecies: "Zebstrika",
		forme: "Mega",
		formeLetter: "M",
		types: ["Electric"],
		baseStats: {hp: 75, atk: 135, def: 85, spa: 90, spd: 78, spe: 134},
		abilities: {0: "Rage Motor"},
		heightm: 1.6,
		weightkg: 79.5,
		color: "Black",
		eggGroups: ["Field"],
	},
	seismitoadmega: {
		num: 537,
		species: "Seismitoad-Mega",
		baseSpecies: "Seismitoad",
		forme: "Mega",
		formeLetter: "M",
		types: ["Water", "Ground"],
		baseStats: {hp: 105, atk: 138, def: 108, spa: 88, spd: 85, spe: 88},
		abilities: {0: "Seismic Vibration"},
		heightm: 1.5,
		weightkg: 62,
		color: "Blue",
		eggGroups: ["Water 1"],
	},
	whimsicottmega: {
		num: 547,
		species: "Whimsicott-Mega",
		baseSpecies: "Whimsicott",
		forme: "Mega",
		formeLetter: "M",
		types: ["Grass", "Fairy"],
		baseStats: {hp: 60, atk: 77, def: 110, spa: 117, spd: 100, spe: 116},
		abilities: {0: "No Guard"},
		heightm: 0.7,
		weightkg: 6.6,
		color: "Green",
		eggGroups: ["Fairy", "Grass"],
	},
	krookodilemega: {
		num: 553,
		species: "Krookodile-Mega",
		baseSpecies: "Krookodile",
		forme: "Mega",
		formeLetter: "M",
		types: ["Ground", "Dark"],
		baseStats: {hp: 95, atk: 167, def: 100, spa: 75, spd: 80, spe: 102},
		abilities: {0: "Tough Claws"},
		heightm: 1.5,
		weightkg: 96.3,
		color: "Red",
		eggGroups: ["Field"],
	},
	maractusmega: {
		num: 556,
		species: "Maractus-Mega",
		baseSpecies: "Maractus",
		forme: "Mega",
		formeLetter: "M",
		types: ["Grass", "Rock"],
		baseStats: {hp: 75, atk: 116, def: 82, spa: 157, spd: 82, spe: 50},
		abilities: {0: "Bulletproof"},
		heightm: 1,
		weightkg: 28,
		color: "Green",
		eggGroups: ["Grass"],
	},
	carracostamega: {
		num: 565,
		species: "Carracosta-Mega",
		baseSpecies: "Carracosta",
		forme: "Mega",
		formeLetter: "M",
		types: ["Water", "Rock"],
		baseStats: {hp: 74, atk: 138, def: 143, spa: 83, spd: 95, spe: 62},
		abilities: {0: "Ancient Armor"},
		heightm: 1.2,
		weightkg: 81,
		color: "Blue",
		eggGroups: ["Water 1", "Water 3"],
	},
	reuniclusmega: {
		num: 579,
		species: "Reuniclus-Mega",
		baseSpecies: "Reuniclus",
		forme: "Mega",
		formeLetter: "M",
		types: ["Psychic"],
		baseStats: {hp: 110, atk: 65, def: 105, spa: 165, spd: 105, spe: 40},
		abilities: {0: "Power Fist"},
		heightm: 1,
		weightkg: 20.1,
		color: "Green",
		eggGroups: ["Amorphous"],
	},
	vanilluxemega: {
		num: 584,
		species: "Vanilluxe-Mega",
		baseSpecies: "Vanilluxe",
		forme: "Mega",
		formeLetter: "M",
		types: ["Ice"],
		baseStats: {hp: 71, atk: 164, def: 100, spa: 100, spd: 100, spe: 100},
		abilities: {0: "Skill Link"},
		heightm: 1.3,
		weightkg: 57.5,
		color: "White",
		eggGroups: ["Mineral"],
	},
	amoongussmega: {
		num: 591,
		species: "Amoonguss-Mega",
		baseSpecies: "Amoonguss",
		forme: "Mega",
		formeLetter: "M",
		types: ["Grass", "Poison"],
		baseStats: {hp: 114, atk: 110, def: 95, spa: 110, spd: 105, spe: 30},
		abilities: {0: "Filter"},
		heightm: 0.6,
		weightkg: 10.5,
		color: "White",
		eggGroups: ["Grass"],
	},
	galvantulamega: {
		num: 596,
		species: "Galvantula-Mega",
		baseSpecies: "Galvantula",
		forme: "Mega",
		formeLetter: "M",
		types: ["Bug", "Electric"],
		baseStats: {hp: 70, atk: 87, def: 80, spa: 142, spd: 60, spe: 133},
		abilities: {0: "Compound Eyes"},
		heightm: 0.8,
		weightkg: 14.3,
		color: "Yellow",
		eggGroups: ["Bug"],
	},
	eelektrossmega: {
		num: 604,
		species: "Eelektross-Mega",
		baseSpecies: "Eelektross",
		forme: "Mega",
		formeLetter: "M",
		types: ["Electric", "Poison"],
		baseStats: {hp: 85, atk: 145, def: 100, spa: 135, spd: 100, spe: 50},
		abilities: {0: "Corrosion"},
		heightm: 2.1,
		weightkg: 80.5,
		color: "Blue",
		eggGroups: ["Amorphous"],
	},
	bearticmega: {
		num: 614,
		species: "Beartic-Mega",
		baseSpecies: "Beartic",
		forme: "Mega",
		formeLetter: "M",
		types: ["Ice"],
		baseStats: {hp: 95, atk: 175, def: 80, spa: 70, spd: 100, spe: 85},
		abilities: {0: "Allotropize"},
		heightm: 2.6,
		weightkg: 260,
		color: "White",
		eggGroups: ["Field"],
	},
	mienshaomega: {
		num: 620,
		species: "Mienshao-Mega",
		baseSpecies: "Mienshao",
		forme: "Mega",
		formeLetter: "M",
		types: ["Fighting", "Flying"],
		baseStats: {hp: 65, atk: 140, def: 85, spa: 115, spd: 85, spe: 115},
		abilities: {0: "Technician"},
		heightm: 1.4,
		weightkg: 35.5,
		color: "Purple",
		eggGroups: ["Field", "Human-Like"],
	},
	braviarymega: {
		num: 628,
		species: "Braviary-Mega",
		baseSpecies: "Braviary",
		forme: "Mega",
		formeLetter: "M",
		types: ["Normal", "Flying"],
		baseStats: {hp: 100, atk: 158, def: 95, spa: 62, spd: 95, spe: 100},
		abilities: {0: "Guts"},
		heightm: 1.5,
		weightkg: 41,
		color: "Red",
		eggGroups: ["Flying"],
	},
	hydreigonmega: {
		num: 635,
		species: "Hydreigon-Mega",
		baseSpecies: "Hydreigon",
		forme: "Mega",
		formeLetter: "M",
		types: ["Dark", "Dragon"],
		baseStats: {hp: 92, atk: 115, def: 120, spa: 165, spd: 120, spe: 88},
		abilities: {0: "Mega Launcher"},
		heightm: 1.8,
		weightkg: 160,
		color: "Blue",
		eggGroups: ["Dragon"],
	},
	volcaronamega: {
		num: 637,
		species: "Volcarona-Mega",
		baseSpecies: "Volcarona",
		forme: "Mega",
		formeLetter: "M",
		types: ["Bug", "Fire"],
		baseStats: {hp: 85, atk: 110, def: 100, spa: 135, spd: 105, spe: 115},
		abilities: {0: "Tinted Lens"},
		heightm: 1.6,
		weightkg: 46,
		color: "White",
		eggGroups: ["Bug"],
	},
	cobalionmega: {
		num: 638,
		species: "Cobalion-Mega",
		baseSpecies: "Cobalion",
		forme: "Mega",
		formeLetter: "M",
		types: ["Steel", "Fighting"],
		baseStats: {hp: 91, atk: 110, def: 159, spa: 110, spd: 92, spe: 118},
		abilities: {0: "Download"},
		heightm: 2.1,
		weightkg: 250,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	terrakionmega: {
		num: 639,
		species: "Terrakion-Mega",
		baseSpecies: "Terrakion",
		forme: "Mega",
		formeLetter: "M",
		types: ["Rock", "Fighting"],
		baseStats: {hp: 91, atk: 159, def: 110, spa: 92, spd: 110, spe: 118},
		abilities: {0: "Defiant"},
		heightm: 1.9,
		weightkg: 260,
		color: "Gray",
		eggGroups: ["Undiscovered"],
	},
	virizionmega: {
		num: 640,
		species: "Virizion-Mega",
		baseSpecies: "Virizion",
		forme: "Mega",
		formeLetter: "M",
		types: ["Grass", "Fighting"],
		baseStats: {hp: 91, atk: 110, def: 92, spa: 110, spd: 159, spe: 118},
		abilities: {0: "Triage"},
		heightm: 2,
		weightkg: 200,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	keldeomega: {
		num: 647,
		species: "Keldeo-Mega",
		baseSpecies: "Keldeo",
		forme: "Mega",
		formeLetter: "M",
		types: ["Water", "Fighting"],
		baseStats: {hp: 91, atk: 92, def: 110, spa: 159, spd: 110, spe: 118},
		abilities: {0: "Soul Heart"},
		heightm: 1.4,
		weightkg: 48.5,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	diggersbymega: {
		num: 660,
		species: "Diggersby-Mega",
		baseSpecies: "Diggersby",
		forme: "Mega",
		formeLetter: "M",
		types: ["Normal", "Ground"],
		baseStats: {hp: 85, atk: 76, def: 127, spa: 50, spd: 107, spe: 78},
		abilities: {0: "Huge Power"},
		heightm: 1,
		weightkg: 42.4,
		color: "Brown",
		eggGroups: ["Field"],
	},
	talonflamemega: {
		num: 663,
		species: "Talonflame-Mega",
		baseSpecies: "Talonflame",
		forme: "Mega",
		formeLetter: "M",
		types: ["Fire", "Flying"],
		baseStats: {hp: 78, atk: 116, def: 74, spa: 109, spd: 74, spe: 148},
		abilities: {0: "Speed Boost"},
		heightm: 1.2,
		weightkg: 24.5,
		color: "Red",
		eggGroups: ["Flying"],
	},
	florgesmega: {
		num: 671,
		species: "Florges-Mega",
		baseSpecies: "Florges",
		forme: "Mega",
		formeLetter: "M",
		types: ["Fairy", "Grass"],
		baseStats: {hp: 78, atk: 65, def: 98, spa: 142, spd: 184, spe: 85},
		abilities: {0: "Flower Power"},
		heightm: 1.1,
		weightkg: 10,
		color: "White",
		eggGroups: ["Fairy"],
	},
	pangoromega: {
		num: 675,
		species: "Pangoro-Mega",
		baseSpecies: "Pangoro",
		forme: "Mega",
		formeLetter: "M",
		types: ["Fighting", "Dark"],
		baseStats: {hp: 95, atk: 194, def: 88, spa: 69, spd: 71, spe: 78},
		abilities: {0: "Moxie"},
		heightm: 2.1,
		weightkg: 136,
		color: "White",
		eggGroups: ["Field", "Human-Like"],
	},
	meowsticmega: {
		num: 678,
		species: "Meowstic-Mega",
		baseSpecies: "Meowstic",
		forme: "Mega",
		formeLetter: "M",
		types: ["Psychic"],
		baseStats: {hp: 74, atk: 48, def: 101, spa: 123, spd: 106, spe: 114},
		abilities: {0: "Psychic Surge"},
		heightm: 0.6,
		weightkg: 8.5,
		color: "Blue",
		eggGroups: ["Field"],
	},
	slurpuffmega: {
		num: 685,
		species: "Slurpuff-Mega",
		baseSpecies: "Slurpuff",
		forme: "Mega",
		formeLetter: "M",
		types: ["Fairy"],
		baseStats: {hp: 82, atk: 105, def: 81, spa: 150, spd: 105, spe: 57},
		abilities: {0: "Fluffy"},
		heightm: 0.8,
		weightkg: 5,
		color: "White",
		eggGroups: ["Fairy"],
	},
	dragalgemega: {
		num: 685,
		species: "Dragalge-Mega",
		baseSpecies: "Dragalge",
		forme: "Mega",
		formeLetter: "M",
		types: ["Poison", "Dragon"],
		baseStats: {hp: 65, atk: 85, def: 105, spa: 137, spd: 148, spe: 54},
		abilities: {0: "pH0"},
		heightm: 1.8,
		weightkg: 81.5,
		color: "Brown",
		eggGroups: ["Water 1", "Dragon"],
	},
	sylveonmega: {
		num: 700,
		species: "Sylveon-Mega",
		baseSpecies: "Sylveon",
		forme: "Mega",
		formeLetter: "M",
		types: ["Fairy"],
		baseStats: {hp: 95, atk: 135, def: 95, spa: 110, spd: 100, spe: 90},
		abilities: {0: "Ribbon Guard"},
		heightm: 1,
		weightkg: 23.5,
		color: "Pink",
		eggGroups: ["Field"],
	},
	goodramega : {
		num: 706,
		species: "Goodra-Mega",
		baseSpecies: "Goodra",
		forme: "Mega",
		formeLetter: "M", 
		types: ["Dragon"], 
		baseStats:{hp: 90, atk: 111, def: 89, spa: 133, spd: 177, spe: 100},
		abilities: {0: "Regenerator"}, 
		heightm: 2,
		weightkg: 150.5, 
	},
	klefkimega : {
		num: 707,
		species: "Klefki-Mega",
		baseSpecies: "Klefki",
		forme: "Mega",
		formeLetter: "M", 
		types: ["Steel", "Fairy"], 
		baseStats:{hp: 57, atk: 70, def: 120, spa: 113, spd: 120, spe: 90},
		abilities: {0: "Lightning Rod"}, 
		heightm: 2,
		weightkg: 3, 
	},
	avaluggmega : {
		num: 713,
		species: "Avalugg-Mega",
		baseSpecies: "Avalugg",
		forme: "Mega",
		formeLetter: "M", 
		types: ["Ice"], 
		baseStats:{hp: 95, atk: 150, def: 200, spa: 44, spd: 90, spe: 35},
		abilities: {0: "Filter"}, 
		heightm: 2,
		weightkg: 505, 
	},
	decidueyemega: {
		num: 724,
		species: "Decidueye-Mega",
		baseSpecies: "Decidueye",
		forme: "Mega",
		formeLetter: "M",
		types: ["Grass", "Ghost"],
		baseStats: {hp: 78, atk: 140, def: 75, spa: 137, spd: 100, spe: 100},
		abilities: {0: "Archer Of Legend"},
		heightm: 1.6,
		weightkg: 36.6,
		color: "Brown",
		eggGroups: ["Flying"],
	},
	incineroarmega: {
		num: 727,
		species: "Incineroar-Mega",
		baseSpecies: "Incineroar",
		forme: "Mega",
		formeLetter: "M",
		types: ["Fire", "Dark"],
		baseStats: {hp: 95, atk: 165, def: 120, spa: 70, spd: 100, spe: 80},
		abilities: {0: "Wrestler"},
		heightm: 1.8,
		weightkg: 83,
		color: "Red",
		eggGroups: ["Field"],
	},
	primarinamega: {
		num: 730,
		species: "Primarina-Mega",
		baseSpecies: "Primarina",
		forme: "Mega",
		formeLetter: "M",
		types: ["Water", "Fairy"],
		baseStats: {hp: 80, atk: 74, def: 94, spa: 156, spd: 126, spe: 100},
		abilities: {0: "Serene Grace"},
		heightm: 1.8,
		weightkg: 44,
		color: "Blue",
		eggGroups: ["Water 1", "Field"],
	},
	toucannonmega: {
		num: 733,
		species: "Toucannon-Mega",
		baseSpecies: "Toucannon",
		forme: "Mega",
		formeLetter: "M",
		types: ["Steel", "Flying"],
		baseStats: {hp: 80, atk: 140, def: 125, spa: 85, spd: 125, spe: 30},
		abilities: {0: "Iron Barbs"},
		heightm: 1.1,
		weightkg: 26,
		color: "Black",
		eggGroups: ["Flying"],
	},
	vikavoltmega: {
		num: 738,
		species: "Vikavolt-Mega",
		baseSpecies: "Vikavolt",
		forme: "Mega",
		formeLetter: "M",
		types: ["Bug", "Electric"],
		baseStats: {hp: 77, atk: 80, def: 80, spa: 152, spd: 65, spe: 146},
		abilities: {0: "Sheer Force"},
		heightm: 1.5,
		weightkg: 45,
		color: "Blue",
		eggGroups: ["Bug"],
	},
	crabominablemega : {
		num: 740,
		species: "Crabominable-Mega",
		baseSpecies: "Crabominable",
		forme: "Mega",
		formeLetter: "M", 
		types: ["Fighting", "Ice"], 
		baseStats:{hp: 97, atk: 172, def: 87, spa: 92, spd: 87, spe: 43},
		abilities: {0: "Iron Fist"}, 
		heightm: 1.7, 
		weightkg: 180, 
		color: "White",
		eggGroups: ["Water 3"],
	},
	araquanidmega: {
		num: 752,
		species: "Araquanid-Mega",
		baseSpecies: "Araquanid",
		forme: "Mega",
		formeLetter: "M",
		types: ["Water", "Bug"],
		baseStats: {hp: 68, atk: 90, def: 102, spa: 30, spd: 222, spe: 42},
		abilities: {0: "Bubble Guard"},
		heightm: 1.8,
		weightkg: 82,
		color: "Green",
		eggGroups: ["Water 1", "Bug"],
	},
	shiinoticmega: {
		num: 756,
		species: "Shiinotic-Mega",
		baseSpecies: "Shiinotic",
		forme: "Mega",
		formeLetter: "M",
		types: ["Grass", "Fairy"],
		baseStats: {hp: 60, atk: 50, def: 95, spa: 120, spd: 150, spe: 30},
		abilities: {0: "Prankster"},
		heightm: 1,
		weightkg: 11.5,
		color: "Purple",
		eggGroups: ["Grass"],
	},
	golisopodmega: {
		num: 784,
		species: "Golisopod-Mega",
		baseSpecies: "Golisopod",
		forme: "Mega",
		formeLetter: "M",
		types: ["Bug", "Water"],
		baseStats: {hp: 75, atk: 150, def: 180, spa: 60, spd: 125, spe: 40},
		abilities: {0: "Intimidate"},
		heightm: 2,
		weightkg: 108,
		color: "Gray",
		eggGroups: ["Bug", "Water 3"],
	},
	silvallymega: {
		num: 773,
		species: "Silvally-Mega",
		baseSpecies: "Silvally",
		forme: "Mega",
		formeLetter: "M",
		types: ["Normal"],
		baseStats: {hp: 95, atk: 115, def: 115, spa: 115, spd: 115, spe: 115},
		abilities: {0: "Protean"},
		heightm: 2.3,
		weightkg: 100.5,
		color: "Gray",
		eggGroups: ["Undiscovered"],
	},
	silvallyelectric: {
		num: 773,
		species: "Silvally-Electric",
		forme: "Electric",
		formeLetter: "E",
		types: ["Electric"],
		gender: "N",
		baseStats: {hp: 95, atk: 95, def: 95, spa: 95, spd: 95, spe: 95},
		abilities: {0: "RKS System"},
		heightm: 2.3,
		weightkg: 100.5,
		color: "Gray",
		prevo: "typenull",
		evoLevel: 2,
		eggGroups: ["Undiscovered"],
	},
	silvallyelectricmega: {
		num: 773,
		species: "Silvally-Electric-Mega",
		baseSpecies: "Silvally-Electric",
		forme: "Mega",
		formeLetter: "M",
		types: ["Electric"],
		baseStats: {hp: 95, atk: 95, def: 135, spa: 130, spd: 95, spe: 120},
		abilities: {0: "Magic Guard"},
		heightm: 2.3,
		weightkg: 100.5,
		color: "Gray",
		prevo: "typenull",
		evoLevel: 2,
		eggGroups: ["Undiscovered"],
	},
	silvallyfire: {
		num: 773,
		species: "Silvally-Fire",
		forme: "Fire",
		formeLetter: "F",
		types: ["Fire"],
		gender: "N",
		baseStats: {hp: 95, atk: 95, def: 95, spa: 95, spd: 95, spe: 95},
		abilities: {0: "RKS System"},
		heightm: 2.3,
		weightkg: 100.5,
		color: "Gray",
		prevo: "typenull",
		evoLevel: 2,
		eggGroups: ["Undiscovered"],
	},
	silvallyfiremega: {
		num: 773,
		species: "Silvally-Fire-Mega",
		baseSpecies: "Silvally-Fire",
		forme: "Mega",
		formeLetter: "M",
		types: ["Fire"],
		baseStats: {hp: 95, atk: 95, def: 145, spa: 115, spd: 110, spe: 110},
		abilities: {0: "Molten Shield"},
		heightm: 2.3,
		weightkg: 100.5,
		color: "Gray",
		prevo: "typenull",
		evoLevel: 2,
		eggGroups: ["Undiscovered"],
	},
	silvallygrass: {
		num: 773,
		species: "Silvally-Grass",
		forme: "Grass",
		formeLetter: "G",
		types: ["Grass"],
		gender: "N",
		baseStats: {hp: 95, atk: 95, def: 95, spa: 95, spd: 95, spe: 95},
		abilities: {0: "RKS System"},
		heightm: 2.3,
		weightkg: 100.5,
		color: "Gray",
		prevo: "typenull",
		evoLevel: 2,
		eggGroups: ["Undiscovered"],
	},
	silvallygrassmega: {
		num: 773,
		species: "Silvally-Grass-Mega",
		baseSpecies: "Silvally-Grass",
		forme: "Mega",
		formeLetter: "M",
		types: ["Grass"],
		baseStats: {hp: 95, atk: 100, def: 110, spa: 115, spd: 160, spe: 90},
		abilities: {0: "Unaware"},
		heightm: 2.3,
		weightkg: 100.5,
		color: "Gray",
		prevo: "typenull",
		evoLevel: 2,
		eggGroups: ["Undiscovered"],
	},
	silvallyice: {
		num: 773,
		species: "Silvally-Ice",
		forme: "Ice",
		formeLetter: "I",
		types: ["Ice"],
		gender: "N",
		baseStats: {hp: 95, atk: 95, def: 95, spa: 95, spd: 95, spe: 95},
		abilities: {0: "RKS System"},
		heightm: 2.3,
		weightkg: 100.5,
		color: "Gray",
		prevo: "typenull",
		evoLevel: 2,
		eggGroups: ["Undiscovered"],
	},
	silvallyicemega: {
		num: 773,
		species: "Silvally-Ice-Mega",
		baseSpecies: "Silvally-Ice",
		forme: "Mega",
		formeLetter: "M",
		types: ["Ice"],
		baseStats: {hp: 95, atk: 135, def: 105, spa: 135, spd: 105, spe: 95},
		abilities: {0: "Adaptability"},
		heightm: 2.3,
		weightkg: 100.5,
		color: "Gray",
		prevo: "typenull",
		evoLevel: 2,
		eggGroups: ["Undiscovered"],
	},
	silvallywater: {
		num: 773,
		species: "Silvally-Water",
		baseSpecies: "Silvally",
		forme: "Water",
		formeLetter: "W",
		types: ["Water"],
		gender: "N",
		baseStats: {hp: 95, atk: 95, def: 95, spa: 95, spd: 95, spe: 95},
		abilities: {0: "RKS System"},
		heightm: 2.3,
		weightkg: 100.5,
		color: "Gray",
		prevo: "typenull",
		evoLevel: 2,
		eggGroups: ["Undiscovered"],
	},
	silvallywatermega: {
		num: 773,
		species: "Silvally-Water-Mega",
		baseSpecies: "Silvally-Water",
		forme: "Mega",
		formeLetter: "M",
		types: ["Water"],
		baseStats: {hp: 95, atk: 125, def: 105, spa: 100, spd: 140, spe: 105},
		abilities: {0: "Drizzle"},
		heightm: 2.3,
		weightkg: 100.5,
		color: "Gray",
		prevo: "typenull",
		evoLevel: 2,
		eggGroups: ["Undiscovered"],
	},
	kommoomega: {
		num: 784,
		species: "Kommo-o-Mega",
		baseSpecies: "Kommo-o",
		forme: "Mega",
		formeLetter: "M",
		types: ["Dragon", "Fighting"],
		baseStats: {hp: 75, atk: 140, def: 145, spa: 120, spd: 115, spe: 105},
		abilities: {0: "No Guard"},
		heightm: 1.6,
		weightkg: 78.2,
		color: "Gray",
		eggGroups: ["Dragon"],
	},
	tapukokomega: {
		num: 785,
		species: "Tapu Koko-Mega",
		baseSpecies: "Tapu Koko",
		forme: "Mega",
		formeLetter: "M",
		types: ["Electric", "Fairy"],
		baseStats: {hp: 70, atk: 128, def: 95, spa: 107, spd: 85, spe: 185},
		abilities: {0: "Electric Efflux"},
		heightm: 1.8,
		weightkg: 20.5,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	tapulelemega: {
		num: 786,
		species: "Tapu Lele-Mega",
		baseSpecies: "Tapu Lele",
		forme: "Mega",
		formeLetter: "M",
		types: ["Psychic", "Fairy"],
		baseStats: {hp: 70, atk: 95, def: 85, spa: 185, spd: 128, spe: 107},
		abilities: {0: "Psychic Pour"},
		heightm: 1.2,
		weightkg: 18.6,
		color: "Pink",
		eggGroups: ["Undiscovered"],
	},
	tapubulumega: {
		num: 787,
		species: "Tapu Bulu-Mega",
		baseSpecies: "Tapu Bulu",
		forme: "Mega",
		formeLetter: "M",
		types: ["Grass", "Fairy"],
		baseStats: {hp: 70, atk: 185, def: 128, spa: 95, spd: 107, spe: 85},
		abilities: {0: "Grassy Gush"},
		heightm: 1.9,
		weightkg: 45.5,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	tapufinimega: {
		num: 788,
		species: "Tapu Fini-Mega",
		baseSpecies: "Tapu Fini",
		forme: "Mega",
		formeLetter: "M",
		types: ["Water", "Fairy"],
		baseStats: {hp: 70, atk: 85, def: 128, spa: 107, spd: 185, spe: 95},
		abilities: {0: "Misty Mount"},
		heightm: 1.3,
		weightkg: 21.2,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
	nihilegomega: {
		num: 793,
		species: "Nihilego-Mega",
		baseSpecies: "Nihilego",
		forme: "Mega",
		formeLetter: "M",
		types: ["Rock", "Poison"],
		baseStats: {hp: 109, atk: 53, def: 97, spa: 157, spd: 151, spe: 103},
		abilities: {0: "Levitate"},
		heightm: 1.2,
		weightkg: 55.5,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	buzzwolemega: {
		num: 794,
		species: "Buzzwole-Mega",
		baseSpecies: "Buzzwole",
		forme: "Mega",
		formeLetter: "M",
		types: ["Bug", "Fighting"],
		baseStats: {hp: 107, atk: 167, def: 167, spa: 67, spd: 73, spe: 89},
		abilities: {0: "Flex"},
		heightm: 2.4,
		weightkg: 333.6,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	pheromosamega: {
		num: 795,
		species: "Pheromosa-Mega",
		baseSpecies: "Pheromosa",
		forme: "Mega",
		formeLetter: "M",
		types: ["Bug", "Fighting"],
		baseStats: {hp: 71, atk: 157, def: 53, spa: 157, spd: 53, spe: 179},
		abilities: {0: "Disarming Pheromones"},
		heightm: 1.8,
		weightkg: 25,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	xurkitreemega: {
		num: 796,
		species: "Xurkitree-Mega",
		baseSpecies: "Xurkitree",
		forme: "Mega",
		formeLetter: "M",
		types: ["Electric", "Grass"],
		baseStats: {hp: 83, atk: 107, def: 127, spa: 193, spd: 107, spe: 53},
		abilities: {0: "Undergrow"},
		heightm: 3.8,
		weightkg: 100,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	celesteelamega: {
		num: 797,
		species: "Celesteela-Mega",
		baseSpecies: "Celesteela",
		forme: "Mega",
		formeLetter: "M",
		types: ["Steel", "Flying"],
		baseStats: {hp: 97, atk: 127, def: 127, spa: 127, spd: 113, spe: 79},
		abilities: {0: "Flare Boost"},
		heightm: 9.2,
		weightkg: 999.9,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	kartanamega: {
		num: 798,
		species: "Kartana-Mega",
		baseSpecies: "Kartana",
		forme: "Mega",
		formeLetter: "M",
		types: ["Grass", "Steel"],
		baseStats: {hp: 59, atk: 211, def: 181, spa: 47, spd: 71, spe: 101},
		abilities: {0: "Paper Cut"},
		heightm: 0.3,
		weightkg: 0.1,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	guzzlordmega: {
		num: 799,
		species: "Guzzlord-Mega",
		baseSpecies: "Guzzlord",
		forme: "Mega",
		formeLetter: "M",
		types: ["Dark", "Dragon"],
		baseStats: {hp: 223, atk: 171, def: 83, spa: 57, spd: 53, spe: 83},
		abilities: {0: "Adaptability"},
		heightm: 5.5,
		weightkg: 888,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	golurkmega : {
num: 623,
species: "Golurk-Mega",
baseSpecies: "Golurk",
forme: "Mega",
formeLetter: "M", 
types: ["Ground", "Fire"], 
baseStats:{hp: 89, atk: 149, def: 110, spa: 50, spd: 110, spe: 70},
abilities: {0: "Speed Boost"}, 
evoLevel: 1,
heightm: 2.8, 
weightkg: 330, 
},

cofagrigusmega : {
num: 563,
species: "Cofagrigus-Mega",
baseSpecies: "Cofagrigus",
forme: "Mega",
formeLetter: "M", 
types: ["Ghost"], 
baseStats:{hp: 58, atk: 70, def: 115, spa: 135, spd: 105, spe: 100},
abilities: {0: "Entomb"},
evoLevel: 1,
heightm: 76.5, 
weightkg: 76.5, 
},

sigilyphmega : {
num: 561,
species: "Sigilyph-Mega",
baseSpecies: "Sigilyph",
forme: "Mega",
formeLetter: "M", 
types: ["Psychic", "Flying"], 
baseStats:{hp: 72, atk: 58, def: 110, spa: 133, spd: 110, spe: 107},
abilities: {0: "Forsee"}, 
evoLevel: 1,
heightm: 1.4, 
weightkg: 14, 
},

samurottmega: {
num: 503, 
species: "Samurott-Mega", 
baseSpecies: "Samurott", 
forme: "Mega", 
formeLetter: "M", 
types:["Water"],
baseStats: {hp: 95, atk: 152, def: 105, spa: 76, spd: 105, spe: 95}, 
abilities: {0: "Supreme Samurai"}, 
weightkg: 94.6, 
evoLevel: 1,
},

serperiormega: {
num: 497, 
species: "Serperior-Mega", 
baseSpecies: "Serperior", 
forme: "Mega", 
formeLetter: "M", 
types:["Grass"],
baseStats: {hp: 75, atk: 125, def: 105, spa: 105, spd: 105, spe: 113}, 
abilities: {0: "Regal Reversal"}, 
weightkg: 63, 
evoLevel: 1,
},

emboarmega: {
num: 500, 
species: "Emboar-Mega", 
baseSpecies: "Emboar", 
forme: "Mega", 
formeLetter: "M", 
types:["Fire", "Fighting "],
baseStats: {hp: 110, atk: 154, def: 125, spa: 99, spd: 85, spe: 55}, 
abilities: {0: "Stamina"}, 
weightkg: 400, 
evoLevel: 1,
},

}
