export const Pokedex: {[k: string]: ModdedSpeciesData} = {
	dragalge: {
		inherit: true,
		num: 1,
		name: "Dragalge",
		types: ["Ghost", "Ice"],
		baseStats: {hp: 143, atk: 50, def: 117, spa: 59, spd: 73, spe: 68},
		abilities: {0: "Pressure", 1: "Prankster", H: "Unburden"},
	},
	rotomwash: {
		inherit: true,
		num: 2,
		name: "Rotom-Wash",
		types: ["Grass", "Dragon"],
		baseStats: {hp: 122, atk: 68, def: 86, spa: 84, spd: 97, spe: 43},
		abilities: {0: "Adaptability", 1: "Download", H: "Rivalry"},
	},
	pyroar: {
		inherit: true,
		num: 3,
		name: "Pyroar",
		types: ["Ghost", "Electric"],
		baseStats: {hp: 53, atk: 73, def: 104, spa: 119, spd: 116, spe: 36},
		abilities: {0: "Illuminate", 1: "Guts", H: "Clear Body"},
	},
	bronzong: {
		inherit: true,
		num: 4,
		name: "Bronzong",
		types: ["Steel"],
		baseStats: {hp: 105, atk: 109, def: 96, spa: 48, spd: 76, spe: 67},
		abilities: {0: "Sniper", 1: "Water Veil", H: "Rock Head"},
	},
	dragapult: {
		inherit: true,
		num: 5,
		name: "Dragapult",
		types: ["Dark"],
		baseStats: {hp: 94, atk: 77, def: 91, spa: 71, spd: 101, spe: 66},
		abilities: {0: "Shell Armor", 1: "Poison Point", H: "Sand Force"},
	},
	spheal: {
		inherit: true,
		num: 6,
		name: "Spheal",
		types: ["Fairy", "Steel"],
		baseStats: {hp: 55, atk: 112, def: 106, spa: 82, spd: 61, spe: 84},
		abilities: {0: "Grassy Surge", 1: "Iron Barbs", H: "Leaf Guard"},
	},
	octillery: {
		inherit: true,
		num: 7,
		name: "Octillery",
		types: ["Rock", "Ground"],
		baseStats: {hp: 45, atk: 105, def: 107, spa: 112, spd: 58, spe: 73},
		abilities: {0: "Guts", 1: "Inner Focus", H: "Download"},
	},
	stakataka: {
		inherit: true,
		num: 8,
		name: "Stakataka",
		types: ["Psychic"],
		baseStats: {hp: 94, atk: 87, def: 38, spa: 87, spd: 101, spe: 93},
		abilities: {0: "Cute Charm", 1: "Marvel Scale", H: "Blaze"},
	},
	ralts: {
		inherit: true,
		num: 9,
		name: "Ralts",
		types: ["Water", "Poison"],
		baseStats: {hp: 122, atk: 43, def: 104, spa: 58, spd: 124, spe: 48},
		abilities: {0: "Truant", 1: "Sap Sipper", H: "Harvest"},
	},
	corsola: {
		inherit: true,
		num: 10,
		name: "Corsola",
		types: ["Bug", "Ice"],
		baseStats: {hp: 92, atk: 52, def: 81, spa: 79, spd: 110, spe: 86},
		abilities: {0: "Compound Eyes", 1: "White Smoke", H: "Cloud Nine"},
	},
	exeggcute: {
		inherit: true,
		num: 11,
		name: "Exeggcute",
		types: ["Normal"],
		baseStats: {hp: 42, atk: 62, def: 88, spa: 134, spd: 93, spe: 81},
		abilities: {0: "Leaf Guard", 1: "Beast Boost", H: "Water Bubble"},
	},
	regice: {
		inherit: true,
		num: 12,
		name: "Regice",
		types: ["Fighting", "Grass"],
		baseStats: {hp: 49, atk: 114, def: 113, spa: 68, spd: 60, spe: 96},
		abilities: {0: "Limber", 1: "Blaze", H: "Regenerator"},
	},
	vivillon: {
		inherit: true,
		num: 13,
		name: "Vivillon",
		types: ["Electric", "Dragon"],
		baseStats: {hp: 41, atk: 86, def: 49, spa: 105, spd: 115, spe: 104},
		abilities: {0: "Pressure", 1: "Soul-Heart", H: "Moxie"},
	},
	zapdos: {
		inherit: true,
		num: 14,
		name: "Zapdos",
		types: ["Flying", "Fire"],
		baseStats: {hp: 85, atk: 127, def: 56, spa: 100, spd: 47, spe: 85},
		abilities: {0: "Poison Touch", 1: "Sand Rush", H: "Swift Swim"},
	},
	giratina: {
		inherit: true,
		num: 15,
		name: "Giratina",
		types: ["Ice", "Dark"],
		baseStats: {hp: 86, atk: 80, def: 100, spa: 47, spd: 86, spe: 100},
		abilities: {0: "Innards Out", 1: "Strong Jaw", H: "Shell Armor"},
	},
	ninjask: {
		inherit: true,
		num: 16,
		name: "Ninjask",
		types: ["Fairy", "Rock"],
		baseStats: {hp: 60, atk: 141, def: 116, spa: 76, spd: 53, spe: 54},
		abilities: {0: "Technician", 1: "Swarm", H: "Slush Rush"},
	},
	galvantula: {
		inherit: true,
		num: 17,
		name: "Galvantula",
		types: ["Ghost", "Steel"],
		baseStats: {hp: 53, atk: 105, def: 46, spa: 93, spd: 96, spe: 106},
		abilities: {0: "Rivalry", 1: "Thick Fat", H: "Hustle"},
	},
	gyarados: {
		inherit: true,
		num: 18,
		name: "Gyarados",
		types: ["Ice"],
		baseStats: {hp: 42, atk: 133, def: 49, spa: 89, spd: 97, spe: 90},
		abilities: {0: "Levitate", 1: "Levitate", H: "Bulletproof"},
	},
	lunala: {
		inherit: true,
		num: 19,
		name: "Lunala",
		types: ["Dark", "Normal"],
		baseStats: {hp: 75, atk: 120, def: 99, spa: 105, spd: 46, spe: 55},
		abilities: {0: "Unburden", 1: "Drought", H: "Neutralizing Gas"},
	},
	reuniclus: {
		inherit: true,
		num: 20,
		name: "Reuniclus",
		types: ["Electric", "Fire"],
		baseStats: {hp: 102, atk: 106, def: 47, spa: 58, spd: 97, spe: 90},
		abilities: {0: "Oblivious", 1: "Sap Sipper", H: "Flame Body"},
	},
	porygonz: {
		inherit: true,
		num: 21,
		name: "Porygon-Z",
		types: ["Water", "Ground"],
		baseStats: {hp: 67, atk: 74, def: 94, spa: 105, spd: 55, spe: 104},
		abilities: {0: "Keen Eye", 1: "Sheer Force", H: "Levitate"},
	},
	floette: {
		inherit: true,
		num: 22,
		name: "Floette",
		types: ["Fire", "Dragon"],
		baseStats: {hp: 123, atk: 59, def: 37, spa: 107, spd: 91, spe: 83},
		abilities: {0: "Sand Veil", 1: "Slow Start", H: "Pressure"},
	},
	karrablast: {
		inherit: true,
		num: 23,
		name: "Karrablast",
		types: ["Rock", "Grass"],
		baseStats: {hp: 55, atk: 107, def: 45, spa: 127, spd: 81, spe: 85},
		abilities: {0: "Friend Guard", 1: "Sticky Hold", H: "Analytic"},
	},
	vanilluxe: {
		inherit: true,
		num: 24,
		name: "Vanilluxe",
		types: ["Dragon"],
		baseStats: {hp: 44, atk: 108, def: 95, spa: 62, spd: 114, spe: 77},
		abilities: {0: "Unnerve", 1: "Contrary", H: "Oblivious"},
	},
};
