'use strict';

/**@type {{[k: string]: TemplateData}} */
let BattlePokedex = {
	pacaby: {
		num: 1,
		species: "Pacaby",
		abilities: {},
		types: ["Grass", "Ground"],
		baseStats: {hp: 65, atk: 50, def: 45, spa: 53, spd: 53, spe: 40},
	},
	thwaca: {
		num: 2,
		species: "Thwaca",
		abilities: {},
		types: ["Grass", "Ground"],
		baseStats: {hp: 82, atk: 65, def: 60, spa: 65, spd: 65, spe: 53},
	},
	alpalpaca: {
		num: 3,
		species: "Alpalpaca",
		abilities: {},
		types: ["Grass", "Ground"],
		baseStats: {hp: 102, atk: 85, def: 80, spa: 85, spd: 85, spe: 73},
	},
	salamad: {
		num: 4,
		species: "Salamad",
		abilities: {},
		types: ["Fire"],
		baseStats: {hp: 41, atk: 65, def: 41, spa: 52, spd: 52, spe: 50},
	},
	salamadder: {
		num: 5,
		species: "Salamadder",
		abilities: {},
		types: ["Fire", "Poison"],
		baseStats: {hp: 50, atk: 80, def: 50, spa: 77, spd: 77, spe: 68},
	},
	salamadness: {
		num: 6,
		species: "Salamadness",
		abilities: {},
		types: ["Fire", "Poison"],
		baseStats: {hp: 70, atk: 100, def: 70, spa: 97, spd: 97, spe: 88},
	},
	krokodola: {
		num: 7,
		species: "Krokodola",
		abilities: {},
		types: ["Water"],
		baseStats: {hp: 65, atk: 48, def: 44, spa: 50, spd: 50, spe: 43},
	},
	krokorak: {
		num: 8,
		species: "Krokorak",
		abilities: {},
		types: ["Water", "Ground"],
		baseStats: {hp: 80, atk: 55, def: 68, spa: 72, spd: 72, spe: 50},
	},
	krokonile: {
		num: 9,
		species: "Krokonile",
		abilities: {},
		types: ["Water", "Ground"],
		baseStats: {hp: 100, atk: 75, def: 88, spa: 92, spd: 92, spe: 70},
	},
	burroworm: {
		num: 10,
		species: "Burroworm",
		abilities: {},
		types: ["Bug", "Ground"],
		baseStats: {hp: 20, atk: 55, def: 20, spa: 25, spd: 25, spe: 55},
	},
	burrowant: {
		num: 11,
		species: "Burrowant",
		abilities: {},
		types: ["Bug", "Ground"],
		baseStats: {hp: 20, atk: 65, def: 35, spa: 20, spd: 20, spe: 40},
	},
	burrowasp: {
		num: 12,
		species: "Burrowasp",
		abilities: {},
		types: ["Bug", "Ground"],
		baseStats: {hp: 35, atk: 90, def: 45, spa: 35, spd: 35, spe: 90},
	},
	larvfly: {
		num: 13,
		species: "Larvfly",
		abilities: {},
		types: ["Bug"],
		baseStats: {hp: 30, atk: 45, def: 30, spa: 25, spd: 25, spe: 45},
	},
	pupfly: {
		num: 14,
		species: "Pupfly",
		abilities: {},
		types: ["Bug"],
		baseStats: {hp: 30, atk: 40, def: 50, spa: 30, spd: 30, spe: 30},
	},
	waspear: {
		num: 15,
		species: "Waspear",
		abilities: {},
		types: ["Bug", "Flying"],
		baseStats: {hp: 45, atk: 85, def: 40, spa: 60, spd: 60, spe: 75},
	},
	scratchling: {
		num: 16,
		species: "Scratchling",
		abilities: {},
		types: ["Normal", "Flying"],
		baseStats: {hp: 35, atk: 56, def: 45, spa: 25, spd: 25, spe: 55},
	},
	hawkarate: {
		num: 17,
		species: "Hawkarate",
		abilities: {},
		types: ["Fighting", "Flying"],
		baseStats: {hp: 60, atk: 76, def: 60, spa: 40, spd: 40, spe: 63},
	},
	falkick: {
		num: 18,
		species: "Falkick",
		abilities: {},
		types: ["Fighting", "Flying"],
		baseStats: {hp: 80, atk: 96, def: 70, spa: 60, spd: 60, spe: 93},
	},
	rodecto: {
		num: 19,
		species: "Rodecto",
		abilities: {},
		types: ["Normal"],
		baseStats: {hp: 28, atk: 60, def: 20, spa: 50, spd: 50, spe: 60},
	},
	micicle: {
		num: 20,
		species: "Micicle",
		abilities: {},
		types: ["Normal", "Ice"],
		baseStats: {hp: 40, atk: 105, def: 40, spa: 78, spd: 78, spe: 80},
	},
	symboo: {
		num: 21,
		species: "Symboo",
		abilities: {},
		types: ["Rock", "Ghost"],
		baseStats: {hp: 60, atk: 51, def: 50, spa: 45, spd: 45, spe: 25},
	},
	eeralith: {
		num: 22,
		species: "Eeralith",
		abilities: {},
		types: ["Rock", "Ghost"],
		baseStats: {hp: 105, atk: 80, def: 85, spa: 60, spd: 60, spe: 51},
	},
	chicanjoey: {
		num: 23,
		species: "Chicanjoey",
		abilities: {},
		types: ["Grass", "Ghost"],
		baseStats: {hp: 46, atk: 35, def: 54, spa: 64, spd: 64, spe: 35},
	},
	koalair: {
		num: 24,
		species: "Koalair",
		abilities: {},
		types: ["Grass", "Ghost"],
		baseStats: {hp: 71, atk: 55, def: 84, spa: 94, spd: 94, spe: 55},
	},
	squeakspark: {
		num: 25,
		species: "Squeakspark",
		abilities: {},
		types: ["Electric", "Normal"],
		baseStats: {hp: 30, atk: 55, def: 30, spa: 55, spd: 55, spe: 90},
	},
	voltchu: {
		num: 26,
		species: "Voltchu",
		abilities: {},
		types: ["Electric", "Normal"],
		baseStats: {hp: 50, atk: 90, def: 50, spa: 95, spd: 95, spe: 110},
	},
	shardvark: {
		num: 27,
		species: "Shardvark",
		abilities: {},
		types: ["Ice"],
		baseStats: {hp: 73, atk: 58, def: 58, spa: 58, spd: 58, spe: 33},
	},
	glaciadillo: {
		num: 28,
		species: "Glaciadillo",
		abilities: {},
		types: ["Ice", "Ground"],
		baseStats: {hp: 71, atk: 100, def: 79, spa: 100, spd: 100, spe: 55},
	},
	nobilith: {
		num: 29,
		species: "Nobilith",
		abilities: {},
		types: ["Rock"],
		baseStats: {hp: 67, atk: 31, def: 55, spa: 50, spd: 50, spe: 30},
	},
	prinstone: {
		num: 30,
		species: "Prinstone",
		abilities: {},
		types: ["Rock"],
		baseStats: {hp: 82, atk: 48, def: 70, spa: 65, spd: 65, spe: 45},
	},
	rokking: {
		num: 31,
		species: "Rokking",
		abilities: {},
		types: ["Rock"],
		baseStats: {hp: 102, atk: 68, def: 90, spa: 85, spd: 85, spe: 65},
	},
	shalady: {
		num: 32,
		species: "Shalady",
		abilities: {},
		types: ["Rock"],
		baseStats: {hp: 30, atk: 60, def: 35, spa: 45, spd: 45, spe: 65},
	},
	prinsestone: {
		num: 33,
		species: "Prinsestone",
		abilities: {},
		types: ["Rock"],
		baseStats: {hp: 45, atk: 75, def: 50, spa: 60, spd: 60, spe: 80},
	},
	rokween: {
		num: 34,
		species: "Rokween",
		abilities: {},
		types: ["Rock"],
		baseStats: {hp: 65, atk: 95, def: 70, spa: 80, spd: 80, spe: 100},
	},
	plunchker: {
		num: 35,
		species: "Plunchker",
		abilities: {},
		types: ["Electric", "Fighting"],
		baseStats: {hp: 66, atk: 70, def: 48, spa: 40, spd: 40, spe: 34},
	},
	shokittium: {
		num: 36,
		species: "Shokittium",
		abilities: {},
		types: ["Electric", "Fighting"],
		baseStats: {hp: 86, atk: 105, def: 68, spa: 75, spd: 75, spe: 49},
	},
	guppeas: {
		num: 37,
		species: "Guppeas",
		abilities: {},
		types: ["Grass", "Water"],
		baseStats: {hp: 40, atk: 29, def: 45, spa: 65, spd: 65, spe: 75},
	},
	filetuce: {
		num: 38,
		species: "Filetuce",
		abilities: {},
		types: ["Grass", "Water"],
		baseStats: {hp: 75, atk: 64, def: 70, spa: 105, spd: 105, spe: 110},
	},
	biye: {
		num: 39,
		species: "Biye",
		abilities: {},
		types: ["Psychic", "Flying"],
		baseStats: {hp: 25, atk: 15, def: 15, spa: 100, spd: 100, spe: 70},
	},
	triye: {
		num: 40,
		species: "Triye",
		abilities: {},
		types: ["Psychic", "Flying"],
		baseStats: {hp: 45, atk: 35, def: 45, spa: 120, spd: 120, spe: 80},
	},
	venuson: {
		num: 41,
		species: "Venuson",
		abilities: {},
		types: ["Normal"],
		baseStats: {hp: 30, atk: 40, def: 25, spa: 60, spd: 60, spe: 65},
	},
	marspian: {
		num: 42,
		species: "Marspian",
		abilities: {},
		types: ["Normal"],
		baseStats: {hp: 70, atk: 75, def: 60, spa: 85, spd: 85, spe: 100},
	},
	fudgie: {
		num: 43,
		species: "Fudgie",
		abilities: {},
		types: ["Poison"],
		baseStats: {hp: 40, atk: 85, def: 30, spa: 50, spd: 50, spe: 50},
	},
	fudgier: {
		num: 44,
		species: "Fudgier",
		abilities: {},
		types: ["Poison"],
		baseStats: {hp: 50, atk: 95, def: 40, spa: 60, spd: 60, spe: 75},
	},
	hotfudgie: {
		num: 45,
		species: "Hotfudgie",
		abilities: {},
		types: ["Poison", "Fire"],
		baseStats: {hp: 70, atk: 110, def: 50, spa: 70, spd: 70, spe: 90},
	},
	mosstone: {
		num: 46,
		species: "Mosstone",
		abilities: {},
		types: ["Rock", "Grass"],
		baseStats: {hp: 45, atk: 40, def: 85, spa: 55, spd: 55, spe: 15},
	},
	lichenrok: {
		num: 47,
		species: "Lichenrok",
		abilities: {},
		types: ["Rock", "Grass"],
		baseStats: {hp: 75, atk: 50, def: 85, spa: 105, spd: 105, spe: 20},
	},
	leafrikson: {
		num: 48,
		species: "Leafrikson",
		abilities: {},
		types: ["Fighting", "Grass"],
		baseStats: {hp: 40, atk: 85, def: 60, spa: 40, spd: 40, spe: 120},
	},
	valkyre: {
		num: 49,
		species: "Valkyre",
		abilities: {},
		types: ["Fighting", "Ice"],
		baseStats: {hp: 80, atk: 70, def: 40, spa: 105, spd: 105, spe: 50},
	},
	jumparoo: {
		num: 50,
		species: "Jumparoo",
		abilities: {},
		types: ["Fighting"],
		baseStats: {hp: 55, atk: 40, def: 40, spa: 20, spd: 20, spe: 30},
	},
	puncharoo: {
		num: 51,
		species: "Puncharoo",
		abilities: {},
		types: ["Fighting"],
		baseStats: {hp: 95, atk: 125, def: 95, spa: 90, spd: 90, spe: 75},
	},
	azurolt: {
		num: 52,
		species: "Azurolt",
		abilities: {},
		types: ["Rock", "Electric"],
		baseStats: {hp: 90, atk: 105, def: 110, spa: 105, spd: 105, spe: 90},
	},
};
exports.BattlePokedex = BattlePokedex;
