'use strict';

exports.BattlePokedex = {
	inteleon: {
		inherit: true,
		species: "Inteleon",
		types: ["Water", "Normal"],
		baseStats: {hp: 70, atk: 75, def: 75, spa: 125, spd: 85, spe: 120},
		abilities: {0: "Torrent", 1: "Infiltrator"},
	},
	falinks: {
		inherit: true,
		species: "Falinks",
		types: ["Fighting", "Ground"],
		baseStats: {hp: 65, atk: 110, def: 110, spa: 70, spd: 60, spe: 95},
		abilities: {0: "Skill Link", 1: "Defiant", H: "Technician"},
	},
	cramorant: {
		inherit: true,
		species: "Cramorant",
		types: ["Flying", "Water"],
		baseStats: {hp: 115, atk: 85, def: 75, spa: 85, spd: 95, spe: 80},
		abilities: {0: "Gulp Missile"},
	},
	eiscue: {
		inherit: true,
		species: "Eiscue",
		types: ["Ice", "Water"],
		baseStats: {hp: 95, atk: 80, def: 120, spa: 65, spd: 110, spe: 50},
		abilities: {0: "Ice Face"},
	},
	eiscuenoice: {
		inherit: true,
		species: "Eiscue-Noice",
		types: ["Ice", "Water"],
		baseStats: {hp: 95, atk: 90, def: 70, spa: 85, spd: 50, spe: 130},
		abilities: {0: "Swift Swim"},
	},
	perrserker: {
		inherit: true,
		species: "Perrserker",
		types: ["Steel"],
		baseStats: {hp: 90, atk: 110, def: 120, spa: 50, spd: 80, spe: 80},
		abilities: {0: "Battle Armor", 1: "Tough Claws", H: "Steely Spirit"},
	},
	mrrime: {
		inherit: true,
		species: "Mr Rime",
		types: ["Ice", "Psychic"],
		baseStats: {hp: 90, atk: 75, def: 95, spa: 110, spd: 120, spe: 70},
		abilities: {0: "Tangled Feet", 1: "Screen Cleaner", H: "Unaware"},
	},
	cursola: {
		inherit: true,
		species: "Cursola",
		types: ["Ghost", "Rock"],
		baseStats: {hp: 100, atk: 75, def: 100, spa: 105, spd: 120, spe: 30},
		abilities: {0: "Regenerator", 1: "Perish Body"},
	},
	rapidashgalar: {
		inherit: true,
		species: "Rapidash-Galar",
		types: ["Psychic", "Fairy"],
		baseStats: {hp: 85, atk: 80, def: 70, spa: 100, spd: 80, spe: 105},
		abilities: {0: "Pastel Veil", 1: "Misty Surge", H: "Psychic Surge"},
	},
	weezinggalar: {
		inherit: true,
		species: "Weezing-Galar",
		types: ["Poison", "Fairy"],
		baseStats: {hp: 75, atk: 85, def: 120, spa: 90, spd: 80, spe: 60},
		abilities: {0: "Levitate", 1: "Neutralising Gas", H: "Misty Surge"},
	},
	stunfiskgalar: {
		inherit: true,
		species: "Stunfisk-Galar",
		types: ["Ground", "Steel"],
		baseStats: {hp: 119, atk: 91, def: 99, spa: 66, spd: 84, spe: 32},
		abilities: {0: "Mimicry", 1: "Water Absorb"},
	},
	boltund: {
		inherit: true,
		species: "Boltund",
		types: ["Electric", "Normal"],
		baseStats: {hp: 89, atk: 110, def: 60, spa: 110, spd: 60, spe: 121},
		abilities: {0: "Strong Jaw", 1: "Scrappy"},
	},
	eldegoss: {
		inherit: true,
		species: "Eldegoss",
		types: ["Grass"],
		baseStats: {hp: 90, atk: 50, def: 90, spa: 100, spd: 120, spe: 60},
		abilities: {0: "Cotton Down", 1: "Regenerator", H: "Fluffy"},
	},
	greedent: {
		inherit: true,
		species: "Greedent",
		types: ["Normal"],
		baseStats: {hp: 160, atk: 105, def: 105, spa: 55, spd: 75, spe: 20},
		abilities: {0: "Cheek Pouch", 1: "Ripen", H: "Sticky Hold"},
	},
	thievul: {
		inherit: true,
		species: "Thievul",
		types: ["Dark", "Ground"],
		baseStats: {hp: 90, atk: 58, def: 78, spa: 107, spd: 92, spe: 95},
		abilities: {0: "Unburden", 1: "Sheer Force", H: "Stakeout"},
	},
	grapploct: {
		inherit: true,
		species: "Grapploct",
		types: ["Fighting", "Water"],
		baseStats: {hp: 115, atk: 118, def: 90, spa: 70, spd: 80, spe: 42},
		abilities: {0: "Technician", 1: "Poison Heal"},
	},
	coalossal: {
		inherit: true,
		species: "Coalossal",
		types: ["Rock", "Fire"],
		baseStats: {hp: 110, atk: 100, def: 130, spa: 80, spd: 100, spe: 30},
		abilities: {0: "Steam Engine", 1: "Flame Body", H: "Flash Fire"},
	},
	sandaconda: {
		inherit: true,
		species: "Sandaconda",
		types: ["Ground", "Dragon"],
		baseStats: {hp: 82, atk: 107, def: 125, spa: 65, spd: 90, spe: 75},
		abilities: {0: "Shed Skin", 1: "Sand Spit", H: "Sand Force"},
	},
	flapple: {
		inherit: true,
		species: "Flapple",
		types: ["Grass", "Dragon"],
		baseStats: {hp: 75, atk: 110, def: 90, spa: 95, spd: 80, spe: 100},
		abilities: {0: "Ripen", 1: "Gluttony", H: "Hustle"},
	},
	appletun: {
		inherit: true,
		species: "Appletun",
		types: ["Grass", "Dragon"],
		baseStats: {hp: 120, atk: 85, def: 90, spa: 110, spd: 85, spe: 45},
		abilities: {0: "Ripen", 1: "Gluttony", H: "Thick Fat"},
	},
	magmortar: {
		inherit: true,
		species: "Magmortar",
		types: ["Fire", "Fighting"],
		baseStats: {hp: 75, atk: 95, def: 67, spa: 125, spd: 95, spe: 83},
		abilities: {0: "Flame Body", 1: "Sheer Force"},
	},
	electivire: {
		inherit: true,
		species: "Electivire",
		types: ["Electric", "Fighting"],
		baseStats: {hp: 75, atk: 123, def: 87, spa: 105, spd: 85, spe: 95},
		abilities: {0: "Motor Drive", 1: "Vital Spirit", H: "Sheer Force"},
	},
	yanmega: {
		inherit: true,
		species: "Yanmega",
		types: ["Bug", "Dragon"],
		baseStats: {hp: 96, atk: 76, def: 86, spa: 116, spd: 56, spe: 95},
		abilities: {0: "Speed Boost", 1: "Tinted Lens", H: "Frisk"},
	},
	dusknoir: {
		inherit: true,
		species: "Dusknoir",
		types: ["Ghost", "Dark"],
		baseStats: {hp: 80, atk: 135, def: 100, spa: 65, spd: 100, spe: 65},
		abilities: {0: "Pressure", 1: "Iron Fist"},
	},
	xatu: {
		inherit: true,
		species: "Xatu",
		types: ["Psychic", "Flying"],
		baseStats: {hp: 90, atk: 70, def: 90, spa: 115, spd: 90, spe: 75},
		abilities: {0: "Synchronise", 1: "Early Bird", H: "Magic Bounce"},
	},
	sudowoodo: {
		inherit: true,
		species: "Sudowoodo",
		types: ["Rock", "Grass"],
		baseStats: {hp: 80, atk: 125, def: 125, spa: 50, spd: 80, spe: 50},
		abilities: {0: "Sturdy", 1: "Rock Head", H: "Rattled"},
	},
	oranguru: {
		inherit: true,
		species: "Oranguru",
		types: ["Normal", "Psychic"],
		baseStats: {hp: 90, atk: 60, def: 90, spa: 110, spd: 110, spe: 50},
		abilities: {0: "Oblivious", 1: "Telepathy", H: "Sheer Force"},
	},
	bellossom: {
		inherit: true,
		species: "Bellossom",
		types: ["Grass"],
		baseStats: {hp: 75, atk: 60, def: 95, spa: 100, spd: 100, spe: 100},
		abilities: {0: "Dancer", 1: "Own Tempo", H: "Triage"},
	},
	garbodor: {
		inherit: true,
		species: "Garbodor",
		types: ["Poison", "Steel"],
		baseStats: {hp: 100, atk: 60, def: 102, spa: 95, spd: 102, spe: 55},
		abilities: {0: "Stench", 1: "Corrosion", H: "Aftermath"},
	},
	druddigon: {
		inherit: true,
		species: "Druddigon",
		types: ["Dragon", "Steel"],
		baseStats: {hp: 77, atk: 130, def: 120, spa: 60, spd: 90, spe: 68},
		abilities: {0: "Mold Breaker", 1: "Rough Skin", H: "Sheer Force"},
	},
	flygon: {
		inherit: true,
		species: "Flygon",
		types: ["Ground", "Dragon"],
		baseStats: {hp: 100, atk: 70, def: 90, spa: 115, spd: 90, spe: 100},
		abilities: {0: "Levitate", 1: "Adaptability", H: "Beserk"},
	},
};