'use strict';

exports.BattlePokedex = {
	butterfree: {
		num: 12,
		species: "Butterfree",
		types: ["Bug", "Psychic"],
		baseStats: {hp: 100, atk: 47, def: 100, spa: 130, spd: 80, spe: 123},
		abilities: {0: "Compound Eyes", 1: "Tinted Lens", H: "Psychic Surge"},
		height: 1.1,
		weightkg: 32,
		prevo: "metapod",
		eggGroups: ["Bug"],
	},
	cherrim: {
		num: 421,
		species: "Cherrim",
		types: ["Grass", "Dark"],
		baseStats: {hp: 100, atk: 85, def: 130, spa: 70, spd: 115, spe: 100},
		abilities: {0: "Flower Gift"},
		height: 0.5,
		weightkg: 9.3,
		prevo: "cherubi",
		eggGroups: ["Fairy", "Grass"],
	},
	cherrimsunshine: {
		num: 421,
		species: "Cherrim-Sunshine",
		types: ["Grass", "Fire"],
		baseStats: {hp: 100, atk: 100, def: 70, spa: 115, spd: 85, spe: 130},
		abilities: {0: "Flower Gift"},
		height: 0.5,
		weightkg: 9.3,
		prevo: "cherubi",
		eggGroups: ["Fairy", "Grass"],
	},
	delibird: {
		num: 225,
		species: "Delibird",
		types: ["Ice", "Steel"],
		baseStats: {hp: 143, atk: 60, def: 132, spa: 66, spd: 121, spe: 77},
		abilities: {0: "Flash Fire", 1: "Snow Warning", H: "Filter"},
		height: 0.9,
		weightkg: 16,
		eggGroups: ["Water1", "Field"],
	},
	drifblim: {
		num: 426,
		species: "Drifblim",
		types: ["Ghost", "Flying"],
		baseStats: {hp: 150, atk: 80, def: 86, spa: 120, spd: 64, spe: 100},
		abilities: {0: "Aftermath", 1: "Speed Boost", H: "Flare Boost"},
		height: 1.2,
		weightkg: 15,
		prevo: "drifloon",
		eggGroups: ["Amorphous"],
	},
	farfetchd: {
		num: 83,
		species: "Farfetch'd",
		types: ["Fighting", "Flying"],
		baseStats: {hp: 72, atk: 135, def: 105, spa: 63, spd: 90, spe: 105},
		abilities: {0: "Super Luck", 1: "Sniper", H: "Aerilate"},
		height: 0.8,
		weightkg: 15,
		eggGroups: ["Flying", "Field"],
	},
	gogoat: {
		num: 673,
		species: "Gogoat",
		types: ["Grass"],
		baseStats: {hp: 123, atk: 100, def: 86, spa: 97, spd: 81, spe: 68},
		abilities: {0: "Sap Sipper", 1: "Thick Fat"},
		height: 1.7,
		weightkg: 91,
		prevo: "skiddo",
		eggGroups: ["Field"],
	},
	golem: {
		num: 76,
		species: "Golem",
		types: ["Rock", "Ground"],
		baseStats: {hp: 95, atk: 140, def: 90, spa: 65, spd: 115, spe: 95},
		abilities: {0: "Sand Stream", 1: "Sand Rush", H: "Technician"},
		height: 1.4,
		weightkg: 300,
		prevo: "graveler",
		eggGroups: ["Mineral"],
	},
	heatmor: {
		num: 631,
		species: "Heatmor",
		types: ["Fire", "Dark"],
		baseStats: {hp: 85, atk: 137, def: 69, spa: 135, spd: 69, spe: 105},
		abilities: {0: "Gluttony", 1: "Flash Fire", H: "Tough Claws"},
		height: 1.4,
		weightkg: 58,
		eggGroups: ["Field"],
	},
	huntail: {
		num: 367,
		species: "Huntail",
		types: ["Water"],
		baseStats: {hp: 85, atk: 114, def: 105, spa: 104, spd: 75, spe: 67},
		abilities: {0: "Swift Swim", 1: "Protean", H: "Water Veil"},
		height: 1.7,
		weightkg: 27,
		prevo: "clamperl",
		eggGroups: ["Water1"],
	},
	kecleon: {
		num: 352,
		species: "Kecleon",
		types: ["Normal", "Ghost"],
		baseStats: {hp: 80, atk: 100, def: 85, spa: 100, spd: 120, spe: 85},
		abilities: {0: "Color Change", 1: "Protean"},
		height: 1,
		weightkg: 22,
		eggGroups: ["Field"],
	},
	
	lunatone: {
		num: 337,
		species: "Lunatone",
		types: ["Dark", "Fairy"],
		gender: "N",
		baseStats: {hp: 105, atk: 60, def: 105, spa: 105, spd: 105, spe: 100},
		abilities: {0: "Misty Surge", 1: "Solid Rock", H: "Gravitate"},
		height: 1,
		weightkg: 168,
		eggGroups: ["Mineral"],
	},
	luvdisc: {
		num: 370,
		species: "Luvdisc",
		types: ["Water", "Fairy"],
		baseStats: {hp: 103, atk: 60, def: 85, spa: 90, spd: 95, spe: 107},
		abilities: {0: "Hydration", 1: "Marvel Scale", H: "Multiscale"},
		height: 0.6,
		weightkg: 8.7,
		eggGroups: ["Water2"],
	},
	maractus: {
		num: 556,
		species: "Maractus",
		types: ["Grass"],
		baseStats: {hp: 97, atk: 100, def: 92, spa: 105, spd: 127, spe: 70},
		abilities: {0: "Harvest", 1: "Chlorophyll", H: "Storm Drain"},
		height: 1,
		weightkg: 28,
		eggGroups: ["Grass"],
	},
	mrmime: {
		num: 122,
		species: "Mr. Mime",
		types: ["Psychic", "Fairy"],
		baseStats: {hp: 130, atk: 60, def: 115, spa: 115, spd: 110, spe: 110},
		abilities: {0: "Magic Bounce", 1: "Soundproof", H: "Wonderous"},
		heightm: 1.3,
		weightkg: 54.5,
		color: "Pink",
		prevo: "mimejr",
		evoType: "levelMove",
		evoMove: "Mimic",
		eggGroups: ["Human-Like"],
		canHatch: true,
	},
	pachirisu: {
		num: 417,
		species: "Pachirisu",
		types: ["Electric"],
		baseStats: {hp: 100, atk: 45, def: 90, spa: 115, spd: 120, spe: 130},
		abilities: {0: "Volt Absorb", 1: "Adaptability", H: "Motor Drive"},
		heightm: 0.4,
		weightkg: 3.9,
		color: "White",
		eggGroups: ["Field", "Fairy"],
	},
	persian: {
		num: 53,
		species: "Persian",
		types: ["Normal", "Ghost"],
		baseStats: {hp: 69, atk: 129, def: 69, spa: 129, spd: 69, spe: 139},
		abilities: {0: "Limber", 1: "Technician", H: "Sheer Force"},
		height: 1,
		weightkg: 32,
		prevo: "meowth",
		eggGroups: ["Field"],
	},
	rampardos: {
		num: 409,
		species: "Rampardos",
		types: ["Rock", "Fighting"],
		baseStats: {hp: 96, atk: 150, def: 92, spa: 60, spd: 79, spe: 93},
		abilities: {0: "Mold Breaker", 1: "Rock Head", H: "Iron Fist"},
		height: 1.6,
		weightkg: 102.5,
		prevo: "cranidos",
		eggGroups: ["Monster"],
	},
	rapidash: {
		num: 78,
		species: "Rapidash",
		types: ["Fire", "Fairy"],
		baseStats: {hp: 95, atk: 100, def: 70, spa: 90, spd: 80, spe: 135},
		abilities: {0: "Flash Fire", 1: "Pixilate", H: "Hard Hooves"},
		height: 1.7,
		weightkg: 95,
		prevo: "ponyta",
		eggGroups: ["Field"],
	},
	relicanth: {
		num: 369,
		species: "Relicanth",
		types: ["Water", "Rock"],
		baseStats: {hp: 130, atk: 90, def: 110, spa: 100, spd: 100, spe: 70},
		abilities: {0: "Rock Head"},
		height: 1,
		weightkg: 23.4,
		eggGroups: ["Water1", "Water2"],
	},
	simisage: {
		num: 512,
		species: "Simisage",
		types: ["Grass", "Fighting"],
		baseStats: {hp: 70, atk: 140, def: 70, spa: 120, spd: 70, spe: 130},
		abilities: {0: "Adaptability", 1: "Sheer Force", H: "No Guard"},
		height: 1.1,
		weightkg: 30.5,
		prevo: "pansage",
		eggGroups: ["Field"],
	},
	solrock: {
		num: 338,
		species: "Solrock",
		types: ["Rock", "Fairy"],
		gender: "N",
		baseStats: {hp: 95, atk: 105, def: 130, spa: 95, spd: 105, spe: 70},
		abilities: {0: "Levitate"},
		height: 1.2,
		weightkg: 154,
		eggGroups: ["Mineral"],
	},
	swalot: {
		num: 317,
		species: "Swalot",
		types: ["Poison", "Normal"],
		baseStats: {hp: 130, atk: 123, def: 115, spa: 103, spd: 115, spe: 74},
		abilities: {0: "Regenerator", 1: "Gluttony", H: "Guts"},
		height: 1.7,
		weightkg: 80,
		prevo: "gulpin",
		eggGroups: ["Amorphous"],
	},
	swanna: {
		num: 581,
		species: "Swanna",
		types: ["Water", "Flying"],
		baseStats: {hp: 115, atk: 137, def: 73, spa: 137, spd: 73, spe: 118},
		abilities: {0: "Delta Stream"},
		height: 1.3,
		weightkg: 24.2,
		prevo: "ducklett",
		eggGroups: ["Water1", "Flying"],
	},
	wailord: {
		num: 321,
		species: "Wailord",
		types: ["Water", "Flying"],
		baseStats: {hp: 255, atk: 105, def: 65, spa: 105, spd: 35, spe: 35},
		abilities: {0: "Thick Fat", 1: "Drizzle", H: "Delta Stream"},
		height: 14.5,
		weightkg: 398,
		prevo: "wailmer",
		eggGroups: ["Field", "Water2"],
	},
	wigglytuff: {
		num: 40,
		species: "Wigglytuff",
		types: ["Normal", "Fairy"],
		baseStats: {hp: 150, atk: 80, def: 85, spa: 105, spd: 90, spe: 60},
		abilities: {0: "Thick Fat", 1: "Competitive", H: "Magic Bounce"},
		height: 1,
		weightkg: 12,
		prevo: "jigglypuff",
		eggGroups: ["Fairy"],
	},
	ariados: {
		num: 168,
		species: "Ariados",
		types: ["Bug", "Dark"],
		baseStats: {hp: 74, atk: 110, def: 80, spa: 60, spd: 80, spe: 126},
		abilities: {0: "Compound Eyes", 1: "Intimidate", H: "Arachnophobia"},
		height: 1.1,
		weightkg: 33.5,
		prevo: "spinarak",
		eggGroups: ["Bug"],
	},
	electivire: {
		num: 466,
		species: "Electivire",
		types: ["Electric", "Fighting"],
		baseStats: {hp: 85, atk: 123, def: 77, spa: 105, spd: 95, spe: 115},
		abilities: {0: "Motor Drive", 1: "No Guard", H: "Sheer Force"},
		height: 1.8,
		weightkg: 138.6,
		prevo: "electabuzz",
		eggGroups: ["Human-Like"],
	},
	regice: {
		num: 378,
		species: "Regice",
		types: ["Ice"],
		gender: "N",
		baseStats: {hp: 100, atk: 60, def: 70, spa: 100, spd: 200, spe: 70},
		abilities: {0: "Levitate", 1: "Heatproof", H: "Everfrost"},
		height: 1.8,
		weightkg: 175,
		eggGroups: ["Undiscovered"],
	},
	watchog: {
		num: 505,
		species: "Watchog",
		types: ["Normal", "Dark"],
		baseStats: {hp: 60, atk: 91, def: 75, spa: 130, spd: 70, spe: 124},
		abilities: {0: "Mold Breaker", 1: "Dark Aura"},
		height: 1.1,
		weightkg: 27,
		prevo: "patrat",
		eggGroups: ["Field"],
	},
	avalugg: {
		num: 713,
		species: "Avalugg",
		types: ["Ice", "Water"],
		baseStats: {hp: 101, atk: 117, def: 195, spa: 60, spd: 85, spe: 42},
		abilities: {0: "Storm Drain", 1: "Filter", H: "Refrigerate"},
		height: 2,
		weightkg: 505,
		prevo: "bergmite",
		eggGroups: ["Monster"],
	},
	unfezant: {
		num: 521,
		species: "Unfezant",
		types: ["Flying", "Fighting"],
		baseStats: {hp: 95, atk: 130, def: 95, spa: 60, spd: 95, spe: 95},
		abilities: {0: "Stamina", 1: "Gale Wings", H: "Flight Risk"},
		height: 1.2,
		weightkg: 29,
		prevo: "tranquill",
		eggGroups: ["Flying"],
	},
	bouffalant: {
		num: 626,
		species: "Bouffalant",
		types: ["Normal"],
		baseStats: {hp: 105, atk: 160, def: 110, spa: 60, spd: 95, spe: 70},
		abilities: {0: "Adaptability", 1: "Sheer Force", H: "Impact Absorber"},
		height: 1.6,
		weightkg: 94.6,
		eggGroups: ["Field"],
	},
	bibarel: {
		num: 400,
		species: "Bibarel",
		types: ["Normal", "Water"],
		baseStats: {hp: 99, atk: 105, def: 80, spa: 65, spd: 80, spe: 91},
		abilities: {0: "Simple", 1: "Unaware", H: "Tough Claws"},
		height: 1,
		weightkg: 31.5,
		prevo: "bidoof",
		eggGroups: ["Water1", "Field"],
	},
	muk: {
		num: 89,
		species: "Muk",
		types: ["Poison"],
		baseStats: {hp: 105, atk: 105, def: 105, spa: 65, spd: 100, spe: 50},
		abilities: {0: "Stench", 1: "Poison Touch", H: "Unaware"},
		height: 1.2,
		weightkg: 30,
		prevo: "grimer",
		eggGroups: ["Amorphous"],
	},
	lapras: {
		num: 131,
		species: "Lapras",
		types: ["Water", "Ice"],
		baseStats: {hp: 120, atk: 120, def: 80, spa: 120, spd: 80, spe: 80},
		abilities: {0: "Shell Armor", 1: "Water Absorb", H: "Drizzle"},
		height: 2.5,
		weightkg: 220,
		eggGroups: ["Monster", "Water1"],
	},
	ledian: {
		num: 166,
		species: "Ledian",
		types: ["Bug", "Fighting"],
		baseStats: {hp: 65, atk: 105, def: 95, spa: 70, spd: 135, spe: 115},
		abilities: {0: "Swarm", 1: "Prankster", H: "Huge Power"},
		height: 1.4,
		weightkg: 35.6,
		prevo: "ledyba",
		eggGroups: ["Bug"],
	},
	sunflora: {
		num: 192,
		species: "Sunflora",
		types: ["Grass", "Electric"],
		baseStats: {hp: 80, atk: 60, def: 100, spa: 150, spd: 110, spe: 100},
		abilities: {0: "Drought", 1: "Solar Power", H: "Early Bird"},
		height: 0.8,
		weightkg: 8.5,
		prevo: "sunkern",
		eggGroups: ["Grass"],
	},
	stunfisk: {
		num: 618,
		species: "Stunfisk",
		types: ["Ground", "Electric"],
		baseStats: {hp: 105, atk: 70, def: 105, spa: 110, spd: 105, spe: 40},
		abilities: {0: "Sand Stream", 1: "Storm Drain", H: " Tough Hide"},
		height: 0.7,
		weightkg: 11,
		eggGroups: ["Water1", "Amorphous"],
	},
	zebstrika: {
		num: 523,
		species: "Zebstrika",
		types: ["Electric", "Fire"],
		baseStats: {hp: 74, atk: 113, def: 68, spa: 100, spd: 68, spe: 132},
		abilities: {0: "Reckless", 1: "Magic Guard", H: "Sap Sipper"},
		height: 1.6,
		weightkg: 79.5,
		prevo: "blitzle",
		eggGroups: ["Field"],
	},
	regigigas: {
		num: 486,
		species: "Regigigas",
		types: ["Normal"],
		gender: "N",
		baseStats: {hp: 110, atk: 160, def: 110, spa: 80, spd: 110, spe: 100},
		abilities: {0: "Slow Start"},
		height: 3.7,
		weightkg: 420,
		eggGroups: ["Undiscovered"],
	},
	granbull: {
		num: 210,
		species: "Granbull",
		types: ["Fairy", "Ground"],
		baseStats: {hp: 110, atk: 140, def: 100, spa: 60, spd: 90, spe: 90},
		abilities: {0: "Intimidate", 1: "Quick Feet", H: "Rattled"},
		height: 1.4,
		weightkg: 48.7,
		prevo: "snubbull",
		eggGroups: ["Field", "Fairy"],
	},
	corsola: {
		num: 222,
		species: "Corsola",
		types: ["Water", "Rock"],
		baseStats: {hp: 105, atk: 69, def: 110, spa: 105, spd: 110, spe: 101},
		abilities: {0: "Protean", 1: "Mega Launcher", H: "Foam Bath"},
		height: 0.6,
		weightkg: 5,
		eggGroups: ["Water1", "Water3"],
	},
	dusknoir: {
		num: 477,
		species: "Dusknoir",
		types: ["Ghost", "Dark"],
		baseStats: {hp: 90, atk: 120, def: 135, spa: 75, spd: 135, spe: 45},
		abilities: {0: "Levitate", 1: "Combative", H: "Frisk"},
		height: 2.2,
		weightkg: 106.6,
		prevo: "dusclops",
		eggGroups: ["Amorphous"],
	},
	ursaring: {
		num: 217,
		species: "Ursaring",
		types: ["Dark", "Fighting"],
		baseStats: {hp: 100, atk: 150, def: 100, spa: 60, spd: 100, spe: 75},
		abilities: {0: "Guts", 1: "Iron Fist", H: "Defiant"},
		height: 1.8,
		weightkg: 125.8,
		prevo: "teddiursa",
		eggGroups: ["Field"],
	},
	bastiodon: {
		num: 411,
		species: "Bastiodon",
		types: ["Steel"],
		baseStats: {hp: 105, atk: 95, def: 150, spa: 60, spd: 150, spe: 40},
		abilities: {0: "Magnet Pull", 1: "Magic Bounce", H: "Armored Plates"},
		height: 1.3,
		weightkg: 149.5,
		prevo: "shieldon",
		eggGroups: ["Monster"],
	},
	carnivine: {
		num: 455,
		species: "Carnivine",
		types: ["Grass", "Dark"],
		baseStats: {hp: 96, atk: 112, def: 82, spa: 110, spd: 82, spe: 98},
		abilities: {0: "Levitate", 1: "Strong Jaw", H: "Triage"},
		height: 1.4,
		weightkg: 27,
		eggGroups: ["Grass"],
	},	
	wishiwashi: {
		num: 746,
		species: "Wishiwashi",
		baseForme: "Solo",
		types: ["Water"],
		baseStats: {hp: 85, atk: 20, def: 20, spa: 25, spd: 25, spe: 125},
		abilities: {0: "Schooling"},
		heightm: 0.2,
		weightkg: 0.3,
		color: "Blue",
		eggGroups: ["Water 2"],
		otherFormes: ["wishiwashischool"],
	},
	wishiwashischool: {
		num: 746,
		species: "Wishiwashi-School",
		baseSpecies: "Wishiwashi",
		forme: "School",
		formeLetter: "S",
		types: ["Water"],
		baseStats: {hp: 85, atk: 140, def: 110, spa: 140, spd: 115, spe: 30},
		abilities: {0: "Schooling"},
		heightm: 8.2,
		weightkg: 78.6,
		color: "Blue",
		eggGroups: ["Water 2"],
	},
	lumineon: {
		num: 457,
		species: "Lumineon",
		types: ["Water", "Fire"],
		baseStats: {hp: 139, atk: 69, def: 86, spa: 99, spd: 96, spe: 121},
		abilities: {0: "Drought", 1: "Drizzle", H: "Comatose"},
		height: 1.2,
		weightkg: 24,
		prevo: "finneon",
		eggGroups: ["Water2"],
	},
	castform: {
		num: 351,
		species: "Castform",
		types: ["Normal"],
		baseStats: {hp: 100, atk: 100, def: 100, spa: 100, spd: 100, spe: 100},
		abilities: {0: "Forecast", 1: "Air Lock"},
		height: 0.3,
		weightkg: 0.8,
		eggGroups: ["Fairy", "Amorphous"],
	},
	noctowl: {
		num: 164,
		species: "Noctowl",
		types: ["Flying", "Ghost"],
		baseStats: {hp: 105, atk: 79, def: 105, spa: 105, spd: 105, spe: 101},
		abilities: {0: "Gale Wings", 1: "Special-Eyes", H: "Tinted Lens"},
		height: 1.6,
		weightkg: 40.8,
		prevo: "hoothoot",
		eggGroups: ["Flying"],
	},
	magcargo: {
		num: 219,
		species: "Magcargo",
		types: ["Fire", "Rock"],
		baseStats: {hp: 110, atk: 95, def: 120, spa: 100, spd: 110, spe: 50},
		abilities: {0: "Flame Body", 1: "Drought", H: "Blazing Flames"},
		height: 0.8,
		weightkg: 55,
		prevo: "slugma",
		eggGroups: ["Amorphous"],
	},
	tropius: {
		num: 357,
		species: "Tropius",
		types: ["Grass", "Fire"],
		baseStats: {hp: 119, atk: 68, def: 103, spa: 102, spd: 107, spe: 121},
		abilities: {0: "Drought", 1: "Tropicalling", H: "Regenerator"},
		height: 2,
		weightkg: 100,
		eggGroups: ["Monster", "Grass"],
	},
	lycanrocmidnight: {
		num: 745,
		species: "Lycanroc-Midnight",
		baseSpecies: "Lycanroc",
		forme: "Midnight",
		formeLetter: "M",
		types: ["Rock", "Dark"],
		baseStats: {hp: 90, atk: 140, def: 115, spa: 60, spd: 105, spe: 90},
		abilities: {0: "Adaptability", 1: "Tough Claws", H: "Intimidate"},
		heightm: 1.1,
		weightkg: 25,
		color: "Red",
		prevo: "rockruff",
		evoLevel: 25,
		eggGroups: ["Field"],
	},
	dunsparce: {
		num: 206,
		species: "Dunsparce",
		types: ["Normal", "Dragon"],
		baseStats: {hp: 100, atk: 100, def: 120, spa: 65, spd: 105, spe: 70},
		abilities: {0: "Serene Grace", 1: "Thick Fat", H: "Levitate"},
		height: 1.5,
		weightkg: 14,
		eggGroups: ["Field"],
	},
	masquerain: {
		num: 284,
		species: "Masquerain",
		types: ["Bug", "Flying"],
		baseStats: {hp: 70, atk: 90, def: 85, spa: 123, spd: 90, spe: 123},
		abilities: {0: "Compound Eyes", 1: "Drizzle", H: "Intimidate"},
		height: 0.8,
		weightkg: 3.6,
		prevo: "surskit",
		eggGroups: ["Water1", "Bug"],
	},
	toucannon: {
		num: 733,
		species: "Toucannon",
		types: ["Steel", "Flying"],
		baseStats: {hp: 100, atk: 120, def: 120, spa: 70, spd: 70, spe: 90},
		abilities: {0: "Filter", 1: "Skill Link", H: "Sheer Force"},
		height: 1.1,
		weightkg: 26,
		prevo: "trumbeak",
		eggGroups: ["Flying"],
	},
	ninjask: {
		num: 291,
		species: "Ninjask",
		types: ["Bug", "Flying"],
		baseStats: {hp: 65, atk: 125, def: 65, spa: 125, spd: 65, spe: 155},
		abilities: {0: "Speed Boost", 1: "Infiltrator"},
		height: 0.8,
		weightkg: 12,
		prevo: "nincada",
		eggGroups: ["Bug"],
	},
	rotomfan: {
		num: 479,
		species: "Rotom-Fan",
		baseSpecies: "Rotom",
		forme: "Fan",
		formeLetter: "S",
		types: ["Electric", "Flying"],
		gender: "N",
		baseStats: {hp: 70, atk: 60, def: 125, spa: 130, spd: 125, spe: 90},
		abilities: {0: "No Guard"},
		heightm: 0.3,
		weightkg: 0.3,
		color: "Red",
		eggGroups: ["Amorphous"],
	},
	gourgeist: {
		num: 711,
		species: "Gourgeist",
		types: ["Grass", "Ghost"],
		baseStats: {hp: 65, atk: 120, def: 100, spa: 120, spd: 75, spe: 90},
		abilities: {0: "Infiltrator", 1: "Drought", H: "Cursed Fire"},
		height: 0.9,
		weightkg: 12.5,
		prevo: "pumpkaboo",
		eggGroups: ["Amorphous"],
	},
	shedinja: {
		num: 292,
		species: "Shedinja",
		types: ["Ghost", "Rock"],
		gender: "N",
		baseStats: {hp: 1, atk: 134, def: 105, spa: 75, spd: 105, spe: 130},
		abilities: {0: "Sturdy", 1: "Magic Shell"},
		height: 0.8,
		weightkg: 1.2,
		prevo: "nincada",
		eggGroups: ["Mineral"],
	},
	politoed: {
		num: 186,
		species: "Politoed",
		types: ["Water", "Grass"],
		baseStats: {hp: 95, atk: 90, def: 110, spa: 90, spd: 110, spe: 90},
		abilities: {0: "Thick Fat", 1: "Aquatic Bloom", H: "Drizzle"},
		height: 1.1,
		weightkg: 33.9,
		prevo: "poliwhirl",
		eggGroups: ["Water1"],
	},
	simipour: {
		num: 516,
		species: "Simipour",
		types: ["Water", "Dark"],
		baseStats: {hp: 85, atk: 100, def: 115, spa: 100, spd: 85, spe: 115},
		abilities: {0: "Mega Launcher", 1: "Sheer Force", H: "Trio Pledge"},
		height: 1,
		weightkg: 29,
		prevo: "panpour",
		eggGroups: ["Field"],
	},
	pyukumuku: {
		num: 771,
		species: "Pyukumuku",
		types: ["Water", "Poison"],
		baseStats: {hp: 95, atk: 100, def: 130, spa: 100, spd: 130, spe: 5},
		abilities: {0: "Innards Out", 1: "Unaware"},
		height: 0.3,
		weightkg: 1.2,
		eggGroups: ["Water1"],
	},
	torterra: {
		num: 389,
		species: "Torterra",
		types: ["Grass", "Ground"],
		baseStats: {hp: 100, atk: 141, def: 130, spa: 60, spd: 92, spe: 77},
		abilities: {0: "Rock Head", 1: "Sturdy", H: "Adaptability"},
		height: 2.2,
		weightkg: 310,
		prevo: "grotle",
		eggGroups: ["Monster", "Grass"],
	},
	poliwrath: {
		num: 62,
		species: "Poliwrath",
		types: ["Water", "Fighting"],
		baseStats: {hp: 90, atk: 95, def: 95, spa: 70, spd: 90, spe: 70},
		abilities: {0: "Water Absorb", 1: "Damp", H: "Swift Swim"},
		height: 1.3,
		weightkg: 54,
		prevo: "poliwhirl",
		eggGroups: ["Water1"],
	},
	walrein: {
		num: 365,
		species: "Walrein",
		types: ["Ice", "Water"],
		baseStats: {hp: 110, atk: 100, def: 70, spa: 60, spd: 200, spe: 65},
		abilities: {0: "Thick Fat", 1: "Terrain Breaker", H: "Refrigerate"},
		height: 1.4,
		weightkg: 150.6,
		prevo: "sealeo",
		eggGroups: ["Water1", "Field"],
	},
	turtonator: {
		num: 776,
		species: "Turtonator",
		types: ["Fire", "Dragon"],
		baseStats: {hp: 115, atk: 60, def: 110, spa: 100, spd: 105, spe: 55},
		abilities: {0: "Shell Armor", H: "Intimidate"},
		height: 2,
		weightkg: 212,
		eggGroups: ["Monster", "Dragon"],
	},
	simisear: {
		num: 514,
		species: "Simisear",
		types: ["Fire"],
		baseStats: {hp: 90, atk: 80, def: 85, spa: 130, spd: 115, spe: 100},
		abilities: {0: "Gluttony", H: "Trio Pledge"},
		height: 1,
		weightkg: 28,
		prevo: "pansear",
		eggGroups: ["Field"],
	},
	slaking: {
		num: 289,
		species: "Slaking",
		types: ["Normal"],
		baseStats: {hp: 150, atk: 160, def: 100, spa: 95, spd: 65, spe: 100},
		abilities: {0: "Oblivious", 1: "Klutz", H: "Comatose"},
		height: 2,
		weightkg: 130.5,
		prevo: "vigoroth",
		eggGroups: ["Field"],
	},
	golduck: {
		num: 55,
		species: "Golduck",
		types: ["Water", "Psychic"],
		baseStats: {hp: 105, atk: 95, def: 95, spa: 100, spd: 95, spe: 85},
		abilities: {0: "Cloud Nine", 1: "Dry Skin", H: "Third Eye"},
		height: 1.7,
		weightkg: 76.6,
		prevo: "psyduck",
		eggGroups: ["Water1", "Field"],
	},
	spinda: {
		num: 327,
		species: "Spinda",
		types: ["Normal", "Fighting"],
		baseStats: {hp: 100, atk: 120, def: 100, spa: 100, spd: 100, spe: 100},
		abilities: {0: "Unaware", 1: "Own Tempo", H: "Contrary"},
		height: 1.1,
		weightkg: 5,
		eggGroups: ["Field", "Human-Like"],
	},
	parasect: {
		num: 47,
		species: "Parasect",
		types: ["Bug", "Ghost"],
		baseStats: {hp: 95, atk: 120, def: 110, spa: 85, spd: 115, spe: 50},
		abilities: {0: "Effect Spore", 1: "Dry Skin", H: "Triage"},
		height: 1,
		weightkg: 29.5,
		prevo: "paras",
		eggGroups: ["Bug", "Grass"],
	},
	sudowoodo: {
		num: 185,
		species: "Sudowoodo",
		types: ["Rock", "Grass"],
		baseStats: {hp: 120, atk: 130, def: 155, spa: 30, spd: 65, spe: 30},
		abilities: {0: "Solid Rock", 1: "Rock Head", H: " Sturdy"},
		height: 1.2,
		weightkg: 38,
		prevo: "bonsly",
		eggGroups: ["Mineral"],
	},
	vespiquen: {
		num: 416,
		species: "Vespiquen",
		types: ["Dark", "Fighting"],
		gender: "F",
		baseStats: {hp: 140, atk: 100, def: 100, spa: 100, spd: 100, spe: 60},
		abilities: {0: "Pressure", 1: "Unnerve", H: "Simple"},
		height: 1.2,
		weightkg: 38.5,
		prevo: "combee",
		eggGroups: ["Bug"],
	},
	silvally: {
		num: 773,
		species: "Silvally",
		types: ["Normal"],
		gender: "N",
		baseStats: {hp: 105, atk: 130, def: 95, spa: 130, spd: 95, spe: 125},
		abilities: {0: "RKS System"},
		height: 2.3,
		weightkg: 100.5,
		prevo: "typenull",
		eggGroups: ["Undiscovered"],
	},
	delcatty: {
		num: 301,
		species: "Delcatty",
		types: ["Fairy", "Normal"],
		baseStats: {hp: 119, atk: 99, def: 109, spa: 99, spd: 109, spe: 109},
		abilities: {0: "Cute Charm", 1: "Thick Fat", H: "Tough Claws"},
		height: 1.1,
		weightkg: 32.6,
		prevo: "skitty",
		eggGroups: ["Field", "Fairy"],
	},
	chimecho: {
		num: 358,
		species: "Chimecho",
		types: ["Grass", "Fire"],
		baseStats: {hp: 75, atk: 50, def: 80, spa: 95, spd: 90, spe: 65},
		abilities: {0: "Levitate"},
		height: 0.6,
		weightkg: 1,
		prevo: "chingling",
		eggGroups: ["Amorphous"],
	},
	wormadam: {
		num: 413,
		species: "Wormadam",
		types: ["Bug", "Grass"],
		gender: "F",
		baseStats: {hp: 107, atk: 47, def: 64, spa: 136, spd: 197, spe: 52},
		abilities: {0: "Chlorophyll", H: "Filter"},
		height: 0.5,
		weightkg: 6.5,
		prevo: "burmy",
		eggGroups: ["Bug"],
	},
	golemalola: {
		num: 76,
		species: "Golem-Alola",
		types: ["Rock", "Ground"],
		baseStats: {hp: 80, atk: 120, def: 130, spa: 55, spd: 65, spe: 45},
		abilities: {0: "Sand Stream", 1: "Sand Rush", H: "Technician"},
		height: 1.7,
		weightkg: 316,
		prevo: "graveleralola",
		eggGroups: ["Mineral"],
	},
	shiftry: {
		num: 275,
		species: "Shiftry",
		types: ["Grass", "Dark"],
		baseStats: {hp: 85, atk: 130, def: 70, spa: 125, spd: 70, spe: 120},
		abilities: {0: "Sturdy", 1: "Magic Shell", H: "Pickpocket"},
		height: 1.3,
		weightkg: 59.6,
		prevo: "nuzleaf",
		eggGroups: ["Field", "Grass"],
	},
	probopass: {
		num: 476,
		species: "Probopass",
		types: ["Electric", "Steel"],
		baseStats: {hp: 90, atk: 60, def: 155, spa: 95, spd: 155, spe: 45},
		abilities: {0: "Levitate", 1: "Electric Surge", H: "Sand Force"},
		height: 1.4,
		weightkg: 340,
		prevo: "nosepass",
		eggGroups: ["Mineral"],
	},
	bellossom: {
		num: 182,
		species: "Bellossom",
		types: ["Grass", "Fairy"],
		baseStats: {hp: 95, atk: 75, def: 100, spa: 100, spd: 125, spe: 70},
		abilities: {0: "Chlorophyll", 1: "Filter", H: "Simple"},
		height: 0.4,
		weightkg: 5.8,
		prevo: "gloom",
		eggGroups: ["Grass"],
	},
	raticatealola: {
		num: 20,
		species: "Raticate-Alola",
		baseSpecies: "Raticate",
		forme: "Alola",
		formeLetter: "A",
		types: ["Dark", "Normal"],
		baseStats: {hp: 115, atk: 91, def: 150, spa: 40, spd: 150, spe: 67},
		abilities: {0: "Gluttony", 1: "Hustle", H: "Thick Fat"},
		heightm: 0.7,
		weightkg: 25.5,
		color: "Black",
		prevo: "rattataalola",
		evoLevel: 20,
		eggGroups: ["Field"],
	},
	arbok: {
		num: 24,
		species: "Arbok",
		types: ["Poison", "Dark"],
		baseStats: {hp: 85, atk: 115, def: 99, spa: 65, spd: 109, spe: 105},
		abilities: {0: "Shed Skin", 1: "Intimidate", H: "Strong Jaw"},
		height: 3.5,
		weightkg: 65,
		prevo: "ekans",
		eggGroups: ["Field", "Dragon"],
	},
};