'use strict';

 exports.BattlePokedex = {
tapulele: {
		num: 786,
		species: "Tapu Lele",
		types: ["Psychic", "Fairy"],
		gender: "N",
		baseStats: {hp: 70, atk: 85, def: 75, spa: 100, spd: 115, spe: 95},
		abilities: {0: "Competitive", H: "Telepathy"},
		heightm: 1.2,
		weightkg: 18.6,
		color: "Pink",
		eggGroups: ["Undiscovered"],
	},
  tapubulu: {
		num: 787,
		species: "Tapu Bulu",
		types: ["Grass", "Fairy"],
		gender: "N",
		baseStats: {hp: 70, atk: 125, def: 95, spa: 85, spd: 85, spe: 70},
		abilities: {0: "Sap Sipper", H: "Telepathy"},
		heightm: 1.9,
		weightkg: 45.5,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
  tapufini: {
		num: 788,
		species: "Tapu Fini",
		types: ["Water", "Fairy"],
		gender: "N",
		baseStats: {hp: 60, atk: 75, def: 100, spa: 85, spd: 115, spe: 85},
		abilities: {0: "Water Veil", H: "Telepathy"},
		heightm: 1.3,
		weightkg: 21.2,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
  magearna: {
		num: 801,
		species: "Magearna",
		types: ["Fairy"],
		gender: "N",
		baseStats: {hp: 80, atk: 105, def: 95, spa: 105, spd: 95, spe: 75},
		abilities: {0: "Steelworker"},
		heightm: 1,
		weightkg: 80.5,
		color: "Gray",
		eggGroups: ["Undiscovered"],
		otherFormes: ["magearnaoriginal"],
	},
  magearnaoriginal: {
		num: 801,
		species: "Magearna-Original",
		baseSpecies: "Magearna",
		forme: "Original",
		formeLetter: "O",
		types: ["Steel", "Fairy"],
		gender: "N",
		baseStats: {hp: 80, atk: 95, def: 115, spa: 130, spd: 115, spe: 65},
		abilities: {0: "Soul-Heart"},
		heightm: 1,
		weightkg: 80.5,
		color: "Red",
		eggGroups: ["Undiscovered"],
		spritenum: 804 + 152,
	},
	 tyranitar: {
		num: 248, 
		species: "Tyranitar",
		types: ["Rock", "Dark"],
		baseStats: {hp: 75, atk: 94, def: 125, spa: 55, spd: 90, spe: 61},
		abilities: {0: "Sand Force", H: "Bullet Proof"},
		heightm: 2,
		weightkg: 202,
		color: "Green",
		prevo: "pupitar",
		evoLevel: 55,
		eggGroups: ["Monster"],
		otherFormes: ["tyranitarmega"],
	},
	 dragonite: {
		num: 149,
		species: "Dragonite",
		types: ["Dragon", "Flying"],
		baseStats: {hp: 84, atk: 105, def: 65, spa: 90, spd: 85, spe: 66},
		abilities: {0: "Inner Focus", H: "Hydration"},
		heightm: 2.2,
		weightkg: 210,
		color: "Brown",
		prevo: "dragonair",
		evoLevel: 55,
		eggGroups: ["Water 1", "Dragon"],
	},
	 garchomp: {
		num: 445,
		species: "Garchomp",
		types: ["Dragon", "Ground"],
		baseStats: {hp: 88, atk: 110, def: 78, spa: 60, spd: 67, spe: 97},
		abilities: {0: "Sand Force", H: "Rough Skin"},
		heightm: 1.9,
		weightkg: 95,
		color: "Blue",
		prevo: "gabite",
		evoLevel: 48,
		eggGroups: ["Monster", "Dragon"],
		otherFormes: ["garchompmega"],
	},
	 buzzwole: {
		 inherite: true,
		 types: ["Bug"],
		 baseStats: {hp: 97, atk: 113, def: 113, spa: 53, spd: 53, spe: 79},
	 },
	 kartana: {
		 inherite: true,
		 baseStats: {hp: 59, atk: 131, def: 109, spa: 59, spd: 31, spe: 97},
	 },
	  nihilego: {
		 inherite: true,
		 baseStats: {hp: 83, atk: 53, def: 47, spa: 107, spd: 113, spe: 97},
	 },
  };
